### ISSUE TITLE
AWS::ApiGateway::Stage-MethodSetting-EnableDetailedCloudWatchMetrics

### ISSUE THREAD

**Issue by pawelaugustyn** [aws-cloudformation/cloudformation-coverage-roadmap#100]
## 1. Title
Add support of Enable Detailed CloudWatch Metrics for AWS::ApiGateway::Stage-MethodSettings attribute.

## 2. Scope
Entries from AWS::ApiGateway::Stage-MethodSettings have enabled detailed CloudWatch metrics since the creation.

## 3. Expected behavior
In create/update, it should allow enabling detailed CloudWatch metrics

## 4. Test case recommendation
Test for upgrading AWS::ApiGateway::Stage MethodSettings parameter

## 5. Links to existing API doc (optional)
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-stage-methodsetting.html

## 6. Category tag (optional)
Networking & Content Delivery

**Comment by brianterry** [comment]
@pawelaugustyn, `MetricsEnabled` is now supported.

Please see our docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-stage-methodsetting.html#cfn-apigateway-stage-methodsetting-metricsenabled
