### ISSUE TITLE
AWS::AutoScaling::LaunchConfiguration - PropagateTagsToVolumeOnCreation

### ISSUE THREAD

**Issue by robertd** [aws-cloudformation/cloudformation-coverage-roadmap#1006]
### Name of the resource

AWS::AutoScaling::LaunchConfiguration

### Description

Now that `PropagateTagsToVolumeOnCreation` is available on `AWS::EC2::Instance` resource (https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/133), it would be nice to expose this in `AWS::AutoScaling::LaunchConfiguration` for the instances running in ASG. Tag propagation to underlying EBS volumes is a very important feature to us. About 90% of our launched solutions are EC2 instances being launched through ASG.

### Other Details

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-propagatetagstovolumeoncreation

**Comment by robertd** [comment]
@WaelA Any chance you can expedite this one now that #133 is in place?

**Comment by issue-submission** [comment]
Hi @robertd, is there any update for this feature?
