### ISSUE TITLE
AWS::Logs::Destination - DestinationPolicy should not be required

### ISSUE THREAD

**Issue by kdgregory** [aws-cloudformation/cloudformation-coverage-roadmap#101]
## 2. Scope of request 

In CloudFormation, the `DestinationPolicy` attribute is marked as required. However, in the API, [PutDestination](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutDestination.html) and [PutDestinationPolicy](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutDestinationPolicy.html) are separate APIs, and the latter is documented (perhaps incorrectly?) as only being required for cross-account access.

A fix would change the status of this attribute to _Not Required_.

## 3. Expected behavior

CloudFormation will not fail stack creation/update if this attribute is not present. 

## 4. Suggest specific test cases

Create destinations with and without this attribute.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

5. Management (CloudTrail, Config...)

**Comment by waifa** [comment]
Changes have been made to make the DestinationPolicy field optional and merged to the [aws-cloudformation-resource-providers-logs](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-logs) repository. The changes are still being deployed. I will update once changes have been fully deployed. Thank you for your patience!

**Comment by waifa** [comment]
Destination policy is now optional!
