### ISSUE TITLE
AWS::EC2::VPCEndpoint support for importing into CloudFormation Stack

### ISSUE THREAD

**Issue by ruchirshetye-aws** [aws-cloudformation/cloudformation-coverage-roadmap#1025]
### Name of the resource

AWS::EC2::VPCEndpoint

### Description

We would like to import existing VPC Endpoints into a CFN stack.

**Comment by TheDanBlanco** [comment]
this is now [supported](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html)
