### ISSUE TITLE
AWS::CloudTrail::Trail AdvancedEventSelector

### ISSUE THREAD

**Issue by rmalecky** [aws-cloudformation/cloudformation-coverage-roadmap#1028]
### Name of the resource

AWS::CloudTrail::Trail

### Description

CloudTrail added the Advanced Event Selector as an alternative to Event Selectors for logged Data Events to a trail in 2020.  CloudFormation supports Event Selectors.  This request is to add Advanced Event Selectors.

### Other Details

[Launch Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/aws-cloudtrail-provides-more-granular-control-of-data-event-logging/)
[API Documentation](https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_AdvancedEventSelector.html)

**Comment by varuraju** [comment]
This feature is now available in all regions. Closing issue.
