### ISSUE TITLE
Details on end of support for AWS::ElasticSearch::Domain

### ISSUE THREAD

**Issue by johancar** [aws-cloudformation/cloudformation-coverage-roadmap#1036]
### Resource Name

Can you provide possible date when AWS::ElasticSearch::Domain will become unsupported?

Thank you.

### Details

Currently migrated cloudformation template with steps provided below. However, would like to know when support for this resource will end.

https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-opensearch-upgrade/

**Comment by pjfitzgibbons** [comment]
There is currently no set-date on the roadmap for deprecating ElasticSearch versions from AWS Opensearch Service.

We do encourage all users to upgrade to OpenSearch versions when you can!
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/version-migration.html
https://onecloudplease.com/blog/migrating-to-opensearch-with-cloudformation
