### ISSUE TITLE
CFn Import support request for AWS::EC2::Route resource

### ISSUE THREAD

**Issue by yoshniwa** [aws-cloudformation/cloudformation-coverage-roadmap#1038]
### Name of the resource

AWS::EC2::Route

### Description

Currently AWS::EC2::Route resource import is not support by CloudFormation. My Customer requested us to support it as a part of resources which can be imported to CloudFormation.

**Comment by johase** [comment]
Today this feature is not available on AWS but we are collecting demand from our customers through our product feature request tool and will update the progress there.

**Comment by alanrdze** [comment]
Feature has been supported. See the supported resources for import here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html
Closing this issue as AWS::EC2::Route is now available for import.
