### ISSUE TITLE
`VPNGatewayRoutePropagation` fails if gateway isn't already attached to VPC before stack update

### ISSUE THREAD

**Issue by BalzGuenat** [aws-cloudformation/cloudformation-coverage-roadmap#1039]
### Name of the resource

AWS::EC2::VPNGatewayRoutePropagation

### Issue Description

A `VPNGatewayRoutePropagation` fails unless the the associated gateway is already attached to the VPC. Specifically, it still fails, even if the appropriate `VPCGatewayAttachment` is applied in the same stack update. The effective result is that at least two stack updates are necessary to create a new VPCGateway, attach it to a VPC, and enable route propagation. A single rollout is not possible.

### Expected Behavior

Application of the route propagation should succeed if an appropriate gateway attachment is applied in the same stack update.

### Observed Behavior

The stack update fails with a `GeneralServiceException`.

### Test Cases

Create an unattached gateway. Apply a template with associated `VPCGatewayAttachment` and `VPNGatewayRoutePropagation`. The update should succeed.

**Comment by ferozbaig-amzn** [comment]
As per the [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpngatewayroutepropagation.html), the `AWS::EC2::VPNGatewayRoutePropagation` resource cannot use the VPN gateway until it has successfully attached to the VPC.
Can you try adding a `DependsOn` attribute to `AWS::EC2::VPNGatewayRoutePropagation` resource to explicitly declare a dependency on the VPN gateway attachment? 
Please share your findings. In case that too doesn't work, kindly share a sample Cloudformation template to replicate the issue.
