### ISSUE TITLE
s3 awscc support does not work due to `object_lock_enabled` parameter

### ISSUE THREAD

**Issue by drewmullen** [aws-cloudformation/cloudformation-coverage-roadmap#1040]
### Name of the resource

AWS::S3::Bucket

### Issue Description

`object_lock_enabled` is not passed correctly. permanently broken

```
resource "awscc_s3_bucket" "tfstate" {
    bucket_name = "<>"

    object_lock_enabled = false
}

terraform {
  required_version = ">= 0.14.0"
  required_providers {
    awscc = {
      source  = "hashicorp/awscc"
      version = ">= 0.11.0"
    }
  }
}

```

### Expected Behavior

should be able to build bucket via idempotent configuration

### Observed Behavior

Always tries to force recreate

```
  # awscc_s3_bucket.tfstate must be replaced
-/+ resource "awscc_s3_bucket" "tfstate" {
      ~ arn                               = "arn:aws:s3:::<>" -> (known after apply)
      ~ domain_name                       = "<>" -> (known after apply)
      ~ dual_stack_domain_name            = "<>" -> (known after apply)
      ~ id                                = "<>" -> (known after apply)
      + object_lock_enabled               = false # forces replacement
```

### Test Cases

run the code above. try:

- omitting `object_lock_enabled`
- `object_lock_enabled = false`
- `object_lock_enabled = true`

run
```
terraform apply -auto-approve
```

run a 2nd apply (fails idempotency)
```
terraform apply -auto-approve
```

**Comment by ewbankkit** [comment]
For this configuration:

```hcl
provider "awscc" {}

resource "awscc_s3_bucket" "test" {
  object_lock_enabled = false
}
```

This is the desired state passed to the Cloud Control `CreateResource` API:

```
CloudControl DesiredState. value: {"ObjectLockEnabled":false}
``

and this is the resource model returned from the Cloud Control `ReadResource` API:

```
ResourceDescription.ResourceModel. value: {"BucketName":"qlnfngml72a8xkjn1w4harbuk-lithyzntm9j8","RegionalDomainName":"qlnfngml72a8xkjn1w4harbuk-lithyzntm9j8.s3.us-west-2.amazonaws.com","DomainName":"qlnfngml72a8xkjn1w4harbuk-lithyzntm9j8.s3.amazonaws.com","WebsiteURL":"http://qlnfngml72a8xkjn1w4harbuk-lithyzntm9j8.s3-website-us-west-2.amazonaws.com","DualStackDomainName":"qlnfngml72a8xkjn1w4harbuk-lithyzntm9j8.s3.dualstack.us-west-2.amazonaws.com","Arn":"arn:aws:s3:::qlnfngml72a8xkjn1w4harbuk-lithyzntm9j8"}
```

The `ObjectLockEnabled` value is **NOT** being returned.

**Comment by drewmullen** [comment]
closed upstream
