### ISSUE TITLE
Allow renaming of DB Cluster via `DBClusterIdentifier` without replacement update

### ISSUE THREAD

**Issue by amedeshm** [aws-cloudformation/cloudformation-coverage-roadmap#1042]
### Name of the resource

AWS::RDS::DBCluster

### Description

Currently is is possible to rename a RDS DB Cluster by specifying the `NewDBClusterIdentifier` property in the `ModifyDBCluster` API call. This can be done via the AWS CLI and the Console as well without the RDS DB Cluster being replaced. 

In CloudFormation, the functionality of `DBClusterIdentifier` property should be updated to leverage the  `NewDBClusterIdentifier` property in the `ModifyDBCluster` API call to allow renaming the resource without replacement update.

**Comment by osdrv** [comment]
Similar to https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1043, this feature would also conflict with CFN assumption that primary identifiers are unique and immutable.
