### ISSUE TITLE
Drift detection: inline policy for a AWS::SSO::PermissionSet causes false positive

### ISSUE THREAD

**Issue by avandyke** [aws-cloudformation/cloudformation-coverage-roadmap#1052]
### Name of the resource

AWS::SSO::PermissionSet

### Issue Description

When creating a AWS::SSO::PermissionSet with inline policies and then running Drift detection on the stack, resource gets flagged as Drifted because the presence of inline policy is being ignored. When reviewing Drift details, only managed policies are present in the "Actual" field, while "Expected" field shows inline policies.

### Expected Behavior

CF correctly identifies presence of inline policies and doesn't mark them as removed when running Drift detection.

### Observed Behavior

Inline policies are being flagged as "Removed" by Drift detection even though they are still there and can be seen in SSO dashboard.

### Test Cases

Create a AWS::SSO::PermissionSet resource with both Managed and Inline policies assigned. Run Drift detection on the resource. Inline policy would be marked are "Removed" and stack will be flagged as Drifted.

**Comment by matthewcarlisle** [comment]
This bug has been bouncing from "Coming soon" to "we're working on it" for a couple of years now. Seems like it should just get fixed, no?

**Comment by ziarrdan** [comment]
Fixed Inline policy false drift deletion for AWS::SSO::PermissionSet.
