### ISSUE TITLE
AWS WAF adds support for CloudWatch Log and logging directly to S3 bucket -> This feature is missing for FMS Policies

### ISSUE THREAD

**Issue by daknhh** [aws-cloudformation/cloudformation-coverage-roadmap#1055]
### Name of the resource

AWS::FMS::Policy

### Resource name

AWS:FMS:Policy

### Description

On 6 December 2021, aws announced WAF support for CloudWatch Log and logging directly to S3 bucket - this feature is missing for the AWS::FMS::Policy resource. 

https://aws.amazon.com/about-aws/whats-new/2021/12/awf-waf-cloudwatch-log-s3-bucket/

**Comment by wy3148** [comment]
This is not a CloudFormation parity issue, our service does not support this feature at all right now.
