### ISSUE TITLE
Add AWS SSM support for latest parameter version as reference

### ISSUE THREAD

**Issue by rantoniuk** [aws-cloudformation/cloudformation-coverage-roadmap#1058]
### Name of the resource

AWS::SecretsManager::Secret

### Description

As described in aws/aws-cdk#18747

Secure string references are currently only supported for a limited number of resource types. See the [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#template-parameters-dynamic-patterns-resources) for the latest list. At this point in time, Lambda functions are not supported.

To support the above use case, CloudFormation will need to add support for this behavior.

**Comment by benbridts** [comment]
This seems to be (partially?) a more specific case of  https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/227

(as a side note: keep in mind that passing a secret to a lambda as en environment variable will expose that value to everyone with read access to that lambda function)

**Comment by rantoniuk** [comment]
Partially, indeed, as I imagine also that changing the SSM variable __value__ should e.g. create [another Lambda 
deployment version](https://docs.aws.amazon.com/lambda/latest/dg/configuration-versions.html) for traceability purposes.
