### ISSUE TITLE
AWS::KinesisAnalyticsV2::Application - FlinkRunConfiguration Coverage

### ISSUE THREAD

**Issue by marcelo-duffles** [aws-cloudformation/cloudformation-coverage-roadmap#1059]
### Name of the resource

AWS::KinesisAnalyticsV2::Application

### Resource name

FlinkRunConfiguration

### Description

`FlinkRunConfiguration` is available via API (https://docs.aws.amazon.com/kinesisanalytics/latest/apiv2/API_FlinkRunConfiguration.html) but not via CloudFormation (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisanalyticsv2-application.html)

**Comment by donghuiy** [comment]
The is by design, since we only support FlinkRunConfiguration when application is in Running state, that level of delicate decision/validation cannot be made through static Cloud Formation template.
