### ISSUE TITLE
AWS::Kinesis::VideoStream - new resource

### ISSUE THREAD

**Issue by mitchellrj** [aws-cloudformation/cloudformation-coverage-roadmap#106]
1. AWS::Kinesis::VideoStream
2. Scope of request -> New resource
3. Expected behavior -> Fully automated luxury space video streams
4. Test case recommendation (optional) -> 
5. Links to existing API doc (optional) -> 
6. Category tag (optional) -> Analytics
7. Any additional context (optional)

**Comment by Mirch** [comment]
Is there any update on this? It looks like terraform and pulumi have this feature available.

**Comment by kddejong** [comment]
I'm going to mark this issue as closed as [AWS::KinesisVideo::Stream](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kinesisvideo-stream.html) exists.  I can re-open as needed.
