### ISSUE TITLE
AWS::Lamba::Function - Zipfile attribute not supported for the runtime 'provided.al2'

### ISSUE THREAD

**Issue by Dgarc359** [aws-cloudformation/cloudformation-coverage-roadmap#1063]
### Name of the resource

AWS::Lambda::Function

### Description

Hello, I am trying to stand up a `lambda.CfnFunction` through aws cdk, using the provided.al2 runtime and attempting to ship my code for that lambda as a zip. The zip contains my bootstrap rust binary that I have already manually deployed through the aws console. When deploying my stack, I receive the error:

The ZipFile attribute is not supported for the runtime 'provided.al2'"

Please advise.

**Comment by micahduron** [comment]
Hello, the `ZipFile` CFN attribute is currently only supported by the `nodejs*` and `python*` runtimes. The naming is unfortunately a bit misleading, as `ZipFile` is used to specify the function's source code directly within the CDK/CFN template. For example:

```
new lambda.CfnFunction(scope, 'MyFunction', {
  code: {
    zipFile: "def main(event, context): return {'Hello': 'world'}"
  },
  runtime: 'python3.9',
  handler: 'index.main',

  // ...
});
```

For runtimes other than nodejs or python, a zip file can only be supplied via S3 (the `s3Bucket` and `s3Key` attributes).

However, there is an alternative if you're able to use the higher level `lambda.Function` construct. With this construct you're able to use a number of helper functions which can take care of the process of uploading the zip file to S3 for you:

```
new lambda.Function(scope, 'MyFunction2', {
  code: lambda.Code.fromAsset(zipFilePath),
  runtime: lambda.Runtime.PROVIDED_AL2,

  // ...
});
```
