### ISSUE TITLE
AWS::ECR::PullThroughCacheConfiguration to set pull through cache rules

### ISSUE THREAD

**Issue by jakob-keller** [aws-cloudformation/cloudformation-coverage-roadmap#1064]
### Name of the resource

Other

### Resource name

AWS::ECR::PullThroughCacheConfiguration

### Description

ECR added support for pull through cache repositories in 2021. This requires a new CloudFormation resource type to set pull through cache rules for ECR private registries.

### Other Details

[Announcement](https://aws.amazon.com/blogs/aws/announcing-pull-through-cache-repositories-for-amazon-elastic-container-registry/)

[ECR documentation](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html)

API documentions: [create](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_CreatePullThroughCacheRule.html), [delete](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_DeletePullThroughCacheRule.html), [describe](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_DescribePullThroughCacheRules.html)

**Comment by xaoyuli** [comment]
This is a feature request. Will evaluate it with service team.

**Comment by ShubhraDeshpande** [comment]
AWS::ECR::PullThroughCacheRule is now available on ECR official documentation 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-pullthroughcacherule.html

**Comment by jakob-keller** [comment]
Works like a charm. Thank you!
