### ISSUE TITLE
AWS::CloudFront::Distribution DistributionConfig DefaultCacheBehavior is required

### ISSUE THREAD

**Issue by jaymccon** [aws-cloudformation/cloudformation-coverage-roadmap#1067]
### Name of the resource

AWS::CloudFront::Distribution

### Resource name

AWS::CloudFront::Distribution DistributionConfig

### Reference Link

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html#cfn-cloudfront-distribution-distributionconfig-defaultcachebehavior

### Details

The `DefaultCacheBehavior` property is listed as optional, but the description text states `You must create exactly one default cache behavior.`. From a test performed by @richardhboyd it appears the description is accurate and the property is NOT optional as stated in the docs.

https://github.com/aws-cloudformation/cfn-lint/issues/672

**Comment by junseokc** [comment]
DefaultCacheBehavior is indeed required. A change has been merged and the documentation has been updated to reflect that.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html#cfn-cloudfront-distribution-distributionconfig-defaultcachebehavior
