### ISSUE TITLE
Stack update status does not consider the backfilling of GlobalSecondaryIndex

### ISSUE THREAD

**Issue by martinezpl** [aws-cloudformation/cloudformation-coverage-roadmap#1075]
### Name of the resource

AWS::DynamoDB::Table

### Description

Currently the stack update completes once the GSI is created - however, depending on the amount of pre-existing data in the table, the backfilling of GSI can take a significant time during which it's not accessible.

An example of boto3 exception:

`ClientError An error occurred (ValidationException) when calling the Query operation: Cannot read from backfilling global secondary index`

This creates a problem when CloudFormation is used for CI/CD - querying GSI during its backfilling is not possible and so it may result in a runtime error or system malfunction. 

Although there are work-arounds (e.g. infrastructure update before source code update), I believe it's an unintuitive inconvenience.

### Other Details

The GSI has a `status` property that signifies whether the backfilling is ready, marking so as `Active`. There is also a metric in CloudWatch tracking the progress called `OnlineIndexPercentageProgress`.

**Comment by vicky-blr** [comment]
This is not an issue but by design, see [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-globalsecondaryindexes).

Stack update doesn't consider backfilling of index because it can take hours depending on the size of the table.
