### ISSUE TITLE
AWS::EC2::TransitGatewayRoute - Update of AttachmentId property not possible

### ISSUE THREAD

**Issue by f7o** [aws-cloudformation/cloudformation-coverage-roadmap#1082]
### Name of the resource

AWS::EC2::TransitGatewayRoute

### Issue Description

Update of property `TransitGatewayAttachmentId` only on resource `AWS::EC2::TransitGatewayRoute` not possible in destination route keeps being the same.

### Expected Behavior

In an existing TgwRoute resource in a Cfn Stack the property TransitGatewayAttachmentId is changed. Cfn performs an update on that resource, uses the `ReplaceTransitGatewayRoute`  API call (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ReplaceTransitGatewayRoute.html) to change the route. Reports success.

### Observed Behavior

Cfn update operation triggers replacement. This causes a route creation with the same destination CIDR. This fails due to already existence of this route. Rollback will be performed without changes to the old route (hopefully).

### Test Cases

Spoke VPC redeployment, e.g. to migrate from one egress VPC to another one, requires the same static route to be pointed to a different TGW attachment. Propagation can not be used in all cases, especially egress or firewall VPCs as they have isolate subnets which should be routed via TGW.

**Comment by cyuste** [comment]
Same issue here, we really need this to deploy vpc confidently using cdk/cfn

**Comment by thu001** [comment]
This issue is now resolved. The route update operation still triggers a replacement, but it will first delete the existing route before creating a new one. That said, it no longer causes an error. Please refer to the attached screenshot for the route replacement event sequence.
![image](https://github.com/user-attachments/assets/c7633b15-f7fc-4b0e-85a2-f6140da14fe5)

**Comment by jk2l** [comment]
I am not sure why updating tag require replacing whole route... that will cause brief network interruption which is not ideal especially a mission critical network require 24/7 up time

**Comment by thu001** [comment]
`AWS::EC2::TransitGatewayRoute` is not a taggable resource, so the case does not apply.  Modifying stack-level tags alone will not impact the route in any way.

> I am not sure why updating tag require replacing whole route... that will cause brief network interruption which is not ideal especially a mission critical network require 24/7 up time

**Comment by jk2l** [comment]
> `AWS::EC2::TransitGatewayRoute` is not a taggable resource, so the case does not apply. Modifying stack-level tags alone will not impact the route in any way.
> 
> > I am not sure why updating tag require replacing whole route... that will cause brief network interruption which is not ideal especially a mission critical network require 24/7 up time

yea but your stack update show DELETE then CREATE. so the TGW route temporary got deleted

**Comment by thu001** [comment]
> > `AWS::EC2::TransitGatewayRoute` is not a taggable resource, so the case does not apply. Modifying stack-level tags alone will not impact the route in any way.
> > > I am not sure why updating tag require replacing whole route... that will cause brief network interruption which is not ideal especially a mission critical network require 24/7 up time
> 
> yea but your stack update show DELETE then CREATE. so the TGW route temporary got deleted

This issue was related update failure when updating `TransitGatewayAttachmentId` and is not related to tagging update. The screenshot below shows the behavior for updating stack-level tags, which does not impact the route at all because the resource is not taggable.
<img width="821" alt="image" src="https://github.com/user-attachments/assets/370276de-e05c-4b1c-83b1-233713eadb1a">
