### ISSUE TITLE
Add ClusterResourceId for AWS::RDS::DBCluster

### ISSUE THREAD

**Issue by JohnPreston** [aws-cloudformation/cloudformation-coverage-roadmap#1083]
### Name of the resource

AWS::RDS::DBCluster

### Description

Hello.
This is a request to add a new return value, `ClusterResourceId` for [AWS::RDS::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#aws-resource-rds-dbcluster-return-values), alike for [AWS::Neptune::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html#aws-resource-neptune-dbcluster-return-values) and [AWS::DocDB::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html#aws-resource-docdb-dbcluster-return-values), which are both based on RDS themselves.

This is most required in order to render ARN for IAM Authentication and other AWS IAM API calls to the resource.

Many thanks,

**Comment by TheDanBlanco** [comment]
this appears to exist as DBClusterResourceId. closing. please re-open if this isn't correct with more info
