### ISSUE TITLE
Exclude targets from stackset deployment

### ISSUE THREAD

**Issue by wayne-folkes** [aws-cloudformation/cloudformation-coverage-roadmap#1088]
### Name of the resource

AWS::CloudFormation::StackSet

### Description

I would like to be able to exclude certain targets (accounts, OUs) from deployment of a stack instance. This would be for cases where I want every account in the org to get something except for certain OUs or accounts

**Comment by TheDanBlanco** [comment]
https://aws.amazon.com/about-aws/whats-new/2022/07/aws-cloudformation-stacksets-support-account-level-targeting-organizational-unit/
