### ISSUE TITLE
Adding a CloudFormation resource coverage for Auto-Adjusting Budgets

### ISSUE THREAD

**Issue by nelomsmn** [aws-cloudformation/cloudformation-coverage-roadmap#1096]
### Name of the resource

AWS::Budgets::Budget

### Resource name

AutoAdjustingBudget

### Description

There is a new feature for AWS Budgets called the Auto-Adjusting budget. Although this feature is released, CloudFormation does not yet support properties to allow for of this type of Budget resource. This is a request for an AWS::Budgets::Budget property that will allow for the provisioning of Auto-Adjusting Budgets.

**Comment by Bmiest** [comment]
This doesn't seem fully implemented yet? 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-budgets-budget-autoadjustdata.html 

![afbeelding](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/18619887/24c2a757-5830-4256-b8ac-223ce82cf3c6)

**Comment by Bmiest** [comment]
This doesn't seem fully implemented yet? 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-budgets-budget-autoadjustdata.html 

![afbeelding](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/18619887/2e18c8c8-4b37-4d6c-b38b-2ee957d272f1)
