### ISSUE TITLE
Stack-level CF tags are not propagated to AWS:EC2::FlowLog

### ISSUE THREAD

**Issue by lvthillo** [aws-cloudformation/cloudformation-coverage-roadmap#1098]
### Name of the resource

AWS::EC2::FlowLog

### Issue Description

[AWS docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html): 

> "All stack-level tags, including automatically created tags, are propagated to resources that CloudFormation supports. Currently, tags aren't propagated to Amazon EBS volumes that are created from block device mappings."

I've added stack-level tags to my CF stack. They are propagated to the underlying resources except VPC Flowlogs.

### Expected Behavior

Flow logs should be tagged with the stack-level defined tags.

### Observed Behavior

The Flow logs aren't tagged. This is causing drift to the stack.

### Test Cases

- Create CF stack with VPC Flow logs and another resource
- Add stack-level tags to the CF stack
- VPCFlow logs won't be tagged while the other resource is tagged.

**Comment by lvthillo** [comment]
@cfn-github-issues-bot The same appears to be true for Route Tables.

**Comment by MrSakhs** [comment]
+1
