### ISSUE TITLE
A Syntax Error is reported when using aws-cfn-bootstrap v2.0 and python3.9

### ISSUE THREAD

**Issue by micko920** [aws-cloudformation/cloudformation-coverage-roadmap#1099]
### Name of the resource

Other

### Resource Name

AWS::CloudFormation::Init

### Issue Description

When using version 2.0 of the cfn bootstrap helper scripts and python 3.9 it reports a syntax error. ~~This causes a non-zero return code and can fail commands in cloud formation scripts.~~

### Expected Behavior

```
# cfn-init -h
Options:
  -h, --help            show this help message and exit
  -s STACK_NAME, --stack=STACK_NAME
                        A CloudFormation stack
  -r LOGICAL_RESOURCE_ID, --resource=LOGICAL_RESOURCE_ID
                        A CloudFormation logical resource ID
  -c CONFIGSETS, --configsets=CONFIGSETS
                        An optional list of configSets (default: "default")
  -u ENDPOINT, --url=ENDPOINT
                        The CloudFormation service URL. The endpoint URL must
                        match the region option. Use of this parameter is
                        discouraged.
  --region=REGION       The CloudFormation region. Default: us-east-1.
  -v, --verbose         Enables verbose logging

  AWS Credentials:
    Options for specifying AWS Account Credentials.

    -f CREDENTIAL_FILE, --credential-file=CREDENTIAL_FILE
                        A credential file, readable only by the owner, with
                        keys 'AWSAccessKeyId' and 'AWSSecretKey'
    --role=IAM_ROLE     An IAM Role
    --access-key=ACCESS_KEY
                        An AWS Access Key
    --secret-key=SECRET_KEY
                        An AWS Secret Key

  Proxy:
    Options for specifying proxies. Format:
    [scheme://][user:password@]host:port

    --http-proxy=HTTP_PROXY
                        A (non-SSL) HTTP proxy
    --https-proxy=HTTPS_PROXY
                        An HTTPS proxy
```

### Observed Behavior

```

/usr/local/bin/cfn-init:115: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if type(e).__name__ is "ValueError" or type(e).__name__ is "JSONDecodeError":
/usr/local/bin/cfn-init:115: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if type(e).__name__ is "ValueError" or type(e).__name__ is "JSONDecodeError":
/usr/local/bin/cfn-init:133: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if type(e).__name__ is "ValueError" or type(e).__name__ is "JSONDecodeError":
/usr/local/bin/cfn-init:133: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if type(e).__name__ is "ValueError" or type(e).__name__ is "JSONDecodeError":
```

### Test Cases

Running `cfn-init -h` should ~~return zero exit code.~~ not return a syntax error. The return code is correct.

### Other Details

There is a workaround for this. By calling python directly with the script and arguments you can pass `-Wignore` to stop the warning. 
```
# python3.9 -Wignore cfn-init -h
```

**Comment by micko920** [comment]
Having worked on the issue a little I found that I was wrong about the return exit code being non-zero after the execution of the script. It still gives the warning. But it returns a 0 exit code when it executes successfully.

**Comment by shri-tambe** [comment]
Due to latest changes since python 3.8, python will throw syntax warning on usage of `is` operator for quality. CloudFormation scripts use this operator at few places. CloudFormation team is taking action to replace that operator with suggested equality operator `==`. Because customers have workaround to ignore this warning, this is being targeted to be fixed by end of May. Please monitor this issue for further updates.

**Comment by JeremySB** [comment]
This issue should be resolved in the latest version of cfn-init. Thanks
