### ISSUE TITLE
AWS::Glue::Crawler-Targets-ExistingTable

### ISSUE THREAD

**Issue by yellowmamba** [aws-cloudformation/cloudformation-coverage-roadmap#110]
* Scope of request -> AWS::Glue::Crawler::Targets supports `JdbcTargets` and `S3Targets` today, but not support existing catalog tables.

* Expected behavior:
- In Create, it should include a property for source type, like the console where you choose `data store` or `existing catalog tables`.
- In Update, it shouldn't require replacement.

* Test case recommendation: it should help me create a crawler targeting an existing Athena table.

* Context: https://docs.aws.amazon.com/glue/latest/dg/define-crawler.html#crawler-source-type

**Comment by brianterry** [comment]
Hi @yellowmamba ,
AWS::Glue::Crawler::Targets supports `CatalogTargets` now.

Please see our documentation:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-crawler-targets.html
