### ISSUE TITLE
[AWS::DocDB::DBCluster] Restoring to a Point in Time

### ISSUE THREAD

**Issue by greg5123334** [aws-cloudformation/cloudformation-coverage-roadmap#1100]
### Name of the resource

AWS::DocDB::DBCluster

### Description

There does not seem to be native support for restoring a [AWS::DocDB::DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html) to a point in time, as per [Restoring to a Point in Time](https://docs.aws.amazon.com/documentdb/latest/developerguide/backup_restore-point_in_time_recovery.html). Granted, one is able to restore from a [SnapshotIdentifier](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html#cfn-docdb-dbcluster-snapshotidentifier), but this isn't quite the same thing.

**Would it be possible to cover the 'Restoring to a Point in Time' DocDB feature in Cloudformation?**

Please let me know if you need any further info from my side and I'll be happy to help.

### Other Details

Boto3 - [restore_db_cluster_to_point_in_time](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/docdb.html#DocDB.Client.restore_db_cluster_to_point_in_time)

**Comment by vezinj** [comment]
This feature is now supported. Thank you for raising this issue!
