### ISSUE TITLE
AWS Synthetics Canary Tags not Propagated

### ISSUE THREAD

**Issue by JordanSinko** [aws-cloudformation/cloudformation-coverage-roadmap#1101]
### Name of the resource

AWS::Synthetics::Canary

### Description

When tagging my canaries, the tags are not propagated to other services that the canary creates, like the Lambda functions it creates on my behalf. I would like provided tags to be added to all underlying infrastructure created as a side-effect of the High-Level resource.

**Comment by pbudzon** [comment]
Has this been done? As of today, when updating tags on Canaries, the Lambda function does NOT get the tags. Also, standard CloudFormation tags (stack name and id) are not placed on the Canary.

**Comment by jcajkovic** [comment]
same question as @pbudzon - was this implemented ? Based on our tests this still does not work.

**Comment by jfversent** [comment]
This is still an issue, and means that canaries are not available in our organisation where we have mandatory cost tags, as the lambda functions are missing the required tag.

**Comment by lvthillo** [comment]
It's shipped so it works now? For me the underlying lambda is still not tagged but I'm using CDK so I'm not sure if it's related. In the end it generates a CF stack which contains a Canary which is tagged properly...

Update: added to CDK: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_synthetics.ResourceToReplicateTags.html

**Comment by llovett2** [comment]
> It's shipped so it works now?

AFAICT this is still an issue.

> For me the underlying lambda is still not tagged but I'm using CDK so I'm not sure if it's related.

This has been fixed, you just need to provide a value for the [ResourcesToReplicateTags property](https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-synthetics-canary.html#cfn-synthetics-canary-resourcestoreplicatetags).
