### ISSUE TITLE
`AWS::EC2::TransitGatewayPeeringAttachment` schema definition: `writeOnlyProperties` refers to undefined property

### ISSUE THREAD

**Issue by ewbankkit** [aws-cloudformation/cloudformation-coverage-roadmap#1105]
### Name of the resource

AWS::EC2::TransitGatewayPeeringAttachment

### Issue Description

The `AWS::EC2::TransitGatewayPeeringAttachment` schema definition contains:

```
    "writeOnlyProperties": [
        "/properties/Options"
    ]
```

but there is no property defined named `Options`.

### Expected Behavior

`writeOnlyProperties` should only refer to defined properties.

### Observed Behavior

`writeOnlyProperties` refers to an undefined property `Options`.

### Test Cases

Ensure that all `writeOnlyProperties` refer to defined properties.

**Comment by PatMyron** [comment]
tracking in:
https://github.com/aws-cloudformation/cloudformation-resource-schema/issues/17
https://github.com/aws-cloudformation/cloudformation-cli/issues/841
