### ISSUE TITLE
Lambda runtime support for .NET6

### ISSUE THREAD

**Issue by SHAISRIN000** [aws-cloudformation/cloudformation-coverage-roadmap#1108]
### Name of the resource

AWS::Lambda::Function

### Description

AWS Lambda console supports .NET6 , however CFN does not support this runtime based on the documentation
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime .

Lack of this support is  impacting CDK as well https://github.com/aws/aws-lambda-dotnet/issues/1088#issuecomment-1050425142

Requesting for Lambda .NET6 runtime support in CFN to support IaC .

**Comment by micahduron** [comment]
Hello, the documentation for both CFN and CDK have been updated to include the `dotnet6` runtime.

**Comment by SHAISRIN000** [comment]
Great ,Thanks for the update.
