### ISSUE TITLE
VersionDescription parameter support

### ISSUE THREAD

**Issue by FireballDWF** [aws-cloudformation/cloudformation-coverage-roadmap#1117]
### Name of the resource

AWS::EC2::LaunchTemplate

### Description

The VersionDescription parameter supported by the API should be supported by the cfn resource

### Other Details

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateLaunchTemplate.html

**Comment by cheenar-aws** [comment]
Hey! Sorry for the delay on this. Launch Templates has released an update to the CloudFormation resource to now include the `VersionDescription` parameter ⛵️

**Documentation**: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-launchtemplate.html
