### ISSUE TITLE
AWS::MediaConnect::Flow (Support for Fujitsu QoS protocol)

### ISSUE THREAD

**Issue by mpnguyenaws** [aws-cloudformation/cloudformation-coverage-roadmap#1134]
### Name of the resource

AWS::MediaConnect::Flow

### Description

Support for Fujitsu QoS protocol is available in AWS Elemental MediaConnect from [Dec 2021](https://aws.amazon.com/about-aws/whats-new/2021/12/fujitsu-qos-protocol-aws-elemental-mediaconnect/), however, CloudFormation does not support these new properties yet (for example: **SenderControlPort** and **SenderIpAddress** under **Source**)

**Comment by xunlu39** [comment]
You can now use AWS CloudFormation templates to create and configure AWS Elemental MediaConnect flows using the Fujitsu QoS protocol.
