### ISSUE TITLE
AWS::Logs::LogGroup Tags forcefully removing existing tags

### ISSUE THREAD

**Issue by tigris** [aws-cloudformation/cloudformation-coverage-roadmap#1137]
### Name of the resource

AWS::Logs::LogGroup

### Issue Description

When you alter the tags of a log group via cloudformation (either via stack-level tags or resource-level tags), cloudformation will trigger an `UntagLogGroup` event for each tag on that log group that is not a part of this cloudformation stack.

This behaviour seems specific to `AWS::Log::LogGroup` resource types. We're not seeing the same behaviour on other resource types, such as `AWS::EC2::Instance` for example, where updating any of the tags via cloudformation won't result changes to other tags that might exist on the resource. So the tagging behaviour seems wildly different for this `AWS::Logs::LogGroup` resource type.

Given tagging Log Groups via cloudformation was never possible until very recently, we have a _very_ large amount of Log Groups that contain tags that were obviously not put there via cloudformation. Some are being put there by by an API call after a stack-update as part of the deploy script. Some are being controlled via a cloudformation custom resource inside the stack. These were all bespoke implementations that were required at the time. All of these tags are now getting forcefully removed when a stack update happens. We use these tags for very important business value, such as how to treat these logs when it comes to centralised log ingestion, or which business unit to cost them out to.

After reviewing our CloudTrail events, we've determined this only started happening on March 29. We do see some functionality was merged [here](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-logs/pull/86) on March 1, but we have confirmed this functionality wasn't occurring for us until March 29. We see deployments on March 28 that did not untag any log groups at all, then the very same deployment processes resulted in untag events the next day.

### Expected Behavior

I would expect cloudformation to not delete tags that it is not in control of. Other resource types work in this way.

Alternatively, I would expect all resource types to act the same way, and all resource types should remove tags that the cloudformation doesn't know about.

We're unsure which of these would be the expected behaviour, so we're currently unsure if this is considered a "bug" in `AWS::Logs::LogGroup`, or is it a bug in every other resource type?

### Observed Behavior

Cloudformation is forcefully removing tags on `AWS::Log::LogGroup` resources that are not included in the cloudformation stack.

### Test Cases

```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyInstance:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: my-test-log-group
      Tags:
        - Key: resource-tag
          Value: test
```

When I deploy the above stack via cloudformation, I will receive 1 log group, with a resource-level tag. I then use the AWS Console to create an extra tag `custom-tag=true`, and witness in the console that my log group now has 2 tags.

I then make an update to my YAML and change the value of my `resource-tag` to `test2` and I trigger an `update-stack`.

I then witness my `custom-tag` disappear via the console.

**Comment by felixfang** [comment]
Hi this looks like a generic question on all resources managed by CFN template. The changes made out of CFN template will be overriden by CFN template. 
 
CFN has a drift detection feature so we can preview the manual change will be difted by CFN template
 deployment https://aws.amazon.com/blogs/aws/new-cloudformation-drift-detection/
