### ISSUE TITLE
AWS::Amplify::App - Allow setting Build Image Settings

### ISSUE THREAD

**Issue by dbartholomae** [aws-cloudformation/cloudformation-coverage-roadmap#1140]
### Name of the resource

AWS::Amplify::App

### Description

Currently, it is not possible to define `Build image settings` like `Build image` and `Live package updates` for Amplify apps. Without this, it is not possible to e.g. deploy an application that relies on a newer NodeJS version than the default one.

**Comment by oliver-leung** [comment]
We recommend that you configure Build image and Live package updates through the environment variables `_CUSTOM_IMAGE` and `_LIVE_UPDATES`, respectively, in the `EnvironmentVariables` property. Documentation about environment variables can be found [here](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html), and we are currently working to add more info on `_CUSTOM_IMAGE`.

**Comment by dbartholomae** [comment]
@oliver-leung Thanks! What's the best ticket to track to be informed about the documentation for `_CUSTOM_IMAGE`? Or could you give a short example in this thread of how to use it?

**Comment by oliver-leung** [comment]
I believe you just need to set the `_CUSTOM_IMAGE` variable to the name of an ECR repo - more details on that [here](https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup).

**Comment by dbartholomae** [comment]
@oliver-leung Thanks! Do you also know where I can find more info on `_LIVE_UPDATES`? I've tried to add a live update for NodeJs, but I'm unsure what to add for two of the fields:

```
{"name":"Node.js version","pkg":"???","type":"???","version":"16.14.2"}
```

**Comment by oliver-leung** [comment]
- `pkg` should be the name of the module as you would write it in your `package.json`, e.g. `@aws-amplify/cli`
- `type` should be the package manager that you would like to source the version from, like `npm` or `yarn`

[This documentation page](https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables) has an example of how you would format the `_LIVE_UPDATES` JSON:
```
[{“name”:”Amplify CLI”,”pkg”:”@aws-amplify/cli”,”type”:”npm”,”version”:”latest”}]
```

Also, if you would like to configure your Node version, you should do that by adding `nvm install $VERSION_NODE_16` in your `amplify.yml`'s prebuild steps (more available environment variables [here](https://github.com/aws-amplify/amplify-hosting/blob/main/images/latest/Dockerfile)).

**Comment by dbartholomae** [comment]
Thanks! The solution I found in some Japanese forum for Node is:
```
[{
  "pkg":"node",
  "type":"nvm",
  "version":"16.14.2",
}]
```

Is there an easy way to get this into the documentation? Or ideally a list of possible `type`s as well as an explanation what `name` does (I assume it is optional)?

**Comment by monkut** [comment]
@dbartholomae Where do you set that in the `AWS::Amplify::App`?
Are these 3 separate environment variables that need to be set?

**Comment by dbartholomae** [comment]
```ts
const overrides = [{
  "pkg":"node",
  "type":"nvm",
  "version":"16.14.2",
}]

const amplifyApp = new amplify.App(this, 'MyApp', {
  // ...
  environmentVariables: { '_LIVE_UPDATES': JSON.stringify(overrides) }
})
```
