### ISSUE TITLE
AWS::AutoScaling::LaunchConfiguration - Missing Instance Metadata Tags support.

### ISSUE THREAD

**Issue by SirPyros** [aws-cloudformation/cloudformation-coverage-roadmap#1141]
### Name of the resource

AWS::AutoScaling::LaunchConfiguration

### Description

Instance metadata Tags support has not been added to Launch Configurations. It is currently available for LaunchTemplates.

**Comment by ashemedai** [comment]
I think your ask will never be implemented as AWS was planning on removing LaunchConfiguration [somewhere last year](https://aws.amazon.com/blogs/compute/amazon-ec2-auto-scaling-will-no-longer-add-support-for-new-ec2-features-to-launch-configurations/).
