### ISSUE TITLE
Tag update for AWS::EC2::TransitGateway leads to replacing the CloudFormation resource

### ISSUE THREAD

**Issue by albaymar** [aws-cloudformation/cloudformation-coverage-roadmap#1144]
### Name of the resource

AWS::EC2::TransitGateway

### Issue Description

Currently updating the Tags property of a Transit Gateway causes resource replacement; however the underlying API (https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-transit-gateway.html) allows making such an update without replacement.

### Expected Behavior

The existing Transit Gateway resource updates its tag

### Observed Behavior

The Transit Gateway resource is recreated.

### Test Cases

* Create a CFN stack with a Transit Gateway resource
* Update a tag on the Transit Gateway
* Observe the Transit Gateway resource being replaced

**Comment by davidadas** [comment]
@albaymar what region is this not working in currently?

**Comment by kallu** [comment]
FYI; This isn't just TGW itself but also `AWS::EC2::TransitGatewayAttachment` does suffer from the similar behavior.
See https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-transitgateway/issues/124
