### ISSUE TITLE
Drift Detection Support for AWS::Lambda::Permission

### ISSUE THREAD

**Issue by morries4321** [aws-cloudformation/cloudformation-coverage-roadmap#1145]
### Name of the resource

AWS::Lambda::Permission

### Resource name

AWS::Lambda::Permission

### Description

As per [1], the "AWS::Lambda::Permission" resource is not supported resource for drift detection. Hence, requesting for drift detection support for the "AWS::Lambda::Permission" resource.

[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

**Comment by rgoltz** [comment]
* => link this case to master-case: #218

**Comment by TheDanBlanco** [comment]
this is now supported as reflected by https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html
