### ISSUE TITLE
Issue marked as shipped, but doesn't appear to be #1092

### ISSUE THREAD

**Issue by jvisker** [aws-cloudformation/cloudformation-coverage-roadmap#1146]
### Name of the resource

Other

### Description

#1092 shows as shipped, but nothing seems to have changed.

**Comment by prerna-p** [comment]
I've reopened #1092

**Comment by Negan1911** [comment]
@prerna-p ticket is still showing as "shipped" on the roadmap but it's definitively not: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/projects/1?card_filter_query=aws+app+runner#card-78396916
