### ISSUE TITLE
SNS Chatbot Configuration association resource

### ISSUE THREAD

**Issue by wayne-folkes** [aws-cloudformation/cloudformation-coverage-roadmap#1155]
### Name of the resource

AWS::Chatbot::SlackChannelConfiguration

### Description

This is a new resource for an existing service. The user story is the following

I have multiple services that need their Cloudwatch Alarm notifications sent to slack via Chatbot. Because the services are owned by the same team I want the alerts to go to the same channel. You cannot create multiple `AWS::Chatbot::SlackChannelConfiguration` that publish to the same slack channel. I would like a way when creating the CF stack for my apps that I can associate my alarm SNS topics with an existing`SlackChannelConfiguration`

**Comment by mekathry** [comment]
Hello and thanks for reaching out to us! At this time, there is no way of creating multiple SlackChannelConfiguration for the same channel id. However, we do support [multiple](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-chatbot-slackchannelconfiguration.html#cfn-chatbot-slackchannelconfiguration-snstopicarns) sns topic arns, which should be a work around for this.
