### ISSUE TITLE
Support for Drift Detection for DynamoDB Table/Stream Configurations

### ISSUE THREAD

**Issue by magnoll-amzn** [aws-cloudformation/cloudformation-coverage-roadmap#1167]
### Name of the resource

AWS::DynamoDB::Table

### Description

We own a DynamoDB table that is created via CDK. The table was originally created without a table stream and was working smoothly. A manual change outside CDK enabled the stream, and now when we try to push a change enabling the stream via CloudFormation the deployment fails with the following error:

```
Table already has an enabled stream: TableName: MyTableName (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: ABCDEFG; Proxy: null)
```

Luckily we're not using actually using the stream yet in production so we believe this can be fixed by the manual operation of disabling the stream. If we were using the stream in production, I'm not sure how we would have solved this issue without data loss. My understanding is that drift detection is specifically meant to address this, but based on conversations with AWS support, that is not yet supported by Dynamo.

Our request is to have Dynamo support drift detection so that it can automatically fix configurations that have changed outside of CloudFormation. Thank you!

**Comment by aygold92** [comment]
DDB Table has been added to the drift detection supported resource list https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html
