### ISSUE TITLE
AWS::QuickSight::DataSet LogicalTableSource / DataSetArn missing

### ISSUE THREAD

**Issue by pt-kojoa** [aws-cloudformation/cloudformation-coverage-roadmap#1171]
### Name of the resource

AWS::QuickSight::DataSet

### Description

AWS Quicksight has a support to reference data-set inside another data-set. This feature is already supported by AWS CLI Quicksight module but for some reason not in Cloudformation. In AWS CLI module, _LogicalTableSource_ can contain source element with _DataSetArn_ property that can be used for referencing another data-set. Cloudformation only has _PhysicalTableId_.

Another thing related to this is, that with AWS CLI, _physicalTableMap_ can be empty, when it's not needed. With Cloudformation or CDK it can't be empty: 

```
UPDATE_ROLLBACK_COMPLETE: Properties validation failed for resource fubar with message:
#/PhysicalTableMap: minimum size: [1], found: [0]
#/LogicalTableMap/fubar/Source/PhysicalTableId: expected maxLength: 64, actual: 67
```

I initially reported this to CDK github repository but it turned out to be missing feature in CloudFormation. See initial issue here: https://github.com/aws/aws-cdk/issues/20229

### Other Details

 - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-dataset-logicaltablesource.html
 - https://docs.aws.amazon.com/cli/latest/reference/quicksight/create-data-set.html

**Comment by dacgray** [comment]
@pt-kojoa I followed your trail here.  Any fix that you know of yet?

**Comment by peterjdavis** [comment]
+1, I'm also not able to get this working

**Comment by pt-kojoa** [comment]
@dacgray haven't touched related project in over a year. At that time I did work around this creating base data-sets with CDK and intermediate data-sets with AWS CLI. With a quick look, it seems that data-set ARN can now be added to both Cloudformation template and also into CDK stack.
