### ISSUE TITLE
StackSets do not handle suspended accounts gracefully

### ISSUE THREAD

**Issue by shantgup** [aws-cloudformation/cloudformation-coverage-roadmap#1177]
### Name of the resource

Other

### Resource Name

AWS StackSets

### Issue Description

Currently, when an account included in a StackSet is suspended, it is not detected by the StackSet and the account remains in the StackSet indefinitely until it is manually removed. While this account remains in the StackSet, it causes a variety of unexpected behaviors such as failed deployments, stuck operations and inaccurate error messages.

### Expected Behavior

The request is to have StackSets detect when an account has been suspended, notify the user about this detection, and then remove the account from the StackSet. If not remove, the account should not be considered in any subsequent StackSet operations or deployments.

### Observed Behavior

Currently, StackSets does not detect, notify or remove the suspended account gracefully. 

### Test Cases

Create a StackSet with several accounts, suspend some of the accounts, and perform an update on the StackSet.

**Comment by krishansrimal** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-removal-stacksets/

**Comment by zhaomicx** [comment]
This feature was added last year. https://aws.amazon.com/about-aws/whats-new/2023/06/aws-cloudformation-stacksets-suspended-accounts-deployments/
