### ISSUE TITLE
Roadmap FAQs claim a term is "obvious"

### ISSUE THREAD

**Issue by jas7553** [aws-cloudformation/cloudformation-coverage-roadmap#119]
In the [CloudFormation Public Coverage Roadmap FAQs](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap#user-content-faqs), the question "What do the roadmap categories mean?" says, "Shipped - should be obvious :)".

This kind of language is condescending to readers for whom this is *not* obvious. For example, those whose first language is not English, or a frustrated user just trying to figure out what roadmap categories mean. The tone of this passage is flippant, rather than professional.

---

1. https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap#user-content-faqs

**Comment by luiseduardocolon** [comment]
I apologize for the unintended tone.  I used language that was approved from another repository.  I will plan to change it based on your feedback.  I will let you know when I do.

**Comment by Ricapar** [comment]
While we're here, I think it could be valuable to further define what Shipped actually entails. There are some things that to me I would assume are obvious based on my definition of "Shipped", but not everyone may agree.

To me, "Shipped" means:

* All docs are fully updated with the new feature
* There was some formal announcement/changelog somewhere that shows it was released
* I can pick it up and use it on any AWS account.

**Comment by rjlohan** [comment]
#120 adds some basic explanation but we might expand on it a little. @luiseduardocolon to have a look.

**Comment by ikben** [comment]
> To me, "Shipped" means:
> 
> - All docs are fully updated with the new feature
> - There was some formal announcement/changelog somewhere that shows it was released
> - I can pick it up and use it on any AWS account.

For me (as a CloudFormation Coverage roadmap user), the definition of shipped is a bit less. I think the test that I make in my head is "Can I start using it now?". That would include it being part of the Resource Documentation and being usable in every account/region. But not necessarily a formal announcement.
For some workflows it might mean being published in the resource spec

**Comment by rjlohan** [comment]
For what it's worth, our definition of 'Shipped' is likely to be something like;

* A release note exists in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html
* The CloudFormation Resource Specification has been updated 
* Documentation has been updated and published

Beyond that, we can't make guarantees around whether a feature is available in all regions or even all accounts, depending on the nature of the underlying service.

**Comment by PatMyron** [comment]
Should shipped issues also be closed?

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/10
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/11
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/12
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/13
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/16
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/17
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/22
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/24
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/26
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/27
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/28
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/29
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/30

**Comment by jas7553** [comment]
Why was this closed?

**Comment by brianterry** [comment]
@jas7553, sorry, closed based on this PR:
#120
