### ISSUE TITLE
AWS::Lightsail::Database "Data Import Mode Enabled"

### ISSUE THREAD

**Issue by sgargel** [aws-cloudformation/cloudformation-coverage-roadmap#1192]
### Name of the resource

AWS::Lightsail::Database

### Resource name

AWS::Lightsail::Database

### Reference Link

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-database.html

### Details

After creating the database resource with cludformation, it's always in "Data Import Mode Enabled" state.

There is no documentation pointing to how disable "Data Import Mode" using cloudformation.

**Comment by godduv-amzn** [comment]
`Data Import Mode` can be configured by using the `BackupRetention` field in the CloudFormation template. Data Import Mode is enabled when BackupRetention is set to false, and is disabled when BackupRetention is set to true.

We have updated the docs to reflect this: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lightsail-database.html
