### ISSUE TITLE
Add PolicyOption to SecurityServicePolicyData attribute for AWS Firewall Manager Policies

### ISSUE THREAD

**Issue by agarwalrahul82** [aws-cloudformation/cloudformation-coverage-roadmap#1194]
### Name of the resource

AWS::FMS::Policy

### Description

AWS Firewall Manager added support to deploy Centralized Network Firewall. To deploy that we have to pass PolicyOption as part of SecurityServicePolicyData  attribute in Firewall Manager Policy, however, its not supported by Cloudformation.

**Excerpt from AWS CLI documentation:** https://docs.aws.amazon.com/cli/latest/reference/fms/put-policy.html

"SecurityServicePolicyData": {
"Type":
"WAF"|"WAFV2"|"SHIELD_ADVANCED"|"SECURITY_GROUPS_COMMON"|"SECURITY_GROUPS_CONTENT_AUDIT"|"SECURITY_GROUPS_USAGE_AUDIT"|"NETWORK_FIREWALL"|"DNS_FIREWALL"|"THIRD_PARTY_FIREWALL",
"ManagedServiceData": "string",
"PolicyOption": {
"NetworkFirewallPolicy": {
"FirewallDeploymentModel": "CENTRALIZED"|"DISTRIBUTED"
},
"ThirdPartyFirewallPolicy": {
"FirewallDeploymentModel": "CENTRALIZED"|"DISTRIBUTED"
}
}
}

### Other Details

Feature Announcement: 
https://aws.amazon.com/about-aws/whats-new/2022/02/aws-firewall-manager-centralized-deployment-model/

References:
https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_SecurityServicePolicyData.html
https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_PutPolicy.html

**Comment by wy3148** [comment]
This is confirmed, we are in the process of release. once it's done we will update the status of this ticket.

**Comment by stevec1980** [comment]
Hello, we are having an issue with this too.

Is there any ETA?
