### ISSUE TITLE
Stack-level CF tags are not propagated to AWS::Batch::JobQueue

### ISSUE THREAD

**Issue by deimagjas** [aws-cloudformation/cloudformation-coverage-roadmap#1195]
### Name of the resource

AWS::Batch::JobQueue

### Issue Description

AWS::Batch::JobQueue does not apply stack level tags during CloudFormation stack create or update operations.

### Expected Behavior

All stack level tags applied to AWS::Batch::JobQueue resource.

### Observed Behavior

Stack level user tags do not get propagated to AWS::Batch::JobQueue resource during CloudFormation Create or Update operation.

### Test Cases

- Create a CF stack with  AWS::Batch::JobQueue and some other resources

- Add stack-level tags to the CF stack

- Stack level tags not propagated to the AWS::Batch::JobQueue while the other resources are tagged.

**Comment by luisantonioa** [comment]
We are aware of the issue and believe we have a fix. Once tested and rolled out we will update this thread.
