### ISSUE TITLE
Stack-level CF tags are not propagated to AWS::Batch::ComputeEnvironment

### ISSUE THREAD

**Issue by deimagjas** [aws-cloudformation/cloudformation-coverage-roadmap#1196]
### Name of the resource

AWS::Batch::ComputeEnvironment

### Issue Description

AWS::Batch::ComputeEnvironment  does not apply stack level tags during CloudFormation stack create or update operations.

### Expected Behavior

All stack level tags applied to AWS::Batch::ComputeEnvironment resource.

### Observed Behavior

Stack level user tags do not get propagated to AWS::Batch::ComputeEnvironment  resource during CloudFormation Create or Update operation.

### Test Cases

- Create a CF stack with AWS::Batch::ComputeEnvironment and some other resources

- Add stack-level tags to the CF stack

- Stack level tags not propagated to the AWS::Batch::ComputeEnvironment while the other resources are tagged.

**Comment by tommydongaws** [comment]
This issue seem to be affecting AWS::ElastiCache::ReplicationGroup as well.

**Comment by luisantonioa** [comment]
We are aware of the issue and believe we have a fix. Once tested and rolled out we will update this thread.

**Comment by pbudzon** [comment]
Has this been actually fixed? We have multiple compute environments which did NOT get any CloudFormation tags, even though they were just replaced due to other changes.
