### ISSUE TITLE
[AppRunner] Missing AutoscalingConfiguration resource

### ISSUE THREAD

**Issue by miloszpiglas** [aws-cloudformation/cloudformation-coverage-roadmap#1205]
### Name of the resource

AWS::AppRunner::Service

### Description

[AutoscalinConfiguration ](https://docs.aws.amazon.com/apprunner/latest/api/API_AuthenticationConfiguration.html) can be referenced in [AppRunner::Service](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-service.html#cfn-apprunner-service-autoscalingconfigurationarn) but it is not possible to create such resource with Cloudformation.

Existing API actions:
* https://docs.aws.amazon.com/apprunner/latest/api/API_CreateAutoScalingConfiguration.html
* https://docs.aws.amazon.com/apprunner/latest/api/API_DeleteAutoScalingConfiguration.html

**Comment by snnles** [comment]
https://github.com/aws/apprunner-roadmap/issues/88

**Comment by rhbecker** [comment]
If this is _actually_ shipped, should I be expecting to see a new page documenting it, and linked from the [AWS App Runner resource type reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_AppRunner.html) page?

**Comment by rhbecker** [comment]
Tangentially related, the [AWS App Runner resource type reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_AppRunner.html) page seems out of sync with what's in GitHub - note that the former has a page documenting [AWS::AppRunner::ObservabilityConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apprunner-observabilityconfiguration.html) that [does NOT seem to exist in the public GitHub repo](https://github.com/awsdocs/aws-cloudformation-user-guide/tree/main/doc_source/aws-resource-apprunner-observabilityconfiguration.md).

**Comment by hiebj** [comment]
So what is the actual answer here? Can we create AutoscalingConfiguration with CloudFormation? The documentation does not appear to have changed since @rhbecker commented on Jul 15, 2022. This is an important question.

Do we need to create a separate issue to update the documentation, or is this not officially supported?

**Comment by Negan1911** [comment]
Is there a reason why this is shipped and done where it looks that there's not

**Comment by Negan1911** [comment]
Well, being tired of this issue not being solved for a year, I did my own resource, so if you use CDK, you can use this to handle Autoscaling with it: https://www.npmjs.com/package/cdk-apprunner-autoscaling.

I'm quite sure there will be also a way if you use plain Cloudformation, let me know if you know how and need help

**Comment by rhbecker** [comment]
Though I believe the original closure of this issue was inadvertent, it does appear that this support [actually shipped](https://github.com/aws/apprunner-roadmap/issues/88#issuecomment-1604732702) within the last couple of months.
