### ISSUE TITLE
Support for Matching property in AWS::CustomerProfiles::Domain

### ISSUE THREAD

**Issue by nikheelsoni** [aws-cloudformation/cloudformation-coverage-roadmap#1207]
### Name of the resource

AWS::CustomerProfiles::Domain

### Description

Currently the resource AWS::CustomerProfiles::Domain does not support the property "Matching"however, the [respective API ](https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_CreateDomain.html#customerprofiles-CreateDomain-request-Matching) does in fact support this property.

Can you please add support for the property "Matching" for the AWS::CustomerProfiles::Domain resource.

**Comment by vallabja** [comment]
Issue resolved, added support for Matching property in `AWS::CustomerProfiles::Domain`
