### ISSUE TITLE
Support values ASSET and CASE  in parameter StandardIdentifiers of AWS::CustomerProfiles::ObjectType ObjectTypeKey

### ISSUE THREAD

**Issue by Marrwen** [aws-cloudformation/cloudformation-coverage-roadmap#1210]
### Name of the resource

AWS::CustomerProfiles::ObjectType

### Description

Resource of type AWS::CustomerProfiles::ObjectType supports only the following types of keys that a ProfileObject can have:

UNIQUE | PROFILE | SECONDARY | LOOKUP_ONLY | NEW_ONLY  

can you add support for the values  ASSET and CASE as it is possible from the API https://docs.aws.amazon.com/customerprofiles/latest/APIReference/API_ObjectTypeKey.html#customerprofiles-Type-ObjectTypeKey-StandardIdentifiers

**Comment by vallabja** [comment]
Added support for ASSET and CASE standard identifiers. Resolving the ticket as the next steps (pushing the change to Github repo) will be tracked in a different ticket (other github open issues related to AWS Customer Profiles)
