### ISSUE TITLE
AWS::FMS::Policy missing in AWS China

### ISSUE THREAD

**Issue by StephanR2** [aws-cloudformation/cloudformation-coverage-roadmap#1211]
### Name of the resource

AWS::FMS::Policy

### Description

Should be able to use AWS::FMS::Policy in AWS China Regions, Beijing and Ningxia.

### Other Details

Firewall Manager Service has been available in AWS China since August 2021. https://www.amazonaws.cn/en/new/2021/amazon-firewall-manager-available-amazon-web-services-china-regions/

**Comment by wy3148** [comment]
AWS Firewall manager service has confirmed we have not launched the cloudformation support for AWS::FMS::Policy resource. We will update once we launch the support.

**Comment by AustinHoag98** [comment]
AWS Firewall Manager has launched CloudFormation support for `AWS::FMS::Policy` in the China (Beijing) and China (Ningxia) Regions.
