### ISSUE TITLE
AWS::EFS::FileSystem - Drift Detection false positive for KmsKeyId property under AWS::EFS::FileSystem resource

### ISSUE THREAD

**Issue by surbhbh** [aws-cloudformation/cloudformation-coverage-roadmap#1219]
### Name of the resource

AWS::EFS::FileSystem

### Issue Description

The KmsKeyId property for the AWS::EFS::FileSystem resource is marked as drifted when alias is given to the resource.

Ideally, drift detection should not have been performed on the KmsKeyId property as per - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html#drift-considerations

```
CloudFormation does not perform drift detection on the KMSKeyId property of any resources. Because AWS KMS keys can be referenced by multiple aliases, CloudFormation can't guarantee consistently accurate drift results for this property.
```

### Expected Behavior

The KmsKeyId property should be IN_SYNC or NOT_CHECKED status.

### Observed Behavior

The KmsKeyId property is marked as NOT_EQUAL with
expected = xxxx-xxxx-xxxx-xxxx
actual = arn:aws:kms:eu-central-1:123465798123:key/xxxx-xxxx-xxxx-xxxx

### Test Cases
```
"efsABCabc1ABAA234": {
   "Type": "AWS::EFS::FileSystem",
   "Properties": {
    "Encrypted": true,
    "FileSystemTags": [
     {
      "Key": "ApplicationID",
      "Value": "xxxx"
     },
     {
      "Key": "ApplicationName",
      "Value": "xxxx"
     },
     {
      "Key": "Environment",
      "Value": "xxx"
     },
     {
      "Key": "Name",
      "Value": "xxxxxxx"
     }
    ],
    "KmsKeyId": {
     "Fn::Join": [
      "",
      [
       "arn:",
       {
        "Ref": "AWS::Partition"
       },
       ":kms:eu-central-1:xxxxxxxx:alias/xxxxxxxxxxxxxxx"
      ]
     ]
    }
```

**Comment by rgoltz** [comment]
I've re-tested a bunch of stacks with AWS::EFS::FileSystem having a KMS-Alias defined for propertry KmsKeyId: By running a new/fresh Drift Detection in eu-central-1 region, it's still showing a false-positive drift result for KmsKeyId.

**Comment by rgoltz** [comment]
Retested again - Our stacks with AWS::EFS::FileSystem using a KMS-Alias for prop KmsKeyId is now IN_SYNC 🌟

**Comment by surbhbh** [comment]
Thanks Robert for the update. Closing the issue now.
