### ISSUE TITLE
AWS::CloudFront::Distribution - UpdatePolicy

### ISSUE THREAD

**Issue by jramakan** [aws-cloudformation/cloudformation-coverage-roadmap#122]
## 1. Title 
AWS::CloudFront::Distribution-UpdatePolicy

## 2. Scope of request 
Enable Cloudformation to provide the same "update bucket policy" functionality provided in the AWS Console when setting up an S3 origin for Cloudfront

## 3. Expected behavior
ref:https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html#private-content-granting-permissions-to-oai

The expected behavior is described here:
If you want CloudFront to automatically give the origin access identity permission to read the files in the Amazon S3 bucket specified in Origin Domain Name, click Yes, Update Bucket Policy.

If you choose Yes, Update Bucket Policy, CloudFront updates bucket permissions to grant the specified origin access identity the permission to read files in your bucket. However, CloudFront does not remove existing permissions. If users currently have permission to access the files in your bucket using Amazon S3 URLs, they will still have that permission after CloudFront updates your bucket permissions. To view or remove existing bucket permissions, use a method provided by Amazon S3. For more information, see Granting the Origin Access Identity Permission to Read Files in Your Amazon S3 Bucket.

**Comment by rama3319** [comment]
I am also running into similar issue. Our s3 buckets are created long back & in production. If I create a bucket policy using cloud formation it says "The bucket policy already exists on bucket ". is there any update on the issue?.
