### ISSUE TITLE
Feature Request - Support import operation for resource type AWS::IAM::ManagedPolicy

### ISSUE THREAD

**Issue by prathikv** [aws-cloudformation/cloudformation-coverage-roadmap#1224]
### Name of the resource

AWS::IAM::ManagedPolicy

### Description

CloudFormation currently doesn't support import resource feature for the IAM Managed policy resource - AWS::IAM::ManagedPolicy. 

Requesting to add resource type AWS::IAM::ManagedPolicy to support import operation.

**Comment by TheDanBlanco** [comment]
managed policies are now [supported](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html)
