### ISSUE TITLE
cannot change EKS cluster encryption config without replacement

### ISSUE THREAD

**Issue by rittneje** [aws-cloudformation/cloudformation-coverage-roadmap#1234]
### Name of the resource

AWS::EKS::Cluster

### Issue Description

EKS supports enabling (but not disabling) secret encryption on an existing cluster. https://docs.aws.amazon.com/eks/latest/userguide/enable-kms.html

However, attempting to enable encryption via CloudFormation will force a replacement for no reason. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html#cfn-eks-cluster-encryptionconfig

### Expected Behavior

Enabling encryption on an existing cluster via CloudFormation should be allowed.

### Observed Behavior

CloudFormation forces a cluster replacement for no reason.

### Test Cases

Create an EKS cluster with encryption disabled. Then update the stack to enable it.

**Comment by lynnnnnnluo** [comment]
Thank you for reaching out, currently we do not support associating encryption config to EKS Clusters through Cloudformation after cluster creation. Please refer to Cloudformation  [document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html#cfn-eks-cluster-encryptionconfig) for property update requires replacement. We do not have a plan to support updating encryption config through CFN at the moment. Currently the workaround is to associate encryption config to the cluster through EKS API directly.

**Comment by rittneje** [comment]
@lynnnnnnluo Was this actually released? I don't see anything about it. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by ktaborski** [comment]
Why this is closed? Can this be fixed
