### ISSUE TITLE
Parameters to Define Visualizations in a QuickSight Analysis

### ISSUE THREAD

**Issue by bretticus-mc** [aws-cloudformation/cloudformation-coverage-roadmap#1238]
### Name of the resource

AWS::QuickSight::Analysis

### Resource name

AWS::QuickSight::Analysis

### Description

There is no way to define visualizations in QuickSight::Analysis at this time. The only work-around I've found is to first create an Analysis with the needed visualizations manually in the UI console. Then I have to reference the ARN of that Analysis in a programmatically created Analysis containing the desired DataSets. This means we can only automate dashboards that use the same DataSet Schema and visualizations.

Each dashboard with different visualizations or schema currently requires an Analysis to be manually created. This severely limits the use-case of the QuickSight CDK as a whole.

### Use Case
We want to fully automate the creation of QuickSight dashboards. There should not be a manual step required to create a dashboard programmatically. Being able to define visuals programmatically will also provide full version control of the dashboards we create.

### Proposed Solution
We need more parameters in the Analysis construct in order to define the visuals that populate our dashboards. Maybe it could even take a JSON payload containing all parameters of the visualizations.

### Other Details

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_quicksight.CfnAnalysis.html

**Comment by youhaoqs** [comment]
Hi @bretticus-mc,

Thanks for providing this feedback. We are aware of this feature request and it is on our roadmap. 

Our team is actively working on providing a parametrized way so that a dashboard/analysis can be created from scratch programmatically. The ETA for delivery should be the end of this year.
