### ISSUE TITLE
AWS::ECR::Repository - (new GetAtt) Address/URI

### ISSUE THREAD

**Issue by lloydpick** [aws-cloudformation/cloudformation-coverage-roadmap#124]
1. Title -> AWS::ECR::Repository
2. Scope of request -> AWS::ECR::Repository should support a !GetAtt of an the repo's address
3. Expected behavior -> When using a !GetAtt on an AWS::ECR::Repository, a host/address should be a valid property and return "01234567890.dkr.ecr.eu-west-1.amazonaws.com/my-repo-name"
4. Test case recommendation (optional) -> No current ability to Ref to an ECR repo, for example within an ECS Task definition, we have to construct it with Joins or Subs. Would save time/mistakes if we could just GetAtt the host and then join the tag we want.
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#aws-resource-ecr-repository-return-values
6. Category tag (optional) -> ECR
7. Any additional context (optional) -> This is adding a GetAtt to an existing resource

**Comment by ebisbe** [comment]
I'd really like to get the URI generated

**Comment by cappellaiomatto** [comment]
It would be useful, as a workaround this is what I did (setting the RepositoryName attribute in the Parameters as "NomeRepository"):

`  !Join [".",[!Sub "${AWS::AccountId}", "dkr", "ecr", !Sub "${AWS::Region}", "amazonaws", "com", !Ref NomeRepository]]`

**Comment by bradgr** [comment]
Thank you for raising this. The RepositoryUri return value is now available: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html
