### ISSUE TITLE
False Drift Detection on AWS::Lambda::Function PackageType property

### ISSUE THREAD

**Issue by scotliu** [aws-cloudformation/cloudformation-coverage-roadmap#1242]
### Name of the resource

AWS::Lambda::Function

### Issue Description

If an AWS::Lambda::Function resource has the PackageType Property, Drift Detection would not see the actual PackageType applied to the function. Thus gives false alarm.

### Expected Behavior

Drift Detection should be able to detect the actual PackageType applied to the function.

### Observed Behavior

$ aws cloudformation describe-stack-resource-drifts --stack-name packagetypedrift

"StackResourceDrifts": [
        {
            ...
            "LogicalResourceId": "TestLambda",
            "PhysicalResourceId": "TestLambda",
            "ResourceType": "AWS::Lambda::Function",
            "ExpectedProperties": "{\"FunctionName\":\"TestLambda\",\"MemorySize\":128,\"PackageType\":\"Image\",\"Role\":\"arn:aws:iam::************:role/lambdaExecutionRole\"}",
            "ActualProperties": "{\"FunctionName\":\"TestLambda\",\"MemorySize\":128,\"Role\":\"arn:aws:iam::************:role/lambdaExecutionRole\"}",
            "PropertyDifferences": [
                {
                    "PropertyPath": "/PackageType",
                    "ExpectedValue": "Image",
                    "ActualValue": "null",
                    "DifferenceType": "REMOVE"
                }
            ],
            "StackResourceDriftStatus": "MODIFIED",
            "Timestamp": "2022-07-14T19:34:17.464000+00:00"
        }
    ]
}

### Test Cases

Create an AWS::Lambda::Function resource with PackageType Property and then try drift detection.  This applies to both value Zip and Image values.

**Comment by psambit9791** [comment]
Is there any update on this? I am encountering the same issue.

**Comment by lucastonelli** [comment]
I've just joined the club:

![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/52139329/12aa4ba1-4652-46b7-8834-c6083886d2a9)

**Comment by alkaales** [comment]
This is a known integration gap between AWS CloudFormation and AWS Lambda. `PackageType` property is missing in drift detection configuration. AWS Lambda is planning to address this issue in Q4 2023.

**Comment by TheDanBlanco** [comment]
hey folks, i've tried to replicate this to no avail. when i run drift on a function with a `PackageType` of `Zip`, it returns `IN_SYNC`. we've been working on our drift detection algorithm to make it more accurate and this appears to have been resolved by it. 

if this isn't the case, please re-open it!
