### ISSUE TITLE
Add Ingestion Schedule for SPICE based Datasets

### ISSUE THREAD

**Issue by robertkossendey** [aws-cloudformation/cloudformation-coverage-roadmap#1244]
### Name of the resource

AWS::QuickSight::DataSet

### Description

Hello,

currently it is not possible to create ingestion schedules via CloudFormation for SPICE based Datasets.
This would be a very helpful addition, since you wouldn't need to create the ingestion via the UI and be able to use a more restrictive permission set that does not allow for the deletion of the dataset.

Best,
Robert

**Comment by trademark18** [comment]
@robertkross I saw this is marked as shipped, but I don't see anything in CF release notes or the documentation about this.  Is this feature fully released and available for use?  I'm not very familiar with the roadmap/release process here, so let me know if I've misunderstood.  Thanks!

**Comment by trademark18** [comment]
Hmm, interesting. Who is the party responsible for the feature's development and release? Who could we contact to find out what the status is?

**Comment by antarabahur** [comment]
@robertkossendey 
I wanted to understand the ask clearly, this is to have a way from cloudformation to create ingestion refresh schedules right? 
This feature: https://docs.aws.amazon.com/quicksight/latest/user/refreshing-imported-data.html through cloud formation?

**Comment by robertkossendey** [comment]
@antarabahur yes exactly! :)

**Comment by antarabahur** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-quicksight-refreshschedule.html

**Comment by robertkossendey** [comment]
@antarabahur amazing, thank you very much!
