### ISSUE TITLE
AWS::Logs::LogGroup don’t receive the aws:cloudformation built-in tags

### ISSUE THREAD

**Issue by aditya2101** [aws-cloudformation/cloudformation-coverage-roadmap#1255]
### Name of the resource

AWS::Logs::LogGroup

### Resource Name

AWS::Logs::LogGroup 

### Issue Description

When you have an AWS::Log::LogGroup resource in your stack, it does not get assigned the built-in tags: aws:cloudformation:stack-name, aws:cloudformation:logical-id and aws:cloudformation:stack-id

This seems to happen both when the resource is created by the stack, and when it is imported.

### Expected Behavior

All stack resources should automatically receive the aws:cloudformation:* built-in tags.

### Observed Behavior

No tags are added automatically to AWS::Log::LogGroup resources.

### Test Cases

AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyInstance:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: my-test-log-group

**Comment by shri-tambe** [comment]
AWS::Logs::LogGroup resource supports aws:cloudformation built-in tags now in all supported regions.

**Comment by nadtakanfuthoem** [comment]
@shri-tambe Is this support on GovCloud?

**Comment by nadtakanfuthoem** [comment]
@shri-tambe When I added tags on toml file to apply with every resources, However, I notice that lambda log group still doesn't get tag. Any idea?
