### ISSUE TITLE
AWS::Logs::LogGroup - Tags

### ISSUE THREAD

**Issue by aditya2101** [aws-cloudformation/cloudformation-coverage-roadmap#1256]
### Name of the resource

AWS::Logs::LogGroup

### Resource Name

AWS::Logs::LogGroup

### Issue Description

CloudFormation  supports Tags property but has the following issue causing drifts:

1.)Create a new stack which does NOT contain a log group, but does have resource tags set on the stack itself (e.g., Foo=Bar)

2.)Update the stack by adding a log group which does NOT have any tags defined

3.)If you look at the log group, you'll see that the stack-level tags did propagate to the log group

4.) Update the stack by adding matching tags (i.e., Foo=Bar) explicitly to the log group

5.) Run a drift detection on the stack

The drift status will now show MODIFIED, and the details will show an expected value of {Foo=Bar, Foo=Bar}, which can never happen on the actual resource.

### Expected Behavior

There should be no drift

### Observed Behavior

if you currently use StackTags on your CFT Stacks, cloudformation thinks those tags are already on your loggroup and therefore will not add the tags even if you put it in your template.

### Test Cases

test case same as in issue description

**Comment by ziarrdan** [comment]
We could not reproduce this issue. Would you please provide us with a stack ARN is case you are still having this problem?
Thank you.

**Comment by farski** [comment]
@ziarrdan Per #919, this issue was opened by the AWS team. It does appear that this behavior is no longer present. Was a change made? Is it expected that this behavior would change?

**Comment by rgoltz** [comment]
Dear @aditya2101 , Dear @ziarrdan , Dear @farski ,
I've ran various scenario for tags on stack- and resource-level for AWS::Logs::LogGroup (with and without other resources inside those stacks). In all my test-cases (made in eu-central-1) the tags on the LogGroup was correct and also CFN Drift detection always reported IN_SYNC correctly.

I agree with Chris - It seems some fixes/improvments has been made here on AWS-backend. Having this said, we may should close this github-issue here, Aditya?

**Comment by aditya2101** [comment]
Yes we can close the issue now.

**Comment by Risae** [comment]
Shouldn't this be moved to "Shipped"?
