### ISSUE TITLE
StatefulRuleGroupReference missing Override:Action property

### ISSUE THREAD

**Issue by evermbr** [aws-cloudformation/cloudformation-coverage-roadmap#1265]
### Name of the resource

AWS::NetworkFirewall::FirewallPolicy

### Description

The [StatefulRuleGroupReference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-networkfirewall-firewallpolicy-statefulrulegroupreference.html) resource type is missing the Override:Action property. These properties are available via [Boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/network-firewall.html#NetworkFirewall.Client.create_firewall_policy), the Console and the [CLI](https://docs.aws.amazon.com/cli/latest/reference/network-firewall/create-firewall-policy.html).  Below is an example of the Override:Action property taken from the CLI documentation: 

  "StatefulRuleGroupReferences": [
    {
      "ResourceArn": "string",
      "Priority": integer,
      **"Override": {
        "Action": "DROP_TO_ALERT"
      }**
    }

**Comment by xiaoqinx** [comment]
is this available in Sydney Region yet? Customer reported below error:
E3002 Invalid Property Resources/InspectionFirewallPolicy/Properties/FirewallPolicy/StatefulRuleGroupReferences/13/Override
target/nbn-firewall-rules.yml:29:13
