### ISSUE TITLE
AWS::FMS::Policy - Not Applying DeleteAllPolicyResources Property

### ISSUE THREAD

**Issue by rwgnr** [aws-cloudformation/cloudformation-coverage-roadmap#1267]
### Name of the resource

AWS::FMS::Policy

### Issue Description

When deploying a AWS::FMS::Policy resource (AWS Firewall Manager - Security Policy) via CloudFormation, one of the properties you can set is `DeleteAllPolicyResources` which will enable resource cleanup depending on the type of policy you deployed. This property is no longer functioning as expected when set to `true`, as the resulting policy does not contain that setting enabled.

### Expected Behavior

What should happen is that when the `AWS::FMS::Policy` property of `DeleteAllPolicyResources`  is set to `true` in the CloudFormation template, this _should_ be telling the AWS FMS API that `deleteUnusedFMManagedResources` should be set to `true`

### Observed Behavior

What is currently happening is that when the `AWS::FMS::Policy` property of `DeleteAllPolicyResources`  is set to `true`  in the CloudFormation template, this is telling the AWS FMS API that `deleteUnusedFMManagedResources` should be set to `false`, which is incorrect

### Test Cases

Using CloudFormation, deploy a template that includes a `AWS::FMS::Policy` resource of any type into the account enabled with AWS Firewall Manager, and set the `DeleteAllPolicyResources` property to `true`

View the deployed AWS FMS Policy in either the AWS WAF & Shield Console or using the AWS CLI and check for the property state.

### Other Details

Reported and confirmed with AWS Support in Case ID 10504538181

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fms-policy.html#cfn-fms-policy-deleteallpolicyresources

**Comment by Root1993** [comment]
The `DeleteAllPolicyResources` flag is only used when deleting a policy to determine if resources created by Firewall Manager should be deleted along with the policy. The `ResourcesCleanUp` flag affects active policies by setting the `DeleteUnusedFMManagedResources` in AWS FMS API, it will cleanup resources that leave the policy’s scope.
