### ISSUE TITLE
AWS::EC2::TransitGatewayAttachment drift detection bug when resource is deleted manually

### ISSUE THREAD

**Issue by Marrwen** [aws-cloudformation/cloudformation-coverage-roadmap#1271]
### Name of the resource

AWS::EC2::TransitGatewayAttachment

### Issue Description

Hello, 

Running drift detection for resource AWS::EC2::TransitGatewayAttachment when the resource is deleted manually shows the resource `In Sync` instead of `Drifted` which is not correct.

### Expected Behavior

The drift detection should show the resource in `Drifted` status

### Observed Behavior

The drift detection show he resource in `In Sync` status

### Test Cases

Create a TransitGateway attachment resource using the following CloudFormation template:

    Resources:
      Test:
        Type: AWS::EC2::TransitGatewayAttachment
        Properties: 
          SubnetIds: 
            - subnet-xxxxxx
            - subnet-xxxxxx
          TransitGatewayId: tgw-xxxxxx
          VpcId: vpc-xxxxxx

Then delete the resource manually and run drift detection

**Comment by thu001** [comment]
This issue has been fixed. I conducted a test through an out-of-band deletion. The results confirmed that both drift detection and deletion functionalities are operating as anticipated.

![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/47364586/9de01976-bb95-45d4-8ce5-9eb9f7be48f6)
![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/47364586/953c7c97-a8fb-4cfb-aa55-99c53974929d)
