### ISSUE TITLE
Cloudformation Coverage for Amazon Managed Grafana

### ISSUE THREAD

**Issue by youngjeong46** [aws-cloudformation/cloudformation-coverage-roadmap#1272]
### Name of the resource

Other

### Resource name

It does not exist

### Description

A new service support is needed for Amazon Managed Grafana. Amazon Managed Grafana has been GA since Aug 2021, and while APIs exist to create new workspaces, there is no Cloudformation Support yet. This will be needed to support things like [CDK implementation](https://github.com/aws/aws-cdk/issues/14352).

**Comment by rgoltz** [comment]
@youngjeong46 There is progress regarding your request: https://aws.amazon.com/de/about-aws/whats-new/2022/12/amazon-managed-grafana-support-aws-cloudformation/ - see also CFN docs: AWS::Grafana::Workspace - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-grafana-workspace.html

**Comment by dsravant** [comment]
Hello Everyone,

On (12/09/22) [Amazon Managed Grafana launched the support for AWS CloudFormation](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-managed-grafana-support-aws-cloudformation).

You can now use AWS CloudFormation templates to create, update, and delete your Amazon Managed Grafana workspaces, as well as manage or update workspace SAML authentication settings. You can use templates to provision new Grafana workspaces, edit workspace settings such as workspace name or description, and manage the lifecycle of your Grafana workspaces programmatically. You can also create CloudFormation templates to configure workspace authentication options such as setting up SAML Identity Providers, specifying user roles, or defining attributes to identify user authentication.

To learn more about manage Amazon Managed Grafana workspaces and configuring workspace SAML authentication with CloudFormation, see the [Amazon Managed Grafana resource type reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Grafana.html) in the CloudFormation user guide. To create Amazon Managed Grafana workspaces using AWS CloudFormation, follow the [reference templates](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-grafana-workspace.html#aws-resource-grafana-workspace--examples).

Feel free to leave a comment if you have any questions. We are actively collecting user feedback and use cases.

**Comment by TheDanBlanco** [comment]
this looks to be resolved! thanks so much @dsravant & team!
