### ISSUE TITLE
AWS::EC2::Subnet Attribute SubnetId not supported in ap-southeast-3

### ISSUE THREAD

**Issue by hasherwi** [aws-cloudformation/cloudformation-coverage-roadmap#1284]
### Name of the resource

AWS::EC2::Subnet

### Resource name

AWS::EC2::Subnet

### Description

In ap-southeast-3, AWS::EC2::Subnet does not include SubnetId as an attribute, which is available in other regions. Please add support.

CFN Spec for ap-southeast-3: https://cfn-resource-specifications-ap-southeast-3-prod.s3.ap-southeast-3.amazonaws.com/latest/CloudFormationResourceSpecification.json
CFN Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html#aws-resource-ec2-subnet-return-values

**Comment by ksiebor** [comment]
Subnet is now fully published in ap-southeast-3.
