### ISSUE TITLE
AWS::Lambda::EventSourceMapping > Add support for SelfManagedKafkaEventSourceConfig

### ISSUE THREAD

**Issue by coltivare** [aws-cloudformation/cloudformation-coverage-roadmap#1285]
### Name of the resource

AWS::Lambda::EventSourceMapping

### Description

When creating an event source mapping for self-managed Apache Kafka via the AWS Lambda API "CreateEventSourceMapping" method, it's possible to specify a consumer group identifier, using the [SelfManagedKafkaEventSourceConfig](https://docs.aws.amazon.com/lambda/latest/dg/API_SelfManagedKafkaEventSourceConfig.html#SSS-CreateEventSourceMapping-request-SelfManagedKafkaEventSourceConfig) property:

It would be useful to have the ability to do this when creating an AWS::Lambda::EventSourceMapping resource as well, ideally with support also extended to AWS SAM when creating an SelfManagedKafka event source type.

Without the ability to specify the consumer group identifier for a SelfManagedKafka event source, I am aware of only two paths open to ensure that the correct authorization is enabled for the event source to consume events from the configured topic:

1. Grant the CREATE permission on the Kafka cluster, so that a consumer group can be created dynamically by AWS Lambda
2. Take the physical identifier (UUID) of the event source mapping itself after it has been created and then create a consumer group with that value on the cluster (either manually, or with whatever infrastructure as code solution is used to manage the Kafka cluster)

Our ideal workflow is to create the Kafka ACLs needed for a consumer (aka, event source) via an infrastructure as code solution (for example, Terraform), including the consumer group, and then use those same values in our SAM/CloudFormation template to create the event source mapping.

**Comment by zabrip** [comment]
Support for SelfManagedKafkaEventSourceConfig was launched for both SAM and CloudFormation on 8/17:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-eventsourcemapping-selfmanagedkafkaeventsourceconfig.html
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-selfmanagedkafka.html
