### ISSUE TITLE
ResponseHeadersPolicyConfig missing ResponseHeadersPolicyServerTimingHeadersConfig

### ISSUE THREAD

**Issue by JamesKyburz** [aws-cloudformation/cloudformation-coverage-roadmap#1286]
### Name of the resource

Other

### Resource name

AWS::CloudFront::ResponseHeadersPolicy ResponseHeadersPolicyConfig

### Description

The timing headers config documented [here](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_ResponseHeadersPolicyServerTimingHeadersConfig.html) is missing from [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-responseheaderspolicy-responseheaderspolicyconfig.html).

**Comment by gangavab** [comment]
[ServerTimingHeadersConfig](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-responseheaderspolicy-responseheaderspolicyconfig.html#cfn-cloudfront-responseheaderspolicy-responseheaderspolicyconfig-servertimingheadersconfig) is very much a part of the resource `AWS::CloudFront::ResponseHeadersPolicy`. CFN users should be able to configure Server-Timing headers in HTTP responses using ServerTimingHeadersConfig.

```
{
  "Comment" : String,
  "CorsConfig" : CorsConfig,
  "CustomHeadersConfig" : CustomHeadersConfig,
  "Name" : String,
  "SecurityHeadersConfig" : SecurityHeadersConfig,
  "ServerTimingHeadersConfig" : ServerTimingHeadersConfig <---
}
```
