### ISSUE TITLE
AWS::OpenSearchService::Domain: SAMLOptions

### ISSUE THREAD

**Issue by lvthillo** [aws-cloudformation/cloudformation-coverage-roadmap#1288]
### Name of the resource

AWS::OpenSearchService::Domain

### Description

It's not possible to configure `SAMLOptions` for an OpenSearch Domain using CloudFormation.
There is a very similar issue (for ElasticSearch) which is "shipped" but it's not available.
- https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/672

### Other Details

It should not be too hard to implement this since the API is available and its possible [using the CLI](https://docs.aws.amazon.com/cli/latest/reference/opensearch/update-domain-config.html).
There is also [terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain_saml_options) and [pulumi](https://www.pulumi.com/registry/packages/aws/api-docs/opensearch/domainsamloptions/) support for it.

**Comment by devardee** [comment]
@lvthillo , `SAMLOptions` is now part of the resource `AWS::OpenSearchService::Domain`
