### ISSUE TITLE
AWS::Lex::Bot VoiceSettings [Engine]

### ISSUE THREAD

**Issue by morottjj** [aws-cloudformation/cloudformation-coverage-roadmap#1290]
### Name of the resource

Other

### Resource name

AWS::Lex::Bot

### Description

The resource AWS::Lex::Bot VoiceSetting currently only supports [voiceId]. The resource is missing coverage for [engine] to set the Bot Locale voice to either "standard" or "neural" as seen in the 'CreateBotLocale' API [here](https://docs.aws.amazon.com/lexv2/latest/dg/API_CreateBotLocale.html).

**Comment by chenqiamzn** [comment]
Hello, the [Engine] has been added to VoiceSettings in AWS::Lex::Bot. Thank you.
