### ISSUE TITLE
Can't set visual job API ( e.g. "codeGenConfigurationNodes" field ) in  CFn template 

### ISSUE THREAD

**Issue by RushaliD12** [aws-cloudformation/cloudformation-coverage-roadmap#1298]
### Name of the resource

AWS::Glue::Job

### Description

create Glue job (AWS::Glue::Job) by CloudFormation and edit the job with visual mode in Glue Studio.
However, I think we can't set visual job API ( e.g. "codeGenConfigurationNodes" field ) in  CFn template [1-2].

#Request
Please support visual job API with Glue job (AWS::Glue::Job) in CFn template so that we can edit the job with visual mode in Glue Studio.

### Other Details

#References

[1]. Visual Job API
https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-visual-job-api.html

[2]. AWS::Glue::Job
https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html

**Comment by ericvg97** [comment]
I see this is solved/shipped, but I can't find it anywhere in the docs. Did you find it @RushaliD12?

**Comment by Rizxcviii** [comment]
Wondering where this configuration is also, I've made a separate request without knowing this exists. https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1922
