### ISSUE TITLE
AWS::LakeFormation::PrincipalPermissions DataCellsFilterResource missing properties

### ISSUE THREAD

**Issue by Sevi7** [aws-cloudformation/cloudformation-coverage-roadmap#1300]
### Name of the resource

Other

### Resource Name

AWS::LakeFormation::PrincipalPermissions

### Issue Description

[DataCellsFilterResource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lakeformation-principalpermissions-datacellsfilterresource.html) struct in CloudFormation has the following properties:
```
{
  "DatabaseName" : String,
  "Name" : String,
  "TableCatalogId" : String,
  "TableName" : String
}
```
The issue is that there is no property to specify a row filter expression. I think there should be a property that recognizes this format: [PartiQL support in row filter expressions](https://docs.aws.amazon.com/lake-formation/latest/dg/partiql-support.html).

Also **ColumnNames** and **ColumnWildcard**  properties from [TableWithColumnsResource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lakeformation-principalpermissions-tablewithcolumnsresource.html) are missing because cell filtering is when you include or exclude specific columns and also provide a row filter expression. Source: [Data filters]( https://docs.aws.amazon.com/lake-formation/latest/dg/data-filters-about.html) 

### Expected Behavior

- A row filter property in [DataCellsFilterResource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lakeformation-principalpermissions-datacellsfilterresource.html) struct that supports PartiQL format.

- ColumnNames and ColumnWildcard from [TableWithColumnsResource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lakeformation-principalpermissions-tablewithcolumnsresource.html) are also missing in **DataCellsFilterResource**.

With these three properties we would be able to establish cell-level security (cell filtering).

Useful documentation about [Data filters]( https://docs.aws.amazon.com/lake-formation/latest/dg/data-filters-about.html) that states the following: 

> The level of filtering that you get depends on how you populate the data filter.
> 
> - When you specify the "all columns" wildcard and provide a row filter expression, you are establishing row-level security (row filtering) only.
> - When you include or exclude specific columns and specify "all rows" using the all-rows wildcard, you are establishing column-level security (column filtering) only.
> - When you include or exclude specific columns and also provide a row filter expression, you are establishing cell-level security (cell filtering).

According to the above we could also be missing a **RowFilterResource** in CloudFormation.

### Observed Behavior

Missing properties in DataCellsFilterResource struct.

### Test Cases

Test row filtering and cell filtering.

**Comment by aws-kaushal-partani** [comment]
Hi @Sevi7,

Depending on the behavior you're expecting, there's 2 paths here:

1. If you want to create a cell filter, you probably want to use [AWS::LakeFormation::DataCellsFilter](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lakeformation-datacellsfilter.html) instead. This will allow you to create a filter within your account and specify a row filter and/or column filter.

2. If you want to grant permissions on a cell filter, you would use AWS::LakeFormation::PrincipalPermissions. You'd be granting permissions on a cell filter that already exists, so you would only need some identifying data to specify it in the CFN template. For that reason, we don't allow information beyond what's specified in the DataCellsFilterResource as you mentioned above.

**Comment by Sevi7** [comment]
Thank you so much for your detailed explanation @aws-kaushal-partani. I misunderstood the documentation, it really makes sense now
