### ISSUE TITLE
Support enabling container insights in AWS Batch Compute Environment

### ISSUE THREAD

**Issue by AChans** [aws-cloudformation/cloudformation-coverage-roadmap#1301]
### Name of the resource

AWS::Batch::ComputeEnvironment

### Description

From AWS Console we can enable container insights for a compute environment but it is not possible to do so through Cfn construct in CDK.

**Comment by chadhayton** [comment]
Thank you for your request. Currently, we are providing this data within the Batch console and do not have plans for expansion via CFN on our roadmap. We have made our product team aware of your request, however, and will consider this improvement going forward. 

Can you please provide details about your particular use case so we can share this with the team as we consider potential solutions?

**Comment by AChans** [comment]
Everytime we create a new compute environment we need to enable container insights manually through the Batch console. This is not ideal. We want to automate our deployments or we risk losing important monitoring metrics because of human error.

**Comment by chadhayton** [comment]
Thank you for this additional information.  We have created a backlog ticket for this work and will manage it there going forward.

**Comment by ybenitezf** [comment]
Still on the backlog for what i can see ?

**Comment by JeromeDuboisVizzia** [comment]
Hi all,

We are deploying our batch infra with CDK, and using the AWS Security Hub with the `AWS Foundational Security Best Practices v1.0.0` security standard enabled.
Anytime we deploy a new cluster, we trigger a new `Medium` importance security finding and must log to the management console to fix this.
As we use Batch in step functions that AI developers can deploy at will for testing, it is a bit annoying and time consuming to have to manually connect to the console as @AChans mentioned.

All in all, thumbs up for this request :+1: !

Any news on this ticket?

**Comment by bdoyle0182** [comment]
What is the current status of this? It's been three years. Right now there's not a batch api way to enable container insights. It's only in console because it has to call the ecs api under the hood for the cluster tied to the batch compute environment. This is a pretty large product gap of aws batch service if you can't configure base line monitoring as a part of its control plane api..

**Comment by dillonwelch** [comment]
+1 to needing this be available via CFN
