### ISSUE TITLE
AWS::EC2::SpotFleet - OnDemandTargetCapacity, OnDemandAllocationStrategy (new properties)

### ISSUE THREAD

**Issue by Guslington** [aws-cloudformation/cloudformation-coverage-roadmap#131]
## Scope

Ability to define On-Demand TargetCapacity and AllocationStrategy properties through cloudformation as you can through the API and console

## Expected behavior

On create it should create a new spotfleet launching the target capacity of the on-demand count in the order defined by the allocation strategy.

On update of the target capacity it should update the existing fleet to the new count. On update of the allocation strategy it should recreate the spotfleet following the same behaviour as the spot allocation strategy property.

## Test case

It should create a spotfleet with on-demand instancesusing the order defined by the allocation strategy

## Links

Spotfleet api properties https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_SpotFleetRequestConfigData.html

**Comment by koenvandesande** [comment]
When will this new property be exposed through cloudformation?

**Comment by wielandr-azn** [comment]
These properties were added sometime earlier this year.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata.html#cfn-ec2-spotfleet-spotfleetrequestconfigdata-ondemandallocationstrategy
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-spotfleetrequestconfigdata.html#cfn-ec2-spotfleet-spotfleetrequestconfigdata-ondemandtargetcapacity
