### ISSUE TITLE
`AWS::KinesisVideo::SignalingChannel` tags not being applied

### ISSUE THREAD

**Issue by ewbankkit** [aws-cloudformation/cloudformation-coverage-roadmap#1311]
### Name of the resource

Other

### Resource Name

AWS::KinesisVideo::SignalingChannel

### Issue Description

When creating a Signaling Channel via the Cloud Control API, any specified tag values do not seem to be applied, causing a permadiff:

% terraform plan 
awscc_kinesisvideo_signaling_channel.foo: Refreshing state... [id=foo]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # awscc_kinesisvideo_signaling_channel.foo has been changed
  ~ resource "awscc_kinesisvideo_signaling_channel" "foo" {
        id                  = "foo"
        name                = "foo"
      - tags                = [
          - {
            - key   = "terraform" -> null
            - value = "true" -> null
          },
        ]
        # (3 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the
following plan may include actions to undo or respond to these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # awscc_kinesisvideo_signaling_channel.foo will be updated in-place
  ~ resource "awscc_kinesisvideo_signaling_channel" "foo" {
        id                  = "foo"
        name                = "foo"
      + tags                = [
          + {
            + key   = "terraform"
            + value = "true"
          },
        ]
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you
run "terraform apply" now.
```

### Expected Behavior

Expected no diff for `tags`

### Observed Behavior

Permadiff:

```console
% terraform apply
awscc_kinesisvideo_signaling_channel.foo: Refreshing state... [id=foo]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # awscc_kinesisvideo_signaling_channel.foo has been changed
  ~ resource "awscc_kinesisvideo_signaling_channel" "foo" {
        id                  = "foo"
        name                = "foo"
      - tags                = [
          - {
            - key   = "terraform" -> null
            - value = "true" -> null
          },
        ]
        # (3 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the
following plan may include actions to undo or respond to these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # awscc_kinesisvideo_signaling_channel.foo will be updated in-place
  ~ resource "awscc_kinesisvideo_signaling_channel" "foo" {
        id                  = "foo"
        name                = "foo"
      + tags                = [
          + {
            + key   = "terraform"
            + value = "true"
          },
        ]
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

awscc_kinesisvideo_signaling_channel.foo: Modifying... [id=foo]
awscc_kinesisvideo_signaling_channel.foo: Modifications complete after 7s [id=foo]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
% terraform plan 
awscc_kinesisvideo_signaling_channel.foo: Refreshing state... [id=foo]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # awscc_kinesisvideo_signaling_channel.foo has been changed
  ~ resource "awscc_kinesisvideo_signaling_channel" "foo" {
        id                  = "foo"
        name                = "foo"
      - tags                = [
          - {
            - key   = "terraform" -> null
            - value = "true" -> null
          },
        ]
        # (3 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the
following plan may include actions to undo or respond to these changes.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # awscc_kinesisvideo_signaling_channel.foo will be updated in-place
  ~ resource "awscc_kinesisvideo_signaling_channel" "foo" {
        id                  = "foo"
        name                = "foo"
      + tags                = [
          + {
            + key   = "terraform"
            + value = "true"
          },
        ]
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you
run "terraform apply" now.
```

### Test Cases

```hcl
terraform {
  required_providers {
    awscc = {
      source  = "hashicorp/awscc"
      version = ">= 0.30.0"
    }
  }
}

resource "awscc_kinesisvideo_signaling_channel" "foo" {
  message_ttl_seconds = 60
  name                = "foo"
  type                = "SINGLE_MASTER"
  tags                = [
    {
      key   = "terraform"
      value = "true"
    }
  ]
}
```

**Comment by sverma-ai** [comment]
`aws cloudcontrol create-resource --type-name "AWS::KinesisVideo::SignalingChannel" --desired-state "{\"Tags\": [{\"Key\": \"TestKey\",\"Value\": \"TestValue\"}]}"` creates resource using [CreateSignalingChannel](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_CreateSignalingChannel.html) API.

`aws cloudcontrol get-resource --type-name "AWS::KinesisVideo::SignalingChannel" --identifier "..."` gets resource using [DescribeSignalingChannel](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_DescribeSignalingChannel.html) API. Not returning tags as part of `get-resource` for `AWS::KinesisVideo::SignalingChannel` is the current behavior as [DescribeSignalingChannel](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_DescribeSignalingChannel.html) API. 

But the tags are still getting applied on the signaling channel resource. This can be verified using [ListTagsForResource](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_ListTagsForResource.html) API.

In order to return tags, [DescribeSignalingChannel](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_DescribeSignalingChannel.html) API behavior will need a change. This task will require some prioritization as this is not on the roadmap.

In the meanwhile, use [ListTagsForResource](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_ListTagsForResource.html) API to get the tags for the resource.
