### ISSUE TITLE
AWS::DeviceFarm resources missing from resource specification

### ISSUE THREAD

**Issue by AKoetsier** [aws-cloudformation/cloudformation-coverage-roadmap#1318]
### Name of the resource

Other

### Resource name

AWS::DeviceFarm::*

### Details

Cloudformation has support for a number of AWS DeviceFarm resources like

- AWS::DeviceFarm::DevicePool
- AWS::DeviceFarm::InstanceProfile
- AWS::DeviceFarm::NetworkProfile
- AWS::DeviceFarm::Project
- AWS::DeviceFarm::TestGridProject
- AWS::DeviceFarm::VPCEConfiguration

However the cloudformation resource specification doesn't contain any of those resources.

**Comment by kddejong** [comment]
DeviceFarm resources are in the us-west-2 spec as the service is only in us-west-2  https://docs.aws.amazon.com/general/latest/gr/devicefarm.html
