### ISSUE TITLE
AWS::IoT::Authorizer Support within Eu-North-1

### ISSUE THREAD

**Issue by ZalmnS** [aws-cloudformation/cloudformation-coverage-roadmap#1321]
### Name of the resource

AWS::IoT::Authorizer

### Description

Currently, eu-north-1 has IOT Endpoints for the region as described in this article (https://docs.aws.amazon.com/general/latest/gr/iot-core.html)
Within the CFN Resource Specification it shows that the AWS::IoT::Authorizer resource is not available within eu-north-1 (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html)

Humbly requesting AWS::IoT::Authorizer Resource to be added to eu-north-1

The Authorizer itself can be made in the Web Console within eu-north-1

AWS::IoT::Authorizer is the only resource within the "AWS::IoT::" family that is not available within the eu-north-1 region despite being available in the eu-west-1, eu-west-2, eu-west-3, and eu-central-1

As an additional note, AWS::IoT::Authorizer is also not available in eu-south-1

**Comment by gmlan** [comment]
This issue is fixed, and AWS::IoT::Authorizer is availability in ARN.
