### ISSUE TITLE
AWS::CloudFront::OriginAccessControl	"Internal error"

### ISSUE THREAD

**Issue by andyt10** [aws-cloudformation/cloudformation-coverage-roadmap#1328]
### Name of the resource

Other

### Issue Description

There appears to be a resource provider error handling, or schema issue, with the `AWS::CloudFront::OriginAccessControl` resource.
When creating a resource `AWS::CloudFront::OriginAccessControl` resource it's possible to receive the following error:

```
Internal error reported from downstream service during operation 'AWS::CloudFront::OriginAccessControl'.
```
The resource had the following properties:

```
  IsABug:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
        Name: test
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
```

If the [*"optional"*](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-originaccesscontrol-originaccesscontrolconfig.html#cfn-cloudfront-originaccesscontrol-originaccesscontrolconfig-description) `Description` value is added, then the resource can be created successfully.

Looking at CFN's CloudTrail calls, we can confirm this is the cause of the error:

```
        "invokedBy": "cloudformation.amazonaws.com"
    },
    "eventTime": "2022-09-25T13:26:10Z",
    "eventSource": "cloudfront.amazonaws.com",
    "eventName": "CreateOriginAccessControl",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "AWS Internal",
    "userAgent": "AWS Internal",
    "errorCode": "ValidationException",
    "errorMessage": "1 validation error detected: Value null at 'originAccessControlConfig.description' failed to satisfy constraint: Member must not be null",
    "requestParameters": {
        "originAccessControlConfig": {
            "originAccessControlOriginType": "s3",
            "signingBehavior": "always",
            "name": "test",
            "signingProtocol": "sigv4"
        }
    },
``` 

The CloudFront API docs suggest `Description` is a required value: https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateOriginAccessControl.html#API_CreateOriginAccessControl_RequestSyntax

### Expected Behavior

Either the resource is created, or a more helpful error message is displayed to the user.

### Observed Behavior

The internal error described above is presented to the user.

### Test Cases

You should be able to test and replicate with the provided CFN snippet:

```
  IsABug:
    Type: AWS::CloudFront::OriginAccessControl
    Properties: 
      OriginAccessControlConfig: 
        Name: test
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
```

**Comment by benbridts** [comment]
It also seems that the Resource Provider retries multiple times (I counted 6 ValidationExceptions in CloudTrail), which makes it seem like the Exception is not caught properly (a ValidationException should be mapped to `InvalidRequest` not to `InternalFailure`) Although in this case the request was valid according to the schema.

Shouldn't this have been caught by a contract test?
