### ISSUE TITLE
Support updating metadata and stack tags

### ISSUE THREAD

**Issue by kabo** [aws-cloudformation/cloudformation-coverage-roadmap#1332]
### Name of the resource

AWS::EC2::LaunchTemplate

### Issue Description

When updating stack tags and LaunchTemplate metadata in the same `update-stack`, the launch template data doesn't get updated. `cfn-hup` isn't triggered and running `cfn-get-metadata` returns the old metadata.

When just updating the metadata everything works fine, it's only when updating the stack tags at the same times that the LT metadata doesn't get updated.

### Expected Behavior

The LaunchTemplate metadata to be updated.

### Observed Behavior

The LaunchTemplate metadata is not updated.

### Test Cases

Pass a parameter into a launchtemplate's metadata. Have an EC2 instance set up with cfn-hup on post.update for the LT metadata. Update the parameter and a stack tag. cfn-hup does not trigger, and cfn-get-metadata returns the old metadata.

**Comment by bcorman3** [comment]
We deployed a fix for this sometime around November which should have resolved this issue. Please reopen if you continue to see this issue.
