### ISSUE TITLE
Support for Import of AWS::ElasticLoadBalancingV2::LoadBalancer Resources

### ISSUE THREAD

**Issue by derekps** [aws-cloudformation/cloudformation-coverage-roadmap#1336]
### Name of the resource

AWS::ElasticLoadBalancingV2::LoadBalancer

### Description

Hey team,

While I trying to Import an `AWS::ElasticLoadBalancingV2::LoadBalancer` into CloudFormation I realized that it is not supported. I'd love if consideration could be given to making that possible.

Cheers!

### Other Details

**Reference**: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html#:~:text=AWS%3A%3AElasticBeanstalk%3A%3AApplication-,AWS%3A%3AElasticLoadBalancingV2,-%3A%3AListener

**Comment by TheDanBlanco** [comment]
this is now [supported](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html)
