### ISSUE TITLE
Support for Import of AWS::EC2::TransitGatewayRouteTable Resources

### ISSUE THREAD

**Issue by morries4321** [aws-cloudformation/cloudformation-coverage-roadmap#1338]
### Name of the resource

AWS::EC2::TransitGatewayRouteTable

### Description

Requesting to add resource type AWS::EC2::TransitGatewayRouteTable to support import operation.

**Comment by kddejong** [comment]
According to the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html) this is supported now.  I haven't had a chance to test it.
