### ISSUE TITLE
AWS::WAFRegional::RuleGroup and AWS::WAF::RuleGroup - New Resources

### ISSUE THREAD

**Issue by adamcousins** [aws-cloudformation/cloudformation-coverage-roadmap#134]
1. Title -> AWS::WAFRegional::RuleGroup
2. Scope of request -> New resources required to support AWS Firewall Management Service managed WebAcls 
3. Expected behavior -> Create/Update/Delete of 'AWS WAF Rule Groups' like the boto API allows.
4. Test case recommendation (optional) ->
5. Links to existing API doc (optional) -> Updated API docs at https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/waf-regional.html#WAFRegional.Client.create_rule_group
6. Category tag (optional) -> Security

**Comment by brianterry** [comment]
@adamcousins , this is now supported with `AWS::WAFv2::RuleGroup`. 

Please see our docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-wafv2-rulegroup.html
