### ISSUE TITLE
CFN Drift detection - AWS::IAM::ManagedPolicy - Tags are shown as Expected if stack-level-tags are added to the stack

### ISSUE THREAD

**Issue by smovva123** [aws-cloudformation/cloudformation-coverage-roadmap#1353]
### Name of the resource

AWS::IAM::ManagedPolicy

### Resource Name

AWS

### Issue Description

Once you create a stack + addings tags on stack-level (!) and your stack containing a AWS::IAM::MangedPolicy, the CloudFormation drift detection reporting such stack as drifted (details see "Observed Behavior").

### Expected Behavior

CloudFormation (Drift detection) should be aware that AWS::IMA::MangedPolicy doesn't support Tags yet (see addtional references in "Other Details" below), hence it's not possible to tag them yet. Furthermore, clarification is needed, if drift detection supports AWS::Events::Rule - If not, doc needs to be updated and drift detection should return a valid information (like "NOT_SUPPORTED") for this resource.

### Observed Behavior

After adding Stack-Level-Tags to your stack containing a AWS::IAM::MangedPolicy and you getting a DRIFTED state for those stacks. This is misleading, since you are not able to fix it. At the same moment other resources inside the stack benefit from setting tags via stack.

### Test Cases

 Here some steps to reconstruct the issue:

1) create a new stack containing a AWS::IAM::ManagedPolicy in eu-central-1
2) adding tags on STACK-LEVEL during creation of the stack
3) after the stack / the resources are created, please run CFN Drift detection via Console
4) check the results for CFN Drift detection - Stack is in state DRIFTED

### Other Details

Once we trigger the CFN Drift detection via Console, we see this resource with AWS::IAM::ManagedPolicy reported as drift regarding "Tags"!

CloudFormation does NOT support adding Tags on resource-level as stated here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html

**Comment by kanitkah** [comment]
CloudFormation identified an issue with recent release which caused the Drift Detection feature to incorrectly report some resources that do not support tags like CloudWatch::Alarm, AWS::ElasticLoadBalancingV2::Listener, AWS::ElasticLoadBalancingV2::ListenerRule, AWS::Events::Rule etc. as Drifted when stack level tags were applied due to incorrect tag comparison. We are rolling back the deployment and the ETA for finishing the rollback is by 10/14/2022.

**Comment by kanitkah** [comment]
This change has been rolled back.

**Comment by rgoltz** [comment]
We reviewed some of our stacks in eu-central-1. Unfortunately we still see drifts, if Stack-Level Tags are set _and_ there is a `AWS::IAM::ManagedPolicy` (without Tags defined in Template) inside the Stack. Could you please cross-check? (I've shared more details like Stack-ARN, Stack-JSON-Template and screenshots with @smovva123 )

**Comment by kanitkah** [comment]
Thanks for the additional info....we will take a look and get back to you.

**Comment by kanitkah** [comment]
@rgoltz The fix for this will be in the next deployment along with many other drift tag fixes. The ECD for the deployment to be completed in all the regions is 12/15. I will provide additional updates once we finish the deployment, or if the ECD changes.

**Comment by smovva123** [comment]
@kanitkah Is the fix in for the regions?

**Comment by kanitkah** [comment]
Deployment is currently in progress, ECD is still 12/15 to complete the deployment.

**Comment by smovva123** [comment]
Hey @kanitkah. Is the deployment done?

**Comment by rgoltz** [comment]
Dear all, Dear @smovva123 - I've re-tested our stacks with AWS::IAM::ManagedPolicy resource (in eu-central-1). It seems that the fix is deployed - Our stacks are not in state IN_SYNC. I would recommend to close this issue as successfully resolved. Thanks for working on the fix @kanitkah

**Comment by smovva123** [comment]
Closing this issue as re the fix was rolled out
