### ISSUE TITLE
Cannot enable backtrack with aurora serverless v2 cluster

### ISSUE THREAD

**Issue by stocks29** [aws-cloudformation/cloudformation-coverage-roadmap#1357]
### Name of the resource

AWS::RDS::DBCluster

### Issue Description

When attempting to deploy a template with an `AWS::RDS::DBCluster` resource that has a setting for `BacktrackWindow`, the deploy fails with:

> Resource handler returned message: "Aurora MySQL Engine Version 8.0.mysql_aurora.3.02.0 with mode: PROVISIONED does not support Backtrack. (Service: Rds, Status Code: 400, Request ID: ...)" (RequestToken: ..., HandlerErrorCode: InvalidRequest)

### Expected Behavior

Backtrack is enabled and the deploy succeeds.

### Observed Behavior

Deploying a stack with an `AWS::RDS::DBCluster` fails when a `BacktrackWindow` setting is configured. See error in description.

### Test Cases

1. Create a stack with a serverless v2 `AWS::RDS::DBCluster` per the [described configuration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#aws-resource-rds-dbcluster--examples--Creating_an_Amazon_Aurora_Serverless_v2_DB_cluster).
2. Include the `BacktrackWindow` setting to turn on the backtrack feature
3. Attempt to deploy the stack

**Comment by stocks29** [comment]
Still receiving an error while attempting to enable backtrack:

> Resource handler returned message: "Aurora MySQL Engine Version 8.0.mysql_aurora.3.02.0 with mode: PROVISIONED does not support Backtrack. (Service: Rds, Status Code: 400, Request ID: a88f87ce-231e-4ad9-822f-29341c8fce1c)" (RequestToken: f4788578-8012-269d-4d73-a21c492af46c, HandlerErrorCode: InvalidRequest)

**Comment by stocks29** [comment]
@cfn-github-issues-bot can you please re-open this?

**Comment by milanmatejka** [comment]
This is expected behavior. It is documented in the AWS public documentation [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Managing.Backtrack.html).

> Currently, you can modify backtracking only for a DB cluster that has the Backtrack feature enabled. The Backtrack section doesn't appear for a DB cluster that was created with the Backtrack feature disabled or if the Backtrack feature has been disabled for the DB cluster.
