### ISSUE TITLE
Neptune DBCluster DBClusterIdentifier replacement update error.

### ISSUE THREAD

**Issue by scotliu** [aws-cloudformation/cloudformation-coverage-roadmap#1358]
### Name of the resource

AWS::Neptune::DBCluster

### Issue Description

When a Neptune DBCluster is created, the DBClusterIdentifier will always be physically set to lower-cases, even if the value in the template contains upper-case characters.

When updating the template value (upper-case) to match the actual/physical value (lower-case), a 'Replacement' type update will be triggered, however this will fail with a 'DBClusterAlreadyExistsFault'.
Despite the error, the update will continue in CloudFormation and will delete the existing DBCluster even though the no new cluster was created to replace it.

### Expected Behavior

CloudFormation update should fail when the 'DBClusterAlreadyExistsFault' occurs.

### Observed Behavior

Update continues and will delete the existing cluster even if error occurs, leaving customers with no clusters at all.

### Test Cases

Create an AWS::Neptune::DBCluster with DBClusterIdentifier using upper-case values such i.e. NeptuneCluster

Check the cluster in the Neptune dashboard, and you should see the identifier will be shown in lower-case.

Update the CFN template such that DBClusterIdentifier is now using lower-case as well i.e. neptunecluster

Note:  Update should succeed and delete the existing cluster, but CTrail events should show a failed 'CreateDBCluster' call.

### Other Details

Possible fixes may be to have a validation in place to ensure DBClusterIdentifier for AWS::Neptune::DBCluster values can only be lower-case.

**Comment by halcoope** [comment]
Thank you for highlighting this bug. I (Amazon Neptune primary for today) will highlight this issue for our platform team to begin investigating and fixing the issue.

**Comment by jaiumang** [comment]
Thank you for reporting this issue. This issue has been fixed successfully. With the current implementation, if you update the CloudFormation stack to reflect the lowercase identifier, the stack template will be updated successfully without making any changes to the DBCluster resource.
