### ISSUE TITLE
CloudFormation fails to retrieve the RootResourceId of Rest API's with more than 200 resources

### ISSUE THREAD

**Issue by Aeolun** [aws-cloudformation/cloudformation-coverage-roadmap#1364]
### Name of the resource

AWS::ApiGateway::RestApi

### Issue Description

I've recently built a new CDK stack for our system, and  I'm running into an issue with API gateway that (from what I've been able to determine) seems to be caused by an CF limitation.

In specific, our API has more than 200 resources, and they're divided across many different CloudFormation Sub-stacks. Each of these stacks tries to retrieve the main API gateway information, but that's where it seems to go wrong.

> Stack |  1/41 | 12:51:54 AM | UPDATE_FAILED        | AWS::CloudFormation::Stack | name.NestedStack/name.NestedStackResource (NameStack) Template error: RootResourceId attribute of API Gateway RestAPI am2r0tfx64 doesn't exist

Support returned me the following information about this.

> Checking internally, I can confirm that this is the result of a CloudFormation service level limit. Unfortunately, CFN can only retrieve the first 200 resources (in aphabetical order) via the get-resources[1] API call. For API Id “am2r0tfx64” the root ID “uhq9lkuxi2” is starting with letter u (which is near the end in alphabet order, after 0->9, a->x). Checking from my side, this Id is in place 317 of 372.

### Expected Behavior

I expect CloudFormation to be able to retrieve the RootResourceId without relying on pagination/ordering. So that no matter how large my API, it'll be able to correctly retrieve references to it.

### Observed Behavior

If the API grows beyond 200 resources, and the ID for the root resource starts with a letter in the latter parts of the alphabet, CloudFormation will fail with a `RootResourceId attribute of API Gateway RestAPI am2r0tfx64 doesn't exist` error.

### Test Cases

Create an API with 400 resources, that has a root resource ID starting with `n-z`. This should guarantee that the root resource is not found in the first 8 pages of API gateway resources.

**Comment by kim00425** [comment]
same here
