### ISSUE TITLE
Missing `deliveryDelay` and `subscription` event types at AWS::SES::ConfigurationSetEventDestination EventDestination.MatchingEventTypes

### ISSUE THREAD

**Issue by Tietew** [aws-cloudformation/cloudformation-coverage-roadmap#1367]
### Name of the resource

AWS::SES::ConfigurationSetEventDestination

### Reference Link

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-configurationseteventdestination-eventdestination.html

### Details

The CloudFormation document says EventDestination.MatchingEventTypes can contain following values: `send`, `reject`, `bounce`, `complaint`, `delivery`, `open`, `click`, and `renderingFailure`. 

But CloudFomration actually accepts `deliveryDelay` and `subscription` in addition,
per `sesv2:CreateConfigurationSetEventDestination` API accepts `DELIVERY_DELAY` and `SUBSCRIPTION`[^1].

[^1]: https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_EventDestinationDefinition.html

**Comment by royal-git** [comment]
Hi, thanks a lot for bringing this to our attention, we are working on updating the documentation to show that we do support these additional fields.

**Comment by amala-chk** [comment]
Hi, This issue has been fixed
