### ISSUE TITLE
AWS::ServiceCatalog::PortfolioShare Add Property for OrganizationNode

### ISSUE THREAD

**Issue by jeffmarcinko** [aws-cloudformation/cloudformation-coverage-roadmap#137]
## 2. Scope of request 
The ServiceCatalog CreatePortfolioShare API supports OrganizationNode objects for sharing portfolios to an Organization ID, OU, or Account ID.  The PortfolioShare CloudFormation resource documentation mentions support for organization nodes but there is no suitable property.  Please add support for OrganizationNode to the PortfolioShare resource similar to the current AccountID property.

Samples: 
## 3. Expected behavior
In create the portfolio should be shared with the AWS Organization or OU when executed from the master account, similar to the the existing behavior with accountID.

## 5. Helpful Links to speed up research and evaluation

Samples:

**Comment by cooptastic** [comment]
any updates on this?

**Comment by ozbillwang** [comment]
We manage all resources with Cloudformation as IaC. It is bad news for us that we can't manage this part. 

Ticket has been raise for 1 year, please update when it can be implemented.

**Comment by KryptoFace** [comment]
This issue is closed because its duplicate issue of https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/594, please follow that issue thread for updates.
