### ISSUE TITLE
AWS::Logs::LogGroup don’t receive the aws:cloudformation built-in tags

### ISSUE THREAD

**Issue by bogdanb** [aws-cloudformation/cloudformation-coverage-roadmap#1379]
### Name of the resource

AWS::Logs::LogGroup

### Issue Description

When you have an `AWS::Log::LogGroup` resource in your stack, it does not get assigned the built-in tags: `aws:cloudformation:stack-name`, `aws:cloudformation:logical-id` and `aws:cloudformation:stack-id`.

Note that the stack explicitly creates the log groups as resources. They are *not* generated automatically by other stack resources, like, e.g. Lambda functions do, even though one would normally expect the stack tags to be added in those cases as well.

### Expected Behavior

All stack resources should automatically receive the aws:cloudformation:* built-in tags.

### Observed Behavior

No tags are added automatically to AWS::Log::LogGroup resources created by a stack.

### Test Cases

AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyInstance:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: my-test-log-group

### Other Details

Note that I have previously reported this as #1158, and that issue was closed by [cfn-github-issues-bot](https://github.com/cfn-github-issues-bot) on June 7. However, I have just started a new stack today which creates several log groups, and none of them have received the appropriate tags. I don’t know how to reopen a closed issue, which is why I’m creating a new one. Please let me know if I should have done something else instead.

**Comment by rgoltz** [comment]
Same issue like #1255

**Comment by shri-tambe** [comment]
AWS::Logs::LogGroup resource supports aws:cloudformation built-in tags now in all supported regions.

**Comment by kornicameister** [comment]
@bogdanb pls update your comment, I think you meant that if group exists it won't receive those tags upon update of the stack, however you wrote something else ;-)
