### ISSUE TITLE
Amplify - Codecommit - SNS trigger

### ISSUE THREAD

**Issue by kennethVerb** [aws-cloudformation/cloudformation-coverage-roadmap#1382]
### Name of the resource

AWS::Amplify::App

### Issue Description

When i configured two amplify apps using the same CodeCommit repo as 'Repository' in the same stack only one SNS trigger gets created in the CodeCommit repo.

When i split my amplify apps into two different sub stacks an SNS trigger gets added for each amplify app in the CodeCommit repo

### Expected Behavior

Expect a trigger created for each Amplify app in the same cloudformation stack

### Observed Behavior

Only the trigger for the first Amplify app in the stack gets created

### Test Cases

Create a codecommit repo
Create a cloudformation stack with 2 amplify apps configured (and for each an 'AWS::Amplify::Branch'  for master branch
observe only one trigger is configured on the CodeCommit repo

**Comment by KennethVrb** [comment]
@victorccccc i was able to work around this by using substacks for each amplify app. How did you guys fix this? I do not see a commit and the bot marked this as closed?
