### ISSUE TITLE
AWS::EC2::Route Cloud WAN CoreNetworkArn

### ISSUE THREAD

**Issue by mgway** [aws-cloudformation/cloudformation-coverage-roadmap#1384]
### Name of the resource

AWS::EC2::Route

### Description

The `AWS::EC2::Route` resource does not contain a property for specifying a Cloud WAN CoreNetworkArn. That property can be specified via API so this issue can be worked around with a custom resource, but it would be great to have support via CFN natively.

**Comment by ZalmnS** [comment]
+1

**Comment by LucasZhu97** [comment]
`CoreNetworkArn` property support was added late 2023. Please check out public doc here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route.html
