### ISSUE TITLE
AWS::SecretsManager::SecretTargetAttachment - Unsupported target type (DatabaseProxy)

### ISSUE THREAD

**Issue by Vesquen** [aws-cloudformation/cloudformation-coverage-roadmap#1394]
### Name of the resource

AWS::SecretsManager::SecretTargetAttachment

### Issue Description

Cloudformation complains about "Unsupported target type" when trying to use DBProxy (instead of DBCluster) as SecretTargetAttachment.

### Expected Behavior

DBProxy is a supported SecretTargetAttachment type

### Observed Behavior

DBProxy is an unsupported SecretTargetAttachment type

### Test Cases

Setup a DBCluster with DBProxy. Generate a DatabaseSecret for the DBProxy along with a SecretTargetAttachment with the DBProxy as target.

**Comment by jordaoesa** [comment]
Any updates on this?

It looks like DBProxy is supported by [CDK](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_secretsmanager.AttachmentTargetType.html), but it doesn't seem to be supported by [CFT](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html).

How is that possible? I don't know! In my understanding, CDK code gets converted to CF Templates.

**Comment by kboxeth** [comment]
Hello, Secrets Manager currently does not support DBProxy in the SecretTargetAttachment CFN resource, we are investigating adding this support. Thank you for reaching out, we will update this issue as work progresses.
