### ISSUE TITLE
AWS::DocDB::DBCluster needs DeletionPolicy=snapshot support 

### ISSUE THREAD

**Issue by dbayardAWS** [aws-cloudformation/cloudformation-coverage-roadmap#1397]
### Name of the resource

AWS::DocDB::DBCluster

### Description

AWS::DocDB::DBCluster is missing from the list of resources that supports a "snapshot" deletionPolicy.

See the list of supported resources at the bottom of this page: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html

Notice that RDS::DBCluster and Neptune::DBCluster are supported, but DocDB::DBCluster has not added this capability yet.

**Comment by grcyl** [comment]
Hi,

This functionality is supported and we will update the documentation.

Thanks
