### ISSUE TITLE
AWS::LakeFormation::DataLakeSettings Full Support

### ISSUE THREAD

**Issue by jliu0812** [aws-cloudformation/cloudformation-coverage-roadmap#1399]
### Name of the resource

AWS::LakeFormation::DataLakeSettings

### Description

I would like LakeFormation DataLakeSettings to be able to fully support what was represent what was declared with the API.

Currently, the API supports the following fields:

```json
{
  "CatalogId": "string",
  "DataLakeSettings": {
    "DataLakeAdmins": [
      {
        "DataLakePrincipalIdentifier": "string"
      }
    ],
    "CreateDatabaseDefaultPermissions": [
      {
        "Principal": {
          "DataLakePrincipalIdentifier": "string"
        },
        "Permissions": [
          "ALL"
        ]
      }
    ],
    "CreateTableDefaultPermissions": [
      {
        "Principal": {
          "DataLakePrincipalIdentifier": "string"
        },
        "Permissions": [
          "ALL"
        ]
      }
    ],
    "Parameters": {
      "string": "string"
    },
    "TrustedResourceOwners": [
      "string"
    ],
    "AllowExternalDataFiltering": true,
    "ExternalDataFilteringAllowList": [
      {
        "DataLakePrincipalIdentifier": "string"
      }
    ],
    "AuthorizedSessionTagValueList": [
      "string"
    ]
  }
}
```

However, the CloudFormation equivalent of this resource only supports the following fields:

```json
{
  "Type" : "AWS::LakeFormation::DataLakeSettings",
  "Properties" : {
      "Admins" : Admins,
      "TrustedResourceOwners" : [ String, ... ]
    }
}
```

Namely, CloudFormation does not support the CreateDatabaseDefaultPermissions, CreateTableDefaultPermissions, Parameters, TrustedResourceOwners, AllowExternalDataFiltering, ExternalDataFilteringAllowList, AuthorizedSessionTagValueList fields.

# Expected Behavior
I would expect CloudFormation to be able to spin up the LakeFormation DataLakeSettings similarly with the API.

### Other Details

Link to PutDataLakeSettings API: https://docs.aws.amazon.com/lake-formation/latest/APIReference/API_PutDataLakeSettings.html
Link to CloudFormation equivalent resource: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lakeformation-datalakesettings.html

**Comment by aws-kaushal-partani** [comment]
Hi,

We will look into this issue, although we are not currently tracking it with an ECD.

In the meantime, if it's absolutely needed, a workaround can be created via CFN custom resources: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-custom-resources.html

**Comment by jliu0812** [comment]
Hello, any update on this? This would be a great future to have.

**Comment by aws-kaushal-partani** [comment]
Hi, the new fields are now supported. We will continue adding to our public docs, but as of now, the new fields are supported: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lakeformation-datalakesettings.html

**Comment by acourtois** [comment]
Hi !
It seems that the following does not remove IAM_ALLOWED_PRINCIPALS "CreateTableDefaultPermissions" and "CreateDatabaseDefaultPermissions".
```yml
LakeFormationSettings:
    Type: AWS::LakeFormation::DataLakeSettings
    Properties:
      Admins:
        - DataLakePrincipalIdentifier: "arn:aws:iam::*****:*****"
      CreateDatabaseDefaultPermissions: []
      CreateTableDefaultPermissions: []
```

But it does well with the API put-data-lake-settings with this json input:
```json
{
    "DataLakeSettings": {
        "DataLakeAdmins": [
            {
                "DataLakePrincipalIdentifier": "arn:aws:iam::*****:*****"
            }
        ],
        "CreateDatabaseDefaultPermissions": [],
        "CreateTableDefaultPermissions": []
	}
}
```

**Comment by jliu0812** [comment]
Can confirm. I am facing the exact same scenario. Please reopen the ticket.

> Hi ! It seems that the following does not remove IAM "CreateTableDefaultPermissions" and "CreateDatabaseDefaultPermissions".
> 
> ```yaml
> LakeFormationSettings:
>     Type: AWS::LakeFormation::DataLakeSettings
>     Properties:
>       Admins:
>         - DataLakePrincipalIdentifier: "arn:aws:iam::*****:*****"
>       CreateDatabaseDefaultPermissions: []
>       CreateTableDefaultPermissions: []
> ```
> 
> But it does well with the API put-data-lake-settings with this json input:
> 
> ```json
> {
>     "DataLakeSettings": {
>         "DataLakeAdmins": [
>             {
>                 "DataLakePrincipalIdentifier": "arn:aws:iam::*****:*****"
>             }
>         ],
>         "CreateDatabaseDefaultPermissions": [],
>         "CreateTableDefaultPermissions": []
> 	}
> }
> ```
