### ISSUE TITLE
Best way to get generated ID (for example VPC_ID) after calling create-resource with cloud control

### ISSUE THREAD

**Issue by jkotalik** [aws-cloudformation/cloudformation-coverage-roadmap#1406]
### Name of the resource

AWS::EC2::VPC

### Issue Description

Currently trying to automate a resource being created with cloud control. When creating a VPC with cloud control, we can call
```
aws cloudcontrol create-resource --type-name AWS::EC2::VPC --desired-state '{"CidrBlock": "10.1.0.0/16"}'
```

After this call is done, updating this resource that is created is hard; we need to get the primary identifier(s) (vpc_id) from the result of `create-resource` and save it locally somewhere. Calling update afterwards requires the primary identifier(s) to be specified.
```
aws cloudcontrol update-resource --identifier <vpc_id> --type-name AWS::EC2::VPC --patch-document --patch-document '[{"op":"replace","path":"CidrBlock","value":"10.0.0.0/18"}]'
```

From what I can tell, with CloudFormation this isn't an issue because a stack is stored/saved on your behalf. Therefore the state storage is handled by AWS for detecting if a resource has been created or updated.

It seems like using Cloud-Control with generated/non-idempotent resources is hard and requires the user to store state for the primary identifiers.

Questions:
- In cloud control, is it the responsibility of the user to store state for the primary identifiers?
- Fundamentally resources that generate IDs are hard to handle, is there anything in cloud control that can help me here?
- Is there any plan to expose a cloud formation stack as part of cloud control?
- Any tips for how to automate usage of cloud control?

### Expected Behavior

Behavior is expected 

### Observed Behavior

Observed behavior is the same as expected

### Test Cases

Using cloud control to deploy resources

### Other Details

Not sure where cloud control issues are filed.

**Comment by aygold92** [comment]
It is the responsibility of the user to store the state of the primaryIdentifier.  Cloud Control is simply a standardized proxy to service APIs, while CloudFormation adds additional features like state management, cross resource coordination, etc. So in this case, the behavior of needing to save the output of the create call mirrors the service API experience if you called create-vpc.  

That said, you can also retrieve the progress (including the identifier) later by calling get-resource-request-status using the requestToken.

CloudFormation Stack will eventually be exposed through CCAPI.  What is the use case you are trying to achieve with that?

As far as tips, do you have more specific questions that were not covered in the [user guide](https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/getting-started.html)?

**Comment by TheDanBlanco** [comment]
closing this. feel free to reopen if you have more questions
