### ISSUE TITLE
AWS::Organizations::Organization - New Resource

### ISSUE THREAD

**Issue by pflorek** [aws-cloudformation/cloudformation-coverage-roadmap#1410]
### Resource Name

AWS::Organizations::Organization
AWS::Organizations::Root _(If GetAtt RootId of `AWS::Organizations::Organization` not possible)_

### Details

Title -> AWS::Organizations::Organization
Scope of request -> Create and manage an AWS Organization
Expected behavior -> A new Organization is created and the OrganizationId as the RootId are available as attributes
Test case recommendation (optional) ->
Links to existing API doc (optional) -> https://docs.aws.amazon.com/organizations/latest/APIReference/API_CreateOrganization.html https://docs.aws.amazon.com/organizations/latest/APIReference/API_ListRoots.html
Category tag (optional) -> Organizations

__

FeatureSet ALL should be default if possible, since it's mandatory for SCP, ...
`AWS::Organizations::Organization` support was forgotten in the roadmap https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/33#issuecomment-1320712833

Without this feature we are forced to either do ClickOps or write own custom CFN resources like https://github.com/pepperize/cdk-organizations/blob/main/src/organization.ts

**Comment by prerna-p** [comment]
I believe this can be closed now:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-organizations-organization.html
