### ISSUE TITLE
AWS::Events::Rule - Timezone

### ISSUE THREAD

**Issue by xrn** [aws-cloudformation/cloudformation-coverage-roadmap#1412]
### Name of the resource

AWS::Events::Rule

### Resource name

AWS::Events::Rule

### Description

Following newest release https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/

There should be support for `schedule-expression-timezone` 
 
```
aws scheduler create-schedule --name SendEmailOnce \ 
--schedule-expression "at(2022-11-01T11:00:00)" \ 
--schedule-expression-timezone "Europe/Helsinki" \
--flexible-time-window "{\"Mode\": \"OFF\"}" \
--target "{\"Arn\": \"arn:aws:sns:us-east-1:xxx:test-chronos-send-email\", \"RoleArn\": \" arn:aws:iam::xxxx:role/sam_scheduler_role\" }"
```

Which is missing https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html

**Comment by iainelder** [comment]
I haven't worked with the Scheduler service yet, but it appears to have CloudFormation coverge.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedule.html

That page doucments a property called ScheduleExpressionTimezone.

AWS::Events::Rule is similar, but a different resource type for a different service. I believe it's what the Scheduler service can replace in some use cases.

The two are compared in this AWS blog post:

https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/

**Comment by xrn** [comment]
Thank you @iainelder
