### ISSUE TITLE
AWS::Glue::Job Flex Execution for Glue Jobs

### ISSUE THREAD

**Issue by butterbach** [aws-cloudformation/cloudformation-coverage-roadmap#1416]
### Name of the resource

AWS::Glue::Job

### Description

As requested in https://github.com/aws/aws-cdk/issues/22224 we would like to set the flex execution option for Glue Jobs which was introduced months ago.

https://aws.amazon.com/about-aws/whats-new/2022/08/aws-glue-supports-flex-execution-option/

**Comment by crea** [comment]
Support to cloud formation is already implemented via the ExecutionClass property. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-job.html
