### ISSUE TITLE
AWS::GameLift::MatchMakingConfiguration resource type coverage request

### ISSUE THREAD

**Issue by isaac-pulumi** [aws-cloudformation/cloudformation-coverage-roadmap#1430]
### Name of the resource

AWS::GameLift::MatchmakingConfiguration

### Description

This resource type is available in CloudFormation but missing from CCAPI. We currently have multiple customers that cannot use the feature without CCAPI support.

Related: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1431

cc: @jaxxstorm

**Comment by xmiao2** [comment]
Tracking with #1431
