### ISSUE TITLE
AWS::GameLift::MatchmakingRuleSet resource type coverage request 

### ISSUE THREAD

**Issue by isaac-pulumi** [aws-cloudformation/cloudformation-coverage-roadmap#1431]
### Name of the resource

AWS::GameLift::MatchmakingRuleSet

### Description

This resource appears to be available in CloudFormation but missing from CCAPI and is blocking a joint customer use case.

Related: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1430

Cc: @jaxxstorm

**Comment by DanGreen100** [comment]
GameLift has released CCAPI support for the AWS::GameLift::MatchmakingRuleSet resource.

For more information see the GameLift release notes: https://docs.aws.amazon.com/gamelift/latest/developerguide/release-notes.html#release-notes-11212023
