### ISSUE TITLE
AWS::MSK::ServerlessCluster Tags update requires replacement

### ISSUE THREAD

**Issue by ccbrown** [aws-cloudformation/cloudformation-coverage-roadmap#1432]
### Name of the resource

AWS::MSK::ServerlessCluster

### Resource Name

AWS::MSK::ServerlessCluster

### Issue Description

Currently, updating Tags for a AWS::MSK::ServerlessCluster resource requires replacement. This is as far as I've encountered the only CloudFormation resource with this behavior, and it is possible to change the tags on an MSK serverless cluster outside of CloudFormation.

### Expected Behavior

It should be possible to change the Tags of an AWS::MSK::ServerlessCluster resource without replacing it.

### Observed Behavior

Changing the Tags of an AWS::MSK::ServerlessCluster resource requires it to be replaced.

### Test Cases

Any AWS::MSK::ServerlessCluster resource will reproduce the issue if you modify the Tags property.

**Comment by sankalpbhatia** [comment]
We are working on supporting updating tags feature through the serverless cluster CloudFormation resource. We expect to release by Q1 2023
