### ISSUE TITLE
change sets for stack sets

### ISSUE THREAD

**Issue by atkinsonm** [aws-cloudformation/cloudformation-coverage-roadmap#144]
I would like to be able to evaluate a change set on a stack set. The change set should return all changes evaluated against all stack instances.

**Comment by PatMyron** [comment]
See also https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/224 about a new `UpdateReplacePolicy` option so every change set `Replacement` value no longer needs to be evaluated

**Comment by TheDanBlanco** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/change-sets-for-nested-stacks.html
