### ISSUE TITLE
Release history references AWS::ECS::TaskDefinition PortMappings update on 12/2, link goes nowhere

### ISSUE THREAD

**Issue by isuftin** [aws-cloudformation/cloudformation-coverage-roadmap#1449]
### Name of the resource

AWS::ECS::TaskDefinition

### Reference Link

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

### Details

For 12/2/22, link for AWS::ECS::TaskDefinition PortMappings goes to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-portmappings.html which doesn't seem to be a thing 

That link responds with a 302 to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/

**Comment by rgoltz** [comment]
I would recommend to open an issue here for this documentation/link issue: https://github.com/awsdocs/aws-cloudformation-user-guide/issues and reference to this issue here :)

**Comment by LiangChiAmzn** [comment]
It looks like the link from release history has an additional 's' in the end

- Incorrect: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-portmappings.html 
- Correct: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-portmapping.html

The hyperlink seems to work as expected in the `AWS::ECS::TaskDefinition ContainerDefinition` documentation page:

- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-containerdefinition.html#cfn-ecs-taskdefinition-containerdefinition-portmappings

Resolving this as the current documentation is accurate.
