### ISSUE TITLE
AWS::RUM::AppMonitor AppMonitorConfiguration missing custom events config

### ISSUE THREAD

**Issue by hoonoh** [aws-cloudformation/cloudformation-coverage-roadmap#1450]
### Name of the resource

Other

### Resource name

AWS::RUM::AppMonitor AppMonitorConfiguration

### Description

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rum-appmonitor-appmonitorconfiguration.html
https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-cloudwatch-rum-custom-events-troubleshooting-application-monitoring/

Hello,
It seem currently there is no way of enabling custom events via CFN.

**Comment by Hasan-Jawaheri** [comment]
+1
