### ISSUE TITLE
AWS::RUM::AppMonitor GetAtt Application ID (App Monitor ID) 

### ISSUE THREAD

**Issue by hoonoh** [aws-cloudformation/cloudformation-coverage-roadmap#1451]
### Name of the resource

Other

### Resource name

AWS::RUM::AppMonitor

### Description

Currently `AWS::RUM::AppMonitor` does not expose `Application ID`(or `App Monitor ID`, as labled in console).
This is required to generate RUM initializer script on front-end (e.g. via ECS task definition environment variables)

**Comment by Hasan-Jawaheri** [comment]
This is needed for most use cases of AWS RUM, alternative is quite ugly: https://aws.amazon.com/blogs/mobile/implementing-real-user-monitoring-of-amplify-application-using-amazon-cloudwatch-rum/

**Comment by limhjgrace** [comment]
We've deployed the changes to include the `Application ID` in the app monitor details. The public docs will updated soon to reflect this change but the functionality is available.
