### ISSUE TITLE
AWS::RUM::AppMonitor missing 'include subdomain' parameter

### ISSUE THREAD

**Issue by hoonoh** [aws-cloudformation/cloudformation-coverage-roadmap#1453]
### Name of the resource

Other

### Resource name

AWS::RUM::AppMonitor

### Description

`AWS::RUM::AppMonitor` is currently missing 'include subdomain' parameter, which is available with the console.

**Comment by limhjgrace** [comment]
Hello, this is expected as CW RUM CFN currently does not support that parameter.

**Comment by hoonoh** [comment]
> Hello, this is expected as CW RUM CFN currently does not support that parameter.

@limhjgrace Does this mean that this parameter will never be added in the future? I was thinking this should be added since otherwise I would have to enable 'include subdomain' via console after every CFN deployment.

**Comment by limhjgrace** [comment]
It's currently a console only feature but if you open a FR, we can definitely prioritize this feature!

**Comment by hoonoh** [comment]
@limhjgrace I thought opening an issue with the template named `Missing CloudFormation support` was for feature requests, which this issue was intended for.
Could this issue be reopened as a feature request?

**Comment by lober-io** [comment]
In Amplify, I used a custom CDK resource to deploy "*.domain.com" and achieved the same result as selecting the "Include Subdomains" checkbox.
When using the console, it's evident in the API request that it achieves the same effect.
