### ISSUE TITLE
AWS::FSx::Volume missing 'OntapVolumeType' under OntapConfiguration property 

### ISSUE THREAD

**Issue by Maha-OU** [aws-cloudformation/cloudformation-coverage-roadmap#1454]
### Name of the resource

Other

### Resource name

AWS::FSx::Volume

### Description

AWS::FSx::Volume is currently missing 'OntapVolumeType' property in OntapConfiguration, this property is available with the console, AWS CLI and Boto3.

### Other Details

CloudFormation only supports creating ONTAP Volumes of type RW(Read-Write), DW (Data Protection) currently not supported.

**Comment by alngy** [comment]
Works fine for me, I see the documentation here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-fsx-volume-ontapconfiguration.html#cfn-fsx-volume-ontapconfiguration-ontapvolumetype

I also tested with the following template and it deployed successfully. **If you are still having issues, please provide steps to reproduce.**

```
AWSTemplateFormatVersion: 2010-09-09

Description: >
  For testing

Parameters:
  SubnetId:
    Type: String
    Default: "subnet-xxx"

Resources:
  OntapFsxSystem:
    Type: AWS::FSx::FileSystem
    Properties:
      FileSystemType: ONTAP
      StorageCapacity: 1024
      SubnetIds: [!Ref SubnetId]
      OntapConfiguration:
        DeploymentType: SINGLE_AZ_1
        ThroughputCapacity: 128
  OntapSVM:
    DependsOn: OntapFsxSystem
    Type: AWS::FSx::StorageVirtualMachine
    Properties:
      FileSystemId:
        Ref: OntapFsxSystem
      Name: OntapSVM
      RootVolumeSecurityStyle: UNIX
  OntapVolume:
    DependsOn: OntapSVM
    Type: AWS::FSx::Volume
    Properties:
      VolumeType: ONTAP
      Name: OntapVolumeUnix
      OntapConfiguration:
        JunctionPath: /fsx-ontap-vol-unix
        SecurityStyle: UNIX
        SizeInMegabytes: 4096
        StorageEfficiencyEnabled: false
        OntapVolumeType: RW
        StorageVirtualMachineId:
          Ref: OntapSVM
```
