### ISSUE TITLE
AWS::Logs::LogGroup does not support the Tags property in the GovCloud regions

### ISSUE THREAD

**Issue by shantgup** [aws-cloudformation/cloudformation-coverage-roadmap#1462]
### Name of the resource

AWS::Logs::LogGroup

### Description

The `AWS::Logs::LogGroup` resource does not support the Tags property in the GovCloud regions.

Steps to reproduce:

1. Create a LogGroup in gov cloud regions using the snippet below.
2. Receive the error "Encountered unsupported property Tags".

Please let me know if I can provide any other information.

**Comment by shri-tambe** [comment]
AWS::Logs::LogGroup resource is now consistent with commercial regions and supports Tags property.
