### ISSUE TITLE
AWS::CE::AnomalySubscription property ThresholdExpression is not allowed.

### ISSUE THREAD

**Issue by lvthillo** [aws-cloudformation/cloudformation-coverage-roadmap#1471]
### Name of the resource

AWS::CE::AnomalySubscription

### Issue Description

There is a [new feature](https://aws.amazon.com/about-aws/whats-new/2022/12/aws-cost-anomaly-detection-percentage-based-thresholds/) that we can use a percentage as threshold.

Documentation [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ce-anomalysubscription.html#cfn-ce-anomalysubscription-threshold) states:

> Threshold
(deprecated)
The dollar value that triggers a notification if the threshold is exceeded.
This field has been deprecated. To specify a threshold, use ThresholdExpression. Continued use of Threshold will be treated as shorthand syntax for a ThresholdExpression.
One of Threshold or ThresholdExpression is required for this resource.

So I'm replacing `Threshold` with `ThresholdExpression`.

During deploy:
```
Properties validation failed for resource AnomalySubscriptionTemp with message: #: required key [Threshold] not found #: extraneous key [ThresholdExpression] is not permitted
```

### Expected Behavior

Resource should be updated.

### Observed Behavior

An error (above). The stack update fails

### Test Cases

Use ThresholdExpression in your CF.

```
  AnomalySubscription:
    Type: AWS::CE::AnomalySubscription
    Properties:
      SubscriptionName: "xxx"
      ThresholdExpression: 100
      Frequency: "IMMEDIATE"
      ...
```
### Other Details

I'm trying to use this updated value because I want to use the new feature explained [here](https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_AnomalySubscription.html#awscostmanagement-Type-AnomalySubscription-ThresholdExpression)

The API should support this, but it seems not possible in CF:
```
{ "Or": [ { "Dimensions": { "Key": "ANOMALY_TOTAL_IMPACT_ABSOLUTE", "MatchOptions": [ "GREATER_THAN_OR_EQUAL" ], "Values": [ "100" ] } }, { "Dimensions": { "Key": "ANOMALY_TOTAL_IMPACT_PERCENTAGE", "MatchOptions": [ "GREATER_THAN_OR_EQUAL" ], "Values": [ "100" ] } } ] }
```

**Comment by keatomue** [comment]
Hello, thank you for raising this issue. We are actively working on delivering this update to the CloudFormation integration for Cost Anomaly Detection. I will post an update here once the change is done and `ThresholdExpression` is ready for use.

In the meantime, please continue to use the `Threshold` field as you have been. It has been marked as deprecated to encourage adoption of `ThresholdExpression`, but we will continue to support its functionality.

**Comment by keatomue** [comment]
Hello, I'm happy to share that `ThresholdExpression` is now launched for our CloudFormation integration!

You can find the related PR here if you're curious:  https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cost-explorer/pull/23
