### ISSUE TITLE
`AWS::Glue::Crawler` missing support for Delta Lake targets (`DeltaTargets`)

### ISSUE THREAD

**Issue by mikix** [aws-cloudformation/cloudformation-coverage-roadmap#1472]
### Name of the resource

AWS::Glue::Crawler

### Description

As [recently announced](https://aws.amazon.com/blogs/big-data/introducing-native-delta-lake-table-support-with-aws-glue-crawlers/), Glue Crawlers can now natively support a Delta Lake target. This is possible in the console web UI, but not yet in CloudFormation.

I would expect that the `Targets` field of an `AWS::Glue::Crawler` would grow support for a `DeltaTargets` value (like `S3Targets`) on which one could set fields like `ConnectionName`,  `CreateNativeDeltaTable`, `DeltaTables`, and `WriteManifest` (i.e. all the fields described in that announcement blog post).

I would also be interested in the `DeltaTables` list being able to allow wildcards, but I'm not sure if the web console supports that, so I understand if that is not in scope.

**Comment by mberchon** [comment]
Hello,

Any work-around to setup a Delta Lake crawler through CloudFormation & CDK ?
Our deployment model makes intensive usage of CDK and going through console to setup our crawler is very painful.

**Comment by bpoweski** [comment]
> Hello,
> 
> Any work-around to setup a Delta Lake crawler through CloudFormation & CDK ? Our deployment model makes intensive usage of CDK and going through console to setup our crawler is very painful.

Agreed.  However, you can use a custom resource to lessen the pain.

**Comment by mikix** [comment]
Hey looks like this got implemented:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-crawler-deltatarget.html

Guess I'll close.
