### ISSUE TITLE
When can we expect StackSets regional support in eu-central-2 - Europe (Zurich)

### ISSUE THREAD

**Issue by johancar** [aws-cloudformation/cloudformation-coverage-roadmap#1473]
### Resource Name

https://docs.aws.amazon.com/general/latest/gr/cfn.html#regional-support-stacksets

### Details

Currently eu-central-2 - Europe (Zurich) is not included in StackSets regional support.

Any information on when it may be available?

Thank you.

**Comment by TheDanBlanco** [comment]
https://aws.amazon.com/about-aws/whats-new/2023/05/aws-cloudformation-stacksets-additional-regions/
