### ISSUE TITLE
 Support for Import of AWS::SNS::TopicPolicy Resource

### ISSUE THREAD

**Issue by a4arjuna** [aws-cloudformation/cloudformation-coverage-roadmap#1476]
### Name of the resource

AWS::SNS::TopicPolicy

### Description

Hello team,

Requesting to add resource type AWS::SNS::TopicPolicy to support import operation.

Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

**Comment by dnicolacopoulos** [comment]
Hello,

Not just TopicPolicy but `AWS::SNS::Topic` as a whole...Thanks!

**Comment by shih** [comment]
Topic should be supported already.

As for `TopicPolicy`, please use `AWS::SNS::TopicInlinePolicy` which should support import.
