### ISSUE TITLE
AWS::Lex::Bot missing Initial response feature

### ISSUE THREAD

**Issue by fbzioui** [aws-cloudformation/cloudformation-coverage-roadmap#1486]
### Name of the resource

Other

### Resource name

AWS::Lex::Bot

### Description

CloudFormation currently doesn't support initial response feature for the Amazon Lex bot - AWS::Lex::Bot.

Requesting to add the feature ‘initial response’ to AWS::Lex::Bot resource.

**Comment by chenqiamzn** [comment]
Hello, the InitialResponseSetting has been added to AWS::Lex::Bot. Thank you.
