### ISSUE TITLE
Cannot specify parameter group name for AWS::Redshift::ClusterParameterGroup resources

### ISSUE THREAD

**Issue by scotliu** [aws-cloudformation/cloudformation-coverage-roadmap#1491]
### Name of the resource

AWS::Redshift::ClusterParameterGroup

### Description

Currently when creating a Redshift cluster parameter group via console or AWS CLI you can specify the parameter group name via the API call here:

CreateClusterParameterGroup
https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateClusterParameterGroup.html

The methods for creating redshift parameter group is also documented here and show that naming the new cluster parameter group is possible:
https://docs.aws.amazon.com/redshift/latest/mgmt/working-with-parameter-groups.html

From CloudFormation documentation there is no property to specify the parameter group name, and using this resource type will generate parameter group name based on the stack name.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-clusterparametergroup.html

Requesting review of this functionality and adding this property to CloudFormation support..

**Comment by leo19900723** [comment]
PR issued: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-redshift/pull/130

**Comment by leo19900723** [comment]
Long been merged. Request to close the issue
