### ISSUE TITLE
AWS::EC2::KeyPair deletes existing KeyPairs if same name is used for KeyName property

### ISSUE THREAD

**Issue by ruvimrd** [aws-cloudformation/cloudformation-coverage-roadmap#1493]
### Name of the resource

Other

### Resource Name

AWS::EC2::KeyPair

### Issue Description

CloudFormation deletes existing Key Pairs if you try to create an AWS::EC2::KeyPair resource with the same name as an already created Key Pair in the account.

### Expected Behavior

Stack rollback due to the "AlreadyExists" handler error code without deleting the already existing key pair under the same name.

### Observed Behavior

Stack fails to create the KeyPair resource because the KeyPair name already exists in the account. On stack rollback, the existing key pair with the same name is deleted.

### Test Cases

Steps of deployment:
    > Create Key Pair in the EC2 Console
    > Create CloudFormation stack with a Key Pair resource, where 'KeyName' is the same name as the above created key pair.
    > This stack will fail to create due to the key pair already existing.
    > During stack rollback, that existing key pair resource will also be deleted. This shouldn't happen, since the resource isn't managed by the stack.

**Comment by jtander-tmr** [comment]
@ruvimrd Was this ever actually fixed? I am running into a similar issue where my key pair is being deleted when I deploy my CloudFormation template.
