### ISSUE TITLE
(RDS::DBCluster): new password not applied when restoring from snapshot

### ISSUE THREAD

**Issue by ryparker** [aws-cloudformation/cloudformation-coverage-roadmap#1500]
### Name of the resource

AWS::RDS::DBCluster

### Issue Description

When provisioning a `DBCluster` with both `SnapshotIdentifier` and a new `MasterUserPassword` the `DBCluster` is restored but it does not update to use the new `MasterUserPassword` provided. 

`DBCluster` event log:

<img width="1404" alt="CleanShot 2023-01-30 at 18 05 15@2x" src="https://user-images.githubusercontent.com/17558268/215641265-42953738-6e46-4e53-891f-2c921d92fccf.png">

However if I provision a `DBInstance` under the same conditions it will result in the `DBInstance` being restored and updated with the provided `MasterUserPassword` all in one deploy. 

`DBInstance` event log (notice the "Reset master credentials" event fired):

<img width="1389" alt="CleanShot 2023-01-30 at 17 47 11@2x" src="https://user-images.githubusercontent.com/17558268/215638618-98706d82-43c3-412b-9063-78c99156293f.png">

### Expected Behavior

I expected the `DBCluster` behavior to match the `DBInstance` behavior. The `DBCluster` should restore from snapshot and update the master password to the new value I provided, all in one deploy.

### Observed Behavior

The `DBCluster` successfully restores from snapshot however the master password is not updated.

### Test Cases

1.) Deploy a DBCluster that has `SnapshotIdentifier` and `MasterUserPassword` props provided. The `MasterUserPassword` should be a different password than the one that was used to create the original `DBCluster`.
2.) Connect to the DBCluster using the password provided in `MasterUserPassword`.

This should work when `MasterUserPassword` is provided as a raw string in the template or as a reference to a new secret.

### Other Details

The Cfn documentation for `DB:Cluster` states that `MasterUserPassword` should not be provided when restoring from a snapshot.

> If you specify the SourceDBClusterIdentifier, SnapshotIdentifier, or GlobalClusterIdentifier property, don't specify this property. The value is inherited from the source DB cluster, the snapshot, or the primary DB cluster for the global database cluster, respectively.
>
> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-masteruserpassword

However similar documentation is also provided for `DB:Instance`, even though it successfully updates the password:

> Some DB instance properties aren't valid when you restore from a snapshot, such as the MasterUsername and MasterUserPassword properties. For information about the properties that you can specify, see the RestoreDBInstanceFromDBSnapshot action in the Amazon RDS API Reference.
>
> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html#cfn-rds-dbinstance-dbsnapshotidentifier

**Comment by kddejong** [comment]
This is now available for `AWS::RDS::DBCluster`.  It will only work for `MasterUserPassword`
