### ISSUE TITLE
[Feature Request] AWS::RUM::AppMonitor missing 'include subdomain' parameter

### ISSUE THREAD

**Issue by hoonoh** [aws-cloudformation/cloudformation-coverage-roadmap#1506]
### Name of the resource

Other

### Resource name

AWS::RUM::AppMonitor

### Description

This is a feature request for `AWS::RUM::AppMonitor`, which is currently missing 'include subdomain' parameter, which is available with the console.

### Other Details

This issue is duplicate of https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1453 which was closed since it was not marked as a Feature Request.

**Comment by adebayor123** [comment]
Hi @hoonoh , thanks for reaching out. You can achieve the same "Include subdomain" functionality by adding a star `*` as part of the domain.

For example, clicking on "Include Subdomain" for `cloudfront.net` would automatically translate it to `*.cloudfront.net`.
