### ISSUE TITLE
AWS::DocDB::DBCluster - support for Dynamic References in MasterUserPassword

### ISSUE THREAD

**Issue by k-ong** [aws-cloudformation/cloudformation-coverage-roadmap#152]
## Instructions for CloudFormation Coverage New Issues Template

Quick Sample Summary:
1. Title -> AWS::DocDB::DBCluster-MasterUserPassword
2. Scope of request -> AWS::DocDB::DBCluster-MasterUserPassword supports String values today, but not Dynamic References to SSM and Secret Manager values.
3. Expected behavior -> In Create, it should be able to resolve Secret Manager values and associations, like the console. 
4. Test case recommendation (optional) -> it should allow usage of SSM and Secrets Manager references given similar support in RDS resources
5. Links to existing API doc (optional) -> 
6. Category tag (optional) -> Database
7. Any additional context (optional)

**Comment by parimaldeshmukh** [comment]
This is implemented now. You should be able to use dynamic references in DocDB resource properties.

**Comment by brianterry** [comment]
Closing because this is a duplicate issue.
#94
