### ISSUE TITLE
(AWS::KMS::Key) resources don't receive the aws:cloudformation built-in tags / default service-managed auto-tags

### ISSUE THREAD

**Issue by rgoltz** [aws-cloudformation/cloudformation-coverage-roadmap#1522]
### Name of the resource

AWS::KMS::Key

### Issue Description

To find the right CloudFormation Stack -where a AWS resource is defined/maintained- **aws:cloudformation:*** built-in tags are needed. This is an important function in day-to-day business.

### Expected Behavior

Resources with type `AWS::KMS::Key` (Customer managed keys), which are managed as CloudFormations Stacks, should automatically receive the aws:cloudformation:* built-in tags / automatic default CFN AutoTags.

Furthermore those aws:cloudformation:* built-in tags must be handled by <ins>CloudFormation Drift-Detection</ins> correctly (hence, aws:cloudformation:* tags are _not_ a drift)

### Observed Behavior

When you have an `AWS::KMS::Key` resource in your stack, it does not get the built-in tags assigned: `aws:cloudformation:stack-name`, `aws:cloudformation:logical-id` and `aws:cloudformation:stack-id`

### Test Cases

Deploy a CloudFormation stack containing this resource named above (e.g. sample from AWS docs) and check the tags on the console. You can't see aws:cloudformation:* built-in tags.

**Comment by ZalmnS** [comment]
This issue regretfully is not resolved as of this comments timestamp in us-east-1 and us-west-2
