### ISSUE TITLE
AWS::SageMaker::ModelPackageGroup - Does not inherit tags from stack

### ISSUE THREAD

**Issue by rtkgeoff** [aws-cloudformation/cloudformation-coverage-roadmap#1523]
### Name of the resource

AWS::SageMaker::ModelPackageGroup

### Description

Cloudformation supports setting the Tags of the `AWS::SageMaker::ModelPackage` resource, but the stack-level tags are not propagating to the resource like they do for other resources with Tags.

Stack-level tags should consistently propagate to any resource in the stack with a Tags attribute.

**Comment by kuttyselva** [comment]
Are you looking for tag attachment in ModelPackage or ModelPackageGroup ?
