### ISSUE TITLE
AWS::ECS::Service Can't update FargateService with CODE_DEPLOY

### ISSUE THREAD

**Issue by sergeivalko** [aws-cloudformation/cloudformation-coverage-roadmap#1529]
### Name of the resource

AWS::ECS::Service

### Issue Description

I found the Update Service API call event and it looks like the cloudformation also sent other information like taskDefinition, network, etc in the requestParameters and I think that's not correct.

![image](https://user-images.githubusercontent.com/21295107/219815995-d4880913-a2b8-4e35-be2c-bd5ef3af421d.png)

### Expected Behavior

Update API call fills fields that have changed

### Observed Behavior

The update API call populates all properties, even those that haven't changed

Error: `Unable to update task definition on services with a CODE_DEPLOY deployment controller. Use AWS CodeDeploy to trigger a new deployment`

### Test Cases

1. create stack with ecs fargate service with `CODE_DEPLOY ` deployment controller type
2. try to update desired count\health check or any [allowed](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html#:~:text=For%20services%20using%20the%20blue,deployment.%20For%20more%20information%2C%20see) then you will see exception

### Other Details

my changeset: 
```json
[
  {
    "resourceChange": {
      "logicalResourceId": "DeploymentGroup6D277AF0",
      "action": "Modify",
      "physicalResourceId": "default",
      "resourceType": "AWS::CodeDeploy::DeploymentGroup",
      "replacement": "False",
      "moduleInfo": null,
      "details": [
        {
          "target": {
            "name": "ECSServices",
            "requiresRecreation": "Never",
            "attribute": "Properties"
          },
          "causingEntity": "ServiceD69D759B.Name",
          "evaluation": "Dynamic",
          "changeSource": "ResourceAttribute"
        }
      ],
      "changeSetId": null,
      "scope": [
        "Properties"
      ]
    },
    "hookInvocationCount": null,
    "type": "Resource"
  },
  {
    "resourceChange": {
      "logicalResourceId": "ServiceD69D759B",
      "action": "Modify",
      "physicalResourceId": "[ARN]-service/n2p-uniteplatform-dev/n2p-unite-call-queue-metrics-service",
      "resourceType": "AWS::ECS::Service",
      "replacement": "False",
      "moduleInfo": null,
      "details": [
        {
          "target": {
            "name": "DesiredCount",
            "requiresRecreation": "Never",
            "attribute": "Properties"
          },
          "causingEntity": null,
          "evaluation": "Static",
          "changeSource": "DirectModification"
        }
      ],
      "changeSetId": null,
      "scope": [
        "Properties"
      ]
    },
    "hookInvocationCount": null,
    "type": "Resource"
  },
  {
    "resourceChange": {
      "logicalResourceId": "ServiceTaskCountTarget23E25614",
      "action": "Modify",
      "physicalResourceId": "service/n2p-uniteplatform-dev/n2p-unite-call-queue-metrics-service|ecs:service:DesiredCount|ecs",
      "resourceType": "AWS::ApplicationAutoScaling::ScalableTarget",
      "replacement": "Conditional",
      "moduleInfo": null,
      "details": [
        {
          "target": {
            "name": "ResourceId",
            "requiresRecreation": "Always",
            "attribute": "Properties"
          },
          "causingEntity": "ServiceD69D759B.Name",
          "evaluation": "Dynamic",
          "changeSource": "ResourceAttribute"
        }
      ],
      "changeSetId": null,
      "scope": [
        "Properties"
      ]
    },
    "hookInvocationCount": null,
    "type": "Resource"
  }
]
```

**Comment by Rainson12** [comment]
it says this is shipped? How can we make us of it?

**Comment by amsoares** [comment]
> it says this is shipped? How can we make us of it?

I'm looking for the same.

**Comment by bharathcp** [comment]
This seems to be incorrectly closed. The cloud formation service is still not fixed. My cloudtrail still shows cloud formation making updateservice call with all params that is not allowed. 
Please reopen the issue.

**Comment by jvesala** [comment]
Hello everyone! 

Do we have more visibility on what `Coming soon` really means? Weeks or months?

**Comment by sergeivalko** [comment]
@jvesala Actually we don't have, we'll have to wait because as you can see the ticket was created on Feb 18th but closed by accident later, hopefully they deliver it soon.

**Comment by terusaku** [comment]
Hopefully this roadmap will resolve my issue, too.

and personally, I want to know the scope, what is (not) possible changes through `cdk deploy` with ECS Fargate that have CODE_DEPLOY config. 

CodeDeploy can update ECS Service through deployment, but cannot update ECS TaskDef, I think. 
Updating TaskDef is the duty of IaC .

ref.) GitHub Actions: [amazon-ecs-deploy-task-definition](https://github.com/aws-actions/amazon-ecs-deploy-task-definition#aws-codedeploy-support)
CodeDeploy just have reference TaskDef, currently.

**Comment by acs-mpatel** [comment]
This is problem if you are using IaC (Cloudformation). You can't update Task Definition and have to manually update it. Kills the purpose of IaC
