### ISSUE TITLE
only changing UpdateReplacePolicy/DeletionPolicy is a no-op

### ISSUE THREAD

**Issue by rittneje** [aws-cloudformation/cloudformation-coverage-roadmap#1543]
### Name of the resource

Other

### Issue Description

This bug affects all resources.

If I alter my CloudFormation stack template such that the only change is the `UpdateReplacePolicy` and/or `DeletionPolicy`, then the resulting changeset incorrectly treats it as a no-op, meaning the original policies are retained.

This means that:
1. If I am setting the `DeletionPolicy` from `Retain` to `Delete` in anticipation of deleting the entire stack, then the resource gets leaked anyway, requiring manual intervention.
2. If I am setting the `DeletionPolicy` from `Delete` to `Retain` in anticipation of deleting the entire stack, then the resource gets deleted anyway, **potentially resulting in unexpected data loss**.

### Expected Behavior

Changing the `UpdateReplacePolicy` and/or `DeletionPolicy` MUST get applied, even if that is the only diff.

### Observed Behavior

See above.

### Test Cases

1. Create a stack template with `UpdateReplacePolicy` and `DeletionPolicy` set to `Delete` for some resource.
2. Deploy the stack.
3. Change the template to set `UpdateReplacePolicy` and `DeletionPolicy` to `Retain`.
4. Deploy the stack.
5. Observe the second deployment is a no-op.

**Comment by jlhood** [comment]
@rittneje Thanks for creating this issue! I have successfully reproduced the issue and our teams will look into it. In the meantime, you can workaround this issue by using the [UpdateStack API](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStack.html), which will apply the change to add DeletionPolicy/UpdateReplacePolicy to the resource.

**Comment by rittneje** [comment]
> In the meantime, you can workaround this issue by using the [UpdateStack API](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStack.html), which will apply the change to add DeletionPolicy/UpdateReplacePolicy to the resource.

We use CDK, so we don't have any control over the API calls it chooses to make.

**Comment by kanitkah** [comment]
This issue has been resolved. Please retest and confirm.
