### ISSUE TITLE
Drift Detection assumes Lambda Functions use Zip Packages, fails

### ISSUE THREAD

**Issue by phs** [aws-cloudformation/cloudformation-coverage-roadmap#1559]
### Name of the resource

AWS::Lambda::Function

### Issue Description

I recently added a lambda function to my stack set.  When I did so, drift detection began to fail.  In the console I see that the `DETECT_DRIFT` stack set operation has status `FAILED`.  When I inspect the operation, the stack set instance for the one region that includes the function (it is isolated to one region with a condition) also has status `FAILED`.  Removing the lambda function from the template and updating allows drift detection to resume working normally.

With the function present in the template and created, I investigated the affected stack directly.  Using the `aws cloudformation detect-stack-drift` CLI command I could trigger a new drift detection and receive a `StackDriftDetectionId`.  When I passed this to `aws cloudformation describe-stack-drift-detection-status`, I could immediately and invariably see a response with this `DetectionStatusReason`:

```
{
    "StackId": "arn:aws:cloudformation:us-west-2:xxx:stack/StackSet-xxx-xxx/xxx",
    "StackDriftDetectionId": "xxx",
    "StackDriftStatus": "IN_SYNC",
    "DetectionStatus": "DETECTION_FAILED",
    "DetectionStatusReason": "{\"Summary\":\"Failed to detect drift on resources [MyLambda]\",\"Failures\":[{\"Resource\":\"MyLambda\",\"FailureReason\":\"Internal Failure\"}]}",
    "DriftedStackResourceCount": 0,
    "Timestamp": "2023-03-13T22:35:40.667Z"
}
```

I could induce this behavior even after stripping my lambda's resource definition down, until it was as simple as

```
"MyLambda": {
  "Type": "AWS::Lambda::Function",
  "Condition": "singleton",
  "Properties": {
    "Code": {
      "ImageUri": "an image Uri in a private ECR repository"
    },
    "PackageType": "Image",
    "Role": "a role arn"
  }
}
```

At this point I started looking in cloud trail.  And there, appearing at the same time as each failed drift detection , I saw records like these:

```
{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "xxx",
        "arn": "my user",
        "accountId": "xxx",
        "accessKeyId": "xxx",
        "userName": "xxx",
        "sessionContext": {
            "sessionIssuer": {},
            "webIdFederationData": {},
            "attributes": { 
                "creationDate": "2023-03-14T01:23:25Z",
                "mfaAuthenticated": "false"
            }     
        },      
        "invokedBy": "cloudformation.amazonaws.com"
    },            
    "eventTime": "2023-03-14T01:23:26Z",
    "eventSource": "lambda.amazonaws.com",
    "eventName": "GetRuntimeManagementConfig",
    "awsRegion": "us-west-2", 
    "sourceIPAddress": "cloudformation.amazonaws.com",
    "userAgent": "cloudformation.amazonaws.com",
    "errorCode": "InvalidParameterValueException",
    "errorMessage": "Lambda couldn't get a runtime management configuration because my-lambda-name is a container image function.",
    "requestParameters": {
        "functionName": "my-lambda-name"
    },
    "responseElements": null,
    "requestID": "xxx",
    "eventID": "xxx",
    "readOnly": true,
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "xxx",
    "eventCategory": "Management"
}
```

### Expected Behavior

I should be able to detect drift on my stack set that contains a container lambda function.

### Observed Behavior

Drift detection fails in regions containing container AWS::Lambda::Function resources.

### Test Cases

To create a minimal example I believe it should be enough to create just a stack with a lambda function that sets `PackageType` to `Image`.  Once the stack is created, detect drift.

**Comment by phs** [comment]
Is anyone able to reproduce or confirm?

To be clear, this is a hard blocker for using drift detection on any stacks with container lambdas.

**Comment by samarthkulk** [comment]
Issue has been fixed successfully

**Comment by phs** [comment]
I can confirm that drift detection operations now themselves complete,thank you.

Issue #1242 however still stops drift detection from working with image-based lambda resources.
