### ISSUE TITLE
Managing Maintenance windows via CloudFormation; AWS::MediaConnect::Flow

### ISSUE THREAD

**Issue by SuryaTeja18** [aws-cloudformation/cloudformation-coverage-roadmap#1560]
### Name of the resource

AWS::MediaConnect::Flow

### Description

MaintenanceWindow property is not available via CloudFormation for the resource type AWS::MediaConnect::Flow. This can hamper customers' ability to easily stand up new video services and customers can make use of this property very effectively as it could greatly help their decision to launch the services.

Ref.: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediaconnect-flow.html

**Comment by ciriolie** [comment]
Hello. The MediaConnect team has launched support for defining maintenance windows through CloudFormation as part of the `AWS::MediaConnect::Flow` resource. More details can be found in the MediaConnect CloudFormation documentation. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mediaconnect-flow.html
