### ISSUE TITLE
AWS::Neptune::DBCluster - In-place upgrade of EngineVersion

### ISSUE THREAD

**Issue by hamilton-earthscope** [aws-cloudformation/cloudformation-coverage-roadmap#1563]
### Name of the resource

AWS::Neptune::DBCluster

## 1. Title
AWS::Neptune::DBCluster - In-place upgrade of EngineVersion

## 2. Scope of request
The ability to do an in-place upgrade of the Neptune engine version via CFN.

## 3. Expected behavior.
This proposal allows you to do an in-place upgrade of `EngineVersion` in the `DBCluster`. Changing `EngineVersion` in `AWS::Neptune::DBCluster` currently requires replacement of Neptune cluster.

We can do an in-place upgrade of `EngineVersion` via the [Modify DBCluster API](https://docs.aws.amazon.com/neptune/latest/apiref/API_ModifyDBCluster.html) from the CLI or console without replacement, but it is not supported by CFN. CFN causes cluster replacement when `EngineVersion` is changed.

## 4. Suggest specific test cases
* a safe upgrading of `EngineVersion` succeeds with no replacement and no data loss
* invalid upgrading such as downgrading `EngineVersion` or incorrect combinations of the parameters will fail

## 5. Helpful Links to speed up research and evaluation
* it appears [this exact same issue was tackled for RDS](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/216)
* [ModifyDBCluster API](https://docs.aws.amazon.com/neptune/latest/apiref/API_ModifyDBCluster.html)
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html

## 6. Category
* DB (Neptune)

**Comment by michaelnchin** [comment]
As of today, Neptune now supports in-place engine version upgrades via the `AWS::Neptune::DBCluster` CloudFormation resource: https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-neptune-cloudformation-serverless/

Please refer to the official Neptune documentation for instructions on usage: https://docs.aws.amazon.com/neptune/latest/userguide/cfn-engine-update.html
