### ISSUE TITLE
Add Route53 Reusable Delegation Set support

### ISSUE THREAD

**Issue by trav-c** [aws-cloudformation/cloudformation-coverage-roadmap#1566]
### Name of the resource

AWS::Route53::HostedZone

### Description

There is currently no way to configure Route53 Hosted Zones with Reusable Delegation Sets.

I would suggest that a new resource type should be created for a Reusable Delegation Set, and the existing HostedZone resource should be extended to accept a DelegationSetId, eg something along the lines of

```
MyDelegationSet:
    Type: AWS::Route53::DelegationSet
    Properties:
        HostedZoneId: (Optional Existing Hosted Zone Id)

MyHostedZone1:
    Type: AWS::Route53::HostedZone
    Properties:
        Name: some.example.com
        DelegationSetId: !Ref MyDelegationSet

MyHostedZone2:
    Type: AWS::Route53::HostedZone
    Properties:
        Name: other.example.com
        DelegationSetId: !Ref MyDelegationSet

```

Where `AWS::Route53::DelegationSet` is a new resource type, and the `DelegationSetId` property of AWS::Route53::HostedZone is a new property for the existing resource.  The `HostedZoneId` of the `AWS::Route53::DelegationSet` resource type would be optional, and allow for using the nameservers of an existing zone (as per the CreateReusableDelegationSet API)

### Other Details

Documentation Links
* [Reusable Delegation Sets](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/route-53-concepts.html#route-53-concepts-reusable-delegation-set)
* [CreateReusableDelegationSet](https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateReusableDelegationSet.html)
* [CreateHostedZone](https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateHostedZone.html)

**Comment by kylekluever** [comment]
Is this actually implemented?  I can't see anything in the docs related to supporting this.  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html

**Comment by saieshwarm** [comment]
There is a duplicate ticket for this issue AWS:: Route53 team will be working on the issue.

**Comment by soer7022** [comment]
> There is a duplicate ticket for this issue AWS:: Route53 team will be working on the issue.

For anyone looking for this, it is #332
