### ISSUE TITLE
[AWS::OpenSearchService::Domain] Drift detected when domain is encrypted with KMS alias

### ISSUE THREAD

**Issue by FrcMoya** [aws-cloudformation/cloudformation-coverage-roadmap#1567]
### Name of the resource

AWS::OpenSearchService::Domain

### Issue Description

According to AWS CloudFormation documentation for OpenSearch Service, we can use either KMS key ID or alias in the template when we want to encrypt the domain with AWS KMS. The problem is that if you use KMS alias, CloudFormation detect a drift because it compares the KMS alias from the template with the KMS ID returned by the background call used by CloudFormation to get the domain info.

### Expected Behavior

No drift detection if we use an KMS alias in the CloudFormation template.

### Observed Behavior

Drift detected if we use an KMS alias in the CloudFormation template.

### Test Cases

Create a OpenSearch domain encrypted using KMS alias. Run a "detect drift" operation.

**Comment by AmanRajAWS** [comment]
hey can you please share the CFN template you used to reproduce the bug

**Comment by FrcMoya** [comment]
You can use an basic OpenSearch domain with this configured in the properties:
EncryptionAtRestOptions:
        Enabled: true
        KmsKeyId: alias/xxxxxxxx

**Comment by FrcMoya** [comment]
Hi again, it seems the bug is already solved in production because I don't see the domain drifted anymore
