### ISSUE TITLE
DatabaseInstance From a Snapshot is ignoring enhanced monitoring and performance insights settings

### ISSUE THREAD

**Issue by scottbisker** [aws-cloudformation/cloudformation-coverage-roadmap#1569]
### Name of the resource

AWS::RDS::DBInstance

### Issue Description

When creating a DatabaseInstance from a Snapshot, enabling performance insights and enhanced monitoring does not work.  By examining CloudTrail for the [RestoreDBInstanceFromDBSnapshot] event, it does not appear that either setting is passed.  The subsequent [ModifyDBInstance] event doesn't change these values either. 
```
Db74F67513": {
   "Type": "AWS::RDS::DBInstance",
   "Properties": {
    "AllocatedStorage": "1000",
    "AutoMinorVersionUpgrade": true,
    "CopyTagsToSnapshot": true,
    "DBInstanceClass": "db.t4g.medium",
    "DBInstanceIdentifier": "db-test",
    "DBSnapshotIdentifier": "arn:aws:rds:us-west-2:<acct>:snapshot:db-snapshot",
    "DBSubnetGroupName": {
     "Ref": "DbSubnetGroup96467FE5"
    },
    "EnableCloudwatchLogsExports": [
     "error",
     "slowquery",
     "audit"
    ],
    "EnablePerformanceInsights": true,
    "Engine": "mysql",
    "EngineVersion": "8.0.32",
    "Iops": 3500,
    "MasterUserPassword": {
     "Fn::Join": [
      "",
      [
       "{{resolve:secretsmanager:",
       {
        "Ref": "StackDbSecret27A88B9D97d2022154130aa861a3bb7feab61e3c"
       },
       ":SecretString:password::}}"
      ]
     ]
    },
    "MaxAllocatedStorage": 2000,
    "MonitoringInterval": 60,
    "MonitoringRoleArn": {
     "Fn::GetAtt": [
      "DbMonitoringRoleAE3F4B7B",
      "Arn"
     ]
    },
    "PerformanceInsightsRetentionPeriod": 7,
    "PubliclyAccessible": false,
    "StorageType": "io1",
    "VPCSecurityGroups": [
     {
      "Fn::GetAtt": [
       "MySQLSecGrp93698302",
       "GroupId"
      ]
     }
    ]
   },
   "UpdateReplacePolicy": "Delete",
   "DeletionPolicy": "Delete",
   "Metadata": {
    "aws:cdk:path": "Stack/Db/Resource"
   }
```

### Expected Behavior

Enhanced monitoring is enabled and Performance Insights is enabled.

### Observed Behavior

Enhanced monitoring is  and Performance Insights are not set correctly

### Test Cases

See template snippet above.  

### Other Details

Originally reported via AWS-CDK, however, it appears the template is correct and CFN is dropping the settings.  
https://github.com/aws/aws-cdk/issues/24726

**Comment by osdrv** [comment]
The issue has been addressed by the PR mentioned above. It is available globally now. Please indicate if any other issues.
