### ISSUE TITLE
URL parameter for AWS::OpenSearchService::Domain::SAMLOptions::IdP::MetadataContent

### ISSUE THREAD

**Issue by lucianpatian** [aws-cloudformation/cloudformation-coverage-roadmap#1575]
### Name of the resource

AWS::OpenSearchService::Domain

### Resource name

AWS::OpenSearchService::Domain::SAMLOptions::IdP::MetadataContent

### Description

Currently the MetadataContent parameter for an IdP is of type string: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opensearchservice-domain-idp.html#cfn-opensearchservice-domain-idp-metadatacontent

This doesn't make it great for using it in a template since the XML files have several lines of strings and the template gets too long, not to mention formatting.

Please add the possibility to add as parameter an URL for the XML so the metadata gets fetched automatically from the external IdP since this is public data.

As an example check the Terraform option: 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/opensearch_domain_saml_options#metadata_content

**Comment by prabhat-chaturvedi** [comment]
This will take some time to bring this capability to accept from a URL, that has some implications to accept from any URL and has to be trusted, validated what is downloaded and currently not prioritized.
This is not a blocker currently, we will revisit this sooner.
