### ISSUE TITLE
Drift Detection false positive for KmsKeyId property under AWS::RDS::DBCluster resource

### ISSUE THREAD

**Issue by satanupa** [aws-cloudformation/cloudformation-coverage-roadmap#1583]
### Name of the resource

AWS::RDS::DBCluster

### Issue Description

Drift Detection throws a false positive for KmsKeyId property when alias is specified. 
No changes are made out of band. 

Example:

Expected:
{
  "StorageEncrypted": true,
  "EngineVersion": "12.13",
  "KmsKeyId": "arn:aws:kms:region:account-no:alias/example-alias",
  "DBClusterIdentifier": "rdskmsdrift",
  "MasterUsername": "testuser",
  "EnableIAMDatabaseAuthentication": true,
  "Engine": "aurora-postgresql",
  "EnableCloudwatchLogsExports": [
    "postgresql"
  ]
}

Actual:
{
  "StorageEncrypted": true,
  "EngineVersion": "12.13",
  "KmsKeyId": "arn:aws:kms:region:account-no:key/key-id",
  "DBClusterIdentifier": "rdskmsdrift",
  "MasterUsername": "testuser",
  "EnableIAMDatabaseAuthentication": true,
  "Engine": "aurora-postgresql",
  "EnableCloudwatchLogsExports": [
    "postgresql"
  ]
}

### Expected Behavior

The resource should not show drifted for KmsKeyId when a kms key alias is specified.

### Observed Behavior

When a resource of type AWS::RDS::DBCluster is created with KmsKeyId as alias or alias arn. The actual resource is created as expected and the stack goes to CREATE_COMPLETE. On performing Drift detection, the resource shows drifted for the KmsKeyId since the expected value shows kms key alias/arn and the actual value gives the full KmsKey Arn.

### Test Cases

Create a Cloudformation stack to provision a DBCluster resource.

Resources:
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Sub ${AWS::StackName}
      Engine: aurora-postgresql
      EngineVersion: '12.13'
      MasterUsername: testuser
      MasterUserPassword: xxxxxxxxx
      StorageEncrypted: true
      KmsKeyId: 'arn:aws:kms:region:account-no:alias/example-alias'

Once the stack goes to CREATE_COMPLETE, perform detect drift and view drift details.

**Comment by osdrv** [comment]
The issue is related to https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1307. The root cause is the same.

**Comment by khebul** [comment]
Let's track this issue under #1307
