### ISSUE TITLE
Missing Server SDK Version in AWS::GameLift::Build

### ISSUE THREAD

**Issue by sv-eden** [aws-cloudformation/cloudformation-coverage-roadmap#1586]
### Name of the resource

AWS::GameLift::Build

### Description

The AWS::GameLift::Build resource is missing an attribute to specify the Server SDK version (ServerSDKVersion in the reference API).

The GameLift Server SDK 5.0.0 requires this attribute to be set on builds, so that required environment variables are set on GameLift-managed EC2 instances. Without it, the deployed builds are set to SDK version 4.0.2 by default, and the builds using the SDK 5.0.0 fail to connect to GameLift due to those missing environment variables, among which the Websocket connection URL, and the fleets created with those builds fail to stabilize - making it impossible to create builds using the 5.0.0 SDK via CloudFormation.

**Comment by xmiao2** [comment]
Hello! `ServerSdkVersion` is now available in CloudFormation's AWS::GameLift::Build resource: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-gamelift-build.html#cfn-gamelift-build-serversdkversion
