### ISSUE TITLE
MSK Kafka connector cannot redeploy after configuration change

### ISSUE THREAD

**Issue by TLadd** [aws-cloudformation/cloudformation-coverage-roadmap#1592]
### Name of the resource

Other

### Resource Name

AWS::KafkaConnect::Connector

### Issue Description

I'm using CDK's L1 construct for as MSK Kafka Connector. I was able to create a new connector just fine.  However, when I tested making a change to the configuration for that connector and deploying again, I got the error 

```
Resource of type 'AWS::KafkaConnect::Connector' with identifier '<connector-name>' already exists.
```

The change policy on the configuration property is "Replacement", which states `AWS CloudFormation usually creates the replacement resource first, changes references from other dependent resources to point to the replacement resource, and then deletes the old resource`.

In this case, that behavior means it's not possible to actually update a connector via cdk/cloudformation. In the console, in order to make a configuration update, I have to delete the connector first and then recreate it once it has been removed.

Ideally, MSK Connect would add support for updating a connector's configuration. But until that happens, it seems like cloudformation ought to delete the existing connector before trying to add the new one with the updated configuration.

### Expected Behavior

Allow making configuration updates via cloudformation by first deleting the existing connector and then creating the new one

### Observed Behavior

Cloudformation attempts to add the new connector and it fails because the existing one is still around with the same connector name.

### Test Cases

- Create an MSK Connector using cloudformation
- Make a change to the configuration field
- Re-deploy and observe it fails

**Comment by kmampent** [comment]
Hello,

The following pull request should address this issue, https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-kafkaconnect/pull/12. It has now been approved and merged. Thank you for notifying us about this issue.
