### ISSUE TITLE
Can't update glue schema with definition json update

### ISSUE THREAD

**Issue by pahud** [aws-cloudformation/cloudformation-coverage-roadmap#1598]
### Name of the resource

AWS::Glue::Schema

### Issue Description

When updating the schemaDefinition, CFN returns schema already exists error.

see https://github.com/aws/aws-cdk/issues/25129#issuecomment-1511418846 for more details.

### Expected Behavior

the schema update should succeed with no error

### Observed Behavior

<img width="909" alt="image" src="https://user-images.githubusercontent.com/278432/232509101-1b44bfc5-7979-4bbe-9848-1b8714383345.png">

### Test Cases

Use this schema for initial deployment

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://random.com/users.json#",
    "title": "users",
    "type": "object",
    "properties": {
      "id": {"type": "string", "format": "uuid"},
    }
  }
```

And this for update:

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://random.com/users.json#",
    "title": "users",
    "type": "object",
    "properties": {
      "id": {"type": "string", "format": "uuid"},
      "payload": {"type": "object"},
      "name": {"type": "string"}
    }
  }
```

**Comment by blacktooth** [comment]
In order to add a new schema version, you need to use `AWS:Glue:SchemaVersion`. The schema definition used in `AWS:Glue:Schema` is the initial schema version and cannot be updated as schema versions are immutable.
