### ISSUE TITLE
AWS::ECR::Repository import into existing stack

### ISSUE THREAD

**Issue by ollilainen** [aws-cloudformation/cloudformation-coverage-roadmap#1607]
### Name of the resource

AWS::ECR::Repository

### Issue Description

When importing resources into same stack in two separate import runs, cloudformation asks again to identify resources that has been imported on previous run.

On second import to same stack this causes error that resource already exists.

_There was an error creating this change set
Resources [LogicalID] passed in ResourceToImport are already in a stack and cannot be imported._

Unable to import additional ecr repositories to same stack

### Expected Behavior

Would only ask to identify resources that are not present on stack

### Observed Behavior

Asks to identify all previously imported resources as well, causes error on later step.

### Test Cases

1. Import one ecr repo to stack  - works ok
2. Try to import another ecr repo to same stack - error

**Comment by michaelb990** [comment]
Hi @ollilainen - can you provide the template you're using and any other logs / output you're getting? 

I just tried to do this in my own account with 2 ECR repositories in 2 separate import runs and it seemed to work fine.

**Comment by ollilainen** [comment]
eu-north-1
1.  Create ECR repos test1 test2
2. Create new CF stack with first resource only AWS::CodeCommit::Repository
3. Enable second resource on template and import first ECR repo test1
4. Enable third resource on template and try to import second ECR to same stack

Template yaml [test.txt](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/files/11664133/test.txt)

2nd import round from GUI
![pic1](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/131850551/e0534c3e-de8a-4790-a475-f0adab35dd00)
![pic2](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/131850551/a03fd979-1c8c-4829-bd8c-b94d24140e11)

**Comment by tylerread** [comment]
Hi @ollilainen, I looked into this a bit, and I was able to reproduce your issue with the CloudFormation template you provided. I found that refreshing the browser window in between importing Repo1 and Repo2 fixed the issue for me.

Can you try a browser refresh and see if that helps?

**Comment by yanmjy** [comment]
Hi @ollilainen , here is a fix shipped in CloudFormation console end which deployed to region FRA, PDX, BJS, IAD, SIN, NRT. So if your CFN stack is in those regions, you should not meet this issue now. The remaining regions would be deployed soon(within 1-2 weeks). We will close the issue once the deployment fully complete.

Thanks!

**Comment by yanmjy** [comment]
Deployment reached to eu-north-1 now, you are supposed to not meet this issue again. Resolved the issue.
