### ISSUE TITLE
EC2 Snapshot/AMI Recycle Bin (rbin) support

### ISSUE THREAD

**Issue by takeda** [aws-cloudformation/cloudformation-coverage-roadmap#1638]
### Name of the resource

Other

### Resource name

AWS::RBin

### Description

n over year ago a recycle bin feature was added that delays deletion of AMI and Snapshots. That feature does not appear to have CloudFormation support and it is something that preferably should be configured as IaC.

### Other Details

https://aws.amazon.com/blogs/aws/new-recycle-bin-for-ebs-snapshots/

**Comment by marcuram** [comment]
Duplicate with: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1089
