### ISSUE TITLE
AWS::XRay::SamplingRule support for the GovCloud regions

### ISSUE THREAD

**Issue by morries4321** [aws-cloudformation/cloudformation-coverage-roadmap#1664]
### Name of the resource

Other

### Resource name

AWS::XRay::SamplingRule

### Description

Requesting to add resource type AWS::XRay::SamplingRule support for the GovCloud regions. As per [1], they are currently not supported in the GovCloud regions.

[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html

**Comment by xaoyuli** [comment]
AWS::XRay::SamplingRule supported in gov region now
