### ISSUE TITLE
(AWS::SSM::Parameter) Implement `Drift Detection`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/cloudformation-coverage-roadmap#1674]
### Name of the resource

AWS::SSM::Parameter

### Description

Currently `AWS::SSM::Parameter` does not support `Drift Detection`. Implementing this would be great.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

**Comment by r-heimann** [comment]
AWS::SSM::Parameter now supports drift detection.

**Comment by rgoltz** [comment]
Attaching a reference to the following problem for Drift Detection of AWS::SSM::Parameter: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1890
