### ISSUE TITLE
AWS::MSK::Cluster Resource import fails if encryptionInfo property is set

### ISSUE THREAD

**Issue by cmogeni** [aws-cloudformation/cloudformation-coverage-roadmap#1688]
### Name of the resource

AWS::MSK::Cluster

### Issue Description

When importing an AWS::MSK::Cluster, specifying encryption options fails with the message:

`Resource handler returned message: "  Updating encryption-at-rest settings on your cluster is not currently supported. (Service: Kafka, Status Code: 400, Request ID: XX , Extended Request ID: null) 'encryptionInfo'" (, HandlerErrorCode: InvalidRequest)`

### Expected Behavior

AWS::MSK::Cluster resource import should not trigger an update to security settings during the import process, CloudFormation should assume that the resource has not changed and not trigger an update

### Observed Behavior

The MSK cluster import fails because it always tries to update the encryption at rest settings, even if they are the same as the imported cluster

### Test Cases

- Create a stack with an AWS msk cluster
- Add retain deletion policy to the MSK Cluster
- Delete the stack
- Attempt to import cluster into a new stack with the same template

**Comment by jantosz** [comment]
This issue has now been fixed.
