### ISSUE TITLE
Encountered unsupported property FilterCriteria

### ISSUE THREAD

**Issue by serkan-at-napoleon** [aws-cloudformation/cloudformation-coverage-roadmap#1694]
### Name of the resource

AWS::Lambda::EventSourceMapping

### Issue Description

I have a AWS::Serverless::Function with Events configured to get triggered by a Kinesis Event.
This creates underneath a AWS::Lambda::Function, and AWS::Lambda::EventSourceMapping.

When configured a FilterCriteria, I get the error that this property isn't supported.

Here's an example of my configuration:
`      Events:
        KinesisEvent:
          Type: Kinesis
          Properties:
            Stream: !Sub "arn:${AWS::Partition}:kinesis:${AWS::Region}:${AWS::AccountId}:stream/ingress-stream"
            StartingPosition: LATEST
            BatchSize: 50
            FilterCriteria:
              Filters:
                - Pattern: '{ "data": { "name": ["OrderPlaced"], "payload": { "provider": ["mastercard"] } } }'
`

### Expected Behavior

I expect this Lambda being created with the configured Trigger, this worked a week ago, without any code changes.

### Observed Behavior

/

### Test Cases

/

### Other Details

SAM version 1.84.0

**Comment by dineshmc2** [comment]
can you confirm if you are still experiencing this issue? 

If yes, can you please provide additional informations such as region, if possible SAM template that you are using to reproduce this issue.

**Comment by bennyfink** [comment]
Hi @serkan-at-napoleon, Lambda team member here. Here is the template we tested with using `SAM CLI, version 1.90.0`. We were unable to reproduce the issue described. Please provide additional information so we can further look into this issue.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template FilterCriteria Testing
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: ['sts:AssumeRole']
            Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
        Version: '2012-10-17'
      Policies:
        - PolicyName: allow-all-Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "*"
                Resource:
                  - "*"
  TestStream:
    Type: AWS::Kinesis::Stream
    Properties: 
      Name: TestStream
      RetentionPeriodHours: 1
      ShardCount: 1

  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.9
      Timeout: 120
      Role:
        Fn::GetAtt: [LambdaRole, Arn]

      InlineCode: |
        def handler(event, context):
          print("Hello, world!")
      Events:
        Kinesis:
          Type: Kinesis
          Properties:
            Stream: Fn::GetAtt: [TestStream, Arn]
            BatchSize: 1
            FilterCriteria:
              Filters:
                - Pattern: "{\"body\" : {\"a\": [1, 2]}}"
```

**Comment by TheDanBlanco** [comment]
if this was closed and the issue continues to persist, feel free to re-open with more information
