### ISSUE TITLE
Lambda Python3.10 runtime support in CloudFormation

### ISSUE THREAD

**Issue by guipaivanz** [aws-cloudformation/cloudformation-coverage-roadmap#1697]
### Name of the resource

AWS::Lambda::Function

### Description

Lambda now supports Python3.10 runtime, but CloudFormation does not offer support for it yet.
As per AWS Documentation, only the following are supported:

Allowed values: dotnet6 | dotnetcore1.0 | dotnetcore2.0 | dotnetcore2.1 | dotnetcore3.1 | go1.x | java11 | java17 | java8 | java8.al2 | nodejs | nodejs10.x | nodejs12.x | nodejs14.x | nodejs16.x | nodejs18.x | nodejs4.3 | nodejs4.3-edge | nodejs6.10 | nodejs8.10 | provided | provided.al2 | python2.7 | python3.10 | python3.6 | python3.7 | python3.8 | python3.9 | ruby2.5 | ruby2.7

**Comment by r-heimann** [comment]
In your `Allowed Values` List it is supported: python3.10

**Comment by guipaivanz** [comment]
thanks @r-heimann for pointing that out. I completely missed it
