### ISSUE TITLE
Support for Import of AWS::SQS::QueuePolicy Resource

### ISSUE THREAD

**Issue by issamsdr** [aws-cloudformation/cloudformation-coverage-roadmap#1700]
### Name of the resource

Other

### Resource name

AWS::SQS::QueuePolicy

### Description

Hello team,

Requesting to add resource type AWS::SQS::QueuePolicy to support import operation.

Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

**Comment by cherylrc** [comment]
AWS::SQS::QueuePolicy will not support import operation.  Customers are suggested to switch to new resource type [AWS::SQS::QueueInlinePolicy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queueinlinepolicy.html) which will support import feature.
