### ISSUE TITLE
AWS::AppSync::GraphQLApi

### ISSUE THREAD

**Issue by daknhh** [aws-cloudformation/cloudformation-coverage-roadmap#1702]
### Name of the resource

AWS::FMS::Policy

### Resource name

AWS::FMS::Policy

### Description

You can enable AWS WAF protections for Amazon GRaphQL. 
Please add support for "AWS::AppSync::GraphQLApi" Type in FMS Policy thanks :)

**Comment by andrewinblue** [comment]
AWS Firewall Manager currently doesn't support WAF for Cognito and AppySnc feature, and we do not have a roadmap item for it in 2023 due to low demand. Please continue add your influence to help us prioritize it against other high demand features.

**Comment by daknhh** [comment]
Any update on this?
