### ISSUE TITLE
Implement support for CloudWatch Log and logging directly to S3 bucket 

### ISSUE THREAD

**Issue by daknhh** [aws-cloudformation/cloudformation-coverage-roadmap#1703]
### Name of the resource

AWS::FMS::Policy

### Resource name

AWS::FMS::Policy

### Description

Waiting for the new feature for s3 logging, because s3 logging just launched few weeks ago: https://aws.amazon.com/about-aws/whats-new/2023/04/aws-firewall-manager-waf-features/

**Comment by daoqihou** [comment]
This is not a CloudFormation parity issue, our service does not support this feature at all right now.

**Comment by andrewinblue** [comment]
AWS Firewall Manager service already support logging directly to S3 bucket for WAF and Network Firewall. We currently have no plan to support CloudWatch Log in 2023.
