### ISSUE TITLE
Unable to update a stackset if the stackset has its stack instances deleted

### ISSUE THREAD

**Issue by shadycuz** [aws-cloudformation/cloudformation-coverage-roadmap#1708]
### Name of the resource

Other

### Resource Name

A stackset I created manually

### Issue Description

Unable to update a stackset manually from the AWS Console

The "region" is unselectable, I'm unable to select a region for the stackset.

Clicking "next" results in this error:

`At least one region must be added to the deployment order.`

This is a bug, ran into it about a year ago.

### Expected Behavior

I should be able to update my stackset and deploy it like normal.

### Observed Behavior

You are unable to update your stackset from the aws console. I can do it manually from the AWS CLI.

### Test Cases

Create a stackset with at least one instance.
You delete all instances in that stackset.
Try to "edit stackset details", upload a new cloudformation template (optional)
when you get to the "Specify regions" section, you will not be able to select any, you will not be able to continue.

**Comment by aradven** [comment]
I am unable to recreate this issue with the steps provided. Would you be able to confirm if this is still an issue, and re-open this ticket if so?

**Comment by shadycuz** [comment]
@aradven I will attempt it again. Note that this only happens in the AWS console. It works fine from the CLI.
