### ISSUE TITLE
exclusionByResourceTypes Support for Config Recorder

### ISSUE THREAD

**Issue by avatarworf** [aws-cloudformation/cloudformation-coverage-roadmap#1710]
### Name of the resource

AWS::Config::ConfigurationRecorder

### Description

Per a [recent announcement](https://aws.amazon.com/about-aws/whats-new/2023/06/aws-config-recording-exclusions-resource-type/), an `exclusionByResourceTypes` property is available via Console/[AWS CLI](https://docs.aws.amazon.com/config/latest/APIReference/API_RecordingGroup.html#config-Type-RecordingGroup-exclusionByResourceTypes) to setup the AWS Config recorder to ignore specific types.

Looking for this extension to Cloudformation.

**Comment by cgspohn** [comment]
Not that this is helpful for teams already using CloudFormation, but the terraform aws provider already released support for this feature in version 5.5.0 per [changelog](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#550-june-23-2023) on June 23, 2023.

**Comment by fyuan12** [comment]
You can now find the CloudFormation documentation for the `ExclusionByResourceTypes` property and `RecordingStrategy` property [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-config-configurationrecorder-recordinggroup.html).
