### ISSUE TITLE
Add support for Amazon Verified Permissions

### ISSUE THREAD

**Issue by dguisinger** [aws-cloudformation/cloudformation-coverage-roadmap#1719]
### Name of the resource

Other

### Resource name

AWS::VerifiedPermissions

### Description

There is currently no support for Amazon Verified Permissions in CloudFormation.

I would like to be able to create policy stores, schemas, policies and policy templates via CloudFormation.

**Comment by rubenrangel** [comment]
AVP support looks to be live now. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_VerifiedPermissions.html

**Comment by dguisinger** [comment]
> AVP support looks to be live now. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_VerifiedPermissions.html

It does indeed!

**Comment by r-heimann** [comment]
@dguisinger Kindly close this issue if its supported.
