### ISSUE TITLE
DocumentDB Elastic

### ISSUE THREAD

**Issue by autarchprinceps** [aws-cloudformation/cloudformation-coverage-roadmap#1729]
### Name of the resource

AWS::DocDB::DBCluster

### Description

Unless I'm not finding it, I don't think DocumentDB Elastic Clusters are supported by CloudFormation yet.

**Comment by grcyl** [comment]
Thanks for raising the issue. 

DocumentDB Elastic Cluster is supported by Cloudformation. Please refer to the documentation here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdbelastic-cluster.html
