### ISSUE TITLE
AWS::OpenSearchService::Domain ClusterConfig ColdStorageOptions missing

### ISSUE THREAD

**Issue by zBart** [aws-cloudformation/cloudformation-coverage-roadmap#1732]
### Name of the resource

AWS::OpenSearchService::Domain

### Description

The new `AWS::OpenSearchService::Domain` resource does not have support for configuring / enabling cold storage: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opensearchservice-domain-clusterconfig.html

The old `AWS::Elasticsearch::Domain` resource does support it, but it is marked as legacy: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-coldstorageoptions.html

The OpenSearch API lists the `ColdStorageOptions` under the `ClusterConfig` as an option so the support does exist: https://docs.aws.amazon.com/opensearch-service/latest/APIReference/API_UpdateDomainConfig.html

Please add support for configuring `ClusterConfig.ColdStorageOptions` to the `AWS::OpenSearchService::Domain` resource

**Comment by Aman199825** [comment]
this feature is available now https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opensearchservice-domain-coldstorageoptions.html
