### ISSUE TITLE
AWS::WAFv2::WebACL: Support other AggregateKeyType in RateBasedStatement

### ISSUE THREAD

**Issue by skywalker-nick** [aws-cloudformation/cloudformation-coverage-roadmap#1736]
### Name of the resource

AWS::WAFv2::WebACL

### Description

We deployed WAFv2 in our business websites via CloudFormation, however, due to the lack of AggregateKeyType, we manually configured RateBasedStatement in the WAFv2 deployments.

The current CloudFormation supports "IP" and "FORWARDED_IP", however, we use "CONSTANT" and "CUSTOM_KEYS" in different deployments.

**Comment by xavi-bean** [comment]
In the same situation here. This is causing inconsistencies in our infrastructure. Any estimated time for this to be fixed?

**Comment by nikita-sokolsky-amazon** [comment]
@xavi-bean @skywalker-nick Thank you for opening this ticket. This feature is now supported within Cloudformation. I will provide an additional update once the `aws-cdk` package has been synchronized with Cloudformation as well.

**Comment by nuttmeister** [comment]
Only `CUSTOM_KEYS` was shipped. Trying to deploy a working rule with `CONSTANT` will produce a validation error in CF. Even something that is known to work via API / Console and/or using the examples in the CF docs will produce a validation error.
