### ISSUE TITLE
add AWS::EC2::InstanceConnectEndpoint

### ISSUE THREAD

**Issue by lart2150** [aws-cloudformation/cloudformation-coverage-roadmap#1749]
### Name of the resource

Other

### Resource name

AWS::EC2::InstanceConnectEndpoint

### Description

The recently added instance connect endpoint is very useful for connecting to restricted services in a vpc replacing the need for a bastion host.  It would be helpful to be able to create instance connect endpoints using cloudformation without using a custom resource.  This is also a blocker for adding support for instance connect endpoints to CDK https://github.com/aws/aws-cdk/issues/26226

**Comment by awsdataarchitect** [comment]
Is there ETA for supporting InstanceConnectEndpoint resource in CFN

**Comment by drzal** [comment]
Cloudformation support for InstanceConnectEndpoint is now live.
