### ISSUE TITLE
AWS::RDS::DBInstance - StorageType defaults to magnetic

### ISSUE THREAD

**Issue by kgregory-chariot** [aws-cloudformation/cloudformation-coverage-roadmap#177]
## 2. Scope of request 

This attribute is [documented](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-storagetype) as defaulting to `io1` or `gp2`. However, if you omit it from a resource specification, the actual database is created with magnetic storage.

## 3. Expected behavior

If I don't specify, I expect to get `gp2` SSD.

## 4. Suggest specific test cases

Use attached CloudFormation template, which has `StorageType` commented-out. Verify storage type using Console or CLI.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

3. DB (RDS, DynamoDB...)

[rds_sans_storage_type.yml.txt](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/files/3617011/rds_sans_storage_type.yml.txt)
![Screenshot_2019-09-16_11-33-52](https://user-images.githubusercontent.com/51966316/64971841-4791f880-d876-11e9-8aae-ec45a1e27321.png)

**Comment by kkolk** [comment]
Ran into this exact same issue and now I have a bunch of instances to fix as a result.
