### ISSUE TITLE
AWS::Transfer::Server - Start and Stop Server

### ISSUE THREAD

**Issue by Rizxcviii** [aws-cloudformation/cloudformation-coverage-roadmap#1779]
### Name of the resource

AWS::Transfer::Server

### Description

A feature available in transfer family and is available through the AWS SDK is to [stop](https://docs.aws.amazon.com/transfer/latest/userguide/API_StopServer.html) and [start](https://docs.aws.amazon.com/transfer/latest/userguide/API_StartServer.html) transfer family servers when required. This is not currently supported by Cloudformation, but would be nice to include, to allow stopping servers when not in use.
Potentially, an `Online` field could be added (as the AWS Console states "Online" or "Offline") which could call these SDK procedures, or something similar.

### Other Details

I've also made a request [here](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-transfer/issues/46) but it seems as though this is the right place to make this issue.

**Comment by Rizxcviii** [comment]
Hi, I currently have a need where there is a need to prevent incoming requests from our clients, for various reasons. Therefore, we would like to temporarily stop the server for a long period of time (days/weeks at a time). Of course we could remove the server entirely, but then we would have to go about adding the users back into the server once again.

**Comment by jud-waite** [comment]
Hello, after discussing this feature request with the team we have determine that it would not be feasible to implement start/stop server in CFN. It is a transient state that would easily lend itself to CFN drift which would be difficult for customers to repair. We recommend using a firewall to deny incoming requests and block specific of IP addresses, please find some relevant resources below: 

- [Add a web application firewall](https://docs.aws.amazon.com/transfer/latest/userguide/web-application-firewall.html)
- [Securing AWS Transfer Family with AWS Web Application Firewall and Amazon API Gateway](https://aws.amazon.com/blogs/storage/securing-aws-transfer-family-with-aws-web-application-firewall-and-amazon-api-gateway/)
- [Securing your AWS Transfer Family SFTP and FTPS VPC public endpoints](https://aws.amazon.com/blogs/storage/secure-your-aws-transfer-family-sftp-and-ftps-vpc-public-endpoints/)
