### ISSUE TITLE
DMS "endpoint settings" vs "extra connection attributes": An issue with coverage, documentation, or both?

### ISSUE THREAD

**Issue by rhbecker** [aws-cloudformation/cloudformation-coverage-roadmap#1781]
### Name of the resource

AWS::DMS::Endpoint

### Description

In preparation for an ongoing replication project (SQL Server on RDS to SQL Server on EC2), I'm reviewing the following documentation:

1. (DMS user guide) [Using a Microsoft SQL Server database as a source for AWS DMS](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.SQLServer.html)
2. (DMS user guide) [Using a Microsoft SQL Server database as a target for AWS Database Migration Service](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.SQLServer.html)
3. (CFN user guide) [AWS::DMS::Endpoint](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html) - particularly the `ExtraConnectionAttributes` property
4. (CFN user guide) [AWS::DMS::Endpoint MicrosoftSqlServerSettings](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dms-endpoint-microsoftsqlserversettings.html)

The first 2 links, from the DMS User Guide, refer to some settings as "Endpoint settings" and others as "extra connection attributes". Likewise, the `AWS::DMS::Endpoint` resource includes both a `MicrosoftSqlServerSettings` property (presumably corresponding to "Endpoint settings" and an `ExtraConnectionAttributes` property (clearly corresponding to "extra connection attributes").

So far, so good! But when I start digging into the details of particular settings and attributes, things get confusing ...

* At [link #1](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.SQLServer.html), several configs are listed both in a table inventorying ["Endpoint settings"](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.SQLServer.html#CHAP_Source.SQLServer.ConnectionAttrib) and in a table inventorying ["extra connection attributes"](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.SQLServer.html#CHAP_Source.SQLServer.AlwaysOn.Secondary), making it unclear which CFN resource property should be used to specify them. None of these are referenced in CFN docs (i.e. [link #3](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html) and [link #4](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dms-endpoint-microsoftsqlserversettings.html)). Does this mean they aren't yet covered by CFN?
  * `ActivateSafeguard`
  * `AlwaysOnSharedSynchedBackupIsEnabled`
  * `ApplicationIntent`
  * `MultiSubnetFailover`
  * `SetUpMsCdcForTables`
* Several other configs listed in tables inventorying "Endpoint settings" (both at [link #1](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.SQLServer.html) and [link #2](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.SQLServer.html)) are referred to as "extra connection attributes" in bulleted lists of limitations on the same respective pages. In these cases, the configs are referenced at [link #4](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dms-endpoint-microsoftsqlserversettings.html) - seemingly validating that they are more likely "Endpoint settings" than "extra connection attributes" ...
  * `UseBcpFullLoad` (target)
  * `ReadBackupOnly` (source)
  * `Use3rdPartyBackupDevice` (source)
* Speaking of `Use3rdPartyBackupDevice` (source), [link #4](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dms-endpoint-microsoftsqlserversettings.html) indicates it was implemented in CFN with a variation on the name (`UseThirdPartyBackupDevice`). That seems like either a needless trap, or a documentation error on one side or the other.
* Several configs are listed only as "Endpoint settings" at [link #1](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.SQLServer.html), but aren't mentioned in [link #4](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dms-endpoint-microsoftsqlserversettings.html). Does this mean they aren't yet covered by CFN?
  * `EnableNonSysadminWrapper`
  * `FatalOnSimpleModel`
  * `ForceLobLookup`
  * `TlogAccessMode`
* A handful of configs are mentioned in [link #4](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dms-endpoint-microsoftsqlserversettings.html), but at neither [link #1](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.SQLServer.html) nor [link #2](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.SQLServer.html). Does that mean they've been deprecated? Probably not, in the case of the latter two, but I'm less clear on the former two. If they remain supported, it would be nice to mention them _somewhere_ in the DMS User Guide ...
  * `BcpPacketSize`
  * `QuerySingleAlwaysOnNode`
  * `SecretsManagerAccessRoleArn`
  * `SecretsManagerSecretId`
* On the bright side, I did find 2 config values where the docs all seem aligned. In both cases, they are only ever referred to as "Endpoint Settings" by [link #1](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.SQLServer.html) and [link #2](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Target.SQLServer.html), and they are listed at [link #4](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dms-endpoint-microsoftsqlserversettings.html) ...
  * `SafeguardPolicy` (source)
  * `ControlTablesFileGroup` (target)

**Comment by chevyye** [comment]
Hi, @rhbecker. You can follow the endpoint settings [here](https://docs.aws.amazon.com/dms/latest/APIReference/API_CreateEndpoint.html#API_CreateEndpoint_RequestSyntax) to create a MSSQL endpoint using CFN. All the endpoint settings here are up-to-date and you should be able to include them in your CFN template (under MicrosoftSqlServerSettings). 

Regarding your confusion on the difference between "endpoint settings" and "extra connection attributes", using all the attributes mentioned in [this]([Using a Microsoft SQL Server database as a source for AWS DMS](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.SQLServer.html)) document as an endpoint settings would be the right move. 

Please let us know if you have further question. Thank you.
