### ISSUE TITLE
Support "languageCode" for AWS::Kendra::DataSource and AWS::Kendra::Faq

### ISSUE THREAD

**Issue by lokemoon** [aws-cloudformation/cloudformation-coverage-roadmap#1787]
### Name of the resource

AWS::Kendra::DataSource

### Description

The field "languageCode" is not supported in AWS::Kendra::DataSource and AWS::Kendra::Faq

Refer the API below for availabilities
https://docs.aws.amazon.com/kendra/latest/APIReference/API_CreateFaq.html
https://docs.aws.amazon.com/kendra/latest/APIReference/API_CreateDataSource.html

### Other Details

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kendra-faq.html 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kendra-datasource.html

**Comment by jregistr** [comment]
Here are the PRs to address this:
- https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-kendra/pull/106
- https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-kendra/pull/109

Once these have finished deployment, I'll follow up on this issue.

**Comment by jregistr** [comment]
See DataSource: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kendra-datasource.html
and FAQ: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kendra-faq.html

Both now include `LanguageCode`.
