### ISSUE TITLE
"Runtime" property of Globals doesn’t resolve Dynamic References 

### ISSUE THREAD

**Issue by SuryaTeja18** [aws-cloudformation/cloudformation-coverage-roadmap#1794]
### Name of the resource

Other

### Resource Name

Globals section of SAM Template

### Issue Description

Hello team,

The Globals section of the SAM template, which has the property 'Runtime' is only accepting the string given as is but not resolving the dynamic references. This is not allowing us to implement our use case of referencing runtime (and other properties) from SSM store.

Error facing during SAM deploy:
```
Error: resolve:ssm:Lambdaruntime runtime is not supported
```

Other properties in Globals like timeout, handler, etc seem to support and resolve the ssm parameter as expected.

### Expected Behavior

SSM Parameter to be resolved correctly to the value stored in the parameter.

### Observed Behavior

Error facing during SAM deploy:
```
Error: resolve:ssm:Lambdaruntime runtime is not supported
```

### Test Cases

SAM build fails and throws the error message when tried to deploy such a SAM template

**Comment by TheDanBlanco** [comment]
@SuryaTeja18 `Globals` is not supported by cloudformation. please re-open this under the [SAM](https://github.com/aws/serverless-application-model) github repository. thanks!
