### ISSUE TITLE
AWS::EC2::TransitGateway - DefaultRouteTableId return value

### ISSUE THREAD

**Issue by x6j8x** [aws-cloudformation/cloudformation-coverage-roadmap#180]
## 2. Scope of request
When creating a TransitGateway with `DefaultRouteTablePropagation: true` and `DefaultRouteTableAssociation: false` there's currently no way to selectively associate TransitGatewayAttachments with the default route table in a Cloudformation template. 

## 3. Expected behavior

There a new `Fn::GetAtt`able attribute that returns the DefaultRouteTableId (or an empty string if `DefaultRouteTablePropagation: false`).

```
{ "Fn::GetAtt" : [ "TransitGateway", "DefaultRouteTableId" ] }
```

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. Compute (EC2, ECS, EKS, Lambda...)

## 7. Any additional context (optional)

**Comment by vedasreeb29** [comment]
The Route Table is created asynchronously after a Transit Gateway is created. Hence, it is not possible to return the DefaultRouteTableId as a return value when AWS::EC2::TransitGateway is created.
