### ISSUE TITLE
Creation of AWS::ECS::Service with multiple LoadBalancers fails validation

### ISSUE THREAD

**Issue by sfussenegger** [aws-cloudformation/cloudformation-coverage-roadmap#1804]
### Name of the resource

AWS::ECS::Service

### Issue Description

Creating a `AWS::ECS::Service` with more than 1 `LoadBalancers` configs and a `Role` fails validation:

```
Resource handler returned message: "Invalid request provided: CreateService error: You cannot specify an IAM role for services that require a service linked role. (Service: AmazonECS; Status Code: 400; Error Code: InvalidParameterException; Request ID: 0e91c90c-0a97-4ee0-a90f-16697195accb; Proxy: null)" (RequestToken: da7667e2-f6da-b722-cb3b-96f9f0cf5b31, HandlerErrorCode: InvalidRequest)
```

I've removed the extra `LoadBalancers` for creation of the resource and then updated with multiple `LoadBalancers` as a workaround.

### Expected Behavior

Creation should work with multiple `LoadBalancers` entries

### Observed Behavior

Only works for updates, not on creation.

### Test Cases

Sample `AWS::ECS::Service`:

```json
"Service": {
	"Type": "AWS::ECS::Service",
	"DependsOn": [ "ListenerRuleOne", "ListenerRuleTwo" ],
	"Properties": {
		"Cluster": { "Fn::ImportValue": "TestCluster" },
		"Role": { "Fn::ImportValue": "TestRole" },
		"TaskDefinition": { "Ref": "TaskDefinition" },
		"DesiredCount": 1,
		"HealthCheckGracePeriodSeconds": 120,
		"DeploymentConfiguration": {
			"MinimumHealthyPercent": 100,
			"MaximumPercent": 200
		},
		"LoadBalancers": [
			{
				"ContainerName": "service",
				"ContainerPort": 8080,
				"TargetGroupArn": { "Ref": "TargetGroupOne" }
			},
			{
				"ContainerName": "service",
				"ContainerPort": 8081,
				"TargetGroupArn": { "Ref": "TargetGroupTwo" }
			}
		]
	}
}
```

**Comment by genbit** [comment]
You can create ECS service with multiple load balancers when you are using a service-linked role. In this case, you've specified "Role": { "Fn::ImportValue": "TestRole" }, as a custom role. By simply removing this argument, you will be able to create ECS service with multiple targets. Would you be able to provide more details for the use case? If you think this functionality is important, please create a feature request on https://github.com/aws/containers-roadmap/issues.

**Comment by sfussenegger** [comment]
This is the role I've used here:

```json
	"TestRole": {
		"Type": "AWS::IAM::Role",
		"Properties": {
			"RoleName": { "Fn::Sub": "${StackPrefix}-test-role" },
			"Path": "/",
			"AssumeRolePolicyDocument": {
				"Statement": [
					{
						"Effect": "Allow",
						"Principal": { "Service": [ "ecs.amazonaws.com" ]},
						"Action": [ "sts:AssumeRole" ]
					}
				]
			},
			"ManagedPolicyArns": [
				"arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole",
				"arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole"
			]
		}
	}
```

We've been using this role for years without problems. I wasn't aware that [AmazonEC2ContainerServiceRole and AmazonEC2ContainerServiceAutoscaleRole are phased out](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/security-iam-awsmanpol-deprecated-policies.html) though. I'll look into that and report back if the problem persists.

Thanks!

**Comment by sfussenegger** [comment]
Works as suggested, thanks again!
