### ISSUE TITLE
Support version 2 pipelines

### ISSUE THREAD

**Issue by alFReD-NSH** [aws-cloudformation/cloudformation-coverage-roadmap#1829]
### Name of the resource

AWS::CodePipeline::Pipeline

### Description

V2 pipelines support parameters and also starting based on git tags: https://docs.aws.amazon.com/codepipeline/latest/userguide/pipeline-types-planning.html

**Comment by rgoltz** [comment]
Dear @alFReD-NSH , Dear all,

from my testing it looks fine: The CloudFormation UserGuide for `AWS::CodePipeline::Pipeline` mentioned parameter `PipelineType` ([link to docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html#cfn-codepipeline-pipeline-pipelinetype)) - including the option for `V2` as allowed value 🥳. (Thanks to Nishant from Support-Team for pointing out the availability for V2 in CFN.)

I ran a test and I can see a "V2-CodePipeline" deployed as a test-stack using CFN:
![image](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/16392819/59c8e60e-f83f-4ad3-9b35-dc0d63eef0ee)

I guess this issue #1829 could be closed as implemented from **CFN** point of view?

I've checked the **CDK** repo regarding this topic: It seems there are some necessary steps to get support via higher level contructs in CDK, as discussed here: https://github.com/aws/aws-cdk/issues/28694 and here: https://github.com/aws/aws-cdk/issues/28476

**Comment by kddejong** [comment]
You can use the [PipelineType property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codepipeline-pipeline.html#cfn-codepipeline-pipeline-pipelinetype) to set it to v2. Is there anything else you are looking to see for v2 support?
