### ISSUE TITLE
Support 'GlueCatalogGeneration' for 'S3Settings' property under AWS::DMS::Endpoint resource type

### ISSUE THREAD

**Issue by amedeshm** [aws-cloudformation/cloudformation-coverage-roadmap#1835]
### Name of the resource

AWS::DMS::Endpoint

### Description

Currently, the `GlueCatalogGeneration` property is supported by the `CreateEndpoint` API for DMS as mentioned here - https://docs.aws.amazon.com/dms/latest/APIReference/API_S3Settings.html#DMS-Type-S3Settings-GlueCatalogGeneration

However, this property is not yet supported in CloudFormation for resource type **AWS::DMS::Endpoint** - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dms-endpoint-s3settings.html

This is a feature request to support `GlueCatalogGeneration` attribute under `S3Settings` property under **AWS::DMS::Endpoint** resource type.

**Comment by chevyye** [comment]
Hi, after the latest update, `GlueCatalogGeneration` is now supported in the CFN for resource type AWS::DMS::Endpoint. Please let us know if there is any question. Thank you!
