### ISSUE TITLE
AWS::DMS::ReplicationTask supports Tag property but the CFN stack tags are not propagated

### ISSUE THREAD

**Issue by ThaDanus** [aws-cloudformation/cloudformation-coverage-roadmap#1841]
### Name of the resource

AWS::DMS::ReplicationTask

### Issue Description

It appears that ReplicationTask supports the Tag property but the stack level tags are not propagating to these resources.

https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-propagate-stack-level-tag/

### Expected Behavior

I would expect the tags to propagate to the DMS replication tasks

### Observed Behavior

No tags appear for the DMS replication instances

### Test Cases

If a replication task is created through Cloudformation, all the tags on the Cloudformation should be propagated to the Replication task as well.

**Comment by chevyye** [comment]
After testing under my personal account, I could not reproduce the issue. The stack tags I added was propagate to my replication task as well as the cloudformation tags. Could you share more details? Thank you so much.
