### ISSUE TITLE
Support maxCapacity on AWS::RedshiftServerless::Workgroup

### ISSUE THREAD

**Issue by edsw** [aws-cloudformation/cloudformation-coverage-roadmap#1844]
### Name of the resource

Other

### Resource name

AWS::RedshiftServerless::Workgroup

### Description

On 2023-11-09 AWS announced the MaxRPU feature in Redshift Serverless [1], implemented as maxCapacity on the Workgroup CRUD APIs [2]. 

[1] https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-redshift-maxrpu-compute-cost-control-redshift-serverless/
[2] https://docs.aws.amazon.com/redshift-serverless/latest/APIReference/API_Workgroup.html

### Other Details

This setting, along with the UsageLimit settings requested on #595, are important for customers to control costs on Redshift Serverless.

**Comment by JakeDahl** [comment]
Can we get this moved forward??

**Comment by IkeNefcy** [comment]
Was about to ask the same, CDK deployments overwrite any manually added max RPU value. This is a key element to CI/CD with Redshift Serverless without cost risks running rampant.

**Comment by IkeNefcy** [comment]
Tested this change and can confirm that it's working.
