### ISSUE TITLE
AWS::CodeBuild::Project - Properties::Triggers with Source::Type GITHUB_ENTERPRISE

### ISSUE THREAD

**Issue by jguice** [aws-cloudformation/cloudformation-coverage-roadmap#185]
## 1. Title
AWS::CodeBuildProject::Properties::Triggers with Source::Type GITHUB_ENTERPRISE

## 2. Scope of request
`AWS::CodeBuildProject::Properties::Triggers` works with some source types, but not `GITHUB_ENTERPRISE`.  Please expand support to work with this source type as well.

## 3. Expected behavior
The attached CFN template should complete successfully, or at least get past this error:

> Failed to call CreateWebhook, reason: The Webhook feature isn't available in AWS CloudFormation for GitHub Enterprise projects. Use the AWS CLI or AWS CodeBuild console to create the webhook. (Service: null; Status Code: 400; Error Code: null; Request ID: null)

## 4. Suggest specific test cases
(see attached)

## 5. Existing references
I couldn't find this limitation mentioned in any documentation or existing issues.  In fact the only reference I can find to it is [this tweet](https://twitter.com/andre_verheij/status/1145980293754417154) from 2/07/2019.

## 6. Category
- Developer Tools

## 7. Additional context (reproducing)
Unzip and launch the attached template via something like:
```
aws --region us-east-2 cloudformation deploy --stack-name githubtrigger --capabilities CAPABILITY_NAMED_IAM --template-file github-trigger.yaml
```

Observe stack failure with the error message quoted above.

[github-trigger.yaml.zip](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/files/3627824/github-trigger.yaml.zip)

**Comment by manota01** [comment]
Is there any further update on this feature ?

**Comment by pjongeneel** [comment]
Also looking for this feature

**Comment by mim-Armand** [comment]
We would like to have this feature enabled as well,
Thank you

**Comment by matthewcarlisle** [comment]
+1

**Comment by dnascimento** [comment]
👍

**Comment by isuruamantha** [comment]
Still not working it seems

**Comment by icmraju55** [comment]
Is there any update on this issue?

**Comment by IngussNeilands** [comment]
:eyes:

**Comment by isuruamantha** [comment]
not yet i guess :cry:

**Comment by IngussNeilands** [comment]
nop, not yet 😢

**Comment by tjbrockmeyer** [comment]
Still waiting on this feature

**Comment by swalmsley11** [comment]
+1 for this feature

**Comment by IngussNeilands** [comment]
still nothing ... 😢

**Comment by wayne-folkes** [comment]
Our team was able to get around this limitation by creating a Cloudformation Resource `MyOrg::CodeBuild::WebhookFilter` it would make the API calls to create the GHE Webhook, take the response that has the URL and the Secret and publish it to an SNS topic where another lambda would create the webhook in the GHE.

**Comment by karpovkos** [comment]
any news?

**Comment by dxciberaws** [comment]
Three and a half years later, and not even the official documentation mentions this is not supported. Deceiving.

**Comment by dxciberaws** [comment]
> 

We have a similar custom resource. Mind that on updates to the project resource, like upgrading the image (such as now standard:4.0 is deprecated), the project trigger configuration will be disabled by the CFN resource, as it is not part of its own configuration. This will render your webhook stale and your custom CFN resource orphaned.

**Comment by reachmehere89** [comment]
I see this feature was requested long back in 2019. Is there any update by when this feature would be released or even if this would be released or not ?

**Comment by colyoonamaz** [comment]
Seems like this issue is covered in the CodeBuild CloudFormation documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codebuild-project-projecttriggers.html:
```
Note
The Webhook feature isn't available in AWS CloudFormation for GitHub Enterprise projects. Use the AWS CLI or AWS CodeBuild console to create the webhook.
```
For context, CodeBuild is unable to create webhook resources within GitHub Enterprise automatically and instead returns a payload URL which customers can use to create the webhook manually within GitHub Enterprise. Given that this feature requires manual steps to finish resource creation, CodeBuild does not support this functionality within CloudFormation
