### ISSUE TITLE
AWS::ApiGateway::RestApi - EndpointConfiguration-vpcEndpointIds

### ISSUE THREAD

**Issue by ckabalan** [aws-cloudformation/cloudformation-coverage-roadmap#186]
## 1. Title 
AWS::ApiGateway::RestApi-EndpointConfiguration-vpcEndpointIds

## 2. Scope of request 
`AWS::ApiGateway::RestApi-EndpointConfiguration` supports `types` today, but not newly released `vpcEndpointIds` feature.

## 3. Expected behavior
The existing `EndpointConfiguration` structure on the Rest API is to be updated to include the new array of VPC Endpoint IDs. Looking at the documentation adding, removing, or updating the attribute does not require re-creation of the resource and does not cause interruption. The field should be an optional array of strings.

## 4. Suggest specific test cases
Common use case: Pass an array of strings (`vpce-xxxxxxxxxx`) and the `endpointConfiguration` attribute of the Rest API should be updated to reflect the same array.

## 5. Helpful Links to speed up research and evaluation

- [AWS Documentation: Associate or Disassociate a VPC Endpoint with a Private REST API](https://docs.aws.amazon.com/apigateway/latest/developerguide/associate-private-api-with-vpc-endpoint.html)
- [AWS Documentation: AWS::ApiGateway::RestApi EndpointConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html)
- [What's New: Amazon API Gateway Simplifies Invoking Private APIs](https://aws.amazon.com/about-aws/whats-new/2019/09/amazon-api-gateway-simplifies-invoking-private-apis/)

## 6. Category
Networking & Content Delivery (API Gateway)

## 7. Any additional context (optional)
None

**Comment by dsharkov** [comment]
I also need vpcEndpointIds for ApiGateway! Hope you will support it soon.

Additionally: when you release it, please add also support for AWS CDK.

Thanks!

**Comment by dmateos** [comment]
Yes this would be nice :) 

Is there a possible estimated timeframe for something like this making it in?

**Comment by dininski** [comment]
Might need confirmation, but this seems to have been address fairly recently: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html

**Comment by xiaket** [comment]
I can confirm as of today, Cloudformation claimed to support this feature in [doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html), but the service would still complain `Encountered unsupported property VpcEndpointIds`.
