### ISSUE TITLE
Add support for "recordingMode" property in AWS::Config::ConfigurationRecorder

### ISSUE THREAD

**Issue by beezly** [aws-cloudformation/cloudformation-coverage-roadmap#1861]
### Name of the resource

AWS::Config::ConfigurationRecorder

### Description

Periodic Recording just launched as a [new feature](https://aws.amazon.com/about-aws/whats-new/2023/11/aws-config-periodic-recording/) in AWS Config. This exposes a new attribute ```recordingMode``` in the ```ConfigurationRecorder``` object supplied when calling the AWS Config Rest API PutConfigurationRecorder call, see https://docs.aws.amazon.com/config/latest/APIReference/API_PutConfigurationRecorder.html#API_PutConfigurationRecorder_RequestSyntax.

Cloudformation should support this new feature, especially as CloudFormation is frequently used to automate the deployment of AWS Config with Control Tower.

**Comment by hrsmoha-amazon** [comment]
Thank you for bringing this to our attention. We have planned CloudFormation support already in the works that will be generally available soon.

**Comment by hrsmoha-amazon** [comment]
The feature should be live now. Please feel free to reopen if needed.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-configurationrecorder.html

**Comment by hrsmoha-amazon** [comment]
The feature should be live now: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-configurationrecorder.html
