### ISSUE TITLE
AWS::ElasticLoadBalancingV2::Listener missing Tags property

### ISSUE THREAD

**Issue by JohnPreston** [aws-cloudformation/cloudformation-coverage-roadmap#1883]
### Name of the resource

AWS::ElasticLoadBalancingV2::Listener

### Description

Missing `Tags` properties which are now supported on Listeners.

**Comment by rgoltz** [comment]
* @JohnPreston - Hi John - I think this issue is a dublicate to https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1527 - May we keep the original issue?

**Comment by JohnPreston** [comment]
> * @JohnPreston - Hi John - I think this issue is a duplicate to [(AWS::ElasticLoadBalancingV2::Listener) Implement `Tags` feature #1460](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1460) - May we keep the original issue?
> 
> 
> CC'd also #1527

Apologies I must have missed it in my search.
