### ISSUE TITLE
AWS Data Exports, Cost and Usage Report (CUR) 2.0

### ISSUE THREAD

**Issue by rhbecker** [aws-cloudformation/cloudformation-coverage-roadmap#1915]
### Name of the resource

AWS::CUR::ReportDefinition

### Resource name

AWS::DataExports

### Description

As far as I can tell, there's not yet support for [AWS Data Exports](https://docs.aws.amazon.com/cur/latest/userguide/), [introduced in November 2023](https://aws.amazon.com/blogs/aws-cloud-financial-management/introducing-data-exports-for-billing-and-cost-management/).

There is support for the predecessor it's supplanting, via the [AWS::CUR::ReportDefinition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cur-reportdefinition.html) resource type.

Maybe the plan is to enhance that existing resource type? The Data Exports docs brand the enhancements as _**Cost and Usage Report (CUR) 2.0**_.

**Comment by bolagadalla** [comment]
Hello,

AWS Data Exports is not yet supporting Cloudformation templates/constructs as of now. There is developments in the work to get this supported, but we do not have an exact time as to when this support will be release. But, currently we support creation of Data Exports through [SDK](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/bcm-data-exports.html), [Billing Management Console](https://docs.aws.amazon.com/cur/latest/userguide/dataexports-create-standard.html), or [CLI](https://docs.aws.amazon.com/cli/latest/reference/bcm-data-exports/)

**Comment by rhbecker** [comment]
@bolagadalla: Thanks for the response.

I don't think this issue should be closed, though, given that this repo is to track the state of CloudFormation coverage.

**Comment by rahuldeverani** [comment]
Hi team , can we please reopen this issue to track it here?

**Comment by rahuldeverani** [comment]
This is now supported using : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-bcmdataexports-export.html

However this resource is only supported in us-east-1 as of now.
