### ISSUE TITLE
The "GitConfig.RepositoryUrl" property in AWS::SageMaker::CodeRepository resource type does replacement during CloudFormation update operation. 

### ISSUE THREAD

**Issue by patel0ankur** [aws-cloudformation/cloudformation-coverage-roadmap#1936]
### Name of the resource

AWS::SageMaker::CodeRepository

### Resource name

GitConfig

### Reference Link

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sagemaker-coderepository.html#cfn-sagemaker-coderepository-gitconfig:~:text=requires%3A%20Replacement-,GitConfig,-Configuration%20details%20for

### Details

In the AWS Documentation (reference link), the "GitConfig.RepositoryUrl" property is indicated as "No interruption" for updates. However, during a CloudFormation Update operation attempting to modify the Repository URL, the resource is replaced, as indicated by the following message in the CloudFormation event:

CloudFormation Event Message:
Requested update requires the creation of a new physical resource; hence creating one.

Please change the Update requires from "No interruption" to "Replacement".

**Comment by mrlikl** [comment]
The document changes are live - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sagemaker-coderepository-gitconfig.html
