### ISSUE TITLE
You are forcing me to go thought a Change Set - And I don't like it.

### ISSUE THREAD

**Issue by davidgatti** [aws-cloudformation/cloudformation-coverage-roadmap#1938]
### Resource Name

AWS::*

### Details

Today, I encountered a new feature where, when updating a deployed CloudFormation stack, I am required to wait for a Change Set to be created before proceeding with the update.

I wish to express my concerns regarding this change, as it significantly impacts my workflow and productivity. My work involves managing large CloudFormation templates, and this new requirement adds a considerable delay—approximately 5 minutes—to even the smallest adjustments. This effectively reduces my working capacity by a factor of five, as I find myself spending a significant portion of my time simply waiting for approval to proceed.

This situation is not only frustrating but also places me in a difficult position when communicating with clients. Tasks that previously took a day to complete now require two, complicating timelines and deliverables.

I urge you to consider the implications of such changes on professionals who rely on your services daily. The goal of updates and new features should be to facilitate our work, making it more efficient rather than adding unnecessary hurdles.

**Comment by ericzbeard** [comment]
This change is being rolled back. When it is re-introduced, it will be an option (opt-in or opt-out TBD).

**Comment by davidgatti** [comment]
I noticed that the changes were reversed today. Thank you for the swift response; it significantly reduced my stress levels. I appreciate your willingness to listen to our feedback.

Best regards.
