### ISSUE TITLE
Batch JobDefinitions don't support multi-container jobs

### ISSUE THREAD

**Issue by ramblingenzyme** [aws-cloudformation/cloudformation-coverage-roadmap#1941]
### Name of the resource

AWS::Batch::JobDefinition

### Description

The Batch documentation outlines how to setup multi-container jobs for ECS and EKS and indicates that it's supported by Clouformation. 

The modified configuration is definitely supported and documented in the RegisterJobDefinition API call, but is missing from the Cloudformation documentation.

Is this an oversight, or does the support still need to be built out?

### Other Details

https://docs.aws.amazon.com/batch/latest/userguide/multi-container-jobs.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html

**Comment by pahud** [comment]
Yes looks like CFN only accepts single container properties
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html

I will create an internal ticket for clarifying.

**Comment by pahud** [comment]
internal tracking: V1279131720
