### ISSUE TITLE
ECR Repository Manually Added Policy Removed After CloudFormation Update

### ISSUE THREAD

**Issue by vandem9** [aws-cloudformation/cloudformation-coverage-roadmap#1962]
### Name of the resource

AWS::ECR::Repository

### Issue Description

When a policy is manually added to an Amazon ECR repository, it is unexpectedly removed after making an unrelated update to the repository through AWS CloudFormation (for example changing a tag value). This issue does not occur with other AWS services (e.g., S3), where manually added policies remain intact after similar CloudFormation updates.

### Expected Behavior

The manually added policy on the ECR repository should remain intact after unrelated updates through CloudFormation, similar to the behaviour observed with other AWS resources like S3 buckets.

### Observed Behavior

The manually added policy on the ECR repository is removed after an unrelated update through CloudFormation.

This issue may lead to unintended access control changes, affecting the security and compliance of the ECR repository. Users relying on manual policies for specific access control requirements might find their settings reverted unexpectedly, potentially leading to unauthorized access or broken workflows.

### Test Cases

Steps to Reproduce:

1. Create an ECR repository using AWS CloudFormation without specifying a policy in the template.

2. Manually add a policy to the ECR repository through the AWS Management Console or AWS CLI.

3. Check the CloudFormation stack drift status, which shows no drift.

4. Trigger a change on the ECR repository using CloudFormation, such as changing a tag value. This change does not involve the repository's policy.

5. Review the CloudFormation change set, which indicates that only the tag value is changing.

6. Execute the CloudFormation stack update.

7. After the update is complete, check the ECR repository and observe that the manually added policy has been removed.

Cloudformation template with ecr repository and no policy
<img width="318" alt="cfn-ecr-template" src="https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/38071372/b20df3c3-2544-4ca4-8ac3-efab8114f74f">

Creation of cloudformation stack complete
<img width="827" alt="cfn-ecr-create-complete" src="https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/38071372/09c4aaa1-890b-44bd-82cc-eb6d8d1aebaf">

Manually add policy to ecr repository
<img width="817" alt="ecr-set-policy" src="https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/38071372/ac995dbb-2880-4463-a0e6-dd792905bbf8">

Check cloudformation stack for drift
<img width="1181" alt="drift-result" src="https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/38071372/8f9ac5ff-6b12-4557-8b39-b554f939521b">

Make a change in the cloudformation template (different tag value)
<img width="329" alt="cfn-template-with-change" src="https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/38071372/2c27624b-ac5b-4866-8f96-7d10e4a967d8">

Check the changeset
<img width="483" alt="cfn-changeset" src="https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/38071372/5567ae07-2e10-48b2-b9aa-e79161dfdc88">

Cloudformation update complete
<img width="872" alt="cfn-update-of-change-complete" src="https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/38071372/7389a0e2-065d-4c58-909c-d1032184cc5c">

ECR repository policy gone
<img width="1149" alt="ecr-empty-policy-result" src="https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/assets/38071372/ec5175d6-c473-4551-ab91-da66e1088914">

**Comment by vandem9** [comment]
@jinsanz 

> This is the expected resource update behavior. When you change a AWS::ECR::Repository resource, it will trigger an update to the entire resource. If the repositoryPolicy is empty, then ECR will delete any existing repositoryPolicy. If the repositoryPolicy is non-empty, then ECR will set to the new repositoryPolicy. It's generally good practice to not manually change a resource that's managed by CFN, since CFN does not know the resource has changed, and hence the change set diff will not be accurate.

Shouldn't this at least be visible in Cloudformation drift detection that a policy has been added to the ECR?

**Comment by jinsanz** [comment]
ECR repository resource currently does not support drift detection https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html?icmpid=docs_cfn_console

There's a Github issue open for it https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1673
