### ISSUE TITLE
AWS::EC2::ClientVpnTargetNetworkAssociation - Support SecurityGroup IDs

### ISSUE THREAD

**Issue by caphrim007** [aws-cloudformation/cloudformation-coverage-roadmap#199]
## 2. Scope of request 

The existing resource does not support the ability to apply security groups to the associated target networks.

This is supported, however, supported via the AWS CLI 

## 3. Expected behavior

In Create, it should include SecurityGroupIds, like the console.

In Update, change the attribute SecurityGroupIds. It shouldn't require replacement, like the API.

In Delete, the security group applied should be the default SG for the VPC. This is the default SG that is applied if no SG is supplied anyway.

## 5. Helpful Links to speed up research and evaluation

Usage of the AWS CLI to implement this today

https://docs.aws.amazon.com/cli/latest/reference/ec2/apply-security-groups-to-client-vpn-target-network.html

## 6. Category - Will help with tagging and be easier to find by other users to +1

Networking & Content (VPC, Route53, API GW,...)

**Comment by nmussy** [comment]
This would also be helpful for the CDK, see [aws-cdk#4233](https://github.com/aws/aws-cdk/pull/4233)

**Comment by WaelA** [comment]
Closing this issue as security groups specified in a ClientVPNEndpoint resource are applied to all associated target networks. Additionally, the apply-security-groups-to-client-vpn-target-network CLI/API performs the same operation as adding or removing security groups via a ClientVPNEndpoint resource.

More information about how Security Groups are used to restrict access in Client VPN can be found here: https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/scenario-restrict.html

**Comment by WaelA** [comment]
Closing this issue as security groups specified in a ClientVPNEndpoint resource are applied to all associated target networks. Additionally, the apply-security-groups-to-client-vpn-target-network CLI/API performs the same operation as adding or removing security groups via a ClientVPNEndpoint resource.

More information about how Security Groups are used to restrict access in Client VPN can be found here: https://docs.aws.amazon.com/vpn/latest/clientvpn-admin/scenario-restrict.html
