### ISSUE TITLE
Missing AWS::ECS::TaskSet CapacityProviderStrategy attribute

### ISSUE THREAD

**Issue by regen100** [aws-cloudformation/cloudformation-coverage-roadmap#1997]
### Name of the resource

AWS::ECS::TaskSet

### Description

c) new attribute for an existing resource is desired

AWS::ECS::TaskSet does not have CapacityProviderStrategy attribute.

References:
- ECS doc: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-external.html
- aws cli has `--capacity-provider-strategy`: https://docs.aws.amazon.com/cli/latest/reference/ecs/create-task-set.html#:~:text=%2D%2D-,capacity%2Dprovider%2Dstrategy,-(list)

**Comment by karanbokil** [comment]
CapacityProviderStrategyItem has been added

**Comment by regen100** [comment]
Thanks for the update! I confirmed that we can create AWS::ECS::TaskSet with CapacityProviderStrategy.
