### ISSUE TITLE
AWS::EKS::Cluster Tags

### ISSUE THREAD

**Issue by pmontanari** [aws-cloudformation/cloudformation-coverage-roadmap#200]
Please add support for tags on AWS::EKS::Cluster

**Comment by whereisaaron** [comment]
https://github.com/aws/containers-roadmap/issues/374

**Comment by robertd** [comment]
Any updates on this?

**Comment by lynnnnnnluo** [comment]
Tags along with other properties (logging, end point access) will be added along with publishing EKS::Cluster resource

**Comment by robertd** [comment]
@lynnnnnnluo When is the next release exactly?

**Comment by aws-tatarkin** [comment]
Hi, any updates?

**Comment by lynnnnnnluo** [comment]
This feature is now available using the EKS cluster CFN resource

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-cluster.html
