### ISSUE TITLE
AWS::RDS::DBParameterGroup - AWS::RDS::*Group .Name

### ISSUE THREAD

**Issue by hoshino3** [aws-cloudformation/cloudformation-coverage-roadmap#212]
We want specifying DBParameterGroupName when creating DBParameterGroup.

**Comment by rpatton4** [comment]
Related - could the same be added for DBClusterParameterGroup?

**Comment by PatMyron** [comment]
**Should be name properties for all these RDS resource types:**
[`AWS::RDS::OptionGroup`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-optiongroup.html): [`aws rds create-option-group`](https://docs.aws.amazon.com/cli/latest/reference/rds/create-option-group.html#synopsis)
[`AWS::RDS::DBParameterGroup`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbparametergroup.html): [`aws rds create-db-parameter-group`](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-parameter-group.html#synopsis)
[`AWS::RDS::DBClusterParameterGroup`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbclusterparametergroup.html): [`aws rds create-db-cluster-parameter-group`](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster-parameter-group.html#synopsis)
[`AWS::RDS::DBSecurityGroup`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-security-group.html): [`aws rds create-db-security-group`](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-security-group.html#synopsis)
~~[`AWS::RDS::DBSubnetGroup`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbsubnet-group.html): [`aws rds create-db-subnet-group`](https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-subnet-group.html#synopsis)~~

**Comment by dingobar** [comment]
When will this be available? Seems strange to not have it.

**Comment by KarlosLam** [comment]
Hope AWS SDK is not the replacement for CF

**Comment by ns-ajith** [comment]
Same issue with CDK too
```
   db_cluster_ParameterGroup=rds.CfnDBClusterParameterGroup (self, 'clusterparametergroup',
  File "/usr/local/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'name'
```

**Comment by labarilem** [comment]
Still not available as of today. Do we need to use the CLI?

**Comment by vramanlal** [comment]
+1
Please implement this capability.

**Comment by valykhin** [comment]
+1
We need it in project for policies which depends on resources name

**Comment by DevOps-RV** [comment]
+1

**Comment by pringtest** [comment]
still not have this capability until now. GG
