### ISSUE TITLE
Support AWS License Manager

### ISSUE THREAD

**Issue by rjpereira** [aws-cloudformation/cloudformation-coverage-roadmap#225]
2. Scope : support for License Manager service
5. Links : https://docs.aws.amazon.com/license-manager/latest/APIReference/Welcome.html
6. Category: Management and Governance

**Comment by brianterry** [comment]
@rjpereira , License Manager is now supported.

Please see our docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_LicenseManager.html
