### ISSUE TITLE
AWS::WAF::WebACL tagging

### ISSUE THREAD

**Issue by ionutz89** [aws-cloudformation/cloudformation-coverage-roadmap#231]
##Scope of request 

####Currently, we can add tags to AWS WAF only by using CLI:

`aws waf tag-resource --resource-arn arn:aws:waf::XXXXXXXXXXXXX:webacl/12340-12234-23452-233455 --tags "Key=tag1,Value=values2`

###It will be great if this option can be added to Cloudformation as well.

##Helpful Links to speed up research and evaluation

####https://docs.aws.amazon.com/cli/latest/reference/waf/tag-resource.html

##Category Security

##I think we should also add tags support to  "Type": "AWS::WAFRegional::WebACL"

**Comment by piotrekwitkowski** [comment]
Customers can migrate their WebACLs to WAFv2. `AWS::WAFv2::WebACL` supports setting tags.
