### ISSUE TITLE
AWS::RDS::DBCluster does not support CopyTagsToSnapshot

### ISSUE THREAD

**Issue by ctaintor** [aws-cloudformation/cloudformation-coverage-roadmap#238]
#### Scope of Request

AWS::RDS::DBCluster does not support CopyTagsToSnapshot

#### Expected behavior

In Create, I should be able to be able to set the CopyTagsToSnapshot attribute

#### Links to existing API doc

https://docs.aws.amazon.com/cli/latest/reference/rds/modify-db-cluster.html `copy-tags-to-snapshot`

#### Category tag

RDS

**Comment by rrezino** [comment]
Any news about it?

**Comment by tvb** [comment]
Yes, I would like to know this as well @craigataws

**Comment by craigataws** [comment]
@tvb @LukeHuston03878 I have a coverage status meeting this week, I'll bring it up and advise here on the details

**Comment by craigataws** [comment]
Spoke to the dev team, they are picking this one up in an upcoming sprint.  Moving this to 'We're working on it' status

**Comment by LukeHuston03878** [comment]
That’s super, thanks Craig


Luke Huston

Principal Database Administrator

GRS Architecture, Cloud and Engineering Enablement

Liberty Mutual Insurance
Direct Dial:  (603) 245-1527
Cell:  (603) 828-5452
Email:  Luke.Huston@LibertyMutual.com<mailto:Luke.Huston@LibertyMutual.com>

[AWS-SME_smaller]

From: Craig Lefkowitz ***@***.***>
Sent: Monday, April 5, 2021 6:18 PM
To: aws-cloudformation/aws-cloudformation-coverage-roadmap ***@***.***>
Cc: Huston, Luke <Luke.Huston@LibertyMutual.com>; Mention ***@***.***>
Subject: {EXTERNAL} Re: [aws-cloudformation/aws-cloudformation-coverage-roadmap] AWS::RDS::DBCluster does not support CopyTagsToSnapshot (#238)


Spoke to the dev team, they are picking this one up in an upcoming sprint. Moving this to 'We're working on it' status

**Comment by mattvanstone** [comment]
I know this is not what this issue is about, but just recently learned about this and wanted to share for those who didn't know. You can use a custom resource to make any JavaScript API call. The custom resource below calls the `modifyDBCluster` action to set the `CopyTagsToSnapshot` to `true` when this resource is created. Since it is dependent on `DatabaseB269D8BB` for the the `DBClusterIdentifier` parameter it will execute after the cluster is created.

So it doesn't solve this, but it is a good workaround which avoids those manual changes outside of your IaC that drive me crazy. VPC Endpoints (https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/196) and CloudWatch Event Rules are other resources that don't currently support tagging through CloudFormation. This should work for those too.


This sample code was pulled out of a cdk synthesized CloudFormation template, but hopefully you get the idea. 

```json
    "copytags0C4036F5": {
      "Type": "Custom::AWS",
      "Properties": {
        "ServiceToken": {
          "Fn::GetAtt": [
            "AWS679f53fac002430cb0da5b7982bd22872D164C4C",
            "Arn"
          ]
        },
        "Create": {
          "Fn::Join": [
            "",
            [
              "{\"action\":\"modifyDBCluster\",\"service\":\"RDS\",\"parameters\":{\"CopyTagsToSnapshot\":true,\"DBClusterIdentifier\":\"",
              {
                "Ref": "DatabaseB269D8BB"
              },
              "\"},\"physicalResourceId\":{\"id\":\"copy-tags\"}}"
            ]
          ]
        },
        "InstallLatestAwsSdk": true
      },
      "DependsOn": [
        "copytagsCustomResourcePolicyD8D3C92E"
      ],
      "UpdateReplacePolicy": "Delete",
      "DeletionPolicy": "Delete",
      "Metadata": {
        "aws:cdk:path": "RdsCdkStack/copy-tags/Resource/Default"
      }
    }
```
Full template: 
[RdsCdkStack.template.txt](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/files/6268969/RdsCdkStack.template.txt)

**Comment by LukeHuston03878** [comment]
Hi gang – any update on this? My compliance folks are being itchy about it 😊

Luke Huston
Principal Database Administrator
GRS Architecture, Cloud and Engineering Enablement
Liberty Mutual Insurance
Direct Dial:  (603) 245-1527
Cell:  (603) 828-5452
Email:  Luke.Huston@LibertyMutual.com<mailto:Luke.Huston@LibertyMutual.com>
[AWS-SME_smaller]

From: Huston, Luke
Sent: Tuesday, April 6, 2021 8:34 AM
To: aws-cloudformation/aws-cloudformation-coverage-roadmap ***@***.***>; aws-cloudformation/aws-cloudformation-coverage-roadmap ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: {EXTERNAL} Re: [aws-cloudformation/aws-cloudformation-coverage-roadmap] AWS::RDS::DBCluster does not support CopyTagsToSnapshot (#238)

That’s super, thanks Craig


Luke Huston

Principal Database Administrator

GRS Architecture, Cloud and Engineering Enablement

Liberty Mutual Insurance
Direct Dial:  (603) 245-1527
Cell:  (603) 828-5452
Email:  Luke.Huston@LibertyMutual.com<mailto:Luke.Huston@LibertyMutual.com>

[AWS-SME_smaller]

From: Craig Lefkowitz ***@***.******@***.***>>
Sent: Monday, April 5, 2021 6:18 PM
To: aws-cloudformation/aws-cloudformation-coverage-roadmap ***@***.******@***.***>>
Cc: Huston, Luke <Luke.Huston@LibertyMutual.com<mailto:Luke.Huston@LibertyMutual.com>>; Mention ***@***.******@***.***>>
Subject: {EXTERNAL} Re: [aws-cloudformation/aws-cloudformation-coverage-roadmap] AWS::RDS::DBCluster does not support CopyTagsToSnapshot (#238)


Spoke to the dev team, they are picking this one up in an upcoming sprint. Moving this to 'We're working on it' status

**Comment by craigataws** [comment]
@LukeHuston03878, the dev team is actively working in it and on track for deployment in Q2.

**Comment by ascar01973** [comment]
Hi, @craigataws, any chance that the planned resolution will include handling AWS::DocDB::DBCluster?
If not, do you know if there's already a ticket opened for that related work (I didn't find one but may have missed it)?

**Comment by craigataws** [comment]
The `CopyTagsToSnapshot` property has been added to `AWS::RDS::DBCluster`:  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-copytagstosnapshot

@ascar01973, `AWS::DocDB::DBCluster` would be a separate issue.  Can you open an issue for that so we can track it?
