### ISSUE TITLE
AWS::SecretsManager::SecretTargetAttachment - TargetType-AWS::ElastiCache::ReplicationGroup

### ISSUE THREAD

**Issue by chrisoverzero** [aws-cloudformation/cloudformation-coverage-roadmap#252]
`AWS::SecretsManager::SecretTargetAttachment`-`TargetType` supports various database resources today, but not ElastiCache Replication Groups.

## Expected Behavior

Now that AWS has [enabled AuthToken rotation][] for ElastiCache Replication Groups, it is possible to auto-rotate this credential in the same way as RDS database credentials can be auto-rotated. However, this introduces the same circular dependency as the one which `AWS::SecretsManager::SecretTargetAttachment` was designed to solve for databases.

As with so much in CloudFormation, this can be worked around with a custom resource, but this solution is unsatisfying for a few reasons, not the least of which is IAM. A Lambda Function, when called as a custom resource, is not invoked as the CloudFormation service role, but as its own execution role. This means that a reusable solution has to have such a policy (among others):

```yaml
Version: 2012-10-17
Id: UpdateSecret
Statement:
  Effect: Allow
  Action:
  - secretsmanager:GetSecretValue
  - secretsmanager:PutSecretValue
  Resource: '*'
```

...which is concerningly open, to me.

Additionally, a custom resource does not have the nice pass-through behavior of returning the ID of the secret when passed to the `Ref` intrinsic.

I would expect such an attachment to function very similarly to the existing feature, in that it would write the following into the specified secret on creation or update:

```json
{
  "id": "<unique identifier of replication group, the value of `Ref`>",
  "host": "<address of same, the value of `GetAtt PrimaryEndPoint.Address`>",
  "port": "<port of same, the value of `GetAtt PrimaryEndPoint.Port`>",
  "ssl": "<transit encryption requirement of same, the value supplied to `TransitEncryptionEnabled` (which is required to be `true` in order to specify `AuthToken`, but why not)>"
}
```

...relying on `AWS::SecretsManager::Secret` to generate the key `password`. (Key names chosen to match those of a Redis connection string.)

[enabled AuthToken rotation]: https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-elasticache-announces-support-for-modifying-redis-authentication-tokens/

## Specific Test Cases

I imagine the resource should fail if the target resource (the value of `TargetId`) which claims to be an `AWS::ElastiCache::ReplicationGroup` is actually an `AWS::ElastiCache::CacheCluster`, as those have no support for the `AuthToken` property.

The resource should not change its `Ref` behavior as a result of this added support.

## Helpful Links

- The current Secret Target Attachment [resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html).
- The [announcement](https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-elasticache-announces-support-for-modifying-redis-authentication-tokens/) of authentication token rotation support.

## Category

Database

## Any additional context

I have created an SAR Application which does this attachment and rotation, but built-in support for the attachment is desirable for the same reason as it was desirable for RDS databases. Workarounds exist -- I know because I'm using one right now -- but adding ElastiCache Replication Group support to this resource would be _better_.

**Comment by avnirambhia2** [comment]
We've reviewed this request. We believe it is an enhancement request, and have added it to our roadmap.
The AWS CloudFormation Public Coverage Roadmap is focused on coverage additions to existing AWS services. Specifically, it is meant to address resource coverage gaps where the service API functionality exists but does not have the equivalent support in CloudFormation. We are therefore closing this issue here.

**Comment by Chaitu1111** [comment]
@TheDanBlanco Is this Issue fixed. If so which troposphere version supports 
TargetType:
AWS::ElastiCache::ReplicationGroup
