### ISSUE TITLE
AWS::SSO::PermissionSet

### ISSUE THREAD

**Issue by atkinsonm** [aws-cloudformation/cloudformation-coverage-roadmap#256]
## 1. Title

Create AWS::SSO::PermissionSet Resource

## 2. Scope of request

It is possible to create AWS SSO permission sets via the console but not through CloudFormation today.

## 3. Expected behavior

Ability to perform CRUD operations on SSO permission sets.

## 4. Suggest specific test cases

Similar properties to `AWS::IAM::ManagedPolicy` resources, name and policy document at minimum.

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/singlesignon/latest/userguide/permissionsetsconcept.html

## 6. Category

Security

**Comment by jplock** [comment]
Is there more documentation for this? https://aws.amazon.com/about-aws/whats-new/2020/09/aws-single-sign-on-adds-account-assignment-apis-and-aws-cloudformation-support-to-automate-multi-account-access-management/

**Comment by atkinsonm** [comment]
Docs are at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sso-permissionset.html.

This issue can be closed.
