### ISSUE TITLE
AWS::AutoScaling::LaunchConfiguration - MetadataOptions

### ISSUE THREAD

**Issue by exidy** [aws-cloudformation/cloudformation-coverage-roadmap#273]
## 2. Scope of request 

Add support to configure the EC2 IMDS to support:
* Enable/disable the endpoint
* Set the HTTP response hop limit
* Make HTTP tokens optional (default) or required (disables IMDSv1)

## 3. Expected behavior

Allow CloudFormation to launch instances in ASGs with IMDS disabled or restricted to v2.

## 5. Helpful Links to speed up research and evaluation

* Description of IMDS: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
* RunInstances API call: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_InstanceMetadataOptionsRequest.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Compute (EC2, ECS, EKS, Lambda...)

**Comment by michaelwittig** [comment]
@TheDanBlanco  seems to be supported now: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-launchconfig.html#cfn-autoscaling-launchconfig-metadataoptions

**Comment by SirPyros** [comment]
LaunchConfiguration is missing the Instance Metadata Tags option that was added to LaunchTemplates.
