### ISSUE TITLE
AWS::Lambda::Function - botocore upgrade

### ISSUE THREAD

**Issue by n-apalm** [aws-cloudformation/cloudformation-coverage-roadmap#286]
## 2. Scope of request 
When using ZipFile property to specify function code interacting with Cloudformation, Cloudformation automatically includes `cfnresponse` with your python lambda function.

`cfnresponse` has a requirement of `botocore` < 1.13, clobbering lambda layer zips that have `botocore` >= 1.13. This makes it impossible to use `botocore` >= 1.13 in a `AWS::Lambda::Function` .

Are there any plans to update this module to use up to date versions of `botocore`?

**Comment by crazy54** [comment]
Is there any way to resolve this until a fix is rolled out? I am having similar issues.

**Comment by kddejong** [comment]
@n-apalm I am trying to replicate this issue but I believe it is now resolved. cfnresponse looks to have been updated to not require botocore https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html#w2ab1c27c24c14b9c15

In your mind has this issue been resolved?

**Comment by micahduron** [comment]
That's correct @kddejong, the cfnresponse module no longer depends on botocore. I believe this issue can be resolved now.
