### ISSUE TITLE
AWS::CloudTrail::Trail - InsightSelectors

### ISSUE THREAD

**Issue by seittema** [aws-cloudformation/cloudformation-coverage-roadmap#287]
## Scope of request 
New attribute for an existing resource is desired

AWS::CloudTrail::Trail - Add support for using Insight Selectors.

## Expected behavior
You should be allowed to specify one or more InsightSelectors when creating a CloudTrail.  Currently today there is only one valid type, but the API is written to handle future types.  Ideally this would follow the same pattern as EventSelectors does:

`InsightSelectors : [ InsightSelector ... ]`

`InsightSelector : { InsightType: String}` - (Allowed Value ApiCallRateInsight)

## Links to existing API doc

https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_PutInsightSelectors.html

## Category

Management

**Comment by dhruvdakoria** [comment]
Any updates on this for native cfn support?

**Comment by seittema** [comment]
Appears this was released on Sept 10th  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html#cfn-cloudtrail-trail-insightselectors

Can close the issue
