### ISSUE TITLE
AWS::EKS::Cluster-Type with Fargate support

### ISSUE THREAD

**Issue by pahud** [aws-cloudformation/cloudformation-coverage-roadmap#288]
## 1. Title 
AWS::EKS::Cluster-Type
AWS::EKS::Cluster-FargateProfileConfiguration

## 2. Scope of request 

   b) new resource type for an existing service is desired

Samples: 

#### In Create, it should create a cluster with the provided Fargate profile configuration

Feel free to describe other desired and relevant implementation details. 

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. Compute (EC2, ECS, EKS, Lambda...)

**Comment by hekonsek** [comment]
Any estimates when this could be available? :)

**Comment by kirnberger1980** [comment]
Please implement this new Resource Type

**Comment by goyertp** [comment]
Hi,

would like to see this in CF !

**Comment by luiseduardocolon** [comment]
We hear ya - have some folks working on this now

**Comment by brianterry** [comment]
@pahud, 
CloudFormation now supports[AWS::EKS::FargateProfile](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-fargateprofile.html).
