### ISSUE TITLE
AWS::RDS::DBCluster - ScalingConfiguration-TimeoutAction

### ISSUE THREAD

**Issue by michaelwittig** [aws-cloudformation/cloudformation-coverage-roadmap#298]
AWS::RDS::DBCluster-ScalingConfiguration does not support the TimeoutAction property

https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ScalingConfiguration.html

**Comment by michaelwittig** [comment]
The option is available now :)

**Comment by docktermj** [comment]
Is there a work-around for this?

**Comment by docktermj** [comment]
Any progress on this?

**Comment by michaelwittig** [comment]
If you sort the issues by :+1: reactions you will find this issue on page 5. I'm not saying that the issues are only worked on in the order of customer demand, but I wouldn't wait fo that attribute to be supported soon 🙉

**Comment by docktermj** [comment]
To help customers overcome this current limitation,  I've created
https://github.com/Senzing/knowledge-base/blob/master/HOWTO/set-aws-rds-force-scaling-capacity.md

**Comment by docktermj** [comment]
@michaelwittig Any progress on this?

**Comment by docktermj** [comment]
@michaelwittig @luiseduardocolon  Any progress on this?

**Comment by gpid007** [comment]
please make this option available in CFN

**Comment by docktermj** [comment]
@michaelwittig Did this actually get shipped?

I don't see it in https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html

**Comment by docktermj** [comment]
If it hasn't been shipped, then please reopen.   (If not, it's OK.  I'll just open another issue on this.)

**Comment by michaelwittig** [comment]
I can [see it here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbcluster-scalingconfiguration.html) :)

<img width="394" alt="Screenshot 2022-11-16 at 14 01 02" src="https://user-images.githubusercontent.com/950078/202187344-656240dd-d307-46b2-9ebb-a04430980115.png">

**Comment by docktermj** [comment]
@michaelwittig Excellent!  Thank you!

**Comment by docktermj** [comment]
@michaelwittig I didn't realize that.  :smile:   I do appreciate your help.  Danke!    (I visited Boeblingen a number of years ago.  Still remember the wonderful taste of Apfelsaft.  I can't seem to find that taste anywhere else.)

**Comment by docktermj** [comment]
I opened https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1404 to track support for **SecondsBeforeTimeout**.

**Comment by michaelwittig** [comment]
@docktermj Fingers crossed that you don't have to wait another three years...
