### ISSUE TITLE
AWS::CloudFormation::Type

### ISSUE THREAD

**Issue by troyready** [aws-cloudformation/cloudformation-coverage-roadmap#299]
## Scope of request 

AWS::CloudFormation::Type - can create resource via API, but not via CloudFormation

## Expected behavior

In Create, it should [register the type](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_RegisterType.html) and [set it as the default version](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_SetTypeDefaultVersion.html)

In Update, it should [register a new type (using the same name)](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_RegisterType.html), [set it as the default version](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_SetTypeDefaultVersion.html), and [deregister the old version](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DeregisterType.html)

In Delete, it should [deregister the current version](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DeregisterType.html)

Updates to the resource changing the name should be rejected.

## Links

* https://aws.amazon.com/about-aws/whats-new/2019/11/now-extend-aws-cloudformation-to-model-provision-and-manage-third-party-resources/

## Category

Management

**Comment by rjlohan** [comment]
This was actually already requested, but I moved the issue over [here](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/issues/3)

I have a PR up for schema discussion in that repo, feel free to chime in 👍 

I have a basic codebase nearly ready to add there too.

**Comment by wulfmann** [comment]
Is this now resolved from this merge? https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/pull/4

**Comment by benkehoe** [comment]
It's only resolved once it ships in CloudFormation proper. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_CloudFormation.html

**Comment by jarreds** [comment]
Any word on when this actually going live?

**Comment by brianterry** [comment]
CloudFormation now supports the following resources:
[AWS::CloudFormation::ResourceDefaultVersion](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-resourcedefaultversion.html)
[AWS::CloudFormation::ResourceVersion](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-resourceversion.html)

Thank you!
