### ISSUE TITLE
AWS::EC2::EIP showing drifted after adding Tags

### ISSUE THREAD

**Issue by badaldavda** [aws-cloudformation/cloudformation-coverage-roadmap#311]
## Instructions for CloudFormation Coverage New Issues Template

Quick Sample Summary:
1. Title -> AWS::EC2::EIP-Existing Attribute
2. Scope of request -> AWS::EC2::EIP::TheResource-ExistingAttribute supports Tagging but Drift detection is showing false positives.
3. Expected behavior -> Actual Values and expected values should be same.
4. Test case recommendation (optional) -> 

`{
"AWSTemplateFormatVersion": "2010-09-09",
    "Resources": {
        "EIPjumphost0": {
            "Properties": {
                "Domain": "vpc", 
                "Tags": [
                    {
                        "Key": "Environment", 
                        "Value": "king"
                    }, 
                    {
                        "Key": "Name", 
                        "Value": "EIPjumphost0"
                    }, 
                    {
                        "Key": "Stack", 
                        "Value": {
                            "Ref": "AWS::StackName"
                        }
                    }
                ]
            }, 
            "Type": "AWS::EC2::EIP"
        }
    }
}`

5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html
6. Category tag (optional) -> Compute
7. Any additional context (optional)
Attaching screenshot 
<img width="1107" alt="Screenshot 2019-12-19 at 11 12 09 AM" src="https://user-images.githubusercontent.com/10769534/71149355-4b0d9500-2254-11ea-9064-3493d3fedbb2.png">

**Comment by rkferreira** [comment]
Is there a workaround to put the stack back to "IN SYNC" state? 
Resources are current in use... 
Its exactly the same scenario, all EIPs are saying TAGs drifted.

Thanks

**Comment by michaelsimon** [comment]
Seeing this as well...

**Comment by zbornstein** [comment]
I'm seeing this behavior as well with SNS::Topics. If you go to add Tags to the resource, the drift shows up and no tags are propagated to the Topic. I am working within the scope of updating a template used to deploy stackset instances.

**Comment by skwasjer** [comment]
I am seeing this for several resources `AWS::ApiGateway::RestApi`, `AWS::ApiGateway::Stage`, `AWS::IAM::Role`, `AWS::SNS::Topic`, but for others (like `AWS::Lambda::Function`) the tags are added and no drift is observed.

**Comment by tstibbs** [comment]
I can't understand how this is an issue. Doesn't this render the drift detection feature pretty much useless? It's not like `RestApi` or `SNS::Topic` are exactly niche, they must be in just about every stack out there.

@badaldavda is it worth updating the title of this issue to make it clear that this affects more than just EIPs?

**Comment by harinder-beatdapp** [comment]
We're facing this issue as well. All our resources are tagged but `AWS::ApiGateway::RestApi`, `AWS::ApiGateway::Stage` and `AWS::ApiGateway::ApiKey` are showing up as `MODIFIED` because Drift Detection thinks their tags were removed

**Comment by Jackhu-gc** [comment]
We got the same issue from 01 Mar 2022. All other resources are fine, `AWS::ECS::Cluster`, `AWS::Logs::LogGroup`, `AWS::ECS::TaskDefinition` are showing `MODIFIED`. ECS Cluster are showing stack-level tags 
`
 "StackResourceDrifts": [
        {
            "StackId": "arn:aws:cloudformation:region:accountId:stack/xxx-uat-xxx/06052380-c9d1-11eb-94d1-022ca2ac0e8a",
            "LogicalResourceId": "ECSCluster",
            "PhysicalResourceId": "XXX-uat-XXX",
            "ResourceType": "AWS::ECS::Cluster",
            "ExpectedProperties": "XXXXXX",
            "ActualProperties": "XXX",
            "PropertyDifferences": [
                {
                    "PropertyPath": "/Tags/7",
                    "ExpectedValue": "null",
                    "ActualValue": "{\"Key\":\"aws:cloudformation:stack-name\",\"Value\":\"XXX-uat-XXX\"}",
                    "DifferenceType": "ADD"
                },
                {
                    "PropertyPath": "/Tags/8",
                    "ExpectedValue": "null",
                    "ActualValue": "{\"Key\":\"aws:cloudformation:logical-id\",\"Value\":\"ECSCluster\"}",
                    "DifferenceType": "ADD"
                },
                {
                    "PropertyPath": "/Tags/9",
                    "ExpectedValue": "null",
                    "ActualValue": "{\"Key\":\"aws:cloudformation:stack-id\",\"Value\":\"arn:aws:cloudformation:region:accountId:stack/xxx-uat-xxx/06052380-c9d1-11eb-94d1-022ca2ac0e8a\"}",
                    "DifferenceType": "ADD"
                }
            ],
            "StackResourceDriftStatus": "MODIFIED",
            "Timestamp": "2022-03-03T03:14:59.866000+00:00"
        },
        {...
`

**Comment by onimitch** [comment]
Confirm I have also this issue with a AWS::ApiGateway::RestApi. When I check the Resource, the tags are definitely there so the drift report is false.

**Comment by bplessis-swi** [comment]
I cannot say for the other resources type listed here (that should probably have their own individuals issues since cloudformation resources are handled by the individuals projects teams) but for AWS::EC2::EIP that don't seem to be an issue anymore
