### ISSUE TITLE
AWS::FSx::FileSystem Multi-AZ Deployment Support

### ISSUE THREAD

**Issue by runderko** [aws-cloudformation/cloudformation-coverage-roadmap#313]
Multi-AZ support is available via the console, but not yet implemented as a native CloudFormation property.

Organizations that prevent resource changes in the console and only allow  them to be made via CloudFormation are unable to take advantage of this new FSx capability.

[Deployment Type Property] (https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateFileSystem.html)

Storage
Management

**Comment by Project0** [comment]
I recently used Multi AZ deployment (windows fsx) two month ago. AFAIK they just rolled it out in April for all regions.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-fsx-filesystem-windowsconfiguration.html#cfn-fsx-filesystem-windowsconfiguration-deploymenttype

**Comment by andcru** [comment]
Amazon FSx support creating Multi-AZ file systems using AWS CloudFormation. See the "DeploymentType" option on https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-fsx-filesystem-windowsconfiguration.html#cfn-fsx-filesystem-windowsconfiguration-deploymenttype for more information.
