### ISSUE TITLE
Add cost usage report support

### ISSUE THREAD

**Issue by softprops** [aws-cloudformation/cloudformation-coverage-roadmap#316]
## 1. The following resources are missing from CloudFormation

* `AWS::CUR::ReportDefinition` 

## 2. Scope of request 

`AWS::CUR::*`

## 3. Expected behavior

To be able to manage cost usage reports via cloud formation

## 5. Helpful Links to speed up research and evaluation

Samples:
## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Other(Billing) https://console.aws.amazon.com/billing/home?#/reports

**Comment by tobilg** [comment]
I created a custom resource for AWS::CUR::ReportDefinition: https://github.com/tobilg/cfn-cur-report-definition

**Comment by mwhouser** [comment]
I too want to create CUR reports via CloudFormation.

+1 please.

**Comment by tobilg** [comment]
I just published an update to my custom resource

**Comment by omerxx** [comment]
Apparently this has documentation as if it has been implemented but it doesn't really exist.
Anyone has any idea on this?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cur-reportdefinition.html

**Comment by brianterry** [comment]
CloudFormation now supports [AWS::CUR::ReportDefinition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cur-reportdefinition.html)

Thank you!

**Comment by craighurley** [comment]
@brianterry the docs are not great and need some love, e.g. clarify what format and compression values are allowed, add an example.

:(

**Comment by ddivilly** [comment]
> CloudFormation now supports [AWS::CUR::ReportDefinition](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cur-reportdefinition.html)
> 
> Thank you!

Shame this is only available in US-EAST-1, hopefully it be GA soon.

**Comment by dacacioa** [comment]
Do you have any plan to do it GA? In some scenarios, use US-EAST-1 region is not possible.
