### ISSUE TITLE
AWS::Organizations::OU - New Resources

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cloudformation-coverage-roadmap#33]
1. Title -> AWS::Organizations::OU 
1. Scope of request -> Create and manage a new OU inside an AWS Organization
1. Expected behavior -> A new OU is created and has the root parent OU or root 
1. Test case recommendation (optional) ->
1. Links to existing API doc (optional) -> https://docs.aws.amazon.com/organizations/latest/APIReference/API_CreateOrganizationalUnit.html
1. Category tag (optional) -> Organizations

**Comment by rhboyd** [comment]
AWS::Organizations::OU should have a "parent" attribute that could be !Ref myOtherOU and not necessarily the root OU.

**Comment by rjlohan** [comment]
Then we can deploy this with StackSets... and include another StackSet in it... and hey presto....

...SkyNet.

**Comment by kddejong** [comment]
yea agreed @rhboyd it should allow for either.  I may have not worded that correctly. 

From the documentation the `ParentId` can be either:
`Root: a string that begins with "r-" followed by from 4 to 32 lower-case letters or digits.`
`Organizational unit (OU): a string that begins with "ou-" followed by from 4 to 32 lower-case letters or digits (the ID of the root that the OU is in) followed by a second "-" dash and from 8 to 32 additional lower-case letters or digits.`

**Comment by rafalwrzeszcz** [comment]
In the meantime you may want to check out:

https://rafalwrzeszcz-wrzasqpl.github.io/pl.wrzasq.lambda/lambda-cform/lambda-cform-organization/guide/usage.html
https://rafalwrzeszcz-wrzasqpl.github.io/pl.wrzasq.lambda/lambda-cform/lambda-cform-organization-unit/guide/usage.html

**Comment by tsykora-verimatrix** [comment]
+1 we'd appreciate AWS Organization support in CloudFormation and CDK

**Comment by rhbecker** [comment]
We're about to work with the AWS Organizations service for the first time and the first thing we did was check for CloudFormation support. I'm glad to see this and related issues exist (not as glad as if they were done, but at least they're on the roadmap).

Is there a reason that an `AWS::Organizations::Organization` resource wasn't requested as well? Being new to the service, I'm not sure if that's a stupid question.

**Comment by mathieubrd** [comment]
> We're about to work with the AWS Organizations service for the first time and the first thing we did was check for CloudFormation support. I'm glad to see this and related issues exist (not as glad as if they were done, but at least they're on the roadmap).
> 
> Is there a reason that an `AWS::Organizations::Organization` resource wasn't requested as well? Being new to the service, I'm not sure if that's a stupid question.

Any update of this? Our current workaround is to use custom resources but it's really a pain to maintain.

**Comment by tomekklas** [comment]
This functionality is badly needed.
It is a sensitive area, especially in complex OU structures in large organizations (which are typically large payers).
Is there an ETA on this?

**Comment by mInrOz** [comment]
> This functionality is badly needed. It is a sensitive area, especially in complex OU structures in large organizations (which are typically large payers). Is there an ETA on this?

I second this!

**Comment by kddejong** [comment]
Now available: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-organizations-organizationalunit.html

**Comment by rhbecker** [comment]
> Is there a reason that an `AWS::Organizations::Organization` resource wasn't requested as well? Being new to the service, I'm not sure if that's a stupid question.

I'm still not sure of the answer to this question. If folks that have experience with the service can weigh in, affirming this would make sense as a new CFN resource type, I'd happily initiate a new issue to track the request.

**Comment by pflorek** [comment]
Yes, `AWS::Organizations::Organization` is missing. Also getAttr RootId i.e. `AWS::Organizations::Root` is missing.

Currently we are forced to either leverage `AwsCustomResource` or the custom_resources provider mini-provider framework like https://github.com/pepperize/cdk-organizations#organization

https://github.com/pflorek/aws-cdk/blob/fc3fe18e4361f7ca2593be21dc880725212debe1/packages/%40aws-cdk/aws-organizations/lib/organization-root.ts#L39-L51
