### ISSUE TITLE
AWS::IAM::ServiceLinkedRole GovCloud

### ISSUE THREAD

**Issue by cmckni3** [aws-cloudformation/cloudformation-coverage-roadmap#334]
## 2. Scope of request 

Should be able to use AWS::IAM::ServiceLinkedRole in GovCloud regions.

I have implemented this as a custom resource.

## 3. Expected behavior

On GovCloud, AWS::IAM::ServiceLinkedRole should create a new service linked role instead of erroring on "resource type not available".

## 4. Suggest specific test cases

Create ElasticSearch service linked role in GovCloud on an account without ElasticSearch service linked role.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

8. Security (IAM, KMS...)

**Comment by cmckni3** [comment]
Should this actually be a bug? Other services automatically create service linked roles as necessary during resource creation (Examples: ECS, API Gateway, ELB).

CloudFormation reported an error from the ES service stating "The Amazon ElasticSearch Service Linked role must exist before creating a cluster."

**Comment by gamma425** [comment]
any update?
