### ISSUE TITLE
AWS::ElasticLoadBalancingV2::Listener -  ForwardActionConfig - Weights

### ISSUE THREAD

**Issue by dvedhire** [aws-cloudformation/cloudformation-coverage-roadmap#338]
## Support for weighted target groups using CloudFormation

- Elastic LoadBalancing has announced support for Weight Target Groups according to the news [release](https://aws.amazon.com/about-aws/whats-new/2019/11/application-load-balancer-simplifies-deployments-support-for-weighted-target-groups/).
- This is supported in the [CreateListener](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateListener.html) and [CreateRule](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateRule.html) API with the object [ForwardActionConfig](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_ForwardActionConfig.html) with the member `TargetGroups.member.N` > `Weight`.
- The [Action](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-defaultactions.html) object in CloudFormation currently doesn't support adding weights but only supports specifying the `TargetGroupArn`. The `Action` object needs to be extended to also support `ForwardActionConfig` property that supports specifying `TargetGroups` and `TargetGroupStickinessConfig`.

**Comment by parvez99** [comment]
Hey @vedhdi , thanks for creating this request. This is an important update that'd help reduce risks for deployments, project that I'm currently working on.

Are there any plans of implementing this soon ? Any inputs would be greatly appreciated, thanks.

**Comment by aaronkvanmeerten** [comment]
I have tested the PR and it works as expected.   +1 for getting this merged and closed!

**Comment by jdub** [comment]
This is [resolved](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-targetgrouptuple.html), isn't it?

**Comment by dogipd** [comment]
Like jdub@ pointed out, support for weighted target groups using CloudFormation is available today.

Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-listener-targetgrouptuple.html
