### ISSUE TITLE
AWS::SSM::Document - Name - No replacement Update

### ISSUE THREAD

**Issue by jk2l** [aws-cloudformation/cloudformation-coverage-roadmap#339]
Extended feature request of the new feature released 11hr ago:
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/115

Current behaviour:
- When SSM Document updated, it will trigger a replacement
- If we use hardcode Name, stack update will fail with the message "GoldenAMIAutomationDoc AWS::SSM::Document UPDATE_FAILED CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename GoldenAmiBuidler and update the stack again."

Expected behaviour:
-  Originally described in the ticket: a new version created and on the success, it should update the current version to Default.
-  For reference can also look into how AWS::SSM::Parameter or AWS::ECS::TaskDefinition is done, it will update and create a new version instead of replacing the document completely.

Currently, I have to create/manage a custom resource just to do this behaviour but maintaining the Custom resource is quite time-consuming for me and I wish I can replace my custom resource to be using native AWS resources only.

The key part of this request is we can have versioning of the AWS SSM Document that we can also reference back into.

As a use case, I have to follow a very strict security audit process (the operation team do not have security clearance to touch production environment. Everything is 100% manage by CloudFormation. or it will need to escalate to system admin that have access which can also costly to do) and the SSM Doc native implementation by CloudFormation is very badly design because it lost the versioning reference which fails auditing process.

Currently, I am using SSM for the following:
- AMI Builder
- System patches
- AWS Inspector
- Some installation and automation

Refrences:
https://docs.aws.amazon.com/cli/latest/reference/ssm/update-document.html
https://docs.aws.amazon.com/cli/latest/reference/ssm/update-document-default-version.html

**Comment by ikben** [comment]
To add to this `aws ssm update-document` (in contrast with what the name would indicate), always creates a new version for that document (even when specifying `--document-version`).

If the SSM team does not plan to support deleting old versions, CloudFromation could mimic this behaviour (and in addition set the default version).

Another approach would to implement something similar as discussed in https://github.com/aws-cloudformation/cloudformation-cli/pull/396 for ResourceProviders.

**Comment by udondan** [comment]
I don't think deleting document versions is supported by the API. You only can delete the whole document.

Also overriding a version is not possible. As you said, when updating a document, it creates a new version.

**Comment by ikben** [comment]
Like you said. It doesn't support delete or update right now. If the SSM team has plans to add delete functionality in the future (like IAM manage policies), it might be an idea to reflect that in the CloudFormation resources too

**Comment by jk2l** [comment]
delete or not doesn't really matter tbh. look at ECS task definition, you can't delete a version after create. but it work fine with cloudformation fine with hardcoded name.

using hardcoded name is quite important for working with multiple environment and team. the name itself shouldn't get change at all so it won't break other team's using my SSM document

**Comment by udondan** [comment]
I just published my custom resource to manage SSM documents. It's made for CDK but I added documentation how to use it in plain old CloudFormation as well - https://github.com/udondan/cdk-ssm-document

**Comment by bgardner-noggin** [comment]
Agreed. I'm going through this now with AWS::Config::RemediationConfiguration which uses hard coded names

The SSM documentation is lacking and so its a trial and error approach to get them working. A bug in my SSM document requires manual intervention to delete the document and recreate it

**Comment by jackdcasey** [comment]
In case anyone is also wrestling with this, my organization was planning to use the Document names in IAM to define access. We were able to get a functional workaround using custom tagging, and allowing Cloudformation to generate and apply the name. 

For example, we have Documents that define some custom attributes for session access. Here's the IAM defining that: 

```
{
 "Action": [
   "ssm:StartSession"
 ],
 "Resource": [
   "arn:aws:ssm:*:*:document/*"
 ],
 "Condition": {
   "StringEquals": {"ssm:resourceTag/CustomTag": "CustomValue"}
 },
 "Effect": "Allow"
},
```

Slightly less elegant, but seems to work well for us. Hope this may come in handy for anyone in the same spot!

**Comment by atheiman** [comment]
I have also created a custom resource for creating, updating, and deleting Systems Manager documents, and another custom resource for sharing documents. Everything needed is contained in a single CloudFormation template, and the deployment is one AWS CLI command. 

https://gist.github.com/atheiman/5d800949e82cf770baa605ca7affa164

```shell
aws cloudformation deploy \
  --template-file ssm-document-custom-resources.yml \
  --stack-name SsmDocumentCustomResources \
  --capabilities CAPABILITY_IAM
```

**Comment by kyle-kluever** [comment]
It looks like this PR may resolve this issue - https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ssm/pull/173

The documentation for AWS::SSM::Document has been updated to reflect the `UpdateMethod` property - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-document.html#cfn-ssm-document-updatemethod

**Comment by damonmaria** [comment]
I can confirm that using `updateMethod: 'NewVersion'` worked for me with the `SSM-SessionManagerRunShell` document that used to fail with posted error.

**Comment by udondan** [comment]
Yep, looking very nice. I just migrated 97 of our documents to the updated AWS::SSM::Document and tested document updates. Looking good. 👍🏼 I'm going to deprecate my custom CDK construct now.

**Comment by kyle-kluever** [comment]
> Yep, looking very nice. I just migrated 97 of our documents to the updated AWS::SSM::Document and tested document updates. Looking good. 👍🏼 I'm going to deprecate my custom CDK construct now.

I just finished converting documents to AWS::SSM::Document this morning and retired the custom resource I wrote for this.  👍

**Comment by tdmalone** [comment]
Nice! I guess this ticket should be closed to go to [Shipped](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/projects/1#column-6024500)?

**Comment by TheDanBlanco** [comment]
this appears to be resolved! if it's not the case, please re-open this with more details

**Comment by createchange** [comment]
Woo - this was such a bane for me a couple of years ago - great to see that it was resolved. Just worked wonderfully for me. Thanks to the team for implementing it.
