### ISSUE TITLE
AWS::Organizations::Policy - New Resource

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cloudformation-coverage-roadmap#34]
1. Title -> AWS::Organizations::Policy
1. Scope of request -> Create and manage a SCP inside an AWS Organization
1. Expected behavior -> A new policy is created and available to be attached to an OU
1. Test case recommendation (optional) ->
1. Links to existing API doc (optional) -> https://docs.aws.amazon.com/organizations/latest/APIReference/API_CreatePolicy.html
1. Category tag (optional) -> Organizations

**Comment by tsykora-verimatrix** [comment]
+1 we'd appreciate AWS Organization support in CloudFormation and CDK

**Comment by rhbecker** [comment]
Is this request only intended to cover SCPs, or other types of policies as well?

If all policies, than issue #841 is seemingly redundant.

**Comment by nbmha1** [comment]
Think just SCPs... Perhaps the name of this issue should be `AWS::Organizations::ServiceControlPolicy` ?  Other types of policies, such as backup policies, are quite different and might lead to a bit of a mess if they're all merged under one CFN resource

**Comment by ivan-aws** [comment]
A sample implementation using the python api for AWS CloudFormation Resource Providers can be found here: https://github.com/aws-samples/aws-cloudformation-resource-providers-organizations-policy

**Comment by erkwish** [comment]
1+ Would really like to see this

**Comment by rob-saffell** [comment]
Being able to programmatically assign resources to an OU from a CDK (so I can also maintain the benefit of using CloudFormation) and deploying my SCPs from that same CloudFormation. +1

**Comment by kddejong** [comment]
Now available: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-organizations-policy.html

**Comment by rhbecker** [comment]
Documentation of the [Type property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-organizations-policy.html#cfn-organizations-policy-type) seems to indicate this resource was implemented to cover SCPs _and_ backup policies, in which case issue #841 can seemingly also be marked as completed.
