### ISSUE TITLE
AWS::Cognito::UserPoolClient - ResourceServer

### ISSUE THREAD

**Issue by tobilg** [aws-cloudformation/cloudformation-coverage-roadmap#345]
## 1. Title 
AWS::Cognito::UserPoolClient-ResourceServer

## 2. Scope of request 
Coverage of CRUD actions on the Cognito User Pool Client's ResourceServer attribute, which is not yet available via CloudFormation

## 5. Helpful Links to speed up research and evaluation

See API methods

* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateResourceServer.html
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateResourceServer.html
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_DeleteResourceServer.html

## 6. Category
8. Security (IAM, KMS...)

**Comment by tobilg** [comment]
Custom CF resource is here: https://github.com/tobilg/cfn-cognito-resource-server

**Comment by JCai2017** [comment]
The Cognito ResourceServer resource is already supported as the "AWS::Cognito::UserPoolResourceServer" resource type.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolresourceserver.html

After creation of the resource server, the scopes on those resources are the ones that can be enabled on the userpool client which can be managed through the "AllowedOAuthScopes" property on the "AWS::Cognito::UserPoolClient" resource type.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-allowedoauthscopes
