### ISSUE TITLE
AWS::Organizations::AttachPolicy - New Resource

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cloudformation-coverage-roadmap#35]
1. Title -> AWS::Organizations::AttachPolicy
1. Scope of request -> Attaches an existing SCP Policy to an existing OU
1. Expected behavior -> An existing policy is attached to an OU.
1. Test case recommendation (optional) -> 
1. Links to existing API doc (optional) -> https://docs.aws.amazon.com/organizations/latest/APIReference/API_AttachPolicy.html
1. Category tag (optional) -> Organizations

Uses the outputs of #33 and #34 to attach a policy to an OU.

**Comment by tsykora-verimatrix** [comment]
+1 we'd appreciate AWS Organization support in CloudFormation and CDK

**Comment by ikben** [comment]
@tsykora-verimatrix 
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
("+1" or "me too" comments generate extra noise for issue followers and do not help prioritize the request)

**Comment by erkwish** [comment]
1+ Would really like to see this

**Comment by benbridts** [comment]
@erkwish 

If you react with the 👍  button to the original issue, (the first comment, click on the smiley face if you're the first reacting), your votes can be used to sort issues and determine priorities.

A comment will send a notification to everyone (participants and watchers, currently that's more than 150 people), but cannot be easily counted as a vote for an issue. Thus It's generally better to vote than to comment with "+1". To keep up to date, you can also add yourself as a watcher.

**Comment by kddejong** [comment]
you can create a policy and attach it to targets with this property:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-organizations-policy.html#cfn-organizations-policy-targetids
