### ISSUE TITLE
AWS::Events::Rule and role being passed 

### ISSUE THREAD

**Issue by ristkari** [aws-cloudformation/cloudformation-coverage-roadmap#352]
## 1. AWS::Events::Rule and roles being passed to rule targets 
This question is more related to AWS::Events::Rule resource and therefore this might not be the correct forum for this so feel free to pass it to Eventbridge team if necessary. 

It says on the documentation that AWS::Events::Rule has property called "RoleArn". Here is the description:

```
RoleArn
The Amazon Resource Name (ARN) of the role that is used for target invocation.

If you're setting an event bus in another account as the target and that account granted permission to your account through an organization instead of directly by the account ID, you must specify a RoleArn with proper permissions in the Target structure, instead of here in this parameter.
```      

This gives you indication that IAM role you pass here would effectively be used to deliver the events to targets. However I don't think this is the case. I've tried using the following:

```      
  CFNTargetRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
      -   PolicyName: "AllowLogging"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: "Allow"
                Action:
                  - 'logs:*'
                Resource: "*"
      -   PolicyName: "AllowLambdaInvoke"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: "Allow"
                Action:
                  - 'lambda:InvokeFunction'
                Resource: !GetAtt EventsFunction.Arn
```
               
without luck. Furthermore you are able to supply role also with the targets (except that Lambda, Cloudwatch at least do not support it, eventbridge on other account does and actually requires it). This is confusing but it's more up to Eventbridge team than cloudformation. However I cannot but wonder why the role passed in RoleArn doesn't work.

So the role being passed is a bit unclear. What is it actually used for? And why do target-configurations require role also? This is confusing for the user.

**Comment by benkehoe** [comment]
It looks like the RoleArn on the Rule provides a default role for all Targets, which can be overridden to give specific roles to specific targets. RoleArn is not a required property on either Rule or Target. As to why cross-account-via-Organizations requires RoleArn from Target, who knows?
