### ISSUE TITLE
AWS::Logs::LogGroup Support for regions

### ISSUE THREAD

**Issue by palsveningson** [aws-cloudformation/cloudformation-coverage-roadmap#379]
**1. Title**
AWS::Logs::LogGroup does not have support for regions

**2. Scope of request**
Today the resource-type can only create loggroup in the launch-region of the template.

**3. Expected behavior**
An optional region-parameter (preferably a list) for the resource to specify where the region or regions where the loggroup should be created. Default could be the launch-region.

**5. Helpful Links to speed up research and evaluation**
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html

**6. Category (required) - Will help with tagging and be easier to find by other users to +1**
Use the categories as displayed in the AWS Management Console (simplified):
Logs
LogGroups
Cloudwatch

**Comment by benkehoe** [comment]
In general, CloudFormation resources don't operate cross-region. Is there a reason [StackSets](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/what-is-cfnstacksets.html) don't work for the use case of creating log groups in multiple regions?

**Comment by palsveningson** [comment]
There is. I want to use the loggroups I create in the stack as a QueryLoggingConfig for som HostedZones in the same stack. Since a QueryLoggingConfig must reside in us-east-1, this is not possible without a custom resource, since I do not want to deploy anything else in that region.

So I guess the option to create the loggroup could be to "just" us-east-1.

**Comment by luiseduardocolon** [comment]
It doesn't appear that the downstream service / API allows you to create a log group in a region other than the current region, since the log group names need to be unique per region per account.  If you can find that the API natively support this, then it will be a lot easier to make this happen.

**Comment by diegosasw** [comment]
How are you guys automating this then? I'm also finding this "issue" when creating a private hosting zone (which is global) and I need to create a log group in us-east-1.

Is the execution of a cloudformation stack with `aws --region us-east-1 cloudformation create-stack` "best" workaround to have cloudformation create these hosting zone + log group resources?

**Comment by kandimallak** [comment]
> There is. I want to use the loggroups I create in the stack as a QueryLoggingConfig for some HostedZones in the same stack. Since a Route53 Loggroup must reside in us-east-1, this is not possible without a custom resource, since I do not want to deploy anything else in that region.
> 
> So I guess the option to create the loggroup could be to "just" us-east-1.

Hey @diegosasw  How did you achieve this? Were you able to create a loggroup in different region using cloudformation?
