### ISSUE TITLE
AWS::EC2::TransitGatewayPeeringAttachment - New resourcetype 

### ISSUE THREAD

**Issue by fsmed** [aws-cloudformation/cloudformation-coverage-roadmap#391]
## 2. Scope of request 
New resourcetype supported by the API.

## 3. Expected behavior

Using !Ref on this resource should return ID of the resource so it can be referred to in AWS::EC2::TransitGatewayRoute:TransitGatewayAttachmentId Property.

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTransitGatewayPeeringAttachment.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Networking & Content (VPC, Route53, API GW,...)

**Comment by jcollinpike** [comment]
Yea, this is much needed in Cloudformation. It appears the only way to do this is through the cli or API. So right now, have to do errrrrrthing else in Cloudformation, and then script it outside after the stack stands up. Sigh

**Comment by allyman17** [comment]
+1

**Comment by guidola** [comment]
For reference. Duplicated issues requesting the same:
- #556
- #544 

Any implementation of this should ideally also include acceptance/auto-acceptance of the attachment either through a new resource or included in the peering itself as that is also currently only available through a CLI/API call.
