### ISSUE TITLE
AWS::ApiGatewayV2::DomainName - Tags broken

### ISSUE THREAD

**Issue by farski** [aws-cloudformation/cloudformation-coverage-roadmap#398]
`AWS::ApiGatewayV2::DomainName` is documented as having support for [tags](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-domainname.html#cfn-apigatewayv2-domainname-tags), but when a template is deployed with tags included the resource fails with the error `Internal Failure`.

I've tried it both using the traditional way

```yaml
Tags:
  - Key: Foo
    Value: Bar
```

as well as with straight key value pairs

```yaml
Tags:
  Foo: Bar
```

The former fails validation with a type error, and the latter fails with the previously mentioned `Internal Failure`.

As an aside, the fact that most `ApiGatewayV2` resources have switched to a tagging format that's incongruous to nearly all other CloudFormation resources is needlessly annoying. It's just one of those small things that adds to the already fairly tough mental gymnastics needed to work with complex Cfn templates.

**Comment by manospasj** [comment]
Any update on this? I have the same issue with `AWS::ApiGatewayV2::Api` and `AWS::ApiGatewayV2::Stage`. I assume the same happens with all `ApiGatewayV2` resources.

**Comment by linyunxiang** [comment]
Additionally, AWS::ApiGatewayV2::DomainName should also add support for stack-level tags.
