### ISSUE TITLE
AWS::Logs::LogGroup GovCloud

### ISSUE THREAD

**Issue by bgardner-noggin** [aws-cloudformation/cloudformation-coverage-roadmap#403]
## 2. Scope of request 
Should be able to use AWS::Logs::LogGroup in GovCloud regions

## 3. Expected behavior

In GovCloud, using this resource type errors with "resource type not available"

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

5. Management (CloudTrail, Config...)

**Comment by PatMyron** [comment]
Minimal [`AWS::Logs::LogGroup`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html) template for testing:
```yaml
Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
```

**Comment by PatMyron** [comment]
@bgardner-noggin we were able to successfully create [`AWS::Logs::LogGroup`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html) in both `us-gov-east-1` or `us-gov-west-1`. Which GovCloud region(s) were you experiencing this in? Are you still experiencing this? Are you using anything to deploy your CloudFormation template that might be throwing this error before calling CloudFormation itself? Could you share template snippets to reproduce?

**Comment by bgardner-noggin** [comment]
I was using the registry to detect types.

> aws cloudformation --region us-gov-west-1 describe-type --type RESOURCE --type-name AWS::Logs::LogGroup

fails in both us-gov-west-1 and us-gov-east-1 with the message

> An error occurred (TypeNotFoundException) when calling the DescribeType operation: The Resource Type 'AWS::Logs::LogGroup' cannot be found.

I've since discovered the registry is not accurate and cannot be relied upon. eg in ap-southeast-2, the "AWS::EC2::VPCEndpointConnectionNotification" is listed as not available, yet works fine in a cloudformation template

**Comment by PatMyron** [comment]
@bgardner-noggin Ah, that makes more sense. Thanks for the details

Same underlying issue as [resource types that are missing from CloudFormation Resource Specifications](https://github.com/aws-cloudformation/cfn-python-lint/issues/1219)

This should diminish over time as resource types are migrated to natively use the [CloudFormation Registry](https://aws.amazon.com/blogs/aws/cloudformation-update-cli-third-party-resource-support-registry/). There are some resource types left still using the older framework

**Comment by cmckni3** [comment]
Ran into this issue back in December as well. `AWS::Logs::LogGroup` does not appear in the CloudFormation Registry on GovCloud but does actually work in CloudFormation templates (with caveats).

-------------

`LogGroupName` results in an invalid template error

> Template contains errors.: Invalid template resource property 'LogGroupName'

-------------

`RetentionInDays` results in an invalid template error.

> Template contains errors.: Invalid template resource property 'RetentionInDays'

-------------

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html

I have been using a custom resource since then due to these limitations.

**Comment by manoj-bandara** [comment]
I am getting errors for LogGroupName and RetentionInDelays. When can we get a fix

**Comment by rgd11** [comment]
AWS::Logs::LogGroup is missing the following properties in the GovCloud spec (https://s3.us-gov-west-1.amazonaws.com/cfn-resource-specifications-us-gov-west-1-prod/latest/CloudFormationResourceSpecification.json):
- KmsKeyId
- Tags

**Comment by jej2003** [comment]
Is there a cadence that details when these updates get pushed to GovCloud?
