### ISSUE TITLE
AWS::SSM::Parameter (detect drift)

### ISSUE THREAD

**Issue by luiseduardocolon** [aws-cloudformation/cloudformation-coverage-roadmap#407]
#### Expected behavior
 when checking for drift for this resource, indicate the change
#### Test case recommendation (optional) 
  support/test all current parameters that can be created via CloudFormation templates
#### Links to existing API doc (optional) 
 I would expect it would check via describe commands, like https://docs.aws.amazon.com/cli/latest/reference/ssm/describe-parameters.html

**Comment by PatMyron** [comment]
linking main issue: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/218
