### ISSUE TITLE
AWS::EC2::TransitGateway AmazonSideAsn doesn't match type {Integer} when using >=4200000000 (32bit ASNs)

### ISSUE THREAD

**Issue by ptaylor10** [aws-cloudformation/cloudformation-coverage-roadmap#412]
## 1. Title 
AWS::EC2::TransitGateway AmazonSideAsn doesn't match type {Integer} when using >=4200000000 (32bit ASNs)

## 2. Scope of request 
Resolve bug that breaks Cloudformation when deploying TransitGateway with a specified AmazonSideAsn using an integer 4200000000 (32bit ASNs)
.

## 3. Expected behavior
Should just build with AmazonSideAsn filled in with an integer

## 4. Suggest specific test cases
```
"CentralTransitGateway": {
   "Type": "AWS::EC2::TransitGateway",
   "Properties": {
     "AmazonSideAsn": 4200000000,
     "AutoAcceptSharedAttachments": "disable"
   }
}
```

## 5. Helpful Links to speed up research and evaluation
[https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgateway.html](url)

## 6. Category (required) -

Networking / (Compute?)

**Comment by geof2001** [comment]
This is blocking our deployment.  Seems like a really simple update when the service already supports it.

**Comment by kgangihv** [comment]
So AWS supports 5000 TGW attachments...is it a fair statement that AWS will soon be releasing a tool to manage all those route tables?  If you use a private BGP ASN, then you are capped at 1022 attachments.  I just want to know if the TGW FAQ is wrong or the Cloudformation docs?  Hmmm...

**Comment by marco48134** [comment]
We really need this coverage

**Comment by bwdbethke** [comment]
I'm hitting this error too.

**Comment by danielmacuare** [comment]
We are seeing the same behavior and this is stopping from deploying a Transit Gateway in our Production Environment.

**Comment by jdraines** [comment]
Yes, this is needed.

**Comment by robin-w-ford** [comment]
really disappointed that this isn't fixed.
Can anyone from AWS confirm ETA?
seems a simple fix to change the template validation from Integer (16bit) to long (32bit)

**Comment by geof2001** [comment]
A year later and still not supported.  This shouldn't be hard to fix.  This is really disappointing to say the least.
