### ISSUE TITLE
AWS::Inspector::AssessmentTemplate - Add the ability to configure SNS Topics to Inspector::AssessmentTemplate

### ISSUE THREAD

**Issue by rnhurt** [aws-cloudformation/cloudformation-coverage-roadmap#415]
## 1. Title 
[`AWS::Inspector::AssessmentTemplate`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-inspector-assessmenttemplate.html)

## 2. Scope of request 
AWS::Inspector::AssessmentTemplate is missing the ability to configure "SNSTopic(s)".

## 3. Expected behavior
I would expect to be able to configure the SNSTopic property in the same way as we can the RulesPackagesArns property.

## 4. Suggest specific test cases
n/a

## 5. Helpful Links to speed up research and evaluation
AWS Inspector API Reference: https://docs.aws.amazon.com/inspector/latest/APIReference/API_SubscribeToEvent.html
Reddit Mention: https://www.reddit.com/r/aws/comments/87u90c/cloudformation_awsinspectorassessmenttemplate_and/

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
Security

**Comment by txynidakis** [comment]
+1!
