### ISSUE TITLE
AWS::SSM::MaintenanceWindowTask - TaskInvocationParameters-MaintenanceWindowRunCommandParameters-CloudWatchOutputConfig

### ISSUE THREAD

**Issue by trav-c** [aws-cloudformation/cloudformation-coverage-roadmap#417]
## 1. Title
AWS::SSM::MaintenanceWindowTask-TaskInvocationParameters-MaintenanceWindowRunCommandParameters-CloudWatchOutputConfig

## 2. Scope of request 
AWS::SSM::MaintenanceWindowTask-TaskInvocationParameters-MaintenanceWindowRunCommandParameters does not support the CloudWatchOutputConfig attribute documented in the API and CLI documentation and appears to only support logging to S3, not CloudWatch.

## 3. Expected behaviour
It should be possible to create a Task that logs to CloudWatch

## 5. Helpful Links to speed up research and evaluation
* https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CloudWatchOutputConfig.html
* https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_RegisterTaskWithMaintenanceWindow.html
* https://docs.aws.amazon.com/cli/latest/reference/ssm/register-task-with-maintenance-window.html

## 6. Category
5. Management (CloudTrail, Config...)

**Comment by n1zyy** [comment]
This was a fairly surprising omission for me that cost me an afternoon and a lot of hair-pulling.

This probably seems like a corner case, until you have a number of unreliable maintenance window jobs where S3 logging won't suffice since it doesn't log things that time out. And then it's a major shortcoming. :(

**Comment by Michael1d** [comment]
And given this is available it seems from the CLI, very frustrating!

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ssm/register-task-with-maintenance-window.html
https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-rc-setting-up-cwlogs.html#sysman-rc-setting-up-cwlogs-send

**Comment by nocoli** [comment]
+1 keen on this. 

I need cloudwatch logging for my tasks and hate having to turn stuff on using CLI or through my browser as I'll forget about it when I deploy the stack to a new region

**Comment by cleorun** [comment]
+1 on this one too

**Comment by usbulat** [comment]
+1 on this

**Comment by progerjkd** [comment]
+1 on this

**Comment by 1robroos** [comment]
+1 on this

**Comment by benbridts** [comment]
@cleorun @usbulat @progerjkd @1robroos 

If you react with the 👍  button to the original issue, (the first comment, click on the smiley face if you're the first reacting), your votes can be used to sort issues and determine priorities.

A comment will send a notification to everyone (participants and watchers), but cannot be easily counted as a vote for an issue. Thus It's generally better to vote than to comment with "+1". To keep up to date, you can also add yourself as a watcher.

**Comment by benbridts** [comment]
@1robroos Can you please re-read the comment right between your two comments?

Every comment on an issue sends a notification to somewhere between 9 and 160 people (and now they got one from me too). I'd appreciate seeing fewer "+1"s in my inbox.

**Comment by zehuawan** [comment]
Hi, CloudFormation support was added for MaintenanceWindowRunCommandParameters CloudWatchOutputConfig  recently. Please check again
