### ISSUE TITLE
Index for AWS resource provider repos

### ISSUE THREAD

**Issue by benkehoe** [aws-cloudformation/cloudformation-coverage-roadmap#422]
There are a growing number of repositories for AWS provider implementions, generally by service. There should be a place to see a list of all of those repositories. Without this, it will be hard for customers to influence the design and implementation of these providers.

Here's the current list that I'm aware of:

- [ACM Private Certificate Authority](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-acmpca)
- [Application Insights](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-applicationinsights)
- [Athena](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-athena)
- [Budgets](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-budgets)
- [CloudFormation](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation)
- [CloudFormation CommandRunner](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-awsutilities-commandrunner)
- [CloudWatch Logs](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-logs)
- [CloudWatch Synthetics](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-synthetics)
- [CodeArtifact](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeartifact)
- [CodeGuru Reviewer](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codegurureviewer)
- [CodeGuru Profiler](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeguru-profiler)
- [Connect Customer Profiles](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-customer-profiles)
- [Cost Explorer](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cost-explorer)
- [Datasync](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-datasync)
- [DevOps Guru](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-devops-guru)
- [EC2 ACM Certificates](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ec2-acmcerts)
- [EC2 Carrier Gateway](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ec2-cagw)
- [EC2 Image Builder](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-imagebuilder)
- [EC2 LocalGateway](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ec2-lgw)
- [EC2 Managed Prefix Lists](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ec2-prefix-list)
- [EMR Containers](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-emrcontainers)
- [EventBridge](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-events)
- [EventBridge Schemas](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-eventschemas)
- [Fraud Detector](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-frauddetector)
- [Global Accelerator](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-globalaccelerator)
- [Glue](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-glue)
- [Glue Databrew](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-databrew)
- [IAM Access Analyzer](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-accessanalyzer)
- [AWS IoT](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-iot)
- [AWS IoT Device Advisor](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-device-advisor)
- [AWS IoT Wireless](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-iotwireless)
- [Kendra](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-kendra)
- [Kinesis Firehose](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-kinesisfirehose)
- [KMS](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-kms)
- [LicenseManager](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-licensemanager)
- [Lookout for Vision](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-lookoutvision)
- [Macie](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-macie)
- [Network Firewall](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-networkfirewall)
- [Network Insights](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ec2-ni)
- [NimbleStudio](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-nimblestudio)
- [OpsWorks CM](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-opsworkscm)
- [RDS](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds)
- [RDS Proxy](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds-proxy)
- [SageMaker](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-sagemaker)
- [SES](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ses)
- [Service Catalog](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-servicecatalog)
- [SNS](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-sns)
- [SSM](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ssm)
- [SSO](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-sso)
- [Step Functions](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-stepfunctions)
- [Timestream](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-timestream)
- [VPC Flow Logs](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ec2-flowlog)
- [WAF v2](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-wafv2)

**Comment by rjlohan** [comment]
We've assigned them all topics, so you can filter the organization repos by `aws-resources`; https://github.com/search?q=topic%3Aaws-resources+org%3Aaws-cloudformation&type=Repositories

**Comment by benkehoe** [comment]
Awesome! How will new users discover this?

**Comment by rjlohan** [comment]
We're thinking about something like https://pages.github.com/ for these sorts of docs as there's not a natural landing page in the repos itself.

**Comment by PatMyron** [comment]
I use https://github.com/aws-cloudformation?q=aws-cloudformation-resource-provider&type=public

investigating [ways](https://sourcegraph.com/batch-changes) to more easily [work with them all though](https://github.com/gruntwork-io/git-xargs). Easier if all providers were in one repo

**Comment by luiseduardocolon** [comment]
I've added the third party types to the awesomelist repo - do you guys want us to add them there for now?

**Comment by luiseduardocolon** [comment]
Following up here - do you want me to put your list in the awesomelist repo?  I can also create a separate page there too

**Comment by benkehoe** [comment]
I have updated the issue with all the current repos using @PatMyron's search method, which matches repos of the form `aws-cloudformation/aws-cloudfomration-resource-providers-*`. I should note that @rjlohan's method, repos under `aws-cloudformation` with the topic `aws-resources` already misses out ACM PCA and Event Schemas, which have no topics.

Why wouldn't this list of official CloudFormation types be in the AWS CloudFormation docs proper? Why wouldn't the repo be linked from the CloudFormation resource type reference itself?

**Comment by benkehoe** [comment]
Added 16 more repos. Still shouldn't need a customer to maintain this information.

**Comment by benkehoe** [comment]
Added 7 more repos. Still an embarrassment that a customer is maintaining this information.

**Comment by benkehoe** [comment]
Added 9 more repos. Still an embarrassment that a customer is maintaining this information.

**Comment by benkehoe** [comment]
Closing this as it now exists as a repo, hopefully well-maintained by CloudFormation: https://github.com/aws-cloudformation/resource-providers-list

**Comment by PatMyron** [comment]
automatically maintained monorepo:
https://github.com/PatMyron/cloudformation-resource-providers

Doubt that manual list will be maintained
