### ISSUE TITLE
AWS::ApiGatewayV2::ApiGatewayManagedOverrides missing from resource specification

### ISSUE THREAD

**Issue by rix0rrr** [aws-cloudformation/cloudformation-coverage-roadmap#438]
`AWS::ApiGatewayV2::ApiGatewayManagedOverrides` exists according to the docs and the release notes

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-apigatewaymanagedoverrides.html

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-cloudformation-release-notes.rss

But it is missing from the Resource Specification: 

https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

Because of this, the CDK is unaware of it and cannot generate code for it. This is blocking our customers: https://github.com/aws/aws-cdk/issues/7208

## 6. Category 

Networking & Content Delivery

**Comment by giovannidegani** [comment]
We are facing the same issue , but with AWS::ApiGatewayV2::VpcLink
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-vpclink.html

**Comment by rrrix** [comment]
Any update on this? It's still missing... These were announced on March 12th, 2020. 

83 days and counting...

**Comment by rrrix** [comment]
@luiseduardocolon @rix0rrr  sorry to bug you, but how can we get more eyes on this? This makes me worried there are lots of _other_ resources missing from the CloudFormation Resource Specification. If the Resource Specification can't be "trusted", that erodes confidence in anything that depends on it - like the CDK.

I'm still having to do weird things like this in the CDK since this issue is still unresolved:

```typescript
    this.httpApiVpcLink = new CfnResource(this, `httpapi-vpc-link`, {
      type: 'AWS::ApiGatewayV2::VpcLink',
      properties: {
        Name: 'httpApiVpcLink',
        SecurityGroupIds: [props.httpApiSecurityGroupId],
        SubnetIds: props.vpc.privateSubnets.map(sub => sub.subnetId),
      },
    });

    this.apiLbIntegration = new CfnResource(this, `httpapi-alb-integration`, {
      type: 'AWS::ApiGatewayV2::Integration',
      properties: {
        ApiId: this.httpApi.httpApiId,
        ConnectionId: this.httpApiVpcLink.ref,
        ConnectionType: 'VPC_LINK',
        Description: `${serviceEnvName} ALB Integration`,
        IntegrationType: 'HTTP_PROXY',
        IntegrationUri: props.albHttpListenerArn,
        PayloadFormatVersion: '1.0',
        IntegrationMethod: 'ANY',
      },
    });
```

**Comment by rrrix** [comment]
I did some digging and here are the only 5 missing types from the [CloudFormationResourceSpecification.json](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json) file:

```
AWS::ApiGatewayV2::ApiGatewayManagedOverrides
AWS::ApiGatewayV2::VpcLink
AWS::GroundStation::Config
AWS::GroundStation::DataflowEndpointGroup
AWS::GroundStation::MissionProfile
```
I'm not launching any satellites anytime soon... but I am creating HTTP API's 🙃

This doesn't however include missing _properties_, such as: 

* [AWS::ApiGatewayV2::Integration.ConnectionId](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-connectionid) or 
* [AWS::ApiGatewayV2::Integration.IntegrationUri](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html#cfn-apigatewayv2-integration-integrationuri)

**Comment by SmritiVashisth** [comment]
These resource specs are present in the CDK resource specification. I searched for both AWS::ApiGatewayV2::ApiGatewayManagedOverrides and 
AWS::ApiGatewayV2::VpcLink

This is not an issue with APIGW.
