### ISSUE TITLE
AWS::Cognito::UserPoolClient - Devices

### ISSUE THREAD

**Issue by brainstorm** [aws-cloudformation/cloudformation-coverage-roadmap#448]
## 1. Title
AWS::Cognito::UserPoolClient-Devices-Always/User Opt-In/No

## 2. Scope of request
Coverage of CRUD actions on the Cognito User Pool Client's "Remember Devices" attribute, which is not yet available via CloudFormation

## 5. Helpful Links to speed up research and evaluation

This is a followup on AWS CDK issue https://github.com/aws/aws-cdk/issues/7245 for Web Console's UserPool->General Settings->Devices, a.k.a:

> "Do you want to remember your user's devices?"

<img width="1257" alt="Skärmavbild 2020-04-17 kl  22 20 27" src="https://user-images.githubusercontent.com/175587/79568896-073f7500-80fa-11ea-964d-6e92fadac372.png">

**Comment by cmckni3** [comment]
Isn't this already available under `DeviceConfiguration`?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-deviceconfiguration.html#cfn-cognito-userpool-deviceconfiguration-challengerequiredonnewdevice 

## Always, MFA Yes

```
DeviceConfiguration:
  ChallengeRequiredOnNewDevice: true
```

### User Opt In, MFA No

```
DeviceConfiguration:
  DeviceOnlyRememberedOnUserPrompt: true
```

### User Opt In, MFA Yes

```
DeviceConfiguration:
  DeviceOnlyRememberedOnUserPrompt: true
  ChallengeRequiredOnNewDevice: true
```

### No

Omit `DeviceConfiguration`


This domain modeling drives me nuts (see also `AccountRecoverySetting`). Way more difficult and confusing than it should be in my opinion. Maybe Cognito team is planning for features that may/may not happen. No idea.

**Comment by bensie** [comment]
@cmckni3 Thanks for supplying all the permutations for this! Such a frustrating API.

**Comment by ayozemr** [comment]
Thanks for the help. I was looking for the "No" option

**Comment by codelogn** [comment]
Saved my cloudformation. Thank you.

**Comment by wascou** [comment]
Thanks for comfirming the solution I was about to implement..
A complementary blog post on how to use that , if required : https://aws.amazon.com/fr/blogs/mobile/tracking-and-remembering-devices-using-amazon-cognito-your-user-pools/

**Comment by timwhunt** [comment]
Thanks from the Cognito team for the feedback. We have updated our documentation to clarify the device configuration settings

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-deviceconfiguration.html
