### ISSUE TITLE
AWS::CloudTrail::Trail - IsOrganizationTrail - new property

### ISSUE THREAD

**Issue by algra** [aws-cloudformation/cloudformation-coverage-roadmap#45]
1. Title -> AWS::CloudTrail::Trail-IsOrganizationTrail
2. Scope of request -> AWS::CloudTrail::Trail does not support IsOrganizationTrail attribute.
3. Expected behavior -> It should pass parameter to API.
4. Test case recommendation (optional)
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_CreateTrail.html#awscloudtrail-CreateTrail-request-IsOrganizationTrail
6. Category tag (optional) -> Management

**Comment by cloudlogist** [comment]
+1

**Comment by mathieubrd** [comment]
Hello, any news on this?

Thank you.

**Comment by mbarneyjr** [comment]
This is implemented now: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudtrail-trail.html#cfn-cloudtrail-trail-isorganizationtrail
