### ISSUE TITLE
AWS::EC2::Volume - Tags-PropagateEC2Tags

### ISSUE THREAD

**Issue by paulramsey** [aws-cloudformation/cloudformation-coverage-roadmap#456]
Scope of request: Currently, EBS volumes created by CloudFormation for an EC2 instance are not tagged to match the EC2 instance they belong to. Customer needs the tags to be propagated for billing and cost allocation.

Expected behavior: On attachment, an EBS volume should be tagged to match the EC2 instance it is being attached to.

Category: Compute/Storage

**Comment by DanyC97** [comment]
is your use case similar to https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/133 ?

**Comment by paulramsey** [comment]
It looks similar, but the request here is to tag the EBS volumes to match the EC2 instance to which the EBS volumes are attached.

**Comment by WaelA** [comment]
A new property is added to EC2::Instance https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-propagatetagstovolumeoncreation to propagate on creation.

Hopefully, this can cover the requester use cases or some of them.

**Comment by as24-asingla** [comment]
Any idea when this will be available in CloudFormation?
