### ISSUE TITLE
AWS::Logs::SubscriptionFilter Distribution Parameter

### ISSUE THREAD

**Issue by leedhi** [aws-cloudformation/cloudformation-coverage-roadmap#462]
## 1. Title 
**AWS::Logs::SubscriptionFilter Distribution Parameter**

## 2. Scope of request 
This is a new attribute for an existing resource is desired:
Please add the "distribution" parameter so that we can evenly push data across all shards.

Samples: 

Type: AWS::Logs::SubscriptionFilter
Properties: 
  DestinationArn: String
  FilterPattern: String
  LogGroupName: String
  RoleArn: String
  Distribution: Random|ByLogStream

## 3. Expected behavior
The cloudformation stack/template will create/update the SubscriptionFilter with the desired "Distribution".

## 4. Suggest specific test cases
High volume of data into the Kinesis stream will start to backup the iterator and throw ThroughputExceeded errors until the data is evenly distributed across all shards.

## 5. Helpful Links to speed up research and evaluation
AWS CLI, boto3, etc.. already supports the distribution param.
https://docs.aws.amazon.com/cli/latest/reference/logs/put-subscription-filter.html

## 6. Category (required)
Management & Governance (CloudWatch)

**Comment by CharlenePan** [comment]
+1
