### ISSUE TITLE
AWS::ApiGatewayV2::DomainName - add support for SecurityPolicy

### ISSUE THREAD

**Issue by naydichev** [aws-cloudformation/cloudformation-coverage-roadmap#465]
## Problem

`AWS::ApiGateway::DomainName` has support for an `SecurityPolicy` field, but this is not present in `AWS::ApiGatewayV2::DomainName`

## Expected

I would like to be able to specify a TLS version for my Custom Domain, like I can do with V1.

## Docs

The current [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/apigatewayv2.html#ApiGatewayV2.Client.create_domain_name) documentation shows that this parameter is available.

There are also docs for [API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-custom-domain-tls-version.html) itself.

**Comment by SmritiVashisth** [comment]
AWS::ApiGatewayV2::DomainName supports security policy. It's present in the DomainNameConfiguration property.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigatewayv2-domainname-domainnameconfiguration.html
