### ISSUE TITLE
AWS::IoT::Policy - PolicyDocument

### ISSUE THREAD

**Issue by msiuts** [aws-cloudformation/cloudformation-coverage-roadmap#469]
## 1. Title 

AWS::IoT::Policy-PolicyDocument

## 2. Scope of request 

AWS::IoT::Policy-PolicyDocument update requires replacement today, even that the API supports adding new versions of PolicyDocument without interruption.

## 3. Expected behavior

Updating the AWS::IoT::Policy-PolicyDocument is possible without replacement.

## 4. Suggest specific test cases

Create a CFN Stack with a defined PolicyName and a PolicyDocument.
Change the PolicyDocument in the template and update the stack.
Update must complete successfully and not show an error similar to:
`CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename XXX and update the stack again.`

## 5. Helpful Links to speed up research and evaluation

Description of the API:
https://docs.aws.amazon.com/iot/latest/apireference/API_CreatePolicyVersion.html

Update documentation of AWS::IoT::Policy:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iot-policy.html#cfn-iot-policy-policydocument

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

11. Other (IoT)

## 7. Any additional context (optional)

The project where this was discovered attaches different Cognito-Identities to the IoT-Policy. The attachment is handled outside of Cloudformation dynamically with a Lambda function. Since an update of the PolicyDocument now means a replacement, all these attachments would be lost.

The workaround might be to implement a CFN Custom Resource for this case, but it would be much more convenient and also easier to understand if CFN would handle IOT-Policies similar to IAM Policies which work the same way.

**Comment by msiuts** [comment]
We now worked around this issue with a CFN Custom Resource.

Please be aware that you need to take care about cleaning up PolicyVersions, since there is a maximum of 5 allowed.

In order to do that, you can not use the `CreatedDate` since we have confirmation from the Support that the policy version creation date is always the same as the policy creation date. This was intended by design with no plans to change it.

As for what to use to determine the oldest version of a policy the IoT team mentioned that the policy version ID number is a monotonically-increasing integer that can be used to determine the last created policy version. You don’t have to worry about cases such as “01”. 

This is not mentioned yet in the documentation, so it might be useful for someone trying to implement a similar workaround.

**Comment by Morras** [comment]
@msiuts is that custom resource something that you are able to share? 
We are running into the same situation now where not being able to update the policies via CFN is a problem, especially as we get more certificates using the policies as we will need to update them if we create new policies.

**Comment by msiuts** [comment]
@Morras Feel free to use this:
https://gist.github.com/msiuts/a4943149ae7f14acbca9c72d0b66f610

We will not do a public repo on it's own, because it's embedded in another project, but I guess this will be enough for you to implement it.

**Comment by Morras** [comment]
Thanks you, that will save me some time!

**Comment by ashwinkkumar** [comment]
Cloudformation now supports updating the PolicyDocument directly without having to delete and create a new resource. A new policy version will be created on updates to the PolicyDocument.

The change is now available in all regions AWS IoT is present in.
