### ISSUE TITLE
[Create] AWS - Aurora -  Global Database 

### ISSUE THREAD

**Issue by vsriv8387** [aws-cloudformation/cloudformation-coverage-roadmap#485]
Quick Sample Summary:

Title -> AWS::Aurora::Global Database - New Resource
Scope of request -> Add support for Global Database creation
Expected behavior -> To create an Aurora Global Database
Test case recommendation (optional) ->
Links to existing API doc (optional) -> Add a new page under https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateGlobalCluster.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds.html#RDS.Client.create_global_cluster
Category tag (optional) -> Database
Any additional context (optional)

**Comment by TheDanBlanco** [comment]
i think this is satisfied by [this resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-globalcluster.html). if not, feel free to re-open
