### ISSUE TITLE
AWS::EC2::EIP - Address

### ISSUE THREAD

**Issue by chalupaa** [aws-cloudformation/cloudformation-coverage-roadmap#486]
## 1. Title
AWS::EC2::EIP-Address

## 2. Scope of request 
Support the Address property in AWS::EC2::EIP resource

## 3. Expected behavior

When Address attribute is specified, the specified address will be associated with the EIP allocation rather than a random address from the address pool.

## 4. Suggest specific test cases

When using bring-your-own-ip IPv4 addresses and you want to allocate a specific IP address to another resource (NAT Gateway, EC2 instance, or Network Load Balancer)

## 5. Helpful Links to speed up research and evaluation

AWS docs:
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AllocateAddress.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Networking & Content Delivery

**Comment by anesmashnyi-godaddy** [comment]
Could you please add the feature. It would be extremely useful for me.

**Comment by himanshs23** [comment]
This has been resolved by the EC2::EIP Resource team. Let us know if there is still an issue

**Comment by StephanR2** [comment]
Please reopen as this issue has not been resolved.

Example:

Resources:
  firewall1Byoip2:
      Type: AWS::EC2::EIP
      Properties:
        Domain: vpc
        PublicIpv4Pool: ipv4pool-ec2-xxxxxxxxxxxxxxx
        Address: 1.2.3.4

Fails with the following error: The parameter PublicIpv4Pool cannot be used with the parameter Address

**Comment by siemenroosen** [comment]
Still get the  message: "The parameter PublicIpv4Pool cannot be used with the parameter Address

But Specifying the Address without the PublicIpv4Pool works, even if the IP is in that Pool. And it maps the EIP to the Address pool automatically
