### ISSUE TITLE
AWS::SES::ConfigurationSetEventDestination - EventDestination-SNS

### ISSUE THREAD

**Issue by JoeAlamo** [aws-cloudformation/cloudformation-coverage-roadmap#50]
**1. Title**

AWS::SES::ConfigurationSetEventDestination-EventDestination-SNS

**2. Scope of request** 

You can't set up a SNS Topic as a SES Configuration Set Event Destination via CloudFormation. At the moment you can only specify CloudWatch or Kinesis Firehose.

**3. Expected behavior**

Specify an SNS Topic ARN to set that as an Event Destination. 
Ensure that you can only specify ONE event destination (CloudWatch OR Kinesis Firehose OR SNS Topic).

**4. Test case recommendation (optional)**

**5. Links to existing API doc (optional)** 

https://docs.aws.amazon.com/ses/latest/APIReference/API_DescribeConfigurationSet.html
Can use that to check what event destination if any is set up
https://docs.aws.amazon.com/ses/latest/APIReference/API_CreateConfigurationSetEventDestination.html
Create event destination association
https://docs.aws.amazon.com/ses/latest/APIReference/API_UpdateConfigurationSetEventDestination.html
Update
https://docs.aws.amazon.com/ses/latest/APIReference/API_DeleteConfigurationSetEventDestination.html
Delete

**6. Category tag (optional)**

Integration

**7. Any additional context (optional)**

None.

**Comment by ashishchandr70** [comment]
Hi - any indication on when this will be available in CDK SES?

**Comment by straygar** [comment]
@ashishchandr70 I guess as soon as it will be available in CloudFormation, which it isn't yet. I really hope that's soon. :)

**Comment by seemantk-schweitzer** [comment]
Hi, from the outside, this seems like an arbitrary omission.  Can we get some clarity on when this feature might be implemented?  This issue has been open now for almost 2 years now.

**Comment by vumdao** [comment]
Sad that this is still in roadmap 😄

**Comment by DucNHoang** [comment]
Still not supported as of today. Does anyone know if this feature is getting any attention?

**Comment by oodgaard** [comment]
Support:
AWS CLI - YES
AWS SDK - YES
Terraform - YES
AWS CDK - NO

**Comment by McDoit** [comment]
> Support: AWS CLI - YES AWS SDK - YES Terraform - YES AWS CDK - NO

Technically AWS CDK has support for it:
https://github.com/aws/aws-cdk/issues/11106#issuecomment-1012487084
Cloudformation lacks it though

**Comment by gabegorelick** [comment]
> Technically AWS CDK has support for it:

I don't think using `AwsCustomResource` counts. CloudFormation technically supports it too if you use a custom resource.

**Comment by ShanonJackson** [comment]
We're on our way to 3 years and no SES -> SNS integration support in aws-cdk. Please can we get an update on this?

**Comment by danrivett** [comment]
Wow, this is crazy, I spent ages hunting round the documentation trying to understand how to configure this in CF.

The _very least_ that could have been done is having the [CF documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-configurationseteventdestination-eventdestination.html) for `AWS::SES::ConfigurationSetEventDestination` mention in a warning at the top after it mentions SNS that configuring SNS is not supported via CloudFormation.

There is already a note at the top of the page containing:

> When you create or update an event destination, you must provide one, and only one, destination. The destination can be Amazon CloudWatch, Amazon Kinesis Firehose or Amazon Simple Notification Service (Amazon SNS).

It would be very easy to at least amend that (a warning block would be better) to say:

> When you create or update an event destination, you must provide one, and only one, destination. The destination can be Amazon CloudWatch, Amazon Kinesis Firehose or Amazon Simple Notification Service (Amazon SNS).
>
> Note:SNS Event Destinations can not currently configurable via CloudFormation, instead it can be best configured ...

That would be a reasonable stop-gap for the first few months whilst it was implemented.

**Comment by kornicameister** [comment]
Guess nobody really thought that having those events delivered over SNS makes sense :D and that's why it is so low in priority list.

**Comment by kornicameister** [comment]
Does anyone know, or maybe can just do that, how to contribute here: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ses ? Perhaps it is as simple as putting a PR there?

**Comment by royal10march** [comment]
Hey, the resource has been updated with SNS destination support, 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-configurationseteventdestination-snsdestination.html

**Comment by JoeAlamo** [comment]
Thank you! ✌
