### ISSUE TITLE
AWS::Redshift::Cluster - EnhancedVpcRouting

### ISSUE THREAD

**Issue by monken** [aws-cloudformation/cloudformation-coverage-roadmap#51]
## 2. Scope of request

new attribute for an existing resource is desired 

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateCluster.html

https://aws.amazon.com/about-aws/whats-new/2016/09/amazon-redshift-now-supports-enhanced-vpc-routing/

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

3. DB (RDS, DynamoDB...)

## 7. Any additional context (optional)

Available since September 2016 (https://aws.amazon.com/about-aws/whats-new/2016/09/amazon-redshift-now-supports-enhanced-vpc-routing/)

**Comment by sprutner** [comment]
+1 this should really be supported 3+ years later after release.

**Comment by campanellaf** [comment]
+1

**Comment by luiseduardocolon** [comment]
Yes.

**Comment by emilioego** [comment]
Yes

**Comment by campanellaf** [comment]
Are you aware of any work/progress on adding this attribute to CF templates?

**Comment by dkushari** [comment]
+1, this will be really beneficial.

**Comment by monken** [comment]
Please stop with this +1 nonsense. Add your thumbs-up to the issue instead. That's how issues are prioritized.

**Comment by shwetayakkali** [comment]
Enhanced VPC Routing is now supported for AWS::Redshift::Cluster in all regions. Customers can create/update clusters to have this support.

**Comment by mquidi86** [comment]
Was this reflected in the documentation? I can't find it here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html

**Comment by shwetayakkali** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html

I see it in the above link

**Comment by mquidi86** [comment]
Oh I see it know, might have been updated in the meantime.

Thanks!
