### ISSUE TITLE
AWS::Transfer::Server - EndpointDetails-SecurityGroups

### ISSUE THREAD

**Issue by derekmurawsky** [aws-cloudformation/cloudformation-coverage-roadmap#516]
## Title
Extend AWS::Transfer::Server-EndpointDetails to support SecurityGroups

## Scope of request 
Transfer Servers now support external endpoints with security groups. https://aws.amazon.com/about-aws/whats-new/2020/01/aws-transfer-for-sftp-supports-vpc-security-groups-and-elastic-ip-addresses/
 
The existing cloudformation transfer server resource automatically creates a VPC Endpoint with the default security group applied for access control. 

There is currently no way to manage security groups on the `VPC` endpoint type. This means manual intervention or cludgy, non-cloudformation methods to restrict the SFTP public endpoints.

Please support adding security groups other than the default.

## Expected behavior
The following code should create a transfer server with a VPC endpoint in the target VPC. The endpoint should have the security groups attached that are listed.

```json
"TransferServer": {
            "Type": "AWS::Transfer::Server",
            "Properties": {
                "EndpointDetails": {
                    "AddressAllocationIds": [ String, ... ],
                    "SubnetIds": [ String, ... ],
                    "VpcId": String,
                    "SecurityGroupIds": [ String, ... ]
                },
                "EndpointType": "VPC",
                "IdentityProviderType": "SERVICE_MANAGED",
                "LoggingRole": String,
                "Protocols": [
                    "SFTP"
                ]
            }
        }
```

### Nice to have
It would be nice to extend the `EndpointDetails` object to support the relevant suite of modifiable endpoint options from https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyVpcEndpoint.html

#### Existing API Docs
* https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateServer.html - Does not support adding security groups.
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcEndpoint.html - VPC endpoints do support managing attached security groups (see SecurityGroupId.N)

#### Current Cloudformation Docs
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-server.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-transfer-server-endpointdetails.html

**Comment by kevin-sellers** [comment]
Support for `EndpointDetails.SecurityGroups` [was added](https://github.com/awsdocs/aws-cloudformation-user-guide/commit/4c40f339a30f64ff2d33a9807bbd57b544956250#diff-fb206abb23422390ab21276a01801ab5f45b875e08afd6ab5c497b10f973c514) in October of 2020. Please [see here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-transfer-server-endpointdetails.html#cfn-transfer-server-endpointdetails-securitygroupids) for the current documentation.
