### ISSUE TITLE
AWS::EC2::TransitGateway Tags changes should not require replacement

### ISSUE THREAD

**Issue by skinsman** [aws-cloudformation/cloudformation-coverage-roadmap#531]
Simply adding a new Tag to an existing AWS::EC2::TransitGateway resource triggers an attempted replacement, whereas of course manually editing tags in the console works fine without disruption.

Expected behavior: Altering Tags definitions for a AWS::EC2::TransitGateway resource should trigger an in-place change, not replacement of the TGW.

Category:
4.  Networking & Content (VPC, Route53, API GW,...)

**Comment by LoboHacks** [comment]
How is this not fixed yet ..

**Comment by jacobsnapp** [comment]
There are other TransitGateway resources also exhibiting this behaviour

- AWS::EC2::TransitGatewayAttachment
- AWS::EC2::TransitGatewayRouteTable

We should be able to update tags without needing to recreate these resources and causing network outages.

**Comment by davidadas** [comment]
@skinsman @LoboHacks can you retry try this and see if that behavior still persists?

**Comment by jacobsnapp** [comment]
Links to https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/354

**Comment by skinsman** [comment]
> @skinsman @LoboHacks can you retry try this and see if that behavior still persists?

I've tried stack updates that modified, added and removed tags on a AWS::EC2::TransitGateway resource - all good now. The resource is modified, not replaced.  Thanks!
