### ISSUE TITLE
AWS::ECS::TaskDefinition drift detection

### ISSUE THREAD

**Issue by CFUserForBug** [aws-cloudformation/cloudformation-coverage-roadmap#535]
## Instructions for CloudFormation Coverage New Issues Template

Quick Sample Summary:
1. Title -> AWS::ECS::Task Definition-Stack level tags
2. Scope of request -> AWS::ECS::Task Definition-Stack level tags, Tagging ECS Task Definition using Stack level tags as well as Tags option give false positive. 
3. Expected behavior -> When tagging the task definition in cloudformation (via commandline), cloudformation created the tags into resources, but cloudformation drift says that the tags doesn't exists. But, the expacted behavior is, the tags should exist. 
4. Test case recommendation (optional) -> CloudFormation ECS

AWSTemplateFormatVersion: '2010-09-09'
Description: this is for test draft
Resources:
TaskDefinition:
Type: AWS::ECS::TaskDefinition
Properties:
Tags :
- Key: Mo
Value: Yousri
ContainerDefinitions:
- Name: elixir
Essential: true
Image: nginx
Command:
- /data/bin/workers foreground
Memory: 100
Environment:
- Name: APP
Value: Appv33
- Name: APP2
Value: Appv2
- Name: APP3
Value: Appv3
- Name: AWS_DEFAULT_REGION
Value: !Ref "AWS::Region"
- Name: Test
Value: Test
- Name: ENVIRONMENT_NAME
Value: Liverpool
- Name: SPARKPOST_API_KEY
Value: 3b2cce9bba7c9610aa53e563e18fe9e63

**Comment by PatMyron** [comment]
linking main issue: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/218

**Comment by kwonn** [comment]
Confirmed that this bug is fixed. Stack level and resource level tags successfully show up and don't show as drift.
