### ISSUE TITLE
Provide ability to import existing stacks into a stackset

### ISSUE THREAD

**Issue by allistera** [aws-cloudformation/cloudformation-coverage-roadmap#539]
We are currently looking into migrating our existing infrastructure stacks into stack sets for centralized management

There are a number of stacks, for example managing networking (VPCs), security groups, IAM roles.

As you can imagine we can't delete and recreate. It also seems stacksets can't import resources like normal stacks.

As a feature request, this would be awesome.

**Comment by epatrice** [comment]
Our team wants to import existing IAM roles created in many AWS accounts to our stacksets. AWS Support mentioned this is not supported. AWS Case ID 8419264281. 

It will be nice if this is supported.

**Comment by bfreiberg** [comment]
I think this feature is now available, see [recent announcement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-import.html)?

**Comment by TheDanBlanco** [comment]
so as described in the original post, this feature exists and matches the above announcement. i'm closing this issue. if you feel this is incorrect, please let us know.
