### ISSUE TITLE
 AWS::EC2::TransitGatewayAttachment - Support for TGW Peering

### ISSUE THREAD

**Issue by be-meyer** [aws-cloudformation/cloudformation-coverage-roadmap#544]
Currently the `AWS::EC2::TransitGatewayAttachment` doesn't allow to initialise a peering to a different TGW. 

## 2. Scope of the Request

Both of them is acceptable:

-  new attribute for an existing resource is desired 
-  new option for an existing attribute is desired 

## Example

One of `{VpcId, SubnetIds}` or `{PeerTgwId}` is required.

```yaml
Type: AWS::EC2::TransitGatewayAttachment
Properties: 
  SubnetIds: 
    - String?
  Tags: 
    - Tag
  TransitGatewayId: String
  VpcId: String?
  PeerTgwId: String?
```

### Sample

```yaml
Type: AWS::EC2::TransitGatewayAttachment
Properties: 
  Tags: 
    - Key: Name
      Value: MyPeeringAttachment
  TransitGatewayId: tgw-123456789
  PeerTgwId: tgw-987654321
```

#### Any particular or uncommon Delete behavior? What are the expected options?

- The peering connection need to be deleted before deletion of the transit gateway to prevent form `DELETE_FAILED	Transit Gateway tgw-xyz did not stabilize.` errors when deleting the stack.

## 5. Helpful Links to speed up research and evaluation

- CLI command to initialize a new peering attachment: https://docs.aws.amazon.com/cli/latest/reference/ec2/create-transit-gateway-peering-attachment.html

## 6. Category (required)

Networking & Content (VPC, Route53, API GW,...)

**Comment by gogonaft** [comment]
+1 for need of TGW Peering in CF

**Comment by nammireddy** [comment]
+1 for support of TGW Peering in CloudFormation

**Comment by plinioh** [comment]
+1 for support of TGW Peering in CloudFormation

**Comment by predrag044** [comment]
+1 for support of TGW Peering in CloudFormation

**Comment by ikben** [comment]
@gogonaft @nammireddy @plinioh @predrag044 
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

**Comment by BennX** [comment]
@plinioh if you are using CDK instead of CloudFormation you can use a `AwsCustomResource` as workaround to get the Attachment Id and use this to add it to the AWS Transit Gateway Route Table. This requires that you bootstrapped the cdk helper into the region of the Transit Gateway VPN Attachment.

```js
const tgw = new CfnTransitGateway(this, "tgw", {
    tags: [{key: "Name", value: "tgw-main-cloud"}],
    defaultRouteTableAssociation: "disable",
    defaultRouteTablePropagation: "disable",
    autoAcceptSharedAttachments: "enable",
});

const tgw_route_table = new CfnTransitGatewayRouteTable(
    this,
    "tgw-cloud-rt",
    {
        transitGatewayId: tgw.ref
    }
);

const cgw = new CfnCustomerGateway(this, "cgw", {
    type: "ipsec.1",
    bgpAsn: 65000,
    ipAddress: VpnServerIp.trim(),
});

const vpn = new CfnVPNConnection(this, "vpn", {
    transitGatewayId: tgw.ref,
    customerGatewayId: cgw.ref,
    type: "ipsec.1",
    staticRoutesOnly: true
});

const vpn_attachment_id = new cr.AwsCustomResource(
    this,
    "vpn_attachment_id",
    {
        onUpdate: {
            service: "EC2",
            action: "describeTransitGatewayAttachments",
            parameters: {
                Filters: [
                    {
                        Name: "resource-type",
                        Values: ["vpn"],
                    },
                    {
                        Name: "resource-id",
                        Values: [vpn.ref],
                    },
                ],
            },
            physicalResourceId: cr.PhysicalResourceId.of(Date.now().toString()), // Update physical id to always fetch the latest version
        },
        policy: cr.AwsCustomResourcePolicy.fromSdkCalls({
            resources: cr.AwsCustomResourcePolicy.ANY_RESOURCE,
        }),
        logRetention: RetentionDays.ONE_DAY
    }
);

const tgw_vpn_onprem_route = new CfnTransitGatewayRoute(
    this,
    "tgw-vpn-onprem-route",
    {
        destinationCidrBlock: onpremCidr,
        transitGatewayAttachmentId: vpn_attachment_id.getResponseField(
            "TransitGatewayAttachments.0.TransitGatewayAttachmentId"
        ),
        transitGatewayRouteTableId: tgw_route_table.ref,
    }
);
tgw_vpn_onprem_route.addDependsOn(tgw_route_table);
tgw_vpn_onprem_route.addDependsOn(vpn);
```

**Comment by felipemadeiros-Dock** [comment]
+1

**Comment by am-alisson** [comment]
+1

**Comment by VanessaDiniz** [comment]
+1

**Comment by GuiBarbetta** [comment]
+1

**Comment by brokenthumbs** [comment]
> * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
> * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

@felipemadeiros-Dock @am-alisson @GuiBarbetta

**Comment by victorlazari** [comment]
+1

**Comment by jessedye** [comment]
+1

**Comment by be-meyer** [comment]
The [AWS::EC2::TransitGatewayPeeringAttachment](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewaypeeringattachment.html) resource solves this request.

```YAML
Type: AWS::EC2::TransitGatewayPeeringAttachment
Properties: 
  PeerAccountId: String
  PeerRegion: String
  PeerTransitGatewayId: String
  Tags: 
    - Tag
  TransitGatewayId: String
```
