### ISSUE TITLE
AWS::Serverless::StateMachine

### ISSUE THREAD

**Issue by jaidisido** [aws-cloudformation/cloudformation-coverage-roadmap#549]
## 1. Title

[`AWS::Serverless::StateMachine`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html)

## 2. Scope of request 

AWS::Serverless:: transform macro supports Lambda functions today (AWS::Serverless::Function) but not State Machines (AWS::Serverless::StateMachine). It has been released through SAM but not CloudFormation:
https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-state-machine-using-sam.html

## 3. Expected behavior

Running an `aws cloudformation package` on a template containing an "AWS::Serverless-2016-10-31" transform and a [`AWS::Serverless::StateMachine`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html) resource would succeed 

## 5. Helpful Links to speed up research and evaluation

Announcement: https://aws.amazon.com/about-aws/whats-new/2020/05/aws-sam-adds-support-for-aws-step-functions/
Docs: https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-state-machine-using-sam.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

9. Integration (MQ, SQS, SNS,...)
Step Functions

**Comment by TheDanBlanco** [comment]
this seems to be working now. if it's still not working for you, please re-open this with a minimally reproducible template that gives an error
