### ISSUE TITLE
AWS::RDS::DBInstance -> Update of Allocated Storage fails in STORAGE_FULL State

### ISSUE THREAD

**Issue by abh1kg** [aws-cloudformation/cloudformation-coverage-roadmap#550]
## 2. Scope of request 
Support updating only allocated storage when RDS Instance is in STORAGE_FULL state

## 3. Expected behavior
According to this [knowledge center article](https://aws.amazon.com/premiumsupport/knowledge-center/rds-out-of-storage/), when an RDS Instance is in STORAGE_FULL State, the instance accepts only allocated storage modifications. Any modifications for other values are rejected. Updating a CloudFormation template for the RDS instance with only modification of the allocated storage should work as per the suggestion in the article.

## 4. Suggest specific test cases

-> Create a CloudFormation template with an RDS instance of engine PostgreSQL and disk allocated storage of 5GB.
-> Fill up the disk by inserting dummy data into the database and wait for the instance to show up as STORAGE_FULL
-> Modify the template to change the allocated storage to around 20GB (as per the constraints provided by AWS) and deploy the stack.

## 5. Helpful Links to speed up research and evaluation

https://aws.amazon.com/premiumsupport/knowledge-center/rds-out-of-storage/

## 6. Category 
- DB

## 7. Any additional context (optional)

Suggestion over a support ticket was to use an AWS CLI Command such as `aws rds modify-db-instance --db-instance-identifier <instance_name> --allocated_storage <new_storage_size> --apply-immediately` to update the allocated storage in case of STORAGE_FULL scenario. However, this totally defeats the purpose of CloudFormation and it's even worse because normal storage updates work but _just in the case of STORAGE_FULL_, I have to deflect from using CloudFormation.

**Comment by BenJetson** [comment]
This is still an issue. 

Disappointing that CloudFormation cannot be used to increase storage when database is already full.

At a minimum, the error message should be improved to let users know that, when instances are in the full state, they must update the DB instances manually outside of CloudFormation.

**Comment by osdrv** [comment]
The PR mentioned above was deployed globally. DBInstance handler should be able to recover the resource from `storage-full` state. Please indicate if the issue still persists.
