### ISSUE TITLE
AWS::EC2::TransitGatewayPeeringAttachment (new resource)

### ISSUE THREAD

**Issue by zloon** [aws-cloudformation/cloudformation-coverage-roadmap#556]
1. Title -> AWS::EC2::TransitGatewayPeeringAttachment (new resource)
2. Scope of request -> AWS::EC2::TransitGatewayPeeringAttachment - can create resource via API, but not via CloudFormation
3. Expected behavior -> I would like to be able to create a Transit Gatway Peering Attachments using CloudFormation.
4. Test case recommendation (optional) ->
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/cli/latest/reference/ec2/create-transit-gateway-peering-attachment.html
6. Category tag (optional) -> Networking & Content
7. Any additional context (optional) -> No.

**Comment by brianterry** [comment]
@zloon, `AWS::EC2::TransitGatewayPeeringAttachment` is now supported.

Please see our docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewaypeeringattachment.html
