### ISSUE TITLE
AWS::EC2::TransitGatewayAttachment - Ipv6Support

### ISSUE THREAD

**Issue by gregoryfranklin** [aws-cloudformation/cloudformation-coverage-roadmap#563]
## 1. Title 
AWS::EC2::TransitGatewayAttachment-Ipv6Support

## 2. Scope of request 
AWS::EC2::TransitGatewayAttachment currently creates attachments with Ipv6Support disabled without any way to enable it.

## 3. Expected behavior
Ipv6Support should be enabled by default (which is what the CreateTransitGatewayVpcAttachment API does) 

or 

there should be an option to enable it.

Note that both `Ipv6Support` and `DnsSupport` attributes are missing from CloudFormation compared to the API

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTransitGatewayVpcAttachmentRequestOptions.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

4.  Networking & Content (VPC, Route53, API GW,...)

**Comment by davidadas** [comment]
Hi @gregoryfranklin! Please confirm this option is available now and working in your region. Thank you!

**Comment by davidadas** [comment]
HI @gregoryfranklin. We've released a new resource type to help solve this issue and to enable more fine-grained controls. See here for more information: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-transitgatewayvpcattachment.html
