### ISSUE TITLE
AWS::ImageBuilder::Recipe-Properties-WorkingDirectory

### ISSUE THREAD

**Issue by cdaniluk** [aws-cloudformation/cloudformation-coverage-roadmap#565]
## Scope
AWS::ImageBuilder::Recipe-Properties-WorkingDirectory is not supported by CloudFormation:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-imagerecipe.html

## Expected Behavior
It is not clear why this field is not supported. The API itself supports it (though it is readonly after create). Not being able to set this means you cannot build a pipeline based on an image that sets `noexec` on `/tmp/`, which is a requirement for the Amazon Linux 2 CIS benchmarks.

This seems like an easy fix and that there would not be a technical reason why this is not supported.

## Category
EC2 Image Builder

**Comment by brianterry** [comment]
@cdaniluk, `WorkingDirectory ` is now supported.

Please see our docs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-imagerecipe.html#cfn-imagebuilder-imagerecipe-workingdirectory
