### ISSUE TITLE
AWS::SQS::Queue - Issue with Drift Detection and RedrivePolicy

### ISSUE THREAD

**Issue by Maycon-Santos-sm** [aws-cloudformation/cloudformation-coverage-roadmap#566]
## Instructions for CloudFormation Coverage New Issues Template

Quick Sample Summary:
1. Title -> AWS::SQS::Queue-RedrivePolicy 
2. Scope of request -> In AWS::SQS::Queue the drift detection is giving a false positive for the RedrivePolicy attribute
3. Expected behavior -> It should not detect as change when the current RedrivePolicy document matches the template setting.
4. Test case recommendation (optional) ->Simple create an AWS::SQS::Queue with RedrivePolicy
5. Links to existing API doc (optional) -> The documentation doesn't mention any limitation for this resource https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift-resource-list.html
6. Category tag (optional) -> Integration
7. Any additional context (optional)
![image](https://user-images.githubusercontent.com/61235077/88268563-f2631680-ccd2-11ea-82dc-3add2ac13357.png)

**Comment by cherylrc** [comment]
We could no longer reproduce this issue, after creating AWS::SQS::Queue with a RedrivePolicy, then run drift detection, No difference is detected for the resource. Please feel free to provide more details if you still facing this issue. thanks
