### ISSUE TITLE
AWS::EC2::Route support for DestinationPrefixListId

### ISSUE THREAD

**Issue by mikeydowntown** [aws-cloudformation/cloudformation-coverage-roadmap#572]
Looks like the CLI and SDKs supports defining a route destination as a prefix list however this is not yet implemented in CloudFormation and I see no evidence that this is planned. Is it? I see that it is implemented in the SecurityGroup resource type as property DestinationPrefixListId.

My use case is that I'm using CFN to create routes across a large number of route tables back to a common set CIDRs, targeted to new transit gateways, via multiple stacks in multiple regions and accounts. These CIDRs will eventually change so customer-managed prefix lists would be a very useful feature here but not practical for me to use if I cannot do so from my CloudFormation template, as I can do for properties such as DestinationCidrBlock.

**Comment by hugo-galindo** [comment]
We have a similar scenario ☝️ for a project. Would really appreciate **DestinationPrefixListId** Cloudformation support for AWS::EC2::Route. We have over 400 route tables to be updated and this would extremely beneficial to our automation process.

**Comment by terryrankine** [comment]
#this

**Comment by datablitz7** [comment]
This seems like an oversight. Please implement this either as a separate property (e.g DestinationPrefixListId) or as a context sensitive one under the existing DestinationCidrBlock, similar to how it works for Security Group entries, where CidrIp can handle PrefixListId, SecurityGroupId or CIDR ranges. Either way, this is a major inconsistency that needs to be addressed.

**Comment by mfang329** [comment]
Concurred.  Use Prefix lists to manage subnets are very beneficial but without the option to add it to the CFN route entry is a useless feature.  I can manually add the Prefix lists manually the route entry to go around this issue, but it defeats the purpose in terms of the CFN automation.

**Comment by tmhccpeet** [comment]
*bump*

Anything being done about this yet?

**Comment by mquidi86** [comment]
I don't understand how something like this can take 1 year or more to be addressed.

**Comment by sbwrege2z** [comment]
I have a similar need to all those expressed here.

**Comment by jtaylormayfield** [comment]
This would be very helpful for one of my client projects.

**Comment by patrickmryan** [comment]
Definitely need this feature. My template to deploy transit gateway, including all the routing, is made unnecessarily complex because I can't route to a prefix list.

**Comment by geof2001** [comment]
So disappointed that there is yet another feature without full support in CloudFormation before being launched.  Complete lack of shock that it's still not implemented over a year after it being pointed out that it's missing.

**Comment by adriantaut** [comment]
also willing to take benefit of this 💯

**Comment by julienbonastre** [comment]
If you're not using CDK  this could also apply but you'd have to bake your own customresource lambda to suit..

Otherwise those of us who use the unstoppable, incredible and amazing AWS CDK: 👌🏼😎🚀🙏🙌

The workaround right now that allows one to keep the infrastructure orchestration and resource building within the stack management and not need an external post script or similar is to use the [AWSCustomResource](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_custom-resources.AwsCustomResource.html)  and call the [JS SDK CreateRoute](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ec2/interfaces/createroutecommandinput.html) with the minimum required params (RouteTableId, DestinantionPrefixListId plus whatever the target is: gateway, endpoint, interface etc)

This is actually what the definition of the what the CustomResource exists for; to fulfil any resource provisioning etc that isn't available natively in CFN constructs. 

This is what we use and it's really very cool and effective 🔥🚀

**Comment by djessup** [comment]
Similarly, this ought to be supported by `AWS::EC2::TransitGatewayRoute` which also support creating routes to prefix lists via console and CLI.

**Comment by thenamanpatwari** [comment]
This issue is yet to be resolved and is a very frustrating experience.

**Comment by julienbonastre** [comment]
@thenamanpatwari  customresources FTW ! 🚀 😍

**Comment by elpres101** [comment]
+1 for this. Very annoying gap.

**Comment by bonzai2010** [comment]
Bumping. It doesn't make sense that we can create a PrefixList resource in CF but not use it in routes. This is a gap that should have already been resolved.

**Comment by disco-msmith** [comment]
Hi, Please address this gap.

**Comment by nwesoccer** [comment]
Any progress on this?  Seems like low hanging fruit, easy to implement and a huge benefit.

**Comment by jackhamburger** [comment]
Please implement this - I have repeatedly run into this issue

**Comment by djessup** [comment]
Chill, it's only been 3 years! Check back in 2030.

**Comment by julienbonastre** [comment]
Let's be honest, CloudFormation is for 🦖 🦕 's..

It's time to drop that pseudo-IaC rubbish and move to a **real** IaC framework..

For example: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route.html#destination_prefix_list_id

**Comment by TheDanBlanco** [comment]
great news everyone! `DestinationPrefixListId` is [available](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-route.html).
