### ISSUE TITLE
AWS::Glue::Database - DatabaseInput-Parameter missing CreateTableDefaultPermissions

### ISSUE THREAD

**Issue by rodalarcon** [aws-cloudformation/cloudformation-coverage-roadmap#576]
## 2. Scope of request 
Implement and document the CreateTableDefaultPermissions option under DatabaseInput parameter when creating a new AWS::Glue::Database resource.

## 4. Suggest specific test cases
Test setting CreateTableDefaultPermissions to [ ] then verify that the option in the Console is cleared upon resource creation, regardless of Lake Formation default settings for permissions.

#### Boto3 alternative: 
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/glue.html#Glue.Client.create_database
With boto3 we can clear default permissions by setting 
'CreateTableDefaultPermissions' = [ ]

#### API Alternative: 
https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-catalog-databases.html#aws-glue-api-catalog-databases-CreateDatabase

## 6. Category
Analytics (Athena, EMR, Glue,...)

## 7. Any additional context (optional)
When creating a Glue Database in a data lake registered with Lake Formation, currently with CloudFormation there is no way to clear the Default Permissions for Tables created under the Database resource. This creates a huge challenge, since even with Custom Resources it is not so simple to modify this option (unless we allow the underlying lambda execution role to be a Lake Formation Admin). In practice, this means with CloudFormation we cannot enforce whether we want new Tables to   contain the "IAMAllowedPrincipals" group or not, nor can we modify this behavior programmatically afterwards using Lambda functions.

**Comment by matt-theguyw1cat** [comment]
+1 this issue.  looking to operate both types of existing and new LF managed DBs side-by-side during  transition to LF.  Need full support for this option in CloudFormation so that the automation can do the right thing for 100% automated provisioning of both the old security model and the new LF model.

**Comment by 70nyIT** [comment]
totally agree, need this feature too. Otherwise it's limited in creating new databases

**Comment by farfaro** [comment]
same! i need something like this
![image](https://user-images.githubusercontent.com/41585747/124169869-20251380-da7d-11eb-9c3b-a6fa34efca08.png)

but its not supported
![image](https://user-images.githubusercontent.com/41585747/124169929-316e2000-da7d-11eb-9b41-a6d32e9d697f.png)

**Comment by pergamzn** [comment]
[CreateTableDefaultPermissions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-database-databaseinput.html#cfn-glue-database-databaseinput-createtabledefaultpermissions) has already been added to [DatabaseInput](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-database-databaseinput.html) for [AWS::Glue::Database](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-database.html) resources.
