### ISSUE TITLE
AWS::LakeFormation::Permissions - Resource missing Catalog

### ISSUE THREAD

**Issue by rodalarcon** [aws-cloudformation/cloudformation-coverage-roadmap#577]
## 2. Scope of request 
Implement and document the Catalog property of AWS::LakeFormation::Permissions-Resource

## 3. Expected behavior
CloudFormation should allow Lake Formation Admins to grant users access to edit the catalog, including Creating and Updating a Database.

## 4. Suggest specific test cases
Test adding a new Database creator, then it should be listed under the Database creator Principals. If removing the Permission, it should also remove the added principal (unless we can provide an equivalent implementation otherwise). 

#### Boto3 Alternative:
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lakeformation.html#LakeFormation.Client.grant_permissions

## 6. Category  
Analytics (Athena, EMR, Glue,...)

## 7. Any additional context (optional)
Currently with CloudFormation there is no way to modify the CreateTableDefaultPermissions under the AWS::Glue::Database-DatabaseInput Parameter. One workaround I tried to implement was using a Custom Resource, but since the underlying execution role is not registered as Database creator I could not use this approach to accomplish this goal. And since we do not have an option to grant Database creator permissions using CloudFormation, I also could not programmatically change the permissions for that execution role. Having this feature would help overcome such limitation.

**Comment by aws-austin-lee** [comment]
Thank you for bringing this to our attention.  This issue has now been fixed.
