### ISSUE TITLE
AWS::ServiceDiscovery::PrivateDnsNamespace - delete failure results in disconnected namespace

### ISSUE THREAD

**Issue by danieljamesscott** [aws-cloudformation/cloudformation-coverage-roadmap#580]
When deleting a namespace which contains a service, CloudFormation attempts to delete the namespace 3 times, and then fails to delete. However, the resource is then decoupled from the stack, causing problems when attempting to re-launch the stack containing the namespace.

**Comment by vanekjar** [comment]
The issue has been fixed and the code change has been deployed to all AWS regions. Thank you for reporting that.
