### ISSUE TITLE
AWS::CloudFront::Distribution

### ISSUE THREAD

**Issue by mmattioli** [aws-cloudformation/cloudformation-coverage-roadmap#586]
# Scope of request

If there is an issue/error when deploying a`AWS::CloudFront::Distribution` resource (e.g. the Alias or CNAME for the distribution is already deployed elsewhere) which is configured to have a Lambda@Edge function (`LambdaFunctionAssociation` within the `DefaultCacheBehavior`), the distribution fails to be created but the Lambda function is still created and cannot be deleted. It's stuck in this weird state where it cannot be deleted because it's a replicated function but the distribution it was attached to never finished creation so there's nothing to delete or disassociate the function from; it cannot be deleted without contacting support.

Someone else had a very similar issue and had to make a [forum post](https://forums.aws.amazon.com/thread.jspa?threadID=325089) for AWS support to help.

# Expected behavior

If there is an error in the stack deployment or update (such as the one described with deploying a `AWS::CloudFront::Distribution`) then the rollback should succeed without failure. I can't pinpoint exactly what's happening under the hood but if the `AWS::CloudFront::Distribution` can't be created or fails to be created then there shouldn't be an issue with rolling back and/or deleting the Lambda@Edge function (either manually or during rollback, but preferably during rollback so no manual intervention is required).

# Category tag

Networking and Content Delivery (CloudFront)

**Comment by andreialecu** [comment]
I think I just ran into something related to this. It was a plain lambda in my case. Opened AWS case #11738978921
