### ISSUE TITLE
AWS::Backup::BackupPlan CopyActionResourceType Support

### ISSUE THREAD

**Issue by jeffmarcinko** [aws-cloudformation/cloudformation-coverage-roadmap#587]
## 1. Title 
AWS::Backup::BackupPlan CopyActionResourceType

## 2. Scope of request 
The AWS::Backup::BackupPlan CopyActionResourceType is documented but unsupported by CloudFormation.  Cross-region backup copies is an important feature in support of certain data standard requirements.  It is less than desirable to manually add the Copy Action to every backup plan across all deployments in a multi-account configuration.  Please add support for this property.

## 3. Expected behavior

Samples:
## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backup-backupplan-copyactionresourcetype.html

## 6. Category 
Use the categories as displayed in the AWS Management Console (simplified):

2. Storage (S3, EFS, Backup...)

**Comment by pavbollu** [comment]
we support https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backup-backupplan-copyactionresourcetype.html

Sample template with Copy actions

---
Description: "Basic BackupPlan test"
Conditions:
IsOptInRegion: !Or
- !Equals [!Ref "AWS::Region", "me-south-1"]
- !Equals [!Ref "AWS::Region", "ap-east-1"]
- !Equals [!Ref "AWS::Region", "af-south-1"]
- !Equals [!Ref "AWS::Region", "eu-south-1"]
Mappings:
PartitionMap:
aws:
DestinationRegion: "us-west-2"
aws-cn:
DestinationRegion: "cn-north-1"
aws-us-gov:
DestinationRegion: "us-gov-west-1"

Resources:
CFNCanaryBackupPlan:
Type: "AWS::Backup::BackupPlan"
Properties:
BackupPlanTags: { "Team": "testTeam" }
BackupPlan:
BackupPlanName: "CFNLocalTestingBackupPlan"
BackupPlanRule:
-
RuleName: "TestRule"
TargetBackupVault: !ImportValue BackupPlanTestBackupVault
ScheduleExpression: "cron(0 8 ? * * *)"
-
RuleName: "CFNLocalTestingBackupPlanTestRule1"
TargetBackupVault: !ImportValue BackupPlanTestBackupVault
StartWindowMinutes: 90
CompletionWindowMinutes: 240
CopyActions: !If
- IsOptInRegion
- []
- - DestinationBackupVaultArn: {"Fn::Sub": ["arn:${AWS::Partition}:backup:${destRegion}:${AWS::AccountId}:backup-vault:Default", {"destRegion": !FindInMap [PartitionMap, !Ref "AWS::Partition", DestinationRegion]}]}
Lifecycle:
MoveToColdStorageAfterDays: 10
DeleteAfterDays: 100
Lifecycle:
DeleteAfterDays: 30
EnableContinuousBackup: true
RecoveryPointTags: { "Service1": "test1" }
ScheduleExpression: "cron(0 6 ? * * *)"
