### ISSUE TITLE
AWS::IoT::TopicRule - Action-CloudwatchLogs

### ISSUE THREAD

**Issue by tortila** [aws-cloudformation/cloudformation-coverage-roadmap#592]
## 1. Title 
AWS::IoT::TopicRule-Action-CloudwatchLogs

## 2. Scope of request 
New attribute for an existing resource is desired:
I would like CloudFormation to support CloudwatchLogs as TopicRule Action. It's already supported in the AWS console, e.g. Cloudwatch action can be added to existing topic rules, but not via CloudFormation template. The resource can also be already created via API: https://docs.aws.amazon.com/iot/latest/developerguide/cloudwatch-logs-rule-action.html

## 3. Expected behavior
Same as creation via API/console.

## 4. Suggest specific test cases
none

## 5. Helpful Links to speed up research and evaluation
API docs: https://docs.aws.amazon.com/iot/latest/developerguide/cloudwatch-logs-rule-action.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
Other (IoT, Migration, Budgets...)

**Comment by willcharlton** [comment]
Please prioritize this. Thanks!

**Comment by kddejong** [comment]
I believe this has shipped.  Can you validate this is what you are looking for?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-cloudwatchlogsaction.html

**Comment by willcharlton** [comment]
Looks like this is now available in CDK as well: https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_iot/CfnTopicRule.html#aws_cdk.aws_iot.CfnTopicRule.CloudwatchLogsActionProperty
