### ISSUE TITLE
AWS::Redshift::ScheduledAction

### ISSUE THREAD

**Issue by BrianFanning** [aws-cloudformation/cloudformation-coverage-roadmap#593]
## 2. Scope of request
 
Support the definition of Redshift scheduled actions (pause and resume) in CloudFormation
 
## 5. Helpful Links to speed up research and evaluation
 
https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateScheduledAction.html
https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-redshift-launches-pause-resume/
https://docs.aws.amazon.com/redshift/latest/mgmt/managing-cluster-operations.html#rs-mgmt-pause-resume-cluster
 
## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
 
DB (RDS, DynamoDB...)
 
## 7. Any additional context (optional)

**Comment by vrnsn** [comment]
This resource should also include "resizecluster" action. It is part of action data type as documented here: https://docs.aws.amazon.com/redshift/latest/APIReference/API_ScheduledActionType.html

**Comment by TheDanBlanco** [comment]
this appears to [exist now](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-scheduledaction.html). closing!
