### ISSUE TITLE
AWS::RDS::DBCluster apply immediately 

### ISSUE THREAD

**Issue by alikian** [aws-cloudformation/cloudformation-coverage-roadmap#597]
Updating RDS Cluster stack will effect next Maintenance window, this issues in Automatic password rotation using Secret Manager and Lambda.
1- After any update stack we may have password rotation, but in same time there will be schedule password reset due to dynamic reference at schedule at Maintenance Windows. This is like a race condition and result of that password stored in Secret Manager goes out of sync with database

Change with CLI and Console has this apply immediately but CloudFormation doesn't have this option. So I suggest to add "applyImmediately" to "AWS::RDS::DBCluster"

Example of event trigger by CloudFormation 
```
 "eventSource": "rds.amazonaws.com",
 "eventName": "ModifyDBCluster",
 "awsRegion": "us-west-2",
 "sourceIPAddress": "cloudformation.amazonaws.com",
 "userAgent": "cloudformation.amazonaws.com",
 "requestParameters": {
        "dBClusterIdentifier": "mydb-id",
        "applyImmediately": false,             <==== This option is not available in CloudFormation 
        "backupRetentionPeriod": 7,
        "dBClusterParameterGroupName": my-cluster-group",
        "port": 3306,
        "masterUserPassword": "****",
        "preferredMaintenanceWindow": "Wed:00:00-Wed:00:40",
        "enableIAMDatabaseAuthentication": true,
        "allowMajorVersionUpgrade": false
    },
```

Thanks,
Ali

**Comment by bkravchenko** [comment]
+1

**Comment by aihaddad** [comment]
+1

**Comment by ikben** [comment]
@bkravchenko @aihaddad 

If you react with the 👍  button to the original issue, (the first comment, click on the smiley face if you're the first reacting), your votes can be used to sort issues and determine priorities.

A comment will send a notification to everyone (participants and watchers), but cannot be easily counted as a vote for an issue. Thus It's generally better to vote than to comment with "+1".

**Comment by sharuzzaman** [comment]
should be available for AWS::RDS::DBInstance as well

**Comment by hummrich** [comment]
+1

**Comment by 422158** [comment]
Same for AWS::ElastiCache::ReplicationGroup

**Comment by Slooz** [comment]
> should be available for AWS::RDS::DBInstance as well

FYI CloudFormation already applies updates to `AWS::RDS::DBInstance` resources with `applyImmediately` set to `true`

**Comment by fahadjanjua-kmart** [comment]
> > should be available for AWS::RDS::DBInstance as well
> 
> FYI CloudFormation already applies updates to `AWS::RDS::DBInstance` resources with `applyImmediately` set to `true`

@Slooz can we set this to false via the cloudformation as of now?

**Comment by osdrv** [comment]
As of now, CFN applies all changes immediately: including AWS::RDS::DBInstance and AWS::RDS::DBCluster. Currently, there are no plans to expose this attribute as it would immediately conflict with the drift detector.
