### ISSUE TITLE
AWS::Events::EventBus - Tags

### ISSUE THREAD

**Issue by sshvetsov** [aws-cloudformation/cloudformation-coverage-roadmap#599]
## 2. Scope of request 

AWS::Events::EventBus-Tags can tag EventBus via API, but not via CloudFormation

## 3. Expected behavior
- in Create, should allow tagging of the EventBus based on this attribute, like API.
- in Update, modify the tags of the EventBus as per attribute value, and it shouldn't require replacement, like the API.
- removal of the attribute from template should remove tags from the EventBus resource.
- in Delete, tags should be deleted along with the resource.

## 5. Helpful Links to speed up research and evaluation

-  CreateEventBus API docs at https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_CreateEventBus.html
- TagResource API docs at https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_TagResource.html
- UntagResoruce API docs at https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_UntagResource.html

## 6. Category

Integration

**Comment by ALutchko** [comment]
Any update here? Two years already :(

**Comment by Risae** [comment]
+1!

**Comment by seanflite** [comment]
Deploying it now, you will see the new feature soon!
