### ISSUE TITLE
AWS::SSM::Document - Attachments 

### ISSUE THREAD

**Issue by san-san** [aws-cloudformation/cloudformation-coverage-roadmap#608]
**Title** 

AWS::SSM::Document-Attachments 

**Scope of request** 

AWS::SSM::Document-Attachments to allow for attachments and scripts to be added to SSM automation documents

**Expected behaviour**

"Attachments" attribute needs to be added to the AWS::SSM::Document resource type when it is created. This is currently supported when creating SSM documents via CLI and API 

The [Attachments](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateDocument.html#systemsmanager-CreateDocument-request-Attachments) attribute should be an array of [AttachmentsSource](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_AttachmentsSource.html) objects

**Use case**

When creating an SSM automation document to run packer (similar to AWS-RunPacker), the binary needs to be attached to the document via an "Attachments" attribute. Currently, this cannot be achieved using CloudFormation.

**Helpful Links**

[CreateDocument API Reference](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateDocument.html)
[AttachmentsSource object reference](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_AttachmentsSource.html)  

**Category** 

Management & Governance - Systems Manager Documents

**Comment by ikben** [comment]
This is already in the source code of the resource provider (https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ssm/blob/master/aws-ssm-document/aws-ssm-document.json#L87),
but not in the released resource (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-document.html)

**Comment by knizami** [comment]
> This is already in the source code of the resource provider (https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ssm/blob/master/aws-ssm-document/aws-ssm-document.json#L87),
> but not in the released resource (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-document.html)

Does this mean that it hasn't been released / made public yet?  I tried to use the property but it is showing as an unsupported resource.  Do we know when this change will be available to support attachments?

**Comment by s0enke** [comment]
Looks like this one is released? https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-document.html#cfn-ssm-document-attachments

**Comment by reillynoah** [comment]
Attachments is a supported property of AWS::SSM::Document: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-document.html#cfn-ssm-document-attachments

It needs to be defined as a list of [AttachmentsSource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ssm-document-attachmentssource.html) as shown here: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ssm/blob/master/aws-ssm-document/aws-ssm-document.json#L90
