### ISSUE TITLE
AWS::CloudFormation::StackSet - CustomResource

### ISSUE THREAD

**Issue by brain-is-afk** [aws-cloudformation/cloudformation-coverage-roadmap#639]
## Instructions for CloudFormation Coverage New Issues Template

I would like to be able to utilize custom resources through stack sets.  Current use-case is to embed a lambda function into a stack and then call that to perform operations not yet supported by cloudformation.  
Example 1: Toggle default ebs encryption for an account.  
Example 2: Toggle default bucket encryption for S3.  
Example 3: Perform vendor specific registration calls to APIs for integrating 3rd party platforms that use IAM Roles eg. SpotInst, PrismaCloud, DataDog etc.

 I know that config may be a better service for 1 and 2 but the goal is to show these as example operations.

## 3. Expected behavior

When deploying a stack set custom resources should execute

## 4. Suggest specific test cases
```
MyFunction
   AWS::Lambda::Function - > inline lamda function
MyResource
   AWS::CustomResource::EmbeddedLambda
      Token: !Ref MyFunction
```

## 5. Helpful Links to speed up research and evaluation

Samples:
## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

5. Management (CloudTrail, Config...)

**Comment by eduardomourar** [comment]
I believe that is the main benefit of using [resource types](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-types.html) instead of custom resources.

**Comment by brain-is-afk** [comment]
> I believe that is the main benefit of using [resource types](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-types.html) instead of custom resources.

Though I would generally agree, that this is the case for reusable within an account, there is a specific call out that says 
>"You can create resource types and make them available for use within the AWS account in which they are registered."

My particular use-case is a one time configuration that I want to be able to deploy from organizations stack sets with automatic distribution or be able to capture 'environment variables' for which I am currently leveraging scripting to drop items into parameter store and ingest from there.  All I'm saying is that there is a lot of pre-work that would be required to be done for the registration before usage for a one time use resource than it may be worth on a short script unless CloudFormation Registry for Organizations comes out first.

**Comment by ranman166** [comment]
@brain-is-afk  I believe you could do this via executing a lambda that is shared out to your target accounts. I am testing this myself soon, but you should be able to utilize a cross account function as long as the function permissions allow for it. (You may need to use lambda aliases if the size of your policy gets too large). Your function would then need to be able to assume into the target account to execute whatever you need. Roles having the correct permissions and being in place would be another requirement.

We have move towards this model of sharing out lambdas rather than deploying into each account and much prefer it.

UpdateSecurity:
    Type: Custom::ServiceControlPolicies
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:function_name:function_alias

**Comment by brain-is-afk** [comment]
> @brain-is-afk I believe you could do this via executing a lambda that is shared out to your target accounts. I am testing this myself soon, but you should be able to utilize a cross account function as long as the function permissions allow for it. (You may need to use lambda aliases if the size of your policy gets too large). Your function would then need to be able to assume into the target account to execute whatever you need. Roles having the correct permissions and being in place would be another requirement.
> 
> We have move towards this model of sharing out lambdas rather than deploying into each account and much prefer it.
> 
> UpdateSecurity:
> Type: Custom::ServiceControlPolicies
> Properties:
> ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:function_name:function_alias

If I understand what you are intending to do, this should fail.  The resource type **Custom** is not permitted.  I am able to distribute Lambda via a properly crafted S3 policy that grants permission on aws:PrincipalOrgId and use StackSets to distribute it.  The goal is to have the automagic deployment of stack sets to run a new stack and as a result, perform a custom task that is not a standard cloudformation resource.   The calling of the resource is what fails because that custom token is not permitted.  

However, after checking documentation it looks like I might be able to register a module and then call that module in the same template as a possible solution.

**Comment by ranman166** [comment]
Ah, I didn't know it failed for those resource types. Surprising as it's just cloudformation invoked within the target account. 

My mistake. I should have tried it before suggesting it. I would agree though given there is support for the cloud registry you could make a private module that does basically the same thing unless it comes with the same limitation. An odd work around, but possible.

**Comment by gergo-dryrun** [comment]
I can't see any official reply on this thread, but based on my attempts, this is working now. Can successfully create StackSets (even SERVICE_MANAGED ones) with the template containing resources such as below:

```yaml
Resources:
  SampleCRInvoke:
    Type: Custom::SampleCR
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - SampleCR
        - Arn
```

**Comment by xiwhuang** [comment]
Custom resources have been supported in StackSets, Resolving this issue. Free to reopen if we seek further assistance on this
