### ISSUE TITLE
AWS::Lightsail::*

### ISSUE THREAD

**Issue by SomayaB** [aws-cloudformation/cloudformation-coverage-roadmap#640]
## 2. Scope of request 

  new service support is desired 

Request on behalf of @zulhfreelancer, originally posted  in https://github.com/aws/aws-cdk/issues/10471

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Compute

**Comment by PatMyron** [comment]
**https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Lightsail.html**

**Comment by esamattis** [comment]
Are Lightsail containers planned?

**Comment by ammokhov** [comment]
Closing this issue since AWS CloudFormation now supports [`AWS::Lightsail::*`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Lightsail.html) resources
