### ISSUE TITLE
AWS::SecretsManager::RotationSchedule - HostedRotationLambda ExcludeCharacters

### ISSUE THREAD

**Issue by jogold** [aws-cloudformation/cloudformation-coverage-roadmap#648]
1. Title -> AWS::SecretsManager::RotationSchedule-HostedRotationLambda ExcludeCharacters
2. Scope of request -> Add a `ExcludeCharacters` property to `HostedRotationLambda`. This is currently supported when deploying the rotation function with a serverless application but not yet when using the `HostedRotationLambda` property of `AWS::SecretsManager::RotationSchedule`. If a secret is generated with a set of excluded characters it should also be possible to specify the same set for the hosted rotation function.
3. Links to existing API doc -> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-secretsmanager-rotationschedule-hostedrotationlambda.html
4. Category tag -> Security

**Comment by jogold** [comment]
@WaelA is this really shipped? I don't see the property documented here https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-secretsmanager-rotationschedule-hostedrotationlambda.html

Thx!

**Comment by avnirambhia2** [comment]
We've reviewed this request and believe it is an enhancement request. The AWS CloudFormation Public Coverage Roadmap is focused on coverage additions to existing AWS services. Specifically, it is meant to address resource coverage gaps where the service API functionality exists but does not have the equivalent support in CloudFormation. Apologies for the confusion in status - we closed this in favor of a feature request, not as a shipped feature.

**Comment by jogold** [comment]
@avnirambhia2 Thanks for the reply.

The `AWS::SecretsManager::RotationSchedule HostedRotationLambda` deploys a SAM application under the hood. This SAM application added support for excluding characters a long time ago:

![image](https://user-images.githubusercontent.com/12623249/135280636-39a412b5-b106-46cd-8f3c-141a5c7b63e9.png)

All other properties of the SAM application are exposed in this CF resource except this one... I don't understand why this request doesn't fit in here.

[AWS CDK](https://github.com/aws/aws-cdk) would greatly benefit from this. There were lots of user requesting to customize the excluded characters set when deploying a hosted rotation function. We currently have to rely on the SAM application (see https://github.com/aws/aws-cdk/blob/master/packages/%40aws-cdk/aws-secretsmanager/lib/secret-rotation.ts) instead of using a full CloudFormation solution (see note here https://github.com/aws/aws-cdk/commit/2cb8e22221b266b90b3a0b6c198a0da6ff4e3b8a).

**Comment by avnirambhia2** [comment]
Thank you for this additional insight. We do recognize this can be useful, and have added it to our roadmap. However, we are tracking this as an enhancement request, rather than a bug fix.

**Comment by jogold** [comment]
> Thank you for this additional insight. We do recognize this can be useful, and have added it to our roadmap. However, we are tracking this as an enhancement request, rather than a bug fix.

Thanks. Are you reopening the issue then?
