### ISSUE TITLE
AWS::ECS::Service - PlacementStrategies 

### ISSUE THREAD

**Issue by belangovan** [aws-cloudformation/cloudformation-coverage-roadmap#651]
## 2. Scope of request 
As we need to update the cloud formation update policy to No interruption as AWS SDK ( > 2.640.0 ) adds the ability to update the task placement strategy and constraints for Amazon ECS services. currently, service resource needs replacement.
AWS::ECS::Service-PlacementStrategies  -- Update requires: Replacement >> Update requires: No interruption
#### in Update, 
change AWS::ECS::Service - PlacementStrategies, and it shouldn't require replacement, like the API. Should it require UpdateReplacePolicy? [aws sdk ](https://github.com/aws/aws-sdk-js/blob/master/CHANGELOG.md#26400)

#### Common use case: 
update  AWS::ECS::Service - PlacementStrategies should replace existing service resource.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
 1. Compute ( ECS )

**Comment by AbhishekNautiyal** [comment]
Updating PlacementStrategies and PlacementConstraints no longer requires replacement.  CFn docs are updated now: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-placementconstraints
