### ISSUE TITLE
AWS::CodeDeploy::DeploymentConfig for Lambda

### ISSUE THREAD

**Issue by jonnekaunisto** [aws-cloudformation/cloudformation-coverage-roadmap#653]
## Scope of request

AWS::CodeDeploy::DeploymentConfig currently supports only creating a config for an EC2 deployment group. However it does not support creating one for Lambda/ECS.

This can also been seen in the CDK packages.

You can see here how CDK doesn't have a way to create a deployment preference for Lambda: https://github.com/aws/aws-cdk/blob/v1.67.0/packages/@aws-cdk/aws-codedeploy/lib/lambda/deployment-config.ts#L64

But here it exists for EC2: https://github.com/aws/aws-cdk/blob/v1.67.0/packages/@aws-cdk/aws-codedeploy/lib/server/deployment-config.ts#L109

## Expected behavior

AWS::CodeDeploy::DeploymentConfig should include an option to create a new DeploymentConfig for Lambda/ECS. Possibly by including a fields for DeploymentType, Step and Interval

## Links to existing API doc

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-deploymentconfig.html

## Category

Compute

**Comment by ajyuan** [comment]
LGTM

**Comment by xaoyuli** [comment]
https://github.com/aws/aws-cdk/blob/main/packages/@aws-cdk/aws-codedeploy/lib/lambda/deployment-config.ts 
https://github.com/aws/aws-cdk/blob/main/packages/%40aws-cdk/aws-codedeploy/lib/ecs/deployment-config.ts
Cdk already support the Lambda and ECS now
