### ISSUE TITLE
AWS::IoT::TopicRule - Action-Timestream

### ISSUE THREAD

**Issue by kennu** [aws-cloudformation/cloudformation-coverage-roadmap#663]
The AWS IoT TopicRule [Action](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-action.html) property is missing support for [Timestream](https://docs.aws.amazon.com/iot/latest/developerguide/timestream-rule-action.html) delivery actions.

I think the implementation is pretty self-explanatory and looks like all the other Actions. Syntax is documented in the [AWS IoT Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/timestream-rule-action.html). Here is an example from the documentation.

```
{
  "topicRulePayload": {
    "sql": "SELECT * FROM 'iot/topic'",
    "ruleDisabled": false,
    "awsIotSqlVersion": "2016-03-23",
    "actions": [
      {
        "timestream": {
          "roleArn": "arn:aws:iam::123456789012:role/aws_iot_timestream",
          "tableName": "devices_metrics",
          "dimensions": [
            {
              "name": "device_id",
              "value": "${clientId()}"
            },
            {
              "name": "device_firmware_sku",
              "value": "My Static Metadata"
            }
          ],
          "databaseName": "record_devices"
        }
      }
    ]
  }
}
```

**Comment by colinw-smartrg** [comment]
Is this on the roadmap ?
Timestream is very useful for IoT seems a shame to not be able to use cloudformation to deploy IoT.

**Comment by kddejong** [comment]
I believe this is released.  Can you validate that this is what you are looking for.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-iot-topicrule-timestreamaction.html

**Comment by colinw-smartrg** [comment]
Hmm, it doesn't seem to reject the Timestream Action any longer, but fails with the TableName when deploying.
Error Message:
Resource handler returned message: "Invalid table name 'RGThingStats|StatsTable-n1fOd4vN3Yt9'. Must satisfy pattern: [a-zA-Z0-9_.-]+.

Seems like the TableName: !Ref StatsTable  is being interpreted as <DatabaseName>|<TableName>.
Obviously the | is illegal and I don't think the DatabaseName is wanted here.
Naming StatsTable Replacing !Ref StatsTable with the string of the Name works.

My template includes this
  StatsTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
         RuleDisabled: false
         Sql: SELECT * FROM '$aws/things/+/stats/+'
         Actions:
         - Timestream:
             DatabaseName: !Ref StatsDB
             Dimensions:
             - Name: device
               Value: ${topic(3)}
             - Name: topic
               Value: ${topic(5)}
             RoleArn: !GetAtt StatsRole.Arn
             TableName: !Ref StatsTable

       
 But

**Comment by praneetap** [comment]
@colinw-smartrg We have updated the example with `AWS::IoT::TopicRule`. Please take a look at how the DB name is being input [here](https://github.com/awslabs/amazon-timestream-tools/blob/master/integrations/iot_core/cfn-iot-rule-to-timestream.json#L33)
hope this helps!
