### ISSUE TITLE
AWS::Pinpoint::App

### ISSUE THREAD

**Issue by civilizeddev** [aws-cloudformation/cloudformation-coverage-roadmap#666]
## 2. Scope of request 

- All `AWS::Pinpoint::*` resource types are only available in [us-east-1](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/registry/resourceTypes)
- I can't create these resources via CloudFormation.

    ```
    Template format error: Unrecognized resource types: [AWS::Pinpoint::App]
    ```

## 3. Expected behavior

All `AWS::Pinpoint::*` resource types should be available across all regions.

## 4. Suggest specific test cases

N/A

## 5. Helpful Links to speed up research and evaluation

- [CloudFormation Resource Registry](https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/registry/resourceTypes)
- [Pinpoint resource type reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Pinpoint.html)

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

- Analytics
- Customer Engagement

**Comment by luxingyAtAmazon** [comment]
This issue has been resolved and now Pinpoint resources can be created via CloudFormation in all Pinpoint available regions.
