### ISSUE TITLE
AWS::RDS::DBInstance - SourceDBInstanceIdentifier (no way to promote replica)

### ISSUE THREAD

**Issue by jdub** [aws-cloudformation/cloudformation-coverage-roadmap#67]
1. Title -> AWS::RDS::DBInstance-SourceDBInstanceIdentifier (no way to promote replica)
1. Scope of request -> removing SourceDBInstanceIdentifier from an existing replica instance currently replaces the replica with a completely fresh database instance as if the property was never added
1. Expected behaviour -> there should be a way to promote the read replica
1. Test case recommendation
1. Links to existing API doc
1. Category tag -> database
1. Any additional context

It's reasonable that "remove SourceDBInstanceIdentifier from replica = promote" is not the correct solution, because the outcome after stack creation and update is entirely different from what was expressed in the config.

Perhaps another property would be appropriate… a hypothetical PromoteToMaster=true would allow users to promote. Additionally, if defined prior to instance creation, it could promote immediately after the replica is created, which might be handy?

**Comment by alexbarnes** [comment]
Another vote for this one. When you have an RDS instance/cluster managed by Cloud Formation as part of a DR solution it would be helpful if you could promote the Cloud Formation managed instance without losing all the data you've been replicating.

I'm not sure of the exact use case for the current behavior, especially when there is no option for Retain for the existing read replica.

**Comment by btsteve** [comment]
This would also be great to have since we are being forces to migrate from mysql 56 to aurora.
