### ISSUE TITLE
AWS::LakeFormation::Permissions - UpdateReplacePolicy not working for AWS::LakeFormation::Permissions

### ISSUE THREAD

**Issue by rodalarcon** [aws-cloudformation/cloudformation-coverage-roadmap#670]
## 2. Scope of request 
Currently testing a CloudFormation Stack where, among other things, I'm granting LakeFormation permissions to an IAM Role on a given Table. The IAM Role is created as part of the stack, the table name is provided via CFN Parameters (existing resource).
If I attempt to update the Stack changing the table name, but maintaining the IAM Role, the Stack will create a new LakeFormation permission, but it will retain the existing permission instead of revoking it. I tried forcing the UpdateReplacePolicy for the resource on CFN to "Delete", but got the same behavior. 
The main problem of this behavior is that, if I then delete the stack, it will delete the IAM policy and the "updated" LakeFormation permission, but the original LakeFormation permission will remain on the list. And since the IAM role no longer exists, the AWS console will not let me revoke the permission (bug on the console side), so I'm forced to revoke the permission using CLI/SDK.

## 3. Expected behavior
In Update, if UpdateReplacePolicy is set to DELETE, create a new LakeFormation Permission granting permissions for the new Table **and revoke the previously granted LakeFormation permission**.

## 4. Suggest specific test cases
Create a new stack granting a LakeFormation Permission to an existing table, with UpdateReplacePolicy set to DELETE. Pass the Table name as a parameter. Then update the stack passing a different Table name. The stack should create a new permission, then delete (revoke) the previous permission.

## 5. Helpful Links to speed up research and evaluation
Here's the CloudFormation Stack I've been using for my tests. It receives a Tabla Name, DB Name and IAM Role, and creates an S3 Access Point associated to the Table location. In this context, LakeFormation is used to grant access to the Lambda Execution Role used to retrieve the S3 location for a given Table:
[CloudFormation Template](https://lakeformation-crossaccount.s3.amazonaws.com/S3AccessPointFromTable.yaml)

**Comment by aws-austin-lee** [comment]
Thank you for bringing this to our attention.  This issue has now been fixed.
