### ISSUE TITLE
AWS::Elasticsearch::Domain - AdvancedSecurityOptions-SAMLOptions

### ISSUE THREAD

**Issue by jsmyczek** [aws-cloudformation/cloudformation-coverage-roadmap#672]
## 2. Scope of request 

AWS::Elasticsearch::Domain-AdvancedSecurityOptions support for newly released `SAMLOptions`.

## 3. Expected behavior

Able to utilize `SAMLOptions` element to configure SAML authentication for Kibana.

## 5. Helpful Links to speed up research and evaluation

Updated API docs at https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-datatypes-advancedsec

Updated CLI docs at https://docs.aws.amazon.com/cli/latest/reference/es/create-elasticsearch-domain.html (under --advanced-security-options)

## 6. Category

Analytics

**Comment by mohdemraan** [comment]
Any ETA?

**Comment by aruandre** [comment]
shipped where?
no mention of it in the docs https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opensearchservice-domain-advancedsecurityoptionsinput.html

**Comment by lvthillo** [comment]
I can't find it either. I was hoping it would be available in the "new" OpenSearch domain: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opensearchservice-domain-advancedsecurityoptionsinput.html

**Comment by twixr** [comment]
Just started migrating my existing dev OpenSearch instance which I configured in the console to CDK. 
Unfortunately there is no way to enable SAML for AWS SSO from CDK or CloudFormation :(

**Comment by mik3fly** [comment]
Any news here?

**Comment by twixr** [comment]
@mik3fly 

My workaround was to run an extra script once after deploying the OpenSearch resource using Cloudformation (CDK):

```
// SAML configuration is not available for CloudFormation / CDK yet,
// so we have to run an additional script that will configure SAML on our OpenSearch instances

import { UpdateDomainConfigCommand, OpenSearchClient } from '@aws-sdk/client-opensearch';
import fetch from 'node-fetch';

(async () => {
  const [_node, _path, domainName, idpKey, region] = process.argv;

  if (!domainName) {
    throw new Error('Missing domainName argument');
  }

  if (!idpKey) {
    throw new Error('Missing idpKey argument');
  }

  const client = new OpenSearchClient({ region: region || 'eu-central-1' });

  const samlMetadataUrl = `https://portal.sso.eu-central-1.amazonaws.com/saml/metadata/${idpKey}`;
  const samlMetadataResponse = await fetch(samlMetadataUrl);
  const samlMetadataContent = await samlMetadataResponse.text();

  await client.send(new UpdateDomainConfigCommand({
    DomainName: domainName,
    AdvancedSecurityOptions: {
      SAMLOptions: {
        Enabled: true,
        Idp: {
          MetadataContent: samlMetadataContent,
          EntityId: `https://portal.sso.eu-central-1.amazonaws.com/saml/assertion/${idpKey}`
        },
        RolesKey: 'Groups',
        SessionTimeoutMinutes: 120,
        MasterBackendRole: '{Master Backend Role}' // SSO Admin group
      }
    }
  }));
})();

```

You only have to change the `MasterBackendRole` and run it according to the README below:


## Configure SAML

SAML configuration is currently not yet supported by CloudFormation / CDK, so we have to use the aws-cdk to configure SAML for OpenSearch instances.  
This is a one time setup operation which we need to run manually.  
You can run this manually from your local machine after creating a new OpenSearch instance using the following command:

```
npx ts-node ./scripts/configure-saml.ts {domainName} {idpKey}
```

`domainName` is the OpenSearch instance name, which is located under "General information" -> "Name"  
`idpKey` is the key for the identity provider configured in the AWS root account.  
`region` (optional) the AWS region for the OpenSearch Instance. Defaults to `eu-central-1`

The IDP can be configured in IAM Identity Center by creating a new Aplication.  
When clicking on [Actions] -> "Edit configuration" you can see the "IAM Identity Center metadata" fields.  
All URLs end with the same key, that is the `idpKey` that you need to provide.
