### ISSUE TITLE
AWS::Elasticsearch::Domain DomainEndpointOptions CustomEndpoint

### ISSUE THREAD

**Issue by mohdemraan** [aws-cloudformation/cloudformation-coverage-roadmap#678]
Scope of request
There is no CloudFormation support for AWS::Elasticsearch::Domain DomainEndpointOptions CustomEndpointEnabled
There is no CloudFormation support for AWS::Elasticsearch::Domain DomainEndpointOptions CustomEndpoint
There is no CloudFormation support for AWS::Elasticsearch::Domain DomainEndpointOptions CustomEndpointCertificateArn

Recently this was introduced but not with CloudFormation support.
https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-elasticsearch-service-now-supports-defining-a-custom-name-for-your-domain-endpoint/

Expected behavior
CloudFormation support should have parity with what can be done in the AWS CLI:

https://docs.aws.amazon.com/cli/latest/reference/es/create-elasticsearch-domain.html

**Comment by yosefbs** [comment]
Looks like it has already been implemented:

[https://docs.aws.amazon.com/cdk/api/v1/docs/aws-opensearchservice-readme.html#:~:text=Custom%20endpoint,custom%20domain%20name.](cdk docs)

**Comment by mohdemraan** [comment]
Yes, it is implemented and I have started using it also. This issue can be closed now.
