### ISSUE TITLE
AWS::SNS::Topic - TopicName-CloudFormation autogenerated name for FIFO topics

### ISSUE THREAD

**Issue by grauj-aws** [aws-cloudformation/cloudformation-coverage-roadmap#681]
## 1. Title 
AWS::SNS::Topic-TopicName

## 2. Scope of request 

- When creating a FIFO topic by using the `AWS::SNS::Topic` resource, if the  `TopicName` property is not defined, CloudFormation will autogenerate a name for the resource
- However, the autogenerated name will not have the ".fifo" extension, causing the Topic creation to fail with an `Invalid parameter: Topic Name` message
- As noted on the [SNS CreateTopic definition](https://docs.aws.amazon.com/sns/latest/api/API_CreateTopic.html):
> For a FIFO (first-in-first-out) topic, the name must end with the .fifo suffix.

## 3. Expected behavior

- It's expected that CloudFormation will generate valid names for the resources defined on the template, when those are not specified.
- On this case, CloudFormation should ensure that the autogenerated FIFO topic names have the ".fifo" sufix appended to them

## 4. Suggest specific test cases

- Issue can be reproduced with the following template definition:
```
Resources:
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      ContentBasedDeduplication: false
      FifoTopic: true
```

## 5. Helpful Links to speed up research and evaluation

- [AWS::SNS::Topic documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html#cfn-sns-topic-topicname)
- [SNS CreateTopic API action definition](https://docs.aws.amazon.com/sns/latest/api/API_CreateTopic.html)

## 6. Category

9. Integration (MQ, SQS, SNS,...)

**Comment by rrhodes** [comment]
Any updates or indication when this will be resolved? It's impacting customers using FIFO topics in the CDK too.

**Comment by yangmarc** [comment]
Hi @rrhodes we will start migrating SNS resources to self service. Once we are migrated, the issue should be resolved. The estimated timeline is the end of Q1. Thanks

**Comment by yangmarc** [comment]
SNS Resources are now live in Github. https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-sns.  The fix is addressed in repository. We are still  in the process of migrating SNS resources to self service. In the meanwhile, you can download the code and deploy it in your own AWS account as a private registry. Cheers

**Comment by BryanCrotaz** [comment]
> Hi @rrhodes we will start migrating SNS resources to self service. Once we are migrated, the issue should be resolved. The estimated timeline is the end of Q1. Thanks

We're now at the end of Q2 and I just hit this. Any news?

**Comment by shih** [comment]
This issue should have been resolved here: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-sns/blob/0bd083cd959ec3a2d67819793262030745efea0b/aws-sns-topic/src/main/java/software/amazon/sns/topic/CreateHandler.java#L33-L36
