### ISSUE TITLE
AWS::DLM::LifecyclePolicy - Tag support

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cloudformation-coverage-roadmap#682]
## 1. Title 
In the format AWS::Service::Resource-Attribute-Existing Attribute) 

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/dlm/latest/APIReference/API_CreateLifecyclePolicy.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Storage (S3, EFS, Backup...)

**Comment by mandy-qi** [comment]
Thanks for bring this to our attention kddejong! Applying tags to Amazon Data Lifecycle Manager policies is now supported through CloudFormation.
For more information, please visit our documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dlm-lifecyclepolicy.html#cfn-dlm-lifecyclepolicy-tags

Please don't hesitate to let us know if you have any other questions/comments.
