### ISSUE TITLE
AWS::CloudFront::Distribution - CacheBehavior-TrustedKeyGroups

### ISSUE THREAD

**Issue by ctd** [aws-cloudformation/cloudformation-coverage-roadmap#686]
## Scope of request 

AWS::CloudFront::Distribution-CacheBehavior does not support the [TrustedKeyGroups attribute](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CacheBehavior.html#cloudfront-Type-CacheBehavior-TrustedKeyGroups) that's in the underlying the CloudFront API.

Amazon CloudFront [launched the key groups feature](https://aws.amazon.com/about-aws/whats-new/2020/10/cloudfront-iam-signed-url/) on Oct 22, 2020.

The key groups feature would also be best supported by additional resource types to manage the key groups themselves, I will create a separate issue for this (#687). This issue is specifically for specifying existing key groups in a distribution configuration. 

## Expected behavior

The behaviours should be the same as for the existing `TrustedSigners` attribute, but affecting the `TrustedKeyGroups` attribute in the CloudFront Distribution Configuration.

On Create and Update, it should include the `TrustedKeyGroups` attribute values in the DistributionConfig that is sent to the CloudFront service.

Ideally, the [Quantity attribute](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_TrustedKeyGroups.html#cloudfront-Type-TrustedKeyGroups-Quantity) is calculated by the CloudFormation resource.

## Suggest specific test cases

The behaviours (and tests) should be the same as for the existing `TrustedSigners` attribute.

## Helpful Links to speed up research and evaluation

- [Feature announcement](https://aws.amazon.com/about-aws/whats-new/2020/10/cloudfront-iam-signed-url/)
- [API Documentation](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CacheBehavior.html#cloudfront-Type-CacheBehavior-TrustedKeyGroups)
- [Documentation of existing TrustedSigners CloudFormation attribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-cachebehavior.html#cfn-cloudfront-distribution-cachebehavior-trustedsigners)
- [An equivalent request for the Terraform provider](https://github.com/hashicorp/terraform-provider-aws/issues/15912)

## Category

Networking & Content (CloudFront)

**Comment by bbalka** [comment]
@ctd  CacheBehavior Supports TrustedKeyGroups attribute

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-cachebehavior.html#cfn-cloudfront-distribution-cachebehavior-trustedkeygroups

Please let me know, what we are missing?

**Comment by ctd** [comment]
It looks like that was added after this issue was created. I'm not actively working on anything that would use this type but it looks like what I recall needing, so I think this can be resolved.
