### ISSUE TITLE
AWS::DocDB::DBCluster - AWS::DocDB::* in sa-east-1

### ISSUE THREAD

**Issue by rescbr** [aws-cloudformation/cloudformation-coverage-roadmap#697]
AWS::DocDB service resources are not recognized by CloudFormation in sa-east-1 region. Service was launched in this region in Nov 20.

**Steps to reproduce:**
1. Run the following AWS CLI command that deploys the sample DocumentDB stack:

`aws cloudformation create-stack --region sa-east-1 --stack-name test-docdb --template-url https://s3.amazonaws.com/amazon-documentdb-samples/v1/cloudformation-templates/documentdb_full_stack.yaml --parameters '[{ "ParameterKey": "DBInstanceClass", "ParameterValue": "db.t3.medium", "UsePreviousValue": false }, { "ParameterKey": "MasterUser", "ParameterValue": "docdb", "UsePreviousValue": false }, { "ParameterKey": "MasterPassword", "ParameterValue": "***********", "UsePreviousValue": false }]'`

**Result:**
`An error occurred (ValidationError) when calling the CreateStack operation: Template format error: Unrecognized resource types: [AWS::DocDB::DBCluster, AWS::DocDB::DBInstance]`

**Expected Result:**
Deployment of a DocumentDB cluster in sa-east-1 region.

**Comment by mllevyha** [comment]
This has been fixed most likely a while ago. I just tested the command you posted and it works as expected now. Thanks for opening the ticket.
