### ISSUE TITLE
AWS::EC2::Volume - Throughput

### ISSUE THREAD

**Issue by sturdiva** [aws-cloudformation/cloudformation-coverage-roadmap#710]
## 2. Scope of request 

EC2 `CreateVolume` now supports the `Throughput` parameter for `gp3` volume types. CloudFormation needs support for this as well. This allows setting the available throughput for a volume independent of volume size of volume IOPS. 

## 5. Helpful Links to speed up research and evaluation

Samples:
## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. Compute

**Comment by tmokmss** [comment]
Shouldn't this issue be closed? It seems it's already been supported. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html#cfn-ec2-ebs-volume-throughput

**Comment by wimsymons** [comment]
@tmokmss No, because it is not supported here : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-blockdev-template.html
