### ISSUE TITLE
AWS::Connect::Instance

### ISSUE THREAD

**Issue by rectalogic** [aws-cloudformation/cloudformation-coverage-roadmap#718]
Add support for Amazon Connect instances, contact flows etc.
API docs https://docs.aws.amazon.com/connect/latest/APIReference/API_Operations.html

Category: Customer Engagement

**Comment by scrthq** [comment]
Currently working on building Connect support out entirely as custom resources right now due to business need, this would be a dream to have natively supported!

**Comment by WaelA** [comment]
Does recent connect announcements fix this issue https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Connect.html?

**Comment by rectalogic** [comment]
Hmm, I don't really see the use case for adding Contact Flow support to CFN. Flows are full of instance specific ARNs so any stack containing a flow could only be used with one specific instance, there would be no way to deploy both a staging and production stack. You need to build an ARN<->ARN mapping and rewrite the flows to use them in another instance. Also flows are authored in a visual environment, so once you author it you would need to then adopt it into CFN I guess? I don't really see how that addition is useful.

I would like to see CFN support for the instance itself (and configuring approved origins, associating lambdas, kinesis, storage etc.), Queues, Routing Profiles etc.

**Comment by TheDanBlanco** [comment]
looks like cloudformation support for connect was updated to include the resources requested above (instances, queues, routing profiles).
