### ISSUE TITLE
AWS::RDS::DBInstance - Scheduling modifications on RDS Instance/Cluster bug 

### ISSUE THREAD

**Issue by dhruvdakoria** [aws-cloudformation/cloudformation-coverage-roadmap#726]
Noticing inconsistent behavior when modifying RDS instance/cluster. Attribute like IAM Database Authentication gets applied on next scheduled maintenance window whereas all other changes like backup window modification, backup retention modification, instance size/settings update, maintenance window updates etc. get applied immediately.

The console provides with an option to apply this changes either immediately or during the next maintenance window. There is no such option when doing modifications/updates with CFN. Please implement this ability to apply modifications (either immediately or next maintenance window).

![101514972-d7c0cf80-394b-11eb-87d5-e7e597992e3d](https://user-images.githubusercontent.com/24723459/102819287-31d88080-43a1-11eb-989b-502839eba749.png)

**Comment by moataz-mhmd** [comment]
I verified that behavior is no longer exist and `EnableIAMDatabaseAuthentication` is always applied immediately for DBInstance and DBCluster resources. If you are still facing this behavior please do not hesitate to reach out [AWS Customer Support](https://aws.amazon.com/contact-us/).

**Comment by LosD** [comment]
@moataz-mhmd It seems the @dhruvdakoria's request is twofold (please correct me if I'm wrong, @dhruvdakoria): Both the inconsistency (which is now fixed), but also a general feature request to be able to choose if changes should apply immediately, or defer until next maintenance window like in the RDS console. That would be an extremely nice feature.

**Comment by moataz-mhmd** [comment]
@LosD CloudFormation platform can not deal with deferred/postponed changes specially if resource has dependent resources on it. Dependent resources updates are triggered once main resource is updated. Dependent resources are expecting main resource to be in sync. This is platform limitation. I opened a feature request to CFN here: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1535

**Comment by xaoyuli** [comment]
Closed this issue, since this is current a platform limit. For the future request implement, please tracking at https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1535
