### ISSUE TITLE
AWS::ECR::Repository - ReplicationSettings

### ISSUE THREAD

**Issue by thenadz** [aws-cloudformation/cloudformation-coverage-roadmap#731]
## 1. Title 
AWS::ECR::Repository-ReplicationSettings

## 2. Scope of request 
Add support for new repositiory cross-region/account replication settings

## 3. Expected behavior

Console provides configuration for replication settings for cross-region and cross-account replication. This new attribute should expose same configuration, including describing target of replication and any other relevant parameters.

## 4. Suggest specific test cases

N/A

## 5. Helpful Links to speed up research and evaluation

Blog post: https://aws.amazon.com/blogs/containers/cross-region-replication-in-amazon-ecr-has-landed/

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

1. Compute (EC2, ECS, EKS, Lambda...)

**Comment by bradgr** [comment]
Hi,

All replication settings are now live in CloudFormation and can be found in the RegistryPolicy (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-registrypolicy.html) and ReplicationConfiguration (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-replicationconfiguration.html) resources.
