### ISSUE TITLE
AWS::Cassandra::Table resource does not provide a way to control PIIR

### ISSUE THREAD

**Issue by mattmassicotte** [aws-cloudformation/cloudformation-coverage-roadmap#732]
## 2. Scope of request
I believe support for point-in-time-recovery would require a new attribute. As of the current implementation, this might be a boolean or a "ENABLED"/"DISABLED" string.

## 3. Expected behavior

Should be possible to define PIIR behavior via CF, and update without requiring resource replacement.

## 4. Suggest specific test cases

New table creation
Table update

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cassandra-table.html
https://docs.aws.amazon.com/keyspaces/latest/devguide/PointInTimeRecovery.html

## 6. Category

DB, Amazon Keyspaces (for Apache Cassandra)

**Comment by bhouse99** [comment]
Should now be supported as of 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cassandra-table.html
