### ISSUE TITLE
Support for Kinesis Data Streams to capture item-level changes in DynamoDB tables

### ISSUE THREAD

**Issue by lucerobr** [aws-cloudformation/cloudformation-coverage-roadmap#736]
CloudFormation support to implement [Kinesis Data Streams capturing item-level changes in DynamoDB tables](https://aws.amazon.com/about-aws/whats-new/2020/11/now-you-can-use-amazon-kinesis-data-streams-to-capture-item-level-changes-in-your-amazon-dynamodb-table/) functionality.

**Comment by anupwarrier** [comment]
Very important feature for my customer. Its a blocker for adopting KDS integration for DynamoDB. +1

**Comment by ankon** [comment]
Is this a dup of https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/707?

**Comment by TheDanBlanco** [comment]
this appears to [exist](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dynamodb-globaltable-kinesisstreamspecification.html). if this isn't the case, feel free to re-open!
