### ISSUE TITLE
AWS::Redshift::Cluster - maintenancetrackname missing from CFN

### ISSUE THREAD

**Issue by jenrae** [aws-cloudformation/cloudformation-coverage-roadmap#738]
AWS::Redshift::Cluster-maintenancetrackname missing from CFN

**Comment by shwetayakkali** [comment]
maintenancetrackname is added as part of support for AWS::Redshift::Cluster.

It is available in  create/restore, update operations.

**Comment by shwetayakkali** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html#cfn-redshift-cluster-maintenancetrackname

please close this issue as this support is available now.
