### ISSUE TITLE
AWS::DMS::Endpoint - Update tags for DMS Endpoint and ReplicationSubnetGroup without replacement

### ISSUE THREAD

**Issue by juajrge** [aws-cloudformation/cloudformation-coverage-roadmap#742]
Quick Sample Summary:
1. Title -> AWS::DMS::Endpoint and AWS::DMS::ReplicationSubnetGroup tags update require replacement.
2. Scope of request -> Currently when a customer wants  to update a tag in a AWS::DMS::Endpoint or AWS::DMS::ReplicationSubnetGroup, it will require a replacement of the whole resource.
3. Expected behavior -> Update the resource instead of replace it.
4. Test case recommendation (optional) ->
5. Links to existing API doc (optional) -> https://docs.aws.amazon.com/dms/latest/APIReference/API_AddTagsToResource.html
6. Category tag (optional) -> CloudFormation / DMS
7. Any additional context (optional)

##1. Update tags for DMS Endpoint and ReplicationSubnetGroup without replacement**
AWS::DMS::Endpoint
AWS::DMS::ReplicationSubnetGroup 

## 2. Scope of request
As described below, whenever a customer wants to update Tags to DMS Endpoint or ReplicationSubnetGroup, CloudFormation while replace the whole resource even though nothing else changed in the CloudFormation template.
AWS::DMS::Endpoint
AWS::DMS::ReplicationSubnetGroup 

## 3. Expected behavior
Since only a Tag is changed an nothing else it would be great if the resource is updated instead of replaced.

## 5. Helpful Links to speed up research and evaluation
As described in the following links, the Tags property will require Replacement if updated.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-replicationsubnetgroup.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dms-endpoint.html#cfn-dms-endpoint-tags

## 6. Category
CloudFormation
Database Migration Service

**Comment by pwhsieh** [comment]
Changes are deployed - update tags for dms endpoint can now be done with no interruption.
