### ISSUE TITLE
AWS::Cassandra::Keyspace cannot be imported

### ISSUE THREAD

**Issue by mattmassicotte** [aws-cloudformation/cloudformation-coverage-roadmap#749]
## 2. Scope of request

Keyspace resources can be successfully created with CloudFormation, but it seems they cannot be imported. The import fails while creating tags.

## 3. Expected behavior

Given that Keyspace tags can be modified manually after creation, it seems like this should be possible.

## 4. Suggest specific test cases

This one should be easy to verify. Manually create Keyspace, attempt an import.

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cassandra-keyspace.html

## 6. Category

DB (Keyspaces)

**Comment by PatMyron** [comment]
linking main issue: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/276

**Comment by bhouse99** [comment]
Good news, this is now supported...
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html
