### ISSUE TITLE
AWS::SSM::MaintenanceWindowTask - Cloudformation - MaintenanceWindowRunCommandParameters - DocumentVersion - Unable to set

### ISSUE THREAD

**Issue by adampblack** [aws-cloudformation/cloudformation-coverage-roadmap#758]
## Instructions for CloudFormation Coverage New Issues Template

When I set the DocumentVersion MaintenanceWindowRunCommandParameters I get this roll back error in CF.

Property validation failure: [Encountered unsupported properties in {/TaskInvocationParameters/MaintenanceWindowRunCommandParameters}: [DocumentVersion]]
--

## 2. Scope of request 

Cloudformation and SSM

## 3. Expected behavior

I would expect the SSM MW Task to have the latest document version specified when opening in web console.

## 4. Suggest specific test cases

NatGatewayMaintenanceWindowTask:  
   Type: AWS::SSM::MaintenanceWindowTask
   Properties: 
     Description: !Ref NatGatewayMaintenanceWindowTaskDescription
     MaxConcurrency: 100%
     MaxErrors: 1
     Name: !Ref NatGatewayMaintenanceWindowTaskName
     Priority: 1
     ServiceRoleArn: !GetAtt NatGatewayMaintenanceWindowTaskRole.Arn
     Targets:
        - Key: WindowTargetIds
          Values:
            - !Ref NatGatewayMaintenanceWindowTarget
     TaskArn: AWS-RunPatchBaseline
     TaskInvocationParameters: 
       MaintenanceWindowRunCommandParameters:
          Comment: Runs patch baseline
          DocumentVersion: '$LATEST'
          TimeoutSeconds: 600
          Parameters: {"Operation":["Install"]}
     TaskType: RUN_COMMAND
     WindowId: !Ref NatGatewayMaintenanceWindow

It works fine after I remove Document version - but does not work when I set it.

## 5. Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_MaintenanceWindowRunCommandParameters.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Security - SSM

**Comment by zehuawan** [comment]
Hi, DocumentVersion support was added for MaintenanceWindowRunCommandParameters recently. Please check again.
