### ISSUE TITLE
AWS::EKS::Nodegroup - ScalingConfig Support EnableMetricsCollection

### ISSUE THREAD

**Issue by senior88oqz** [aws-cloudformation/cloudformation-coverage-roadmap#761]
## Quick Summary:
1. Title -> AWS::EKS::Nodegroup-ScalingConfig Support EnableMetricsCollection
2. Scope of request -> AWS::EKS::Nodegroup-ScalingConfig should have the option to enable metrics collection for the Auto Scaling group created by this property
3. Expected behavior -> Should be able to enable asg metric collections

**Comment by suket22** [comment]
Hello! This isn't supported by the EKS Nodegroup API and is therefore something you cannot do via the CloudFormation resource either.

 You can track the status of the feature request here - https://github.com/aws/containers-roadmap/issues/762. Any API change to address this will be accompanied with the CloudFormation resource update as well.
