### ISSUE TITLE
AWS::Logs::LogGroup tag support

### ISSUE THREAD

**Issue by kjpgit** [aws-cloudformation/cloudformation-coverage-roadmap#77]
We use cfn with lambdas.  Lambdas generate lots of log activity (that you can't even fully disable), and we want to track the full costs of lambda services by using tags (specifically, the top level tags passed into stack create).

So please:

- Support setting tags on LogGroups (particularly using inherited tags, e.g. aws cloudformation deploy --tags XXX=YYY)

Existing docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html

**Comment by Giaco9** [comment]
Hi all,
 is there any news on this?

Thank you

**Comment by martavoi** [comment]
Any updates?

**Comment by mgmarino** [comment]
The referenced PR that will close has been approved, it seems we are just waiting for merge/release.

**Comment by wangyun1517** [comment]
When is it ready to use?

**Comment by PatMyron** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-tags

**Comment by msplival** [comment]
> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-tags

PatMyron, does this mean that cloudformation will automatically tag AWS::Logs::LogGroup resources, or 'Tags' property needs to be added? (Ideally, I'd prefer similar behaviour as, say DBCluster, where one can add additional tags using Tags property, but CloudFormation will always add ones defined with the stack itself)

**Comment by mgmarino** [comment]
@msplival On stack updates, I have seen stack tags get propagated to Log Group resources as expected.  

Nice!

**Comment by shekharsh75** [comment]
Looks like this feature is not supported in the China regions. Any ETA on when it will be supported in those regions?

**Comment by swaranga** [comment]
Is this a joke? Why is this not supported in BJS and PDT etc?
