### ISSUE TITLE
[Feature Request] Enable to specify an S3 bucket when uploading template files

### ISSUE THREAD

**Issue by kome2** [aws-cloudformation/cloudformation-coverage-roadmap#777]
## 1. Title
[Feature Request] Enable to specify an S3 bucket when uploading template files

## 2. Scope of request 

Currently, when uploading template files, the files are automatically saved into S3 bucket "cf-template-**".
So we would like to set the specified S3 bucket when uploading these files.

## 3. Expected behavior

We can set the specified S3 bucket when uploading template files.

## 4. Suggest specific test cases

N/A

## 5. Helpful Links to speed up research and evaluation

N/A

## 6. Category 

Developer Tools

**Comment by ankon** [comment]
Can't you do that by explicitly uploading the template, and then point to it?
