### ISSUE TITLE
AWS::Cognito::IdentityPool - [Feature Request] AWS::Cognito::IdentityPoolAttributesForAccessControl

### ISSUE THREAD

**Issue by ghost** [aws-cloudformation/cloudformation-coverage-roadmap#779]
## 1. Title 
AWS::Cognito::IdentityPoolPrincipalTagAttributeMap

## 2. Scope of request 
Currently there is no way in Cloudformation to set the Attributes for Access Control settings for Authentication Providers. To set this I have to do it manually in the console or use the cli command.

## 3. Expected behavior
Be able to set the Attributes for Access Control settings in a Cloudformation Template

## 4. Suggest specific test cases
N/A

## 5. Helpful Links to speed up research and evaluation
CLI command for settings principal tag attribute map
https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cognito-identity/set-principal-tag-attribute-map.html 

## 6. Category
Use the categories as displayed in the AWS Management Console (simplified):
8. Security (IAM, KMS...), Security, Identity, & Compliance, Cognito

**Comment by nsorens** [comment]
This is coming soon, although we don't have a date yet.

**Comment by jeff-wishnie** [comment]
Any update on this? My entire app, aside from this one setting, is managed via SAM and templates. It's annoying to have to manually run `aws` cli after every deploy for this one little setting!

Thank you!

**Comment by aniketK2021** [comment]
This feature request has currently been prioritized and we will have a release date soon.

**Comment by yadaom** [comment]
Hello AWS Team,
Is there any update on this?
Thanks in advance.

**Comment by mpinto1991** [comment]
any update on this issue?

**Comment by deepaktammali** [comment]
Hello,
Is there any update on this feature? thanks.

**Comment by yadaom** [comment]
Hello Deepak,

I was facing the same issue. 
But in the end I end up writing a shell script which I execute once the Cloudformation script has finished?
I have attached the script here.
You should be able to understand it and modify to your needs.

[set-principal-tag-mapping.sh.zip](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/files/10235190/set-principal-tag-mapping.sh.zip)

**Comment by armandsyah134** [comment]
Hello, a new CFN resource has now been released that will now allow you to set Attributes for Access Control settings for your Identity Pool. This resource is called `AWS::Cognito::IdentityPoolPrincipalTag`. 

Documentation for this resource is available here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypoolprincipaltag.html
