### ISSUE TITLE
AWS::GlobalAccelerator::Accelerator IPs attribute

### ISSUE THREAD

**Issue by rjpereira** [aws-cloudformation/cloudformation-coverage-roadmap#782]
AWS::GlobalAccelerator::Accelerator supports AcceleratorArn and DnsName output properties in addition to Ref.
None of those though makes the static IP pair available in the template.

Current solution is to use custom resources to use e.g. 

    response = client.describe_accelerator(
                    AcceleratorArn=event['ResourceProperties']['AcceleratorArn']
    )

    {
    "Accelerator": {
        "AcceleratorArn": "arn:aws:globalaccelerator::xxxxx:accelerator/yyyyyy",
        "Name": "Accelerator",
        "IpAddressType": "IPV4",
        "Enabled": true,
        "IpSets": [
            {
                "IpFamily": "IPv4",
                "IpAddresses": [
                    "1.1.1.1",                 <--------------------- This &
                    "2.2.2.2"               <--------------------- this
                ]
            }
        ],
        "DnsName": "zzzzz.awsglobalaccelerator.com",
        "Status": "DEPLOYED",
        "CreatedTime": "2021-02-15T21:52:31+01:00",
        "LastModifiedTime": "2021-02-15T21:53:02+01:00"
    }
    }

which is verbose at the list. Just like https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/109, this request is about making the IP addresses available in the logical resource.

**Comment by coolfrood** [comment]
Thank you for reaching out. I agree that the IP address would be a useful piece of information provided via output properties. We will look into this.

**Comment by coolfrood** [comment]
@rjpereira: Thank you for reporting this issue. An accelerator's IP addresses are now available as  `Ipv4Addresses` attribute.

Please see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-globalaccelerator-accelerator.html for details.
