### ISSUE TITLE
AWS::CloudWatch::Dashboard - DashboardName

### ISSUE THREAD

**Issue by ghost** [aws-cloudformation/cloudformation-coverage-roadmap#783]
## 2. Scope of request
Change the behavior, when the DashboardName is not given. The default naming function of DashboardName is not based on the name of the cloud formation resource name. It's always easier to maintain resources which have a proper auto naming, specially when the resource must be replaced. 

## 3. Expected behavior
The name includes the logical id of the cloud formation template

## 4. Suggest specific test cases
Deploy a stack twice with different stack names.

## 5. Helpful Links to speed up research and evaluation
- [Cloud formation Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-dashboard.html)

## 6. Category
5. Management (CloudTrail, Config...)

**Comment by gcacace** [comment]
CloudWatch Dashboard Name is already prefixed with the resource logical name provided in the CloudFormation Template.
