### ISSUE TITLE
AWS::ECR::Repository support for importing into existing stack

### ISSUE THREAD

**Issue by RyanFrench** [aws-cloudformation/cloudformation-coverage-roadmap#784]
## 2. Scope of request 

We have a number of ECR Repositories that were created with Terraform a few years ago. We would like to migrate these repositories into a CloudFormation stack.

## 3. Expected behavior

I should be able to import an ECR repository, including all of it's configuration and permissions, into a new CloudFormation stack.

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

Use the categories as displayed in the AWS Management Console (simplified):

Containers (ECR)

**Comment by PatMyron** [comment]
linking main issue: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/218

**Comment by bradgr** [comment]
Hi Ryan,
Thanks for raising this. 
Both importing ECR repositories into an existing stack and creating a new stack using existing ECR repositories are supported today. Are you running into issues on import?

**Comment by scravy** [comment]
@bradgr This is not reflected in the documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

**Comment by bradgr** [comment]
Thank you for bringing the documentation to our attention. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html has now been updated.
