### ISSUE TITLE
AWS::Cognito::UserPoolClient - Fn::GetAtt

### ISSUE THREAD

**Issue by yenhanshih** [aws-cloudformation/cloudformation-coverage-roadmap#794]
## 2. Scope of request

AWS::Cognito::UserPoolClient-Fn::GetAtt ClientSecret does not exist, you can currently get the client ID via the AWS::Cognito::UserPoolClient-Ref. It would be helpful to be able to return the client secret as well.

## 3. Expected behavior

AWS::Cognito::UserPoolClient-Fn::GetAtt should be able to retrieve the ClientSecret for easy reference to reference a generated secret into AWS Secret Manager.

## 4. Test case recommendation (optional)
N/A

## 5. Links to existing API doc (optional)
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html

## 6. Category tag (optional)
Security (IAM, KMS...)

## 7. Any additional context (optional)

**Comment by timwhunt** [comment]
Hello @yenhanshih,

I work on the Amazon Cognito team. Thank you for submitting this issue and apologies for the delay in responding. We cannot support returning the ClientSecret at this time, but we are discussing potential future options internally. In the meantime, you may be able to use a workaround based on a Lambda function as demonstrated in this example from AWS Amplify: https://github.com/aws-amplify/amplify-cli/blob/a4eb66ca1a89ce79e83f551e328c1dc04ba62f7e/packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs#L339.

**Comment by rafalwrzeszcz** [comment]
Hi @yenhanshih , I have no idea what is the problem with that, but I created a custom type handler which can return you this property: https://rafalwrzeszcz-wrzasqpl.github.io/pl.wrzasq.cform/cform-data-cognito-client/guide/usage.html as I had exactly same problem

**Comment by lpsinger** [comment]
> I work on the Amazon Cognito team. Thank you for submitting this issue and apologies for the delay in responding. We cannot support returning the ClientSecret at this time, but we are discussing potential future options internally.

That's too bad. Terraform has supported this for years.
