### ISSUE TITLE
AWS::Cognito::UserPoolClient - Name and ClientSecret

### ISSUE THREAD

**Issue by hauntingEcho** [aws-cloudformation/cloudformation-coverage-roadmap#800]
## Scope of request 

`AWS::Cognito::UserPoolClient` does not currently provide any way to get the Name and ClientSecret via CloudFormation

## Expected behavior

A way to retrieve the Name and ClientSecret.  Another solution could be to allow the ClientSecret as an input, letting SecretsManager be responsible for generating and holding the value and letting other resources reference the same source secret.

## Suggested specific test cases

A CloudFormation template which creates an `AWS::Cognito::UserPoolClient` and an `AWS::SecretsManager::Secret` containing the UserPoolClient's Name and ClientSecret, with no custom resources

## Helpful Links to speed up research and evaluation

This was once a documented feature, but was removed from the documentation in [this commit](https://github.com/awsdocs/aws-cloudformation-user-guide/commit/640230f21f1d1d2813057db4dacb1f1d5c980317#diff-ebede00818a7a40b13a06858333dee3ea04919b93d9d3839e09f137b07a9121c).

Amplify currently [uses a custom resource as a workaround to this issue](https://github.com/aws-amplify/amplify-cli/blob/a4eb66ca1a89ce79e83f551e328c1dc04ba62f7e/packages/amplify-category-auth/provider-utils/awscloudformation/cloudformation-templates/auth-template.yml.ejs#L339)

There is some discussion around this [in the AWS forums](https://forums.aws.amazon.com/thread.jspa?threadID=261958&tstart=0)

## Category

Security, Identity, and Compliance

**Comment by michaelwittig** [comment]
related to #794

**Comment by hauntingEcho** [comment]
Was this fixed?  I'm not seeing any references to it in [the documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-generatesecret)

**Comment by rafalwrzeszcz** [comment]
Hi @hauntingEcho , no resolution (for whatever reason) was kind of "wont-do" o.0

I created a custom type handler as I had exactly same problem: https://rafalwrzeszcz-wrzasqpl.github.io/pl.wrzasq.cform/cform-data-cognito-client/guide/usage.html
