### ISSUE TITLE
AWS::ECS::Service , AWS::ECS::Cluster, AWS::ECS::TaskDefinition: Generated stack-level tags not propagated

### ISSUE THREAD

**Issue by wolverian** [aws-cloudformation/cloudformation-coverage-roadmap#807]
## Scope of request 

AWS::ECS::Service, AWS::ECS::Cluster, AWS::ECS::TaskDefinition: propagate autogenerated stack-level tags like `aws:cloudformation:stack-id` to these resources.

[The documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html) is misleading:

> All stack-level tags, including automatically created tags, are propagated to resources that CloudFormation supports. Currently, tags aren't propagated to Amazon EBS volumes that are created from block device mappings.

I would say CloudFormation does support these resources, but it nevertheless does not propagate these tags.

## Expected behavior

Automatically created stack-level tags are propagated to all ECS resources.

**Comment by Jackhu-gc** [comment]
We got the same issue from 01 Mar 2022. All other resources are fine, `AWS::ECS::Cluster` is showing `MODIFIED`. ECS Cluster is showing stack-level tags drifted
`
 "StackResourceDrifts": [
        {
            "StackId": "arn:aws:cloudformation:region:accountId:stack/xxx-uat-xxx/06052380-c9d1-11eb-94d1-022ca2ac0e8a",
            "LogicalResourceId": "ECSCluster",
            "PhysicalResourceId": "XXX-uat-XXX",
            "ResourceType": "AWS::ECS::Cluster",
            "ExpectedProperties": "XXXXXX",
            "ActualProperties": "XXX",
            "PropertyDifferences": [
                {
                    "PropertyPath": "/Tags/7",
                    "ExpectedValue": "null",
                    "ActualValue": "{\"Key\":\"aws:cloudformation:stack-name\",\"Value\":\"XXX-uat-XXX\"}",
                    "DifferenceType": "ADD"
                },
                {
                    "PropertyPath": "/Tags/8",
                    "ExpectedValue": "null",
                    "ActualValue": "{\"Key\":\"aws:cloudformation:logical-id\",\"Value\":\"ECSCluster\"}",
                    "DifferenceType": "ADD"
                },
                {
                    "PropertyPath": "/Tags/9",
                    "ExpectedValue": "null",
                    "ActualValue": "{\"Key\":\"aws:cloudformation:stack-id\",\"Value\":\"arn:aws:cloudformation:region:accountId:stack/xxx-uat-xxx/06052380-c9d1-11eb-94d1-022ca2ac0e8a\"}",
                    "DifferenceType": "ADD"
                }
            ],
            "StackResourceDriftStatus": "MODIFIED",
            "Timestamp": "2022-03-03T03:14:59.866000+00:00"
        },
        {...
`

**Comment by rgoltz** [comment]
@Jackhu-gc Maybe your topic is covered by #1222 (aws cfn autotags on ECS::Cluster)
