### ISSUE TITLE
AWS::SSM::Document - DocumentType: Package - AttachmentSource argument missing

### ISSUE THREAD

**Issue by warci** [aws-cloudformation/cloudformation-coverage-roadmap#808]
## 2. Scope of request
When trying to create a SSM Distributor package (**DocumentType: Package**), it seems like we also need to provide the **AttachmentSource** parameter which is not supported.

### cli
```
aws ssm create-document \
	--name ${DOCUMENT_NAME} \
	--content file://manifest.json \
	--attachments Key="SourceUrl",Values="https://s3.amazonaws.com/${S3_INSTALL_FOLDER}" \
	--document-type Package
```
### manifest.json example
```
{
    "schemaVersion": "2.0",
    "version": "1.0.0",
    "packages": {
        "${DISTRO}": {
            "_any": {
                "_any": {
                    "file": "${ZIPFILE}"
                }
            }
        }
    },
    "files": {
        "${ZIPFILE}": {
            "checksums": {
                "sha256": "${CHECKSUM}"
            }
        }
    }
}
```
### CFN Template
```
Resources:
  ${RESOURCE_NAME}:
    Type: AWS::SSM::Document
    Properties: 
      Content: 
          {
              "schemaVersion": "2.0",
              "version": "1.0.0",
              "packages": {
                  "${DISTRO}": {
                      "_any": {
                          "_any": {
                              "file": "${ZIPFILE}"
                          }
                      }
                  }
              },
              "files": {
                  "${ZIPFILE}": {
                      "checksums": {
                          "sha256": "${CHECKSUM}"
                      }
                  }
              }
          }
      DocumentType: Package
      Name: ${DOCUMENT_NAME}
```
### CFN error message
```
AttachmentSource not provided in the input request. (Service: AmazonSSM; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: xxxxxxxxxx; Proxy: null)
```

## 5. Helpful Links to speed up research and evaluation
Terraform implementation: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssm_document
Boto3 (Attachments request parameter): https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ssm.html#SSM.Client.create_document

**Comment by reillynoah** [comment]
We do have support for AttachmentsSource for Document resource type in CFN: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ssm-document-attachmentssource.html

The Attachments property is defined as a list of AttachmentsSource as shown here: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ssm/blob/master/aws-ssm-document/aws-ssm-document.json#L90
