### ISSUE TITLE
AWS::EC2::NetworkAclEntry - PrefixListId

### ISSUE THREAD

**Issue by rhbecker** [aws-cloudformation/cloudformation-coverage-roadmap#812]
## Scope of request 

I'm seeking support for a new attribute (**PrefixListId**) for an existing resource (**[AWS::EC2::NetworkAclEntry]**).

I believe the backing services would need to be enhanced before cloudformation could support the functionality.

## Expected behavior

According to the VPC service's [Prefix lists] documentation, a prefix list may be referenced when specifying ...

1. a VPC security group's ingress and egress rules,
2. a subnet route table's entries, and
3. a transit gateway route table's entries.

It's unexpected (to me, at least) that they cannot be used when specifying a Network ACL's ingress and egress rules.

The attribute would operate in a fashion that parallels how a prefix list may be referenced when specifying a VPC security group's ingress and egress rules, which is already supported by the service and via cloudformation.

## Helpful Links to speed up research and evaluation

* [AWS::EC2::NetworkAclEntry] is the resource for which I'm requesting the enhancement.
* Existing resource attributes whose functionality and implementation I'd suggest copying:
  * [AWS::EC2::SecurityGroupIngress-SourcePrefixListId]
  * [AWS::EC2::SecurityGroupEgress-DestinationPrefixListId]
* [AWS::EC2::PrefixList]

## Category tags

* Compute
* Networking & Content

[AWS::EC2::NetworkAclEntry]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-network-acl-entry.html
[AWS::EC2::PrefixList]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-prefixlist.html
[AWS::EC2::SecurityGroupEgress-DestinationPrefixListId]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule.html#cfn-ec2-security-group-rule-destinationprefixlistid
[AWS::EC2::SecurityGroupIngress-SourcePrefixListId]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group-rule-1.html#cfn-ec2-securitygroup-ingress-sourceprefixlistid
[Prefix lists]: https://docs.aws.amazon.com/vpc/latest/userguide/managed-prefix-lists.html

**Comment by sbwrege2z** [comment]
I would also like prefix lists to be able to be referenced by network acls if possible.

At a minimum it would be nice if a route could reference DestinationPrefixListId the same as a security group (which is already available through CLI and the console, but not through a cloud formation template).

**Comment by rhbecker** [comment]
Issue #572 seems to be about that. I suppose that's the more likely to receive CloudFormation support, given the functionality is already supported by the underlying service.

**Comment by rhbecker** [comment]
@sbwrege2z: Would you mind adding your 👍 to the first post? That seems to be how the team tracks interest.

**Comment by sbwrege2z** [comment]
Done.  Do you have any ideas what the issues with adding prefix list support to the network ACL's?  Is it harder because they are hardware devices?  I mostly use security groups, but the ability to Deny traffic through the ACL's can't easily be replicated with Security Groups.  Being able to define a region-wide blacklist that every VPC's network ACL could use would be very nice.

**Comment by rhbecker** [comment]
> Done.

Thanks!

> Do you have any ideas what the issues with adding prefix list support to the network ACL's? Is it harder because they are hardware devices?

I don't know, and I'm curious as well. AWS engineers are a clever bunch, so I assume the lack of support is **_not_** due to the idea never occurring to them.

**Comment by sabya08** [comment]
NetworkAcls (NACL) today does not support PrefixListIds in the NACL entries. So this is not a coverage issue or a bug in CloudFormation resource AWS::EC2::NetworkAclEntry and instead this is a feature request for NACLs.

**Comment by rhbecker** [comment]
I'm surprised to see this issue has been marked as `Shipped`. Is the intention to close it as "won't fix"?

> NetworkAcls (NACL) today does not support PrefixListIds in the NACL entries. So this is not a coverage issue or a bug in CloudFormation resource AWS::EC2::NetworkAclEntry and instead this is a feature request for NACLs.

This is my understanding as well. Does anyone know a method for requesting this NACL feature that will reach the right 👀 on the right team at AWS?
