### ISSUE TITLE
AWS::Backup::BackupPlan - BackupRuleResourceType-ContinuousBackups

### ISSUE THREAD

**Issue by danieljamesscott** [aws-cloudformation/cloudformation-coverage-roadmap#813]
## 2. Scope of request 

Support the new 'ContinuousBackups' feature

https://aws.amazon.com/blogs/storage/point-in-time-recovery-and-continuous-backup-for-amazon-rds-with-aws-backup/

**Comment by pavbollu** [comment]
We are supporting ContinuousBackups 

Documentation on how to use it.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-backup-backupplan-backupruleresourcetype.html#cfn-backup-backupplan-backupruleresourcetype-enablecontinuousbackup
