### ISSUE TITLE
AWS::ElasticBeanstalk::Environment Add "EnvironmentURL" return value

### ISSUE THREAD

**Issue by uldall** [aws-cloudformation/cloudformation-coverage-roadmap#822]
## Scope of request 
Today it is possible to get the EndpointURL as a return value when creating an AWS::ElasticBeanstalk::Environment in CloudFormation.

EndpointURL unfortunately points to the private CNAME of the load balancer that the EB environment has created. The issue is that EB managed the load balancer and can change this address without warning and so a CloudFormation template cannot use the value reliably for creating Route53 records pointing to the environment.

This issue specifically shows when rebuilding an environment.

It would be great if a new return value named EnvironmentURL was added which points to the public CNAME of the EB environment. In this way one can reliably point Route53 records to this CNAME without fear of it changing out of nowhere.

## Expected behavior
A return value that can be fetched using Fn::GetAtt called **EnvironmentURL**. This value will return a value under the *.elasticbeanstalk.com domain. Example:
test-site-m46fsag5h6h78.ebd-74fbnu7p.eu-west-1.elasticbeanstalk.com

## Category
Compute

**Comment by benbridts** [comment]
As a workaround:

You can set your own EnvironmentURL as a Property on the resource.

It might also be useful to check if this is already on the [Elastic Beanstalk Roadmap](https://github.com/aws/elastic-beanstalk-roadmap)

**Comment by uldall** [comment]
> As a workaround:
> 
> You can set your own EnvironmentURL as a Property on the resource.
> 
> It might also be useful to check if this is already on the [Elastic Beanstalk Roadmap](https://github.com/aws/elastic-beanstalk-roadmap)

That would indeed be a very nice improvement!

**Comment by shwilliamson** [comment]
This says it is shipped, but it does not appear in the cloud formation documentation for Elastic Beanstalk Environment.  When I tried to use EnvironmentURL, my stack update failed with the message: "Requested attribute EnvironmentURL does not exist in schema for AWS::ElasticBeanstalk::Environment".  Any word on when this will be available for use?  We need this to add a root domain alias in route 53 as part of our cloud formation template.  Thanks!

**Comment by ghost** [comment]
Also wondering if this is actually shipped. I don't see a new property on the resource for the CNAME value and it is not in the documentation.

**Comment by deepanshu-ethosx** [comment]
I wonder if this will be shipped in 2025.
