### ISSUE TITLE
AWS::Personalize::*

### ISSUE THREAD

**Issue by kannanpk24** [aws-cloudformation/cloudformation-coverage-roadmap#827]
My customer would like to leverage the to be launched template generation feature of CloudFormation. In order for them to be able to use this feature, they would like to be able to invoke APIs for their ML services. CFN does not currently support Amazon Personalize which is one of their widely used ML services.

**Comment by TheDanBlanco** [comment]
looks like [personalize](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Personalize.html) is now supported. please re-open if you don't feel this is the case & add more detail. thanks!
