### ISSUE TITLE
AWS::RDS::DBInstance - Not able to modify DBInstanceClass for Aurora RDS instance

### ISSUE THREAD

**Issue by ghost** [aws-cloudformation/cloudformation-coverage-roadmap#847]
## 2. Scope of request 
Allow Cloudformation to be able to update DBInstanceClass 

## 3. Expected behavior
Aurora RDS instance class should be changed

## 4. Suggest specific test cases
a. Create Aurora RDS instance via CF
```
  cluster-id:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      DBClusterIdentifier: cluster-id
      EngineVersion: "5.6"
      MasterUsername: admin
      MasterUserPassword: ChangeMeN0W
  instance-id:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.r5.large
      DBClusterIdentifier:
        Ref: cluster-id
      DBInstanceIdentifier: instance-id
      Engine: aurora
      EngineVersion: "5.6"
```    
b. Create a changeset to modify instance class
```
Stack xxx
Resources
[~] AWS::RDS::DBInstance xxx
 └─ [~] DBInstanceClass
     ├─ [-] db.r5.large
     └─ [+] db.r5.24xlarge

```    
c. InstanceClass should be changed -> but gives errors
```
UPDATE_FAILED        | AWS::RDS::DBInstance              | xxx
The specified DB Instance is a member of a cluster. Modify the DB engine version for the DB Cluster using the ModifyDbCluster API (Service: AmazonRDS; Status Code: 400; Error Code: InvalidParameterCombination; Request ID: c8268c48-5ebc-426c-9134-e7b0700cdb89; Proxy: null
)
```
## 6. Category
3. DB (RDS, DynamoDB...)

**Comment by osdrv** [comment]
CFN attempted to modify EngineVersion as apparently the instance resource drifted from the stack definition. This correlates with @spg 's observations. As a rule of thumb, running a drift detector on a resource before an upgrade might indicate such discrepancies.
