### ISSUE TITLE
AWS::RDS::DBProxy - Auth entries as separate resource

### ISSUE THREAD

**Issue by hauntingEcho** [aws-cloudformation/cloudformation-coverage-roadmap#850]
## Scope of request 

Many different services, with their own set of credentials to a database, may need to use a proxy to reach the database.  Allowing independent management of the Auth entries would allow those services to manage their own credential lifecycle.

## Expected behavior

Ability to manage Auth items independently of both the proxy itself and other auth items

## Suggest specific test cases

a stack containing a database, a DBProxy with no auth entries in the base definition, and a separate auth item for the root user

## Category

DB, Networking & Content, Security, Management

**Comment by siyuxingaws** [comment]
Hi,

The Auth entries are stored as a configuration parameter in RDS Proxy. It cannot be created, deleted, or mutated as a separate resource. This is limited by RDS Proxy's APIs.

Thanks.

**Comment by hauntingEcho** [comment]
I hadn't seen that, but [you're right](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/modify-db-proxy.html).  This makes for a very messy chain of dependencies if your database server has multiple users (e.g. a schema-per-service model).  Do you know if there's any intent to support this in the future, or where the right place to ask about that would be?
