### ISSUE TITLE
AWS::RDS::DBInstance - PointInTime

### ISSUE THREAD

**Issue by ptc-pcech** [aws-cloudformation/cloudformation-coverage-roadmap#855]
## 2. Scope of request 
   c) new attribute for an existing resource is desired 

A `PointInTime` attribute would ask to create new DB instance using point-in-time restore (`RestoreDBInstanceToPointInTime` API call). This is a counterpart for already existing `DBSnapshotIdentifier` attribute which asks to create new DB instance using restore from snapshot (`RestoreDBInstanceFromDBSnapshot` API call). Feel free to adjust the suggested attribute name.

## 3. Expected behavior

In Create, it should restore DB instance from point-in-time specified by the value of the attribute `PointInTime`. Using latest available point-in-time should be supported, either by special attribute value or a separate attribute.

## 4. Suggest specific test cases
The `PointInTime`, the possible "use latest point-in-time" and `DBSnapshotIdentifier` attributes are mutually exclusive.

## 5. Helpful Links to speed up research and evaluation

RDS RestoreDBInstanceToPointInTime API docs: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_RestoreDBInstanceToPointInTime.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

3. DB (RDS)

**Comment by moataz-mhmd** [comment]
Addressed in https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-rds/pull/355

**Comment by xaoyuli** [comment]
Confirmed with rds team, this issue has already been fixed
