### ISSUE TITLE
AWS::DocDB::DBCluster - EngineVersion Update behavior should be "Some interruptions," not "Replacement."

### ISSUE THREAD

**Issue by Shigerello** [aws-cloudformation/cloudformation-coverage-roadmap#858]
## 1. Title 
AWS::DocDB::DBCluster-EngineVersion

## 2. Scope of request 
Update behavior change (e.g. no interruption, some interruptions, replacement).

## 3. Expected behavior
Update behavior of changing AWS::DocDB::DBCluster-EngineVersion should be "some interruptions."
In contrast, update behavior of changing `engine-version` in `aws docdb modify-db-cluster` and `aws rds modify-db-cluster` is an outage ("some interruptions"), not "replacement."
"Some interruption" is more desirable when compared to "replacement."

## 5. Helpful Links to speed up research and evaluation
1. CloudFormation AWS::DocDB::DBCluster: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html#cfn-docdb-dbcluster-engineversion
2. CLI docdb modify-db-cluster: https://docs.aws.amazon.com/cli/latest/reference/docdb/modify-db-cluster.html
3. CLI rds modify-db-cluster: https://docs.aws.amazon.com/cli/latest/reference/rds/modify-db-cluster.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
DB

**Comment by vezinj** [comment]
AWS DocumentDB only supports modifying AWS::DocDB::DBCluster-EngineVersion as a "Replacement". Modifying the engine version is not supported with the CLI for Amazon DocumentDB (see https://docs.aws.amazon.com/cli/latest/reference/docdb/modify-db-cluster.html). We have added an item to our product backlog for the ability to upgrade your software without interruptions.
