### ISSUE TITLE
AWS::SSM::MaintenanceWindow Add Support For Drift Detection

### ISSUE THREAD

**Issue by megachromemonkey** [aws-cloudformation/cloudformation-coverage-roadmap#860]
## 2. Scope of request 
e) other coverage-related issue with the resource/attribute/option

AWS::SSM::MaintenanceWindow - Is [not a supported resource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html) for CloudFormation drift detection. Having this feature would help with removing custom logic to ensure `MaintenanceWindow` resources are in an expected state.
## 3. Expected Behavior
For drift detection checks to work for `MaintenanceWindow`.

## 5. Helpful Links to speed up research and evaluation
* AWS::SSM::MaintenanceWindow: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-maintenancewindow.html
* Resources that support import and drift detection operations: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1
* Management & Governance (Systems Manager)

**Comment by PatMyron** [comment]
While that documentation may not be keeping up, [I think this should actually be available since that is a Registry resource type](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/218#issuecomment-703884480)
