### ISSUE TITLE
AWS::RDS::DBCluster EnableGlobalWriteForwarding

### ISSUE THREAD

**Issue by c-py** [aws-cloudformation/cloudformation-coverage-roadmap#861]
## 2. Scope of request 

AWS::Service::DBCluster does not support EnableGlobalWriteForwarding

## Expected behavior
Expected behavior -> In Create, it should include EnableGlobalWriteForwarding.

## Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-cluster.html

**Comment by veho-mac** [comment]
Any updates on this? It's been an open issue for two years and we'd love to be able to use this for serverless v2 postgres

**Comment by kcolemangt** [comment]
Yes, please support this.

[Amazon Aurora Global Database for PostgreSQL now supports write forwarding](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-aurora-global-database-postgresql-forwarding/).

[Enabling write forwarding in Aurora PostgreSQL](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-write-forwarding-apg.html#aurora-global-database-write-forwarding-enabling-apg).

**Comment by veho-mac** [comment]
Is there a reason this isn't being worked on? Isn't it a simple configuration at this point? In fact, it's shown as being supported in the [v2 api docs for CfnDBCluster](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds.CfnDBCluster.html), as well as in the [CloudFormation user guide for DBCluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html) but this is not true for the aws-cdk-lib.
