### ISSUE TITLE
AWS::CloudFront::Function

### ISSUE THREAD

**Issue by jasonabradley** [aws-cloudformation/cloudformation-coverage-roadmap#862]
AWS::CloudFront::Function needs to exist for creation of CloudFront Functions that can be associated with CloudFront Distribution behaviors.

*Expected Behavior*

Create a CloudFront Function as can be done in the console and associated to one or many behaviors within various CloudFront distributions. 

*Category*

Networking & Content (VPC, Route53, API GW,...)

https://aws.amazon.com/blogs/aws/introducing-cloudfront-functions-run-your-code-at-the-edge-with-low-latency-at-any-scale/

**Comment by benbridts** [comment]
It wasn't there on release date, but it's here now: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-function.html
