### ISSUE TITLE
AWS::ACMPCA::CertificateAuthority-CrlConfiguration-S3ObjectAcl

### ISSUE THREAD

**Issue by nbmha1** [aws-cloudformation/cloudformation-coverage-roadmap#866]
AWS::ACMPCA::CertificateAuthority-CrlConfiguration supports all of the attributes listed in the API (https://docs.aws.amazon.com/acm-pca/latest/APIReference/API_CrlConfiguration.html) except the new `S3ObjectAcl` attribute.

**Comment by rohits-spec** [comment]
Support for S3ObjectAcl has been released. More information here https://docs.amazonaws.cn/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-acmpca-certificateauthority-crlconfiguration.html#cfn-acmpca-certificateauthority-crlconfiguration-s3objectacl
