### ISSUE TITLE
AWS::Redshift::Cluster - ::AvailabilityZoneRelocation

### ISSUE THREAD

**Issue by vrnsn** [aws-cloudformation/cloudformation-coverage-roadmap#867]
## 1. Title
AWS::Redshift::Cluster::AvailabilityZoneRelocation
## 2. Scope of request
AWS::Redshift::Cluster should include AvailabilityZoneRelocation property
## 3. Expected behavior
CloudFormation would allow enabling Cluster Relocation for a related cluster
## 5. Helpful Links to speed up research and evaluation
https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateCluster.html
## 6. Category tag
Analytics, Redshift

**Comment by shwetayakkali** [comment]
This feature is available for Create/Restore and Update for Redshift Cluster in Uluru.

**Comment by vrnsn** [comment]
The property is available. Please refer to [https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html).
