### ISSUE TITLE
AWS::Redshift::Cluster - ::AquaConfigurationStatus

### ISSUE THREAD

**Issue by vrnsn** [aws-cloudformation/cloudformation-coverage-roadmap#868]
## 1. Title 
AWS::Redshift::Cluster::AquaConfigurationStatus
## 2. Scope of request
AWS::Redshift::Cluster does not include AquaConfigurationStatus. Aqua configuration should be a property associated with a cluster. 
## 3. Expected behavior
CloudFormation property for configuring the cluster with Aqua states (enabled, disabled or auto)
## 5. Helpful Links to speed up research and evaluation
https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateCluster.html
https://docs.aws.amazon.com/redshift/latest/APIReference/API_ModifyAquaConfiguration.html
## 6. Category tag
Analytics, Redshift

**Comment by shwetayakkali** [comment]
This feature is available for Create/Restore and Update for Redshift Cluster in Uluru.

**Comment by vrnsn** [comment]
The property is available. Please refer to [https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html).
