### ISSUE TITLE
AWS::Redshift::EventSubscriptions

### ISSUE THREAD

**Issue by vrnsn** [aws-cloudformation/cloudformation-coverage-roadmap#869]
## 1. Title 
AWS::Redshift::EventSubscriptions
## 2. Scope of request 
AWS::Redshift does not include Event Subscriptions configuration option for the clusters. 
## 3. Expected behavior
CloudFormation should have a parameter/resource for Event Subscriptions with related CreateEventSubscription, ModifyEventSubscription and DeleteEventSubscription APIs. 
## 5. Helpful Links to speed up research and evaluation
Create:  https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateEventSubscription.html
Modify: https://docs.aws.amazon.com/redshift/latest/APIReference/API_ModifyEventSubscription.html
Delete: https://docs.aws.amazon.com/redshift/latest/APIReference/API_DeleteEventSubscription.html

## 6. Category tag
Analytics, Redshift

**Comment by TheDanBlanco** [comment]
this appears to be [supported](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-eventsubscription.html) now. please re-open if this isn't the case!
