### ISSUE TITLE
AWS::Redshift::SnapshotConfiguration

### ISSUE THREAD

**Issue by vrnsn** [aws-cloudformation/cloudformation-coverage-roadmap#870]
## 1. Title 
AWS::Redshift::SnapshotConfiguration
## 2. Scope of request 
AWS::Redshift does not include a resource for configuring cluster snapshot settings. It would be helpful to have a resource to set snapshot configuration associated to a Redshift cluster. The properties would include:
CreateSnapshotSchedule
ModifyClusterSnapshotSchedule
DeleteSnapshotSchedule
DeleteSnapshotCopyGrant
CreateSnapshotCopyGrant
EnableSnapshotCopyRequest
DisableSnapshotCopyRequest
ModifySnapshotCopyRetentionPeriodRequest
RestoreTableFromClusterSnapshotRequest

RestoreFromClusterSnapshotRequest. << _Note: this api would probably be part of Redshift::Cluster resource._ 

## 3. Expected behavior
Snapshot configurations that are associated with clusters could be properties that is part of a snapshot configuration resource 

## 5. Helpful Links to speed up research and evaluation
All APIs noted above are documented in Redshift APIs https://docs.aws.amazon.com/redshift/latest/APIReference/API_Operations.html

## 6. Category tag
Analytics, Redshift

**Comment by TheDanBlanco** [comment]
it looks like a lot of this is included in the [cluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html) configuration. can you confirm? i'm closing this for now, feel free to re-open if this hasn't been addressed yet & include some more info. thanks!

**Comment by jon-ruckwood** [comment]
@TheDanBlanco I don’t believe this functionality is implemented yet. I am trying to use CloudFormation, and it seems this feature is still missing. Can this be reopened?

Specifically, this concerns creating Redshift snapshot schedules and attaching them to a cluster. Currently, this is only possible via API or CLI.

For an example of the missing CloudFormation functionality, see the equivalent Terraform implementation realised in these two resources:

- `redshift_snapshot_schedule` – https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_snapshot_schedule
- `redshift_snapshot_schedule_association` –https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/redshift_snapshot_schedule_association
