### ISSUE TITLE
AWS::Redshift::ClusterOperations

### ISSUE THREAD

**Issue by vrnsn** [aws-cloudformation/cloudformation-coverage-roadmap#871]
## 1. Title 
AWS::Redshift::ClusterOperations
## 2. Scope of request 
AWS::Redshift does not include resource or properties for cluster operations (non scheduled) such as: 
ResizeClusterRequest
PauseClusterRequest
RebootClusterRequest
ResizeClusterRequest
## 3. Expected behavior
These operations that can define the state of the cluster could be part of the cluster definition in CloudFormation as a separate resource that could be associated with a cluster. 
Please note that, there is another issue that was opened specifically for Scheduled Actions (https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/593)
## 5. Helpful Links to speed up research and evaluation
All APIs are documented in Redshift API guide: https://docs.aws.amazon.com/redshift/latest/APIReference/API_Operations.html
## 6. Category tag
Analytics, Redshift

**Comment by kddejong** [comment]
@vrnsn Can you help me understand a little more about your request?

I believe [ResizeCluster](https://docs.aws.amazon.com/redshift/latest/APIReference/API_ResizeCluster.html) should be handled by the definition in the [AWS::Redshift::Cluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html).  Having two resource types affect the instance type and count could result in some interesting downstream impacts.

[PauseCluster](https://docs.aws.amazon.com/redshift/latest/APIReference/API_PauseCluster.html) looks like it should be a status attribute of [AWS::Redshift::Cluster](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html).  

[RebootCluster](https://docs.aws.amazon.com/redshift/latest/APIReference/API_RebootCluster.html) I'm not sure if this one should exist. This looks like an action on a resource not a defined state of a resource. Pause is a state but reboot seems to be an action to me.

**Comment by vrnsn** [comment]
@kddejong I agree with your comments. +1 to your thoughts about rebootcluster operation. Also ++1 to resize and and pause.

**Comment by TheDanBlanco** [comment]
this looks to be supported as a [ClusterAction](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html#cfn-redshift-cluster-resourceaction). if this isn't the case, please re-open!
