### ISSUE TITLE
AWS::Redshift::Logging

### ISSUE THREAD

**Issue by vrnsn** [aws-cloudformation/cloudformation-coverage-roadmap#872]
## 1. Title 
AWS::Redshift::Logging
## 2. Scope of request 
AWS::Redshift resource for configuring audit logging for a cluster
## 3. Expected behavior
Enables or disables audit logging for a cluster
## 5. Helpful Links to speed up research and evaluation
https://docs.aws.amazon.com/redshift/latest/APIReference/API_EnableLogging.html
## 6. Category tag
Analytics, Redshift

**Comment by rohits-spec** [comment]
The Logging property is available on the cluster resource today https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-redshift-cluster-loggingproperties.html 

Does this cover your usecase? If not can you provide more info?

**Comment by vrnsn** [comment]
@rohits-spec, this was my bad. Yes, logging is already covered.

**Comment by brianterry** [comment]
The Logging property is available on the cluster resource today https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-redshift-cluster-loggingproperties.html

**Comment by flexelem** [comment]
Hey guys, 

We are trying to figure out enable audit logging to CloudWatch via CloudFormation. Is there any plan to support this feature?
