### ISSUE TITLE
AWS::ApplicationAutoScaling::ScalingPolicy attach math expression metrics 

### ISSUE THREAD

**Issue by romanbovda** [aws-cloudformation/cloudformation-coverage-roadmap#88]
## Scope of request 

We can use CloudFormation to attach alarms, based on standard metrics to the ECS Scaling Policy using MetricName. But there is no such option for Metrics with math expression. 

```
Metrics

The name of the metric associated with the alarm. This is required for an alarm based 
on a metric. For an alarm based on a math expression, you use Metrics instead and 
you can't specify MetricName.
```
Right now, if we want to use some custom metrics, we need to handle all calculation by lambda function and return result of the expression. In this case alarms technically are not based on math expression and we can use MetricName to attach Alarm to the ECS Scaling Policy.

## Expected behavior
MetricName available for an alarms, based on a math expression. Alarms can be attached by MetricName to the ECS Scaling Policy using CloudFormation Template.

## Helpful Links to speed up research and evaluation

https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#cfn-cloudwatch-alarm-metrics

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalingpolicy.html#cfn-applicationautoscaling-scalingpolicy-policytype

https://gist.github.com/LukasMusebrink/f9e018895763955b9fd017c9c4a91f18#file-metricmathalarm-yaml

**Comment by marcuram** [comment]
Feature has been added based on: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-applicationautoscaling-scalingpolicy-customizedmetricspecification.html#cfn-applicationautoscaling-scalingpolicy-customizedmetricspecification-metrics
