### ISSUE TITLE
AWS::MediaLive::Channel fails without the Name property #906

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/cloudformation-coverage-roadmap#907]
### Name of the resource

AWS::MediaLive::Channel

### Issue Description

When deploying the following template, CloudFormation gives the error "Non-empty channel name required (Service: AWSMediaLive; Status Code: 400; Error Code: BadRequestException; Request ID: 7187ff03-b6cd-49a5-92da-4e1f167c8ffb; Proxy: null)", instead of generation a Name.

Note that the template is valid, Name is not a required property

Additionally, other required properties, are not marked as such (if you add a Name, the error changes to "At least one inputAttachment must be specified"). 

```
Resources:
  MediaLiveChannel:
    Type: "AWS::MediaLive::Channel"
```

### Expected Behavior

The  resource should auto-generate an acceptable name before sending the request to the MediaLive service.

### Observed Behavior

The service returns an error

### Test Cases

See the template in the description for a failing template. Adding the "Name" property makes the error change

### Other Details

related: #906

**Comment by benbridts** [comment]
I'm not going to log every error that I receive when working with MediaLive, the schema does not match what's required at all.

This seems to be caused by the API not matching the actual implementation (or at least, it can be explained that way - you'd expect the contract test to find these issues). According to the API docs, "Name" is not a required property at all: https://docs.aws.amazon.com/medialive/latest/apireference/channels.html#channels-prop-createchannel-name

**Comment by zidanemoggy** [comment]
Hi Ben, I am one of the writers for our live encoders. The service team has made a fix to the underlying code, so that the REQUIRED field is slightly more accurate. However, it is important to keep in mind that it will say FALSE if the requirement is conditional. So there will be some fields that are TRUE (and dependably true), some that are FALSE (and you really can skip it), but some that are FALSE (but actually conditionally false because there might be a second field that you set in a way that makes the first field required). 
We are going to generate the API guide and the CloudFormation docs again early next week.
There are a lot of configuration fields for a channel. We find that most of our customers poke around in the console and get something that works, then download the JSON and use that as an XML template for new channels. It would be possible to do the same thing in CloudFormation.

**Comment by benbridts** [comment]
Thanks for the detailed update, Catherine!

I'm looking forward to the new API docs and CloudFormation schema (if you would like input on those, feel free to reach out).

Some other things I was thinking about:

> However, it is important to keep in mind that it will say FALSE if the requirement is conditional

(I'll wait until I see the updated docs to give concrete examples, but) you can actually express this in CloudFormation, both for the case where properties are mutual exclusive, or dependent on each other (the case that you described).

Additionally, you can specify `minItems` for Properties like `Destinations`, where iirc you always need one (and in that case cfn-lint and/or CloudFormation can warn customers before they deploy, leading to a better time for us).

> There are a lot of configuration fields for a channel. We find that most of our customers poke around in the console and get something that works, then download the JSON and use that as an XML template for new channels. It would be possible to do the same thing in CloudFormation

That's what we did, the problem is that those templates based on describe calls are better after a bit of clean-up to increase maintainability and follow CloudFormation best practices, some examples:

### Not setting the Name property: 
It's generally a good idea to have CloudFormation generate names, that way it's very easy to deploy the same stack twice, or execute a change where the resource will have to be recreated (CloudFormation creates new resources before deleting old ones, so if you have a fixed name there will be a conflict).

### Removing " Empty" properties
Eg. In my current template I have

```yaml
MotionGraphicsConfiguration:
    MotionGraphicsInsertion: "ENABLED"
    MotionGraphicsSettings:
            HtmlMotionGraphicsSettings: {}
```
Setting HtmlMotionGraphicsSettings (to only allowed property under MotionGraphicsSettings) to an empty dictionary, seems to me to be the same as not setting it at all. Removing that whole section makes the template more readable by making it a bit shorter.

```yaml
MotionGraphicsConfiguration:
    MotionGraphicsInsertion: "ENABLED"
````

### Not setting things that are the default
The same readability comment goes for other properties, where I might be using the defaults. This is important, because unlike in the console I don't get contextual hints about wether this might have been something I've changed or not. This is much more context-dependent than the previous one (sometimes being explicit is better than being implicit). For the cases where the defaults are well understood, it really helps the maintainability by showing "these are the settings that are specific to our setup".

I think CloudFront is a good example for this, where you can have these properties (nested in the configuration).

```yaml
 DomainName: example.com
```

### Thinking about updates

**Comment by benbridts** [comment]
Thanks for the detailed update, Catherine!

I'm looking forward to the new API docs and CloudFormation schema (if you would like input on those, feel free to reach out).

Some other things I was thinking about:

> However, it is important to keep in mind that it will say FALSE if the requirement is conditional

(I'll wait until I see the updated docs to give concrete examples, but) you can actually express this in CloudFormation, both for the case where properties are mutual exclusive, or dependent on each other (the case that you described).

Additionally, you can specify `minItems` for Properties like `Destinations`, where iirc you always need one (and in that case cfn-lint and/or CloudFormation can warn customers before they deploy, leading to a better time for us).

> There are a lot of configuration fields for a channel. We find that most of our customers poke around in the console and get something that works, then download the JSON and use that as an XML template for new channels. It would be possible to do the same thing in CloudFormation

That's what we did, the problem is that those templates based on describe calls are better after a bit of clean-up to increase maintainability and follow CloudFormation best practices, some examples:

### Not setting the Name property: 
It's generally a good idea to have CloudFormation generate names, that way it's very easy to deploy the same stack twice, or execute a change where the resource will have to be recreated (CloudFormation creates new resources before deleting old ones, so if you have a fixed name there will be a conflict).

### Removing " Empty" properties
Eg. In my current template I have

```yaml
MotionGraphicsConfiguration:
    MotionGraphicsInsertion: "ENABLED"
    MotionGraphicsSettings:
            HtmlMotionGraphicsSettings: {}
```
Setting HtmlMotionGraphicsSettings (to only allowed property under MotionGraphicsSettings) to an empty dictionary, seems to me to be the same as not setting it at all. Removing that whole section makes the template more readable by making it a bit shorter.

```yaml
MotionGraphicsConfiguration:
    MotionGraphicsInsertion: "ENABLED"
````

### Not setting things that are the default
The same readability comment goes for other properties, where I might be using the defaults. This is important, because unlike in the console I don't get contextual hints about wether this might have been something I've changed or not. This is much more context-dependent than the previous one (sometimes being explicit is better than being implicit). For the cases where the defaults are well understood, it really helps the maintainability by showing "these are the settings that are specific to our setup".

I think CloudFront is a good example for this, where you can have these properties (nested in the configuration).

```yaml
 DomainName: example.com
 CustomOriginConfig:
  HTTPPort: 80
  HTTPSPort: 443
```
If you're always generating your configuration from an existing distribution, your template will look like that (because the API returns those properties), however if a person wrote that, they would leave out the Ports, because people will assume that HTTP is port 80 anyway.

Which also means that 
```yaml
 DomainName: example.com
 CustomOriginConfig:
  HTTPPort: 8080
```
would call attention, making debugging easier (eg. We are using a non-default port - did we also change the security group)

### Thinking about updates
While I like generating templates as a first step, it does increase the burden when things need to change. Because you will not know which properties are required, or why something was configured a certain way. Eg. From the api output it might not be clear if the name of an AudioDescription is important (since it was autogenerated). With a cleaned up template, it could look like this:

```yaml
  MediaLiveChannel:
    Type: "AWS::MediaLive::Channel"
    Properties:
# [...]
      EncoderSettings:
        AudioDescriptions:
          - Name: "audio1"  # referenced in  OutputGroups
            AudioTypeControl: "FOLLOW_INPUT"
            LanguageCodeControl: "FOLLOW_INPUT"
        OutputGroups:
          -  Outputs:
              - OutputName: "output1"
                AudioDescriptionNames:
                  - "audio1"  # see EncoderSettings.AudioDescriptions
# [...]
```

Not knowing what you have configured, and what was configured by the console limits the way to do updates. With a big chance being required to go back to the console (even for a small change). This increase either the cost (If you keep a not-automated resource running 24/7, overhead (if you have to spin up a new resource by hand when you need to make changes) or risk (if you use the console to edit a resource that is managed by CloudFormation).



Anyway, that turned into more of a wall of text than I intended, but I strongly believe that a good CloudFormation resource schema / template is important for long term maintainability. In the simple case it represents "what", but unlike the console it can also represent "why", either implicitly or explicitly.

**Comment by rbberns** [comment]
Hello! We've implemented a fix for this issue, and channel names will now be automatically generated if none was provided. This fix has been fully deployed and should now be available in all production regions.

**Comment by benbridts** [comment]
@rbberns Thanks, it's nice to not have to specify the name.

Does this also fix

- the documentation (both CloudFormation and API) not matching what is actually required?
- CLoudFormation requiring properties like MotionGraphicsSettings, even if the value(s underneath) are null?
