### ISSUE TITLE
AWS::RDS::DBInstance - Support for RDS Cross-Region Automated Backups configuration

### ISSUE THREAD

**Issue by SkeyeLlama** [aws-cloudformation/cloudformation-coverage-roadmap#913]
### Name of the resource

AWS::RDS::DBInstance

### Resource name

AWS::RDS::DBInstance

### Description

Add CloudFormation support for the RDS Cross-Region Automated Backups feature. 

RDS cross-region automated backup configuration should be definable as a new resource-type and/or an additional attribute on the AWS::RDS::DBInstance resource type.

### Other Details

Latest feature expansion announcement:
https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-rds-cross-region-automated-backups-regional-expansion/

Documentation on enabling and describing Cross-Region Automated Backups
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReplicateBackups.html#AutomatedBackups.Replicating.Enable

**Comment by Vadim-Zenin** [comment]
Hello,
Could helpful to have BackupCopyRegion: String as well.
It is business critical for production disaster recovery.

**Comment by KellyBilodeau-Moodys** [comment]
Any ETA update for this?

**Comment by azatoth** [comment]
Would by nice if this could be added sooner than later; Has been a while now and I can't fathom why it hasn't been implemented yet.

**Comment by hibhag** [comment]
Quick updates. Deployment for this feature support is in progress, we can expect availability in all regions by 10th Oct 2023.

**Comment by azatoth** [comment]
> Quick updates. Deployment for this feature support is in progress, we can expect availability in all regions by 10th Oct 2023.

Do we have any official source for this?

**Comment by kddejong** [comment]
Released into the docs and specs:  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html#cfn-rds-dbinstance-automaticbackupreplicationregion

**Comment by azatoth** [comment]
> Released into the docs and specs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html#cfn-rds-dbinstance-automaticbackupreplicationregion

"Property description not available" - I hope this is going to be fixed

**Comment by kddejong** [comment]
Let me check

**Comment by zessx** [comment]
The `AutomaticBackupReplicationRegion` is now available on `AWS::RDS::DBInstance` resources, but it looks like it's not working in a cluster configuration:

```json
{
  …
  "DbClusterInstanceXXXXXXXXX": {
    "Type": "AWS::RDS::DBInstance",
    "Properties": {
      "AutomaticBackupReplicationRegion": "eu-central-1",
      …
    }
  }
}
```

**Comment by khebul** [comment]
The feature is now supported for DBInstances. Automated Backup replication to another region is not supported by RDS for instance which are the part of DBCluster, therefore it is not yet possible to add the support for it in CloudFormation.

**Comment by ShannonSD-h** [comment]
Hi @khebul,
Is support for cross-region automated backup replication for instances part of a cluster on the roadmap?
