### ISSUE TITLE
AWS::LakeFormation::Permissions  LF::* Tag Resources and Permissions

### ISSUE THREAD

**Issue by lucasvieirasilva** [aws-cloudformation/cloudformation-coverage-roadmap#920]
### Name of the resource

AWS::LakeFormation::Permissions

### Resource name

AWS::LakeFormation::Permissions

### Description

This is for all AWS::LakeFormation::* resources

Lake Formation LF Tag Resources and permissions is supported by the SDK:

- [grant_permissions](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lakeformation.html#LakeFormation.Client.grant_permissions)
- [add_lf_tags_to_resource](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lakeformation.html#LakeFormation.Client.add_lf_tags_to_resource)
- [create_lf_tag](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lakeformation.html#LakeFormation.Client.create_lf_tag)
- [delete_lf_tag](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lakeformation.html#LakeFormation.Client.delete_lf_tag)
- [update_lf_tag](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lakeformation.html#LakeFormation.Client.update_lf_tag)

but is not available in CloudFormation:

- [aws-properties-lakeformation-permissions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lakeformation-permissions-resource.html)

Full Lake Formation CloudFormation resources
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_LakeFormation.html

**Comment by setu4993** [comment]
Would be great to have.

**Comment by jeffersoncandidozup** [comment]
There would be some prediction for coverage of these features?

**Comment by pwc-yara-jens-gjolme** [comment]
Would be nice!

**Comment by matt-theguyw1cat** [comment]
LF Tags solve so many problems with the original 'per-resource' permission scheme.  For large and automated data lakes with thousands of databases and tables granting perms to a 'tag' decouples provisioning of the thing that will require the access (e.g. a lambda or ECS task) to the resource from the lifecycle of the resource itself... a beautiful thing for automation and why this feature is screaming for cloud formation support.

**Comment by lucasvieirasilva** [comment]
AWS CloudFormation now supports the LF Tags resources:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lakeformation-principalpermissions.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lakeformation-tag.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lakeformation-tagassociation.html
