### ISSUE TITLE
AWS::Lambda::Function - Support AWS Graviton2 processor

### ISSUE THREAD

**Issue by ueokande** [aws-cloudformation/cloudformation-coverage-roadmap#926]
### Name of the resource

AWS::Lambda::Function

### Description

Lambda Functions now support Graviton2 processor. An `Architectures` parameter is added on [`CreateFunction`](https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#API_CreateFunction_RequestBody) API, but [Function](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html) resource in CloudFormation does not support it.

### Other Details

- [Achieve up to 34% better price/performance with AWS Lambda Functions powered by AWS Graviton2 processor](https://aws.amazon.com/about-aws/whats-new/2021/09/better-price-performance-aws-lambda-functions-aws-graviton2-processor/)
- [AWS Lambda Functions Powered by AWS Graviton2 Processor – Run Your Functions on Arm and Get Up to 34% Better Price Performance](https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/)

**Comment by micahduron** [comment]
Although the documentation hasn't been updated to reflect it yet, arm64 Lambda functions are supported in CloudFormation. The `Architectures` property for `AWS::Lambda::Function` accepts a list of architecture names like so:

```
MyLambdaFunction:
  Type: AWS::Lambda::Function
  Properties:
    # ...
    Architectures:
      - arm64
```

**Comment by micahduron** [comment]
The documentation has been updated. Resolving the issue.
