### ISSUE TITLE
Error when trying to update via replacement an AWS::ImageBuilder::ImageRecipe without updating Name

### ISSUE THREAD

**Issue by commanderson** [aws-cloudformation/cloudformation-coverage-roadmap#927]
### Name of the resource

AWS::ImageBuilder::ImageRecipe

### Issue Description

When updating any property requiring Replacement on an AWS::ImageBuilder::ImageRecipe resource (all except AdditionalInstanceConfiguration), unless the Name property is also updated, update fails with an error:

`Resource handler returned message: "Resource of type 'AWS::ImageBuilder::Component' with identifier '<whatever Name you used>' already exists.`

### Expected Behavior

CloudFormation should be able to handle replacing a resource as part of an update even if that resource requires a unique name and the Name property hasn't been changed.

### Observed Behavior

Unless the Name property is also updated, update fails with an error:

`Resource handler returned message: "Resource of type 'AWS::ImageBuilder::Component' with identifier '<whatever Name you used>' already exists.`

### Test Cases

This behavior can be tested by creating a basic Image Builder component, creating an ImageRecipe where this is the only component, and then making a change to any property other than AdditionalInstanceConfiguration

**Comment by wyuzheng** [comment]
Hi there, I don't have details about your template but when it comes to the error message, it is related to `component` (which is also an immutable resource). It basically says the component is already existent(could be created already not via CFN).

The primary identifier for component & image-recipe is ARN which is determined by the`name` and `vesion` combination.
Our service is designed not to handle the update with replacement on CFN due to we have the versioning in the resource for enhancement feature in other place for example semantic version x.x.x, 1.x.x, 1.0.x. Therefore we would recommend user to bump up the version for their essential resource update.

**Comment by kidbrax** [comment]
I have this same error when updating a recipe. I did bump the version but still get the error. Are you also required to bump the component version used by the recipe?

**Comment by OlegSmirnov** [comment]
>Our service is designed not to handle the update with replacement on CFN due to we have the versioning in the resource for enhancement feature
@wyuzheng Any chance you can reconsider this? I can always bump the version myself (if I choose to keep the original deployed), but other than that all versioning is happening at the repo level and there is no reason to keep all previous versions deployed. This is a massive antipattern to general CFN usage.

**Comment by tarunb12** [comment]
This is solved with this recent EC2 Image Builder service release: [EC2 Image Builder now supports auto-versioning and enhances Infrastructure as Code experience](https://aws.amazon.com/about-aws/whats-new/2025/11/ec2-image-builder-auto-versioning-infrastructure/), which eliminates the need for manual/custom version number logic on recipes, components, and workflows. You can now include a single `x` in your recipe version which will automatically increment the version number on updates. For components and workflows, your build number will be incremented automatically, so you can have multiple components/workflows with the same name and version which would avoid conflict errors previously seen in IaC setups.
