### ISSUE TITLE
DocumentDB cluster template doesn't support CopyTagsToSnapshot

### ISSUE THREAD

**Issue by SF3** [aws-cloudformation/cloudformation-coverage-roadmap#928]
### Name of the resource

AWS::DocDB::DBCluster

### Description

We have a requirement to Implement changes to the CFT for DocumentDB to enable tags to be copied from DocumentDB Clusters to Snapshots. I tried to deploy this by adding the property 'CopyTagsToSnapshot: true' to the documentdb.template file but the build failed as follows:
"Executed At: 2021-09-29T11:50:48.289, Status: INFO, Text: sf-cloudformation-385-sandbox.DBCluster: entered status CREATE_FAILED, reason: Property validation failure: [Encountered unsupported properties in {/}: [CopyTagsToSnapshot]]."
This feature is supported for Relation databases - Aurora/Postgres SQL as we have implemented that. 
Not sure if AWS plans to support this in future releases/updates?  If not, would there be another way of implementing this using Custom Resources/CLI etc. Maybe someone has encountered this before. 

### Other Details

N/A

**Comment by mllevyha** [comment]
Hi @SF3, thanks for bringing this to our team's attention. We are looking into implementing this and it is already prioritized in our backlog.

**Comment by SF3** [comment]
Hi Matias, thank you for the update. I see from the cloudformation-coverage-roadmap that this feature is 'Coming Soon', which is great. Would there be an ETA as to when the feature will be available for us to implement? Kind regards and thanks, Sean.

**Comment by mllevyha** [comment]
This feature should now be available to you. Thanks for your help 😄
