### ISSUE TITLE
AWS::Lex::*

### ISSUE THREAD

**Issue by mweagle** [aws-cloudformation/cloudformation-coverage-roadmap#93]
Please add support for [Lex](https://aws.amazon.com/blogs/aws/amazon-lex-now-generally-available/) resources and properties.

Expected Behavior: Resource definition for Lex resource available in CloudFormation [Schema](https://d201a2mn26r7lk.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json).

**Comment by fedeBollo** [comment]
+1

**Comment by benkehoe** [comment]
> +1

@fedeBollo It's usually better to use reactions (the "+😀" button on a comment) than to have lots of individual people clutter up the comments (and notifications) with "+1" comment.

**Comment by jessedoyle** [comment]
@PatMyron - I'm just pinging to see if there's any activity planning in the future for this feature?

It's pretty crazy that Lex has been generally available since 2017 and still lacks CloudFormation bindings.

**Comment by bpottier** [comment]
Is there any update as to when we might see support? We're trying to automate the management of Lex and finding that it is going to take a lot of effort without cloudformation support.

**Comment by rohits-spec** [comment]
As on 12/9, the Lex support is available in Cloudformation. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Lex.html 

Resolving this issue.

**Comment by jogold** [comment]
@rohits-spec getting the following error message when trying to create a `AWS::Lex::BotAlias`:

```
Properties validation failed for resource BotVersionAliasF9D332F9 with message:
#/BotAliasLocaleSettings/0: required key [Key] not found
#/BotAliasLocaleSettings/0: required key [Value] not found
```

using the following template:
```json
{
  "Type": "AWS::Lex::BotAlias",
  "Properties": {
    "BotAliasName": "prod",
    "BotId": {
      "Fn::GetAtt": [
        "Bot138FBCDF",
        "Id"
      ]
    },
    "BotAliasLocaleSettings": [
      {
        "LocaleId": "fr_FR"
      }
    ],
    "BotVersion": {
      "Fn::GetAtt": [
        "BotVersionA27D27C1",
        "BotVersion"
      ]
    }
  }
}
```
