### ISSUE TITLE
[AWS AppSync] Creating multiple Resolvers in the same GraphQL API or Schema fails from time to time

### ISSUE THREAD

**Issue by mario-catalan-aurea** [aws-cloudformation/cloudformation-coverage-roadmap#932]
### Name of the resource

AWS::AppSync::Resolver

### Issue Description

When deploying a GraphQL API with its schema and multiple resolvers in a stack using CDK, it fails from time to time with errors like the following:
```
app1                                         │    20/100 |00:00:00 AM | CREATE_FAILED        | AWS::AppSync::Resolver              | execution-stack/Mutation4Resolver (Mutation4Resolver4DD88B4F) No data source found named Mutation4DataSource (Service: AWSAppSync; Status Code: 404; Error Code: NotFoundException; Request ID: 123e4567-e89b-12d3-a456-426614174000; Proxy: null)
```

Very rough estimate: for APIs with 50-150 resolvers, deployments fail 10-15% of the time.

Investigating this issue with AWS Support, we found out that some calls to action `CreateResolver` in the AWS AppSync API (https://docs.aws.amazon.com/appsync/latest/APIReference/API_CreateResolver.html) were failing with `ConcurrentModificationException` errors like the following:
```
{
    "eventTime": "2021-09-14T00:00:00Z",
    "eventSource": "appsync.amazonaws.com",
    "eventName": "CreateResolver",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "cloudformation.amazonaws.com",
    "userAgent": "cloudformation.amazonaws.com",
    "errorCode": "ConcurrentModificationException",
    "requestParameters": {
        "fieldName": "<field_name>",
        "kind": "UNIT",
        "typeName": "Query",
        "apiId": "<api_id>",
        "dataSourceName": "<data_source_name>"
    },
    "responseElements": {
        "message": "Schema is currently being altered, please wait until that is complete."
        ...
```

Also, I noticed that the data source causing the `NotFoundException` actually existed, and that its creation was completed before the creation of the resolver was started - which is expected, since the resolver _depends on_ the data source.

For these reasons, I think that error message _No data source found named <data_source_name>_ is wrong and masking the actual problem, and that the actual problem is that these resolvers being created in parallel occasionally results in `ConcurrentModificationException` errors.

### What could AWS CloudFormation do to mitigate or fix this issue?

Retry the creation of an AppSync resolver if it fails with a `ConcurrentModificationException` error. If this is being done already, increase the number of retries.

### Expected Behavior

Deployments of AppSync GraphQL APIs with multiple resolvers using AWS CloudFormation do not fail from time to time, or they fail much less frequently than currently (for example, less than 1% of the time).

### Observed Behavior

Deployments of AppSync GraphQL APIs with multiple resolvers using AWS CloudFormation fail from time to time. Very rough estimate: for APIs with 50-150 resolvers, they fail 10-15% of the time.

### Test Cases

Reproducing this issue might be challenging, since even for AppSync GraphQL APIs with a considerable amount of resolvers which can all be deployed in parallel, it might take a fair number of attempts. I can only suggest what is already evident: try to maximize the chances of getting a `ConcurrentModificationException` by maximizing the number of resolver creations being run in parallel, for which you would have to define a fair number of resolvers, avoid defining other resources which can get in the way, try defining resolvers which take longer to create, etc.

### Other Details

Even though, as I said, we are using AWS CloudFormation through AWS CDK and not directly, it should be clear from my explanations above that the problem is not related to the generation of the templates, but with the provisioning of the resources, and it falls, hence, within the scope of AWS CloudFormation and not AWS CDK.

**Comment by MrFlark** [comment]
Hello, we believe a fix has been rolled out to address this, also mentioned in [this](https://github.com/aws-amplify/amplify-cli/issues/9372#issuecomment-1018845758) GitHub issue. Is this still being observed?

**Comment by mario-catalan-aurea** [comment]
@MrFlark: Since I have not encountered this issue in a while, I am closing this.

**Comment by AWSZM** [comment]
> @MrFlark: Since I have not encountered this issue in a while, I am closing this.

Hello, AWS SSMT received a Twitter contact from a user experiencing this issue still. May we kindly re-open this?

User: https://twitter.com/rkustner/status/1502382116297969664
