### ISSUE TITLE
CF stack tags are not applied to AWS::IAM::SAMLProvider causing drift

### ISSUE THREAD

**Issue by tcondeixa** [aws-cloudformation/cloudformation-coverage-roadmap#943]
### Name of the resource

AWS::IAM::SAMLProvider

### Issue Description

The tags defined at stack level are not applied to AWS::IAM::SAMLProvider and it cases a drift that we need to manually correct.

### Expected Behavior

Expected that stack tags are applied to the SAML Identity Provider

### Observed Behavior

Tags are not applied to AWS::IAM::SAMLProvider

### Test Cases

you can just create a stack with a few tags and a AWS::IAM::SAMLProvider resource

**Comment by jtgrohn** [comment]
This also appears to be an issue for `AWS::IAM::OIDCProvider`
