### ISSUE TITLE
Cloudformation Update fails to replace AWS::GameLift::MatchmakingRuleSet

### ISSUE THREAD

**Issue by jonnixt17** [aws-cloudformation/cloudformation-coverage-roadmap#944]
### Name of the resource

AWS::GameLift::MatchmakingRuleSet

### Issue Description

Per the documentation an update to thAWS::GameLift::MatchmakingRuleSet resource's ruleset body should result in a replacement resource. Replacement creation fails as the rule being replaced exists with the same name.

### Expected Behavior

The resource should be replaced in the background correctly, either by temporarily renaming the existing ruleset without the template needing change, or Name should not be a required fields and be generated by AWS automatically like other resources allowing replacement using a new auto-generated name.

### Observed Behavior

Cloudformation update fails with An error occurred: gameliftRuleSet - Rule set <rulesetName> already exists (Service: AmazonGameLift; Status Code: 400; Error Code: InvalidRequestException; Request ID: <requestId>; Proxy: null).

### Test Cases

Create a new matchmaking configuration and ruleset using cloudformation and deploy. Update the ruleset body but not the name.

**Comment by DanGreen100** [comment]
Hello! Today GameLift Matchmaking RuleSets are immutable and cannot be updated once created. We recommend customers instead create a new RuleSet with the updated matchmaking rules, which can be done by specifying a new RuleSet name. Deleting and re-creating a Matchmaking RuleSet is not recommended, since that leaves a period of time where your RuleSet would not exist to route players.

**Comment by jonnixt17** [comment]
@DanGreen100 Is this not a well used pattern in Cloudformation, that upon needing replacement, a new resource is created first, any references are shifted over then in the cleanup stage the original is deleted? Also we see in other areas of CF that new resources with unspecified names can be created with auto-generated names. I don't see why GameLift resources cannot follow these same patterns? This is what the documentation says should happen.
