### ISSUE TITLE
AWS::ResourceGroups::Group Drift Detection does not consider stack-level tags when Resource has Tags Property

### ISSUE THREAD

**Issue by linyunxiang** [aws-cloudformation/cloudformation-coverage-roadmap#955]
### Name of the resource

Other

### Resource Name

AWS::ResourceGroups::Group

### Issue Description

If an AWS::ResourceGroups::Group resource has the Tags Property, Drift Detection would expect ONLY the specified tags but not any stack-level tags. Thus gives false alarm.

### Expected Behavior

Drift Detection should expect stack-level tags properly when detecting drifts.

### Observed Behavior

Incorrect Drfit Status:

$ aws cloudformation describe-stack-resource-drifts --stack-name lambda

            "LogicalResourceId": "ResourceGroup",
            "PhysicalResourceId": "XXXXX",
            "ResourceType": "AWS::ResourceGroups::Group",
            "ExpectedProperties": "{\"Tags\":[{\"Value\":\"value\",\"Key\":\"key\"}],\"ResourceQuery\":{\"Type\":\"CLOUDFORMATION_STACK_1_0\",\"Query\":{\"StackIdentifier\":\"arn:aws:cloudformation:us-east-1:XXXXX:stack/lambda/30a93910-3203-11ec-9a61-0e2b626336fb\"}},\"Name\":\"attini-setup\"}",
            "ActualProperties": "{\"Tags\":[{\"Key\":\"aws:cloudformation:stack-name\",\"Value\":\"lambda\"},{\"Key\":\"aws:cloudformation:stack-id\",\"Value\":\"arn:aws:cloudformation:us-east-1:XXXXX:stack/lambda/30a93910-3203-11ec-9a61-0e2b626336fb\"},{\"Key\":\"aws:cloudformation:logical-id\",\"Value\":\"ResourceGroup\"},{\"Key\":\"key\",\"Value\":\"value\"}],\"Name\":\"attini-setup\",\"ResourceQuery\":{\"Type\":\"CLOUDFORMATION_STACK_1_0\",\"Query\":{\"StackIdentifier\":\"arn:aws:cloudformation:us-east-1:XXXXX:stack/lambda/30a93910-3203-11ec-9a61-0e2b626336fb\"}}}",
            "PropertyDifferences": [
                {
                    "PropertyPath": "/Tags/0/Value",
                    "ExpectedValue": "value",
                    "ActualValue": "ResourceGroup",
                    "DifferenceType": "NOT_EQUAL"
                },
                {
                    "PropertyPath": "/Tags/1",
                    "ExpectedValue": "null",
                    "ActualValue": "{\"Key\":\"aws:cloudformation:stack-id\",\"Value\":\"arn:aws:cloudformation:us-east-1:XXXXX:stack/lambda/30a93910-3203-11ec-9a61-0e2b626336fb\"}",
                    "DifferenceType": "ADD"
                },
                {
                    "PropertyPath": "/Tags/3",
                    "ExpectedValue": "null",
                    "ActualValue": "{\"Key\":\"key\",\"Value\":\"value\"}",
                    "DifferenceType": "ADD"
                },
                {
                    "PropertyPath": "/Tags/0/Key",
                    "ExpectedValue": "key",
                    "ActualValue": "aws:cloudformation:logical-id",
                    "DifferenceType": "NOT_EQUAL"
                },
                {
                    "PropertyPath": "/Tags/2",
                    "ExpectedValue": "null",
                    "ActualValue": "{\"Key\":\"aws:cloudformation:stack-name\",\"Value\":\"lambda\"}",
                    "DifferenceType": "ADD"
                }
            ],
            "StackResourceDriftStatus": "MODIFIED",

### Test Cases

Create an AWS::ResourceGroups::Group resource with Tags Property and then try drift detection.

**Comment by juano-amzn** [comment]
Hello,


I'm Juan, from the Resources Groups team. Apologies for our long delay here :/  but this issue has been now fixed, we've worked together with the CloudFormation and a fix has been deployed.

To test this, I created a stack, and executed drift detection, which looked fine. I added some tags out-of-band and this was reflected as drift when I ran drift detection again.

```
➜  ~ aws cloudformation create-stack --stack-name "bug-test-955" --template-body file://~/test_stack.yml --region us-east-1
{
    "StackId": "arn:aws:cloudformation:us-east-1:444786198083:stack/bug-test-955/0ebc8d70-8e3d-11ec-ae54-0a529d9489a7"
}
➜
➜  ~ aws cloudformation detect-stack-drift --stack-name "bug-test-955"
{
    "StackDriftDetectionId": "4696cd00-8e3d-11ec-9adc-0a3f8d258fdd"
}
➜  ~ aws cloudformation describe-stack-resource-drifts --stack-name "bug-test-955"
{
    "StackResourceDrifts": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:444786198083:stack/bug-test-955/0ebc8d70-8e3d-11ec-ae54-0a529d9489a7",
            "LogicalResourceId": "UluruManualTestTagBasedGroup",
            "PhysicalResourceId": "GitHubP52715767",
            "ResourceType": "AWS::ResourceGroups::Group",
            "ExpectedProperties": "{\"Description\":\"This group is used for testing\",\"Tags\":[{\"Value\":\"Test\",\"Key\":\"Env\"}],\"ResourceQuery\":{\"Type\":\"TAG_FILTERS_1_0\",\"Query\":{\"TagFilters\":[{\"Values\":[\"bar\"],\"Key\":\"foo\"}],\"ResourceTypeFilters\":[\"AWS::AllSupported\"]}},\"Name\":\"GitHubP52715767\"}",
            "ActualProperties": "{\"Description\":\"This group is used for testing\",\"Tags\":[{\"Key\":\"Env\",\"Value\":\"Test\"}],\"Name\":\"GitHubP52715767\",\"ResourceQuery\":{\"Type\":\"TAG_FILTERS_1_0\",\"Query\":{\"ResourceTypeFilters\":[\"AWS::AllSupported\"],\"TagFilters\":[{\"Key\":\"foo\",\"Values\":[\"bar\"]}]}}}",
            "PropertyDifferences": [],
            "StackResourceDriftStatus": "IN_SYNC",
            "Timestamp": "2022-02-15T08:57:20.103000+00:00"
        }
    ]
}
➜  ~ aws resource-groups tag --arn arn:aws:resource-groups:us-east-1:444786198083:group/GitHubP52715767 --tags Foo=Bar
{
    "Arn": "arn:aws:resource-groups:us-east-1:444786198083:group/GitHubP52715767",
    "Tags": {
        "Foo": "Bar"
    }
}
➜  ~ aws cloudformation detect-stack-drift --stack-name "bug-test-955"
{
    "StackDriftDetectionId": "ce94f610-8e41-11ec-abfe-0eff9922f2df"
}
➜  ~ aws cloudformation describe-stack-resource-drifts --stack-name "bug-test-955"
{
    "StackResourceDrifts": [
        {
            "StackId": "arn:aws:cloudformation:us-east-1:444786198083:stack/bug-test-955/0ebc8d70-8e3d-11ec-ae54-0a529d9489a7",
            "LogicalResourceId": "UluruManualTestTagBasedGroup",
            "PhysicalResourceId": "GitHubP52715767",
            "ResourceType": "AWS::ResourceGroups::Group",
            "ExpectedProperties": "{\"Description\":\"This group is used for testing\",\"Tags\":[{\"Value\":\"Test\",\"Key\":\"Env\"}],\"ResourceQuery\":{\"Type\":\"TAG_FILTERS_1_0\",\"Query\":{\"TagFilters\":[{\"Values\":[\"bar\"],\"Key\":\"foo\"}],\"ResourceTypeFilters\":[\"AWS::AllSupported\"]}},\"Name\":\"GitHubP52715767\"}",
            "ActualProperties": "{\"Description\":\"This group is used for testing\",\"Tags\":[{\"Key\":\"Foo\",\"Value\":\"Bar\"},{\"Key\":\"Env\",\"Value\":\"Test\"}],\"Name\":\"GitHubP52715767\",\"ResourceQuery\":{\"Type\":\"TAG_FILTERS_1_0\",\"Query\":{\"ResourceTypeFilters\":[\"AWS::AllSupported\"],\"TagFilters\":[{\"Key\":\"foo\",\"Values\":[\"bar\"]}]}}}",
            "PropertyDifferences": [
                {
                    "PropertyPath": "/Tags/1",
                    "ExpectedValue": "null",
                    "ActualValue": "{\"Key\":\"Foo\",\"Value\":\"Bar\"}",
                    "DifferenceType": "ADD"
                }
            ],
            "StackResourceDriftStatus": "MODIFIED",
            "Timestamp": "2022-02-15T09:29:46.346000+00:00"
        }
    ]
}
```

Thanks for reporting this and have fun developing :)
