### ISSUE TITLE
New CFN Resource: AWS::OpenSearch::DomainPolicy

### ISSUE THREAD

**Issue by JohnPreston** [aws-cloudformation/cloudformation-coverage-roadmap#958]
### Name of the resource

Other

### Resource name

AWS::OpenSearch::Domain

### Description

When creating a new OS Domain, one can set the domain policy within which can be handy for initialization.
However, it would be much better to have as well, a `AWS::OpenSearch::DomainPolicy` that would allow the users to set the Policy after the domain (and possibly other resources) have been created.

Typically, if I do not set the `DomainName` property, I do not yet know the final name of the domain and therefore to set the Resource policy statements properly, it means I would have to set a policy that might just be too generic.

*Note: IMHO, all resources supporting a Resource policy should have that feature*

Thank you for your consideration

### Other Details

Similar functionality wanted as the AWS S3 Bucket Policy CFN resource type which allows to set the policy on the bucket **after** it is created or in another stack even.

**Comment by rhbecker** [comment]
I'm trying to understand what has been shipped. Is there a new `AWS::OpenSearch::DomainPolicy` resource? If so, I don't see a page for it in the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_OpenSearchService.html).
