### ISSUE TITLE
(ssm): Retrieve secure string without version number

### ISSUE THREAD

**Issue by fire015** [aws-cloudformation/cloudformation-coverage-roadmap#961]
### Name of the resource

AWS::SSM::Parameter

### Description

There does not seem to be a way to retrieve a SecureString without specifying a version number (unlike a regular string) from SSM. This makes it difficult when you deploy the same stack to different environments and the version of the secret may differ between environments.

Issue and code sample is referenced here: https://github.com/aws/aws-cdk/issues/17091

**Comment by gomibushi** [comment]
In addition to the above mention issues you can not resolve a SecureString that might be updated by another process. You need to know it has been updated and supply the latest version. The default behaviour should absolutely be to retrieve the latest version if no version number (or 0) is supplied.

**Comment by fire015** [comment]
It looks like this has been resolved with https://github.com/aws/aws-cdk/pull/18187
