### ISSUE TITLE
AWS::SNS::Topic - Generated stack-level tags not copied to SNS resource

### ISSUE THREAD

**Issue by WaelA** [aws-cloudformation/cloudformation-coverage-roadmap#962]
### Name of the resource

AWS::SNS::Topic

### Issue Description

Generated stack-level tags not copied to SNS resource

### Expected Behavior

All three generated tags (aws:cloudformation:stack-name, aws:cloudformation:stack-id, aws:cloudformation:logical-id) should be applied to all resources that support tagging

### Observed Behavior

AWS::SNS::Topic resource do not have the generated stack-level tags (e.g. aws:cloudformation:stack-name) applied to them. For comparison, AWS::S3::Bucket and AWS::Lambda::Function resources do receive those tags.

### Test Cases

create an SNS using cloudformation, note that it doesn't get the generated tags set on it.

### Other Details

Links to existing API doc:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html defines these tags and states that they should be copied to all resources, so it's unclear whether this is a coverage issue or a bug.

**Comment by shih** [comment]
I opened a new issue in SNS's repo, instead of leaving the issue here.

**Comment by shih** [comment]
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-sns/pull/71
