### ISSUE TITLE
AWS::Events:Rule does not detect `DeadLetterConfig`

### ISSUE THREAD

**Issue by tcondeixa** [aws-cloudformation/cloudformation-coverage-roadmap#968]
### Name of the resource

AWS::Events::Rule

### Issue Description

AWS::Events:Rule does not detect `DeadLetterConfig` config applied causing drift after.

### Expected Behavior

It is expected that the AWS::Events:Rule is able to detect the `DeadLetterConfig` applied, so the actual matches the expected.

### Observed Behavior

AWS::Events:Rule does not detect `DeadLetterConfig` config applied causing drift after.

### Test Cases

Create a AWS::Events:Rule with a `DeadLetterConfig` with an SQS and detect the drift after.

**Comment by phs** [comment]
This still reproduces for me in multiple regions.  Is there a timeline when we should expect it to be deployed?
