### ISSUE TITLE
ap-southeast-02 AWS::EC2::TransitGatewayConnect Support

### ISSUE THREAD

**Issue by dcolcott** [aws-cloudformation/cloudformation-coverage-roadmap#972]
### Name of the resource

AWS::EC2::TransitGateway

### Resource name

AWS::EC2::TransitGatewayConnect

### Description

Cloudformation in ap-southeast-2 doesn't yet support the AWS::EC2::TransitGatewayConnect resource. 

Request to road-map regional support to allow CDK automation of critical transit Gateway infra for enterprise customer.

**Comment by ilyavas3** [comment]
Hello,
This feature is not supported by CloudFormation in regions eu-north-1 and eu-central-1. 
Could you please also add it to road map?
Thank you.

**Comment by fortinetps** [comment]
Not sure if it is related, I was trying to create connect attachment in us-east-2, and I got,
Template format error: Unrecognized resource types: [AWS::EC2::TransitGatewayConnect]
Any clue?

Thanks!

**Comment by ilyavas3** [comment]
> Not sure if it is related, I was trying to create connect attachment in us-east-2, and I got, Template format error: Unrecognized resource types: [AWS::EC2::TransitGatewayConnect] I have no problem creating this connect attachment manually with AWS GUI console. Any clue?
> 
> Thanks!

Hello,

I was have the same error. Most probably this feature is not supported by CloudFormation in this region.

**Comment by fortinetps** [comment]
As I checked, this feature (with CFN) is only available on us-east-1 and eu-west-1, but this feature (with AWS console) is available on most of the regions. It doesn't make sense, AWS should roll out this feature together with CFN...

**Comment by antoineaws** [comment]
Hello, 
Same here, requesting this construct "AWS::EC2::TransitGatewayConnect" and a Connect Peers construct in ca-central-1. Thank you!

**Comment by davidadas** [comment]
@dcolcott this should be available now in ap-southeast-02 :)

**Comment by antoineaws** [comment]
Team, we have different regions added to this issue as well such as ca-central-1. Can we re-open or do you need a new issue? 
@davidadas

**Comment by davidadas** [comment]
You can re-open @antoineaws. That's fine.

**Comment by antoineaws** [comment]
@davidadas Unfortunately I can't re-open as I am not part of the cfn org. I can also open a new one more generic if it makes more sense. Thanks

**Comment by suhaniladani** [comment]
@antoineaws The resource should now be available in us-east-2, eu-north-1 and eu-central-1.
