### ISSUE TITLE
AWS::AutoScaling::AutoScalingGroup under Resources Tab in Console has broken URL

### ISSUE THREAD

**Issue by shantgup** [aws-cloudformation/cloudformation-coverage-roadmap#973]
### Name of the resource

AWS::AutoScaling::AutoScalingGroup

### Resource Name

AWS::AutoScaling::AutoScalingGroup

### Issue Description

When the `AWS::AutoScaling::AutoScalingGroup` resource is created, the Stack Resources tab has an incorrect URL for the resource which points to a broken page.

I have seen this brought up multiple times, creating this issue on Github for tracking and visibility.

### Expected Behavior

The URL should point to the ASG resource in the console correctly. 

### Observed Behavior

The URL currently points to an invalid URL.

### Test Cases

You can check this by creating an `AWS::AutoScaling::AutoScalingGroup` resource and then click the link in the console under Stack Resources for the ASG resource and it should correctly open the ASG console with the resource.

**Comment by rgoltz** [comment]
Hi @shantgup - I've re-tested this issue. While having the new Console (New EC2 Experience) for AutoScaling active, I didn't see this issue anymore. Once clicking on the Resource-Link in CloudFormation Resource-Overview (mode "Flat View"), I'm successfully enter the ASG overview-page. The ASG is "pre-selected". Could you please cross-check as well?

**Comment by mulmar-aws** [comment]
I have also re-tested this issue and the console Stack Resources links for resources of type `AutoScalingGroup` work and correctly take me to the AutoScaling console.
