### ISSUE TITLE
Enable more configuration options for AWS::SES::ConfigurationSet

### ISSUE THREAD

**Issue by GeorgiosGoniotakis** [aws-cloudformation/cloudformation-coverage-roadmap#974]
### Name of the resource

AWS::SES::ConfigurationSet

### Description

Hello there 😃 In my organization, we have recently started using this resource and we have found it quite useful. However, we are finding the customizability of the resource quite limited. Besides setting the name, we would like to be able to set other options of the resource such as the TLS enforcement and others. Any assistance would be much appreciated.

**Comment by royal10march** [comment]
More options have been added to the resource, 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-configurationset.html

**Comment by royal10march** [comment]
Hey, this resource now has been updated with more options for you to configure, 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-configurationset.html

Specifically, the TLS enforcement you're looking for is available in DeliveryOptions, 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-configurationset-deliveryoptions.html

**Comment by GeorgiosGoniotakis** [comment]
Thank you for reaching out and addressing this limitation @royal10march!
