### ISSUE TITLE
Stack Failure Options - Preserve successfully provisioned resources - Bug when used with NoEcho Parameters

### ISSUE THREAD

**Issue by shantgup** [aws-cloudformation/cloudformation-coverage-roadmap#977]
### Name of the resource

Other

### Resource Name

Stack Failure Options

### Issue Description

Upon specifying the Stack Failure Option `Preserve successfully provisioned resources`, after a failure clicking the Retry button does not re-resolve the Parameters configured as `NoEcho: True`, and they persist as ****** for the actual update.

While this can be fixed by manually updating the Parameters, this is unexpected behavior and I would like to request a patch for this behavior on behalf of our customers.

### Expected Behavior

The Parameters configured as `NoEcho: True` should be re-resolved when the Stack is retried upon failure.

### Observed Behavior

The Parameters configured as `NoEcho: True` is not re-resolved and is used as-is i.e with ******* during the retry.

### Test Cases

1. Create a stack with NoEcho Parameters, and Stack Failure option `Preserve successfully provisioned resources` and upon failure click Retry.

2. After clicking retry the NoEcho parameters should not be shown as ****** and should instead resolve correctly to their actual values.

**Comment by SeveroeHe** [comment]
This issue should already been fixed, and has nothing to do with resource coverage. 

If you believe you still face the issue, please reach out to aws support to open a case with stack ID attached, and we can start the investigation from there

**Comment by konbk** [comment]
Just an FYI from my side, this bug is not resolved. I experienced it yesterday.
