### ISSUE TITLE
AWS::EKS::Cluster - missing support for managing OIDC identity providers

### ISSUE THREAD

**Issue by adammw** [aws-cloudformation/cloudformation-coverage-roadmap#978]
### Name of the resource

AWS::EKS::Cluster

### Description

There is currently no way to attach/detach an OIDC identity provider to an EKS cluster in the existing AWS::EKS::Cluster resource, nor is there a dedicated AWS::EKS::IdentityProvider or similar to create the resource and attach it separately.

### Other Details

Relevant EKS APIs:

- https://docs.aws.amazon.com/eks/latest/APIReference/API_AssociateIdentityProviderConfig.html
- https://docs.aws.amazon.com/eks/latest/APIReference/API_DisassociateIdentityProviderConfig.html
- https://docs.aws.amazon.com/eks/latest/APIReference/API_ListIdentityProviderConfigs.html
- https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeIdentityProviderConfig.html

**Comment by lynnnnnnluo** [comment]
We recently launched AWS::EKS::IdentityProviderConfig Cloudformation resource, please refer to the [document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-eks-identityproviderconfig.html) for details.
