### ISSUE TITLE
AWS::DLM::LifecyclePolicy Parameters NoReboot parameter issue

### ISSUE THREAD

**Issue by rajeshgovada** [aws-cloudformation/cloudformation-coverage-roadmap#980]
### Resource Name

AWS::DLM::LifecyclePolicy

### Details

When giving the parameter NoReebot for the Resource AWS::DLM::LifecyclePolicy, under PolicyDetails->Parameters->NoReboot, in a cloudformation template, the value given is not being taken, whether it is true or false, but instead getting replaced with true which is mentioned as default value in the documentation. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-dlm-lifecyclepolicy-parameters.html#cfn-dlm-lifecyclepolicy-parameters-noreboot

This change can be observed in the cloudformation console while executing the template which consists of the NoReboot parameter it shows a warning that template has changed.
![image](https://user-images.githubusercontent.com/84064095/142633107-59352760-e1b7-4d12-80cb-aa3be7b9c325.png)

**Comment by carpnick** [comment]
+1

I am finding NoReboot is not being honored.  Instead it is setting to Always reboot

**Comment by michaelkemmerer** [comment]
I dont know if you have this issue resolved but position in the DLM Policy seems to play a factor here.  Putting the Parameter: NoReboot: true at the end of the PolicyDetails has resolved this issue for me

PolicyDetails:
        ResourceTypes:
        - INSTANCE 
        PolicyType: IMAGE_MANAGEMENT
        TargetTags:
        - Key: Snapshot Backup
          Value: 'Enabled'
        - Key: Retain
          Value: !Ref 'DlmRetentionTag'
        - Key: Backup Interval
          Value: !Ref 'DlmScheduleTag'
        Schedules:
        - Name: Daily AMI
          CreateRule:
            Interval: 24
            IntervalUnit: HOURS
            Times:
            - '08:00'
          RetainRule:
            Count: 2
          CopyTags: true
        Parameters: 
          NoReboot: true

**Comment by mkemmererpcsnt** [comment]
I dont know if you have had this resolved or not.  But with this it seems that the position of the Parameter: NoReboot has an impact on the evaluation.

When putting this at the end of the PolicyDetails: it resolved the issue for me
`PolicyDetails:
        ResourceTypes:
        - INSTANCE 
        PolicyType: IMAGE_MANAGEMENT
        # Parameters:
        #   NoReboot: true
        TargetTags:
        - Key: Snapshot Backup
          Value: 'Enabled'
        - Key: Retain
          Value: !Ref 'DlmRetentionTag'
        - Key: Backup Interval
          Value: !Ref 'DlmScheduleTag'
        Schedules:
        - Name: Daily AMI
          CreateRule:
            Interval: 24
            IntervalUnit: HOURS
            Times:
            - '08:00'
          RetainRule:
            Count: 2
            # Interval: !Ref DLMRetentionInterval
            # IntervalUnit: !Ref DLMRetentionIntervalUnits
          CopyTags: true
        Parameters: 
          NoReboot: true`

**Comment by dctam2** [comment]
This issue has been fixed and deployed.
Fix: DLM team has now included the "NoReboot" parameter when creating the CFN resource.
