### ISSUE TITLE
AWS::EMR::Cluster - Adding Multiple CustomAMI to CloudFormation Template

### ISSUE THREAD

**Issue by alanrdze** [aws-cloudformation/cloudformation-coverage-roadmap#982]
### Name of the resource

AWS::EMR::Cluster

### Resource name

AWS::EMR::Cluster

### Description

When specifying a CustomAMI, currently CloudFormation only supports the addition of 1 custom AMI to the cluster. The custom AMIs should be applied to the instance group level not cluster level.

Customer wants to implement multiple custom AMIs to the stack template which they are able to deploy in their Instance Groups.

The addition of multiple AMIs is supported via CLI following documentation: https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-custom-ami.html#multiple-custom-ami

**Comment by WaelA** [comment]
I believe support for this feature has been added recently
