### ISSUE TITLE
AWS::SQS::Queue - Support Amazon SQS-managed encryption keys (SSE-SQS)

### ISSUE THREAD

**Issue by xeres** [aws-cloudformation/cloudformation-coverage-roadmap#989]
### Name of the resource

AWS::SQS::Queue

### Description

Currently, AWS::SQS::Queue only supports AWS-managed customer master key (CMK) for Amazon SQS or custom CMK by attribute KmsMasterKeyId.

Amazon SQS has announced a new Server-Side Encryption method, Amazon SQS-managed encryption keys (SSE-SQS).
AWS::SQS::Queue needs to be able to specify SSE-SQS with KmsMasterKeyId attribute or a new attribute to support this method.

### Other Details

AWS::SQS::Queue - AWS Cloudformation
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-sqs-queue-kmsmasterkeyid

Amazon SQS Announces Server-Side Encryption with Amazon SQS-managed encryption keys (SSE-SQS)
https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-sqs-server-side-encryption-keys-sse/

**Comment by parraletz** [comment]
Is there any WA?

**Comment by parraletz** [comment]
### **WA:**

**Create a CustomResource** 

Example using aws cdk and lambda.

https://github.com/parraletz/sse-sqs-wa

**Comment by KANNANKDP** [comment]
Any ETA to add support for this feature? This is a very important feature which will save a lot of time for systems using SQS.

**Comment by VanessaHenderson** [comment]
Asking again, any updates on when this might get added? Its seriously causing a headache at the company I work at

**Comment by asura-asp** [comment]
This works fine with 

```
"serverless": "^3.12.0"

```

**Comment by a-h** [comment]
What works fine @asura-asp?

This issue is about the AWS::SQS::Queue CloudFormation resource (documented at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html) not supporting an attribute to set SSE-SQS mode.

Reading through the docs, I think the expected mechanism to enable SSE-SQS via CloudFormation is actually to set the KmsMasterKeyId via to `alias/aws/sqs`?

**Comment by JakeHendy** [comment]
> Reading through the docs, I think the expected mechanism to enable SSE-SQS via CloudFormation is actually to set the KmsMasterKeyId via to `alias/aws/sqs`.

That uses the AWS Managed KMS key for SQS. If you look at the Documentation for the SQS API, you can see there's another field to use SSE-SQS.

**Comment by davesdere** [comment]
Any update? It's supported in Terraform but not in Cloudformation... I thought that AWS was committed to support CF first...

**Comment by jtaub** [comment]
ETA please?

**Comment by jean-passos** [comment]
It seems AWS fix this issue, I tested today setting attribute SqsManagedSseEnabled to true, as @asura-asp mentioned, and that’s really works.

**Comment by afterhill** [comment]
yes, confirmed it is working but the documentation is outdated, please update it!

**Comment by jumic** [comment]
There is a "Provide feedback" link at the bottom of each [documentation page](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html). I have reported the outdated documentation.
I hope this triggers the AWS team to update the documentation.

**Comment by davesdere** [comment]
thank you @jumic

**Comment by a-h** [comment]
The documentation was updated at some point. It's correct now:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/1029947/185669117-7941a950-67bc-4f12-bac5-8b4ca5d18650.png">
