### ISSUE TITLE
New Resource Type: AWS::ECR::RegistryScanningConfiguration 

### ISSUE THREAD

**Issue by JohnPreston** [aws-cloudformation/cloudformation-coverage-roadmap#993]
### Name of the resource

Other

### Resource name

AWS::ECR::RegistryScanningConfiguration

### Description

The name`AWS::ECR::RegistryScanningConfiguration` is only a suggestion but this is to support 

put_registry_scanning_configuration

In boto3 SDK -> https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecr.html#ECR.Client.put_registry_scanning_configuration

Thank you!

**Comment by bradgr** [comment]
Hi @JohnPreston, thanks for raising this.
We are currently working to add CloudFormation support for this resource.

**Comment by ngamradt-turner** [comment]
@JohnPreston, is there an update as to when this feature will get added to CloudFormation?

**Comment by TheDanBlanco** [comment]
there appears to be [ScanningConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecr-repository-imagescanningconfiguration.html) available now. closing this. if this doesn't meet your needs, please feel free to re-open with more info!

**Comment by JohnPreston** [comment]
No, this is not it. You are taking of repository, I am talking of registry!

**Comment by bradg-aws** [comment]
The [scanning configuration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecr-repository-imagescanningconfiguration.html) in AWS::ECR::Repository is for repository level configuration. ECR has launched [RegistryScanningConfiguration](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_PutRegistryScanningConfiguration.html), and the request here it to add support for this in CloudFormation.

We still have this on our roadmap, but I don't have any concrete updates to provide at this time.

**Comment by JohnPreston** [comment]
Thanks for taking the time @bradg-aws 
If I find the time happy to work on the AwsCommunity version of that. Or you can chase the ECR team to publish it too hehe
