### ISSUE TITLE
 CDK mighth not be passing TAG information to CFN template

### ISSUE THREAD

**Issue by xdiegoro** [aws-cloudformation/cloudformation-coverage-roadmap#999]
### Name of the resource

AWS::Redshift::Cluster

### Description

When creating for Redshift cluster via CDK , the CFN template is not getting the tags. Tags are applied when using native cfn but not when using CDK.

**Comment by pepdekpd** [comment]
To add some more detail:
In the cdk stack (CDK v2.1) a redshift-subnetgroup, redshift-parametergroup and a redshift-cluster are created ( using @aws-cdk/aws-redshift-alpha library). The tags defined in the cdk-stack are to found after deployment on the cloudformation stack itself, on the redshift parametergroup and on the redshift subnetgroup, but *not* on the redshift cluster.

**Comment by njlynch** [comment]
@xdiegoro / @pepdekpd  - This is the issue tracker for CloudFormation itself, not the CDK. I've opened an issue for you in the CDK repo; can you please follow up there? https://github.com/aws/aws-cdk/issues/18360
